#+title: 佛罗里达是南宋海外飞地

https://zhuanlan.zhihu.com/p/532557296
耶元1844年魏源写成《海国图志》一书，书中记载：育奈士迭国（即united states，美国），在北阿墨刺加洲中为最巨之区，其地自古不通各洲，土旷人稀，皆因底阿生番（印第安土著），游猎其间。耶稣纪岁千二百九十二年（即耶元1292年），（宋祥兴十五年）吕宋（当今的即菲律宾）之戈揽麻士乘船西驶，始知此地，创立佛罗里达部落，开垦兴筑。将二百年，辟地未广。千五百八十四年，（明万历十二年即1584年）英吉利女王衣里萨柏时，有英吉利人往弥利坚海岸开垦，大吕宋人拒战，英吉利人败走。”

佛罗里达，是标准的汉语衍化音，是汉语地方语。
《坤舆万国全图》“佛罗里达”标示处为“得尔勿罗洛，译云花地”。但是，其却恰恰是汉语尤其是闽南语“多儿花儿勒地（‘花’的闽南语为“fa”或“hue”。‘儿’为儿化音“l”，当把“l”的音节从儿化音错断成声母后，就发为“罗”的音。“勒”即“的”）”。因此，耶元1507年的“佛罗里达”已经有名字为“佛罗里达”，且其全名恰好有“多（花的地方）”的发音。而所谓西班牙语则没有“多”的发音。“耶元1513年西班牙探险者胡安·庞塞·德·莱昂最先发现并用西班牙语La Florida（“多花的地方”）命名了这个地方”是十足的谎言。

大宋灭亡于耶元1279年崖山之战。大宋灭亡时，宋末丞相陆秀夫背着小皇帝蹈海而死[fn:: 观者云: 好死不如赖活着，为啥不早点跑呢？]。部分南宋遗民先时在吕宋（陆宋）岛以陆自立为领袖，逐渐汇聚了不少南下的宋人，然后继续朝四海扩张。吕宋即陆宋。亦取“旅行在外之宋”之意。吕宋人于耶元1282年发现美洲并在北美洲东部佛罗里达建立部落。

明朝郑和下西洋之时，船队多次停泊过吕宋岛的港口。耶元1405年，郑和亲传永乐皇帝的旨意，册封吕宋岛华侨巨富福建人许柴佬（Ko Cha Lao）为吕宋总督。

 耶元1511年，葡萄牙人占领马六甲，六年后遣特使来华。明朝得知马六甲已亡于佛郎机的事实，颇为震动。御史丘道隆为此上奏《请却佛郎机贡献疏》，建议拒绝佛郎机的封贡要求。他说：“满剌加朝贡诏封之国，而佛朗机并之，且啖我以利，邀求封赏，于义决不可听。请却其贡献，明示顺逆，使归还满剌加疆土之后，方许朝贡。脱或执迷不悛，虽外夷不烦兵力，亦必檄召诸夷，声罪致讨。”《明世宗实录》（卷二四，嘉靖二年三月壬戌条，第693－694页）载：“佛朗机国人别都卢……恃其巨铳利兵，劫掠满剌加诸国，横行海外，至率其属疏世利等千余人驾舟五艘破巴西国，遂寇新会县西草湾。备倭指挥柯荣、百户王应恩率师截海御之，转战至稍州，向化人潘丁苟先登，众兵齐进，生擒别都卢、疏世利等四十二人，斩首三十五级”。

明世宗出生于耶元1507年，去世于耶元1566年。《明世宗实录》以上内容明确记载西洋人攻击美洲巴西。明朝出兵“截海御之”，生擒西洋船队并斩首。

为什么明朝后期几乎放弃了对美洲的保护与管辖？答案就在以徐光启为代表的东林党身上。
