#+OPTIONS: toc:nil num:nil
*  大品.第一（有二十五经）（第三念诵）

柔软、龙象、处，无常、请、瞻波，

二十亿、八难，贫穷、欲、福田，

优婆塞、怨家，教昙弥、降魔，

赖吒、优婆离，释问及善生，

商人、世间、福，息止、至边、喻。

#+TOC: headlines 2

**  第29卷 大品.柔软经第一
我闻如是：一时，佛游舍卫国，在胜林给孤独园。

尔时，世尊告诸比丘：“自我昔日出家学道，为从优游、从容闲乐、极柔软来。我在父王悦头檀家时，为我造作种种宫殿，春殿、夏殿及以冬殿。为我好游戏故，去殿不远，复造种种若干华池，青莲华池、红莲华池、赤莲华池、白莲华池。于彼池中植种种水华，青莲华、红莲华、赤莲华、白莲华，常水常华，使人守护，不通一切。为我好游戏故，于其池岸植种种陆华，修摩那华、婆师华、薝蔔华、修揵提华、摩头揵提华、阿提牟多华、波罗头华。

“为我好游戏故，而使四人沐浴于我；沐浴我已，赤旃檀香用涂我身；香涂身已，著新缯衣，上下、内外、表里皆新，昼夜常以伞盖覆我------莫令太子夜为露所沾，昼为日所灸。如常他家粗䵃[kuàng]、麦饭、豆羹、姜菜，为第一食，如是我父悦头檀家最下使人，粳粮肴馔为第一食。复次，若有野田禽兽，最美禽兽，提帝逻惒吒、劫宾阇逻、奚米何犁泥奢施罗米，如是野田禽兽，最美禽兽，常为我设如是之食。

“我忆昔时父悦头檀家，于夏四月升正殿上，无有男子，唯有女妓而自娱乐，初不来下。我欲出至园观之时，三十名骑，简选上乘，卤簿前后，侍从导引，况复其余？我有是如意足，此最柔软。

“我复忆昔时看田作人止息田上，往诣阎浮树下，结跏趺坐，离欲、离恶不善之法，有觉、有观，离生喜、乐，得初禅成就游。我作是念：‘不多闻愚痴凡夫自有病法，不离于病，见他人病，憎恶薄贱，不爱不喜，不自观己。我复作是念：‘我自有病法，不离于病，若我见他病而憎恶薄贱，不爱不喜者，我不宜然，我亦有是法故。如是观已，因不病起贡高者，即便自灭。我复作是念：‘不多闻愚痴凡夫自有老法，不离于老，见他人老，憎恶薄贱，不爱不喜，不自观己。我复作是念：‘我自有老法，不离于老，若我见他老而憎恶薄贱，不爱不喜者，我不宜然，我亦有是法故。如是观已，若因寿起贡高者，即便自灭。不多闻愚痴凡夫为不病贡高豪贵放逸，因欲生痴，不行梵行；不多闻愚痴凡夫为少壮贡高豪贵放逸，因欲生痴，不行梵行；不多闻愚痴凡夫为寿贡高豪贵放逸，因欲生痴，不行梵行。”

于是，世尊即说颂曰：

<div class="poem">

病法老法，及死亡法，\\
如法自有，凡夫见恶。\\
若我憎恶，不度此法，\\
我不宜然，亦有是法。\\
彼如是行，知法离生，\\
无病少壮，为寿贡高，\\
断诸贡高，见无欲安。\\
彼如是觉，无怖于欲，\\
得无有想，行净梵行。

</div>

佛说如是，彼诸比丘闻佛所说，欢喜奉行。

--------------

** 第29卷 大品.龙象经第二

我闻如是：一时，佛游舍卫国，在东园鹿子母堂。

尔时，世尊则于晡时从宴坐起，堂上来下，告曰：“乌陀夷，共汝往至东河澡浴。”

尊者乌陀夷白曰：“唯然。”

于是，世尊将尊者乌陀夷往至东河，脱衣岸上，便入水浴。浴已还出，拭体著衣。

尔时，波斯匿王有龙象，名曰念，作一切妓乐，历度东河。众人见已，便作是说：“是龙中龙，为大龙王，为是谁耶？”

尊者乌陀夷叉手向佛，白曰：“世尊，象受大身，众人见已，便作是说：‘是龙中龙，为大龙王，为是谁耶？”

世尊告曰：“如是，乌陀夷。如是，乌陀夷。象受大身，众人见已，便作是说：‘是龙中龙，为大龙王，为是谁耶？乌陀夷，马、骆驼、牛、驴、胸行、人、树，生大形。乌陀夷，众人见已，便作是说：‘是龙中龙，为大龙王，为是谁耶？乌陀夷，若有世间，天及魔、梵、沙门、梵志，从人至天，不以身、口、意害者，我说彼是龙。乌陀夷，如来于世间，天及魔、梵、沙门、梵志，从人至天，不以身、口、意害，是故我名龙。”

于是，尊者乌陀夷叉手向佛，白曰：“世尊，惟愿世尊加我威力！善逝加我威力！令我在佛前，以龙相应颂颂赞世尊。”

世尊告曰：“随汝所欲。”

于是，尊者乌陀夷在于佛前，以龙相应颂赞世尊曰：

<div class="poem">

正觉生人间，自御得正定，\\
修习行梵迹，息意能自乐。\\
人之所敬重，越超一切法，\\
亦为天所敬，无著至真人。\\
越度一切结，于林离林去，\\
舍欲乐无欲，如石出真金。\\
普闻正尽觉，如日升虚空，\\
一切龙中高，如众山有岳。\\
称说名大龙，而无所伤害，\\
一切龙中龙，真谛无上龙。\\
温润无有害，此二是龙足，\\
苦行及梵行，是谓龙所行。\\
大龙信为手，二功德为牙，\\
念项智慧头，思惟分别法。\\
受持诸法腹，乐远离双臂，\\
住善息出入，内心至善定。\\
龙行止俱定，坐定卧亦定，\\
龙一切时定，是谓龙常法。\\
无秽家受食，有秽则不受，\\
得恶不净食，舍之如师子。\\
所得供养者，为他慈愍受，\\
龙食他信施，存命无所著。\\
断除大小结，解脱一切缚，\\
随彼所游行，心无有系著。\\
犹如白莲华，水生水长养，\\
泥水不能著，妙香爱乐色。\\
如是最上觉，世生行世间，\\
不为欲所染，如华水不著。\\
犹如燃火炽，不益薪则止，\\
无薪火不传，此火谓之灭。\\
慧者说此喻，欲令解其义，\\
是龙之所知，龙中龙所说。\\
远离淫欲恚，断痴得无漏，\\
龙舍离其身，此龙谓之灭。

</div>

佛说如是，尊者乌陀夷闻佛所说，欢喜奉行。

--------------

** 第29卷 大品.说处经第三

我闻如是：一时，佛游舍卫国，在胜林给孤独园。

尔时，世尊告诸比丘：“此有三说处，无四无五。若比丘见已，因彼故说而说我见、闻、识、知，比丘说而说是我所知。云何为三？比丘，因过去世说，而说如是过去世时有；比丘，因未来世说，而说如是未来世时有；比丘，因现在世说，而说如是现在世时有。是谓三说处，无四无五。若比丘见已，因彼故说而说我见、闻、识、知，比丘说而说是我所知，因所说善习得义，因不说不善习得义。

“贤圣弟子两耳一心听法，彼两耳一心听法已，断一法、修一法、一法作证；彼断一法、修一法、一法作证已，便得正定。贤圣弟子心得正定已，便断一切淫、怒、痴。贤圣弟子如是得心解脱，解脱已，便知解脱：我生已尽，梵行已立，所作已办，不更受有，知如真。因其所说有四处，当以观人，此贤者可共说、不可共说。若使此贤者一向论不一向答者，分别论不分别答者，诘论不诘答者，止论不止答者，如是此贤者不得共说，亦不得共论。若使此贤者一向论便一向答者，分别论分别答者，诘论诘答者，止论止答者，如是此贤者得共说，亦得共论。

“复次，因其所说，更有四处，当以观人，此贤者可共说、不可共说。若使此贤者于处、非处不住者，所知不住者，说喻不住者，道迹不住者，如是此贤者不可共说，亦不可共论。若此贤者于处、非处住者，所知住者，说喻住者，道迹住者，如是此贤者可得共说，亦可得共论。因所说时止息口行，舍己所见，舍怨结意，舍欲、舍恚、舍痴、舍慢、舍不语、舍悭嫉、不求胜、不伏他，莫取所失，说义说法。说义说法已，教复教止，自欢喜、令彼欢喜。如是说义，如是说事，是圣说义，是圣说事，谓至竟漏尽。”

于是，世尊说此颂曰：

<div class="poem">

若有诤论议，杂意怀贡高，\\
非圣毁呰德，各各相求便。\\
但求他过失，意欲降伏彼，\\
更互而求胜，圣不如是说。\\
若欲得论议，慧者当知时，\\
有法亦有义，诸圣论如是。\\
慧者如是说，无诤无贡高，\\
意无有厌足，无结无有漏。\\
随顺不颠倒，正知而为说，\\
善说则然可，自终不说恶。\\
不以诤论议，亦不受他诤，\\
知处及说处，是彼之所论。\\
如是圣人说，慧者俱得义，\\
为现法得乐，亦为后世安。\\
当知聪达者，非倒非常说。

</div>

佛说如是，彼诸比丘闻佛所说，欢喜奉行。

--------------

** 第29卷 大品.说无常经第四

我闻如是：一时，佛游舍卫国，在胜林给孤独园。

尔时，世尊告诸比丘：“色者无常，无常则苦，苦则非神。觉亦无常，无常则苦，苦则非神。想亦无常，无常则苦，苦则非神。行亦无常，无常则苦，苦则非神。识亦无常，无常则苦，苦则非神。是为色无常，觉、想、行、识无常，无常则苦，苦则非神。多闻圣弟子作如是观，修习七道品，无碍正思正念。彼如是知、如是见，欲漏心解脱，有漏、无明漏心解脱；解脱已，便知解脱：我生已尽，梵行已立，所作已办，不更受有，知如真。若有众生及九众生居，乃至有想无想处行余第一有，于其中间是第一、是大、是胜、是最、是尊、是妙，谓世中阿罗诃。所以者何？世中阿罗诃得安隐快乐。”

于是，世尊说此颂曰：

<div class="poem">

无著第一乐，断欲无有爱，\\
永舍离我慢，裂坏无明网。\\
彼得不移动，心中无秽浊，\\
不染著世间，梵行得无漏。\\
了知于五阴，境界七善法，\\
大雄游行处，离一切恐怖。\\
成就七觉宝，具学三种学，\\
妙称上朋友，佛最上真子。\\
成就十支道，大龙极定心，\\
是世中第一，彼则无有爱。\\
众事不移动，解脱当来有，\\
断生老病死，所作办灭漏。\\
兴起无学智，得身最后边，\\
梵行第一具，彼心不由他。\\
上不及诸方，彼无有喜乐，\\
能为师子吼，世间无上觉。

</div>

佛说如是，彼诸比丘闻佛所说，欢喜奉行。

--------------

** 第29卷 大品.请请经第五（下一请字慈井切）

我闻如是：一时，佛游王舍城，在竹林迦兰哆园，与大比丘众五百人俱，共受夏坐。

尔时，世尊月十五日，说从解脱相请请时，在比丘众前敷座而坐，告诸比丘：“我是梵志，而得灭讫，无上医王。我今受身，最是后边。我是梵志，得灭讫后，无上医王。我今受身，最是后边，谓汝等辈是我真子，从口而生，法法所化。谓汝等辈是我真子，从口而生，法法所化，汝当教化，转相教诃。”

尔时，尊者舍梨子亦在众中。于是，尊者舍梨子即从座起，偏袒著衣，叉手向佛，白曰：“世尊，向之所说：‘我是梵志，而得灭讫，无上医王。我今受身，最是后边。我是梵志，得灭讫后，无上医王。我今受身，最是后边，谓汝等辈是我真子，从口而生，法法所化。谓汝等辈是我真子，从口而生，法法所化，汝当教化，转相教诃。世尊诸不调者令得调御，诸不息者令得止息，诸不度者而令得度，诸不解脱者令得解脱，诸不灭讫者令得灭讫，未得道者令其得道，不施设梵行令施设梵行，知道、觉道、识道、说道。世尊弟子于后得法，受教、受诃，受教、诃已，随世尊语，即便趣行，得如其意，善知正法。唯然，世尊不嫌我身、口、意行耶？”

彼时，世尊告曰：“舍梨子，我不嫌汝身、口、意行。所以者何？舍梨子，汝有聪慧、大慧、速慧、捷慧、利慧、广慧、深慧、出要慧、明达慧。舍梨子，汝成就实慧。舍梨子，犹转轮王而有太子，不越教已，则便受拜父王所传，而能复传。如是，舍梨子，我所转法轮，汝复能转。舍梨子，是故我不嫌汝身、口、意行。”

尊者舍梨子复再叉手向佛，白曰：“唯然，世尊不嫌我身、口、意行。世尊不嫌此五百比丘身、口、意行耶？”

世尊告曰：“舍梨子，我亦不嫌此五百比丘身、口、意行。所以者何？舍梨子，此五百比丘尽得无著，诸漏已尽，梵行已立，所作已办，重担已舍，有结已尽，而得善义正智正解脱。唯除一比丘，我亦本已记于现法中得究竟智：生已尽，梵行已立，所作已办，不更受有，知如真。舍梨子，是故我不嫌此五百比丘身、口、意行。”

尊者舍梨子复三叉手向佛，白曰：“唯然，世尊不嫌我身、口、意行，亦不嫌此五百比丘身、口、意行。世尊，此五百比丘，几比丘得三明达？几比丘得俱解脱？几比丘得慧解脱耶？”

世尊告曰：“舍梨子，此五百比丘，九十比丘得三明达，九十比丘得俱解脱，余比丘得慧解脱。舍梨子，此众无枝无叶，亦无节戾，清净真实，得正住立。”

尔时，尊者傍耆舍亦在众中。于是，尊者傍耆舍即从座起，偏袒著衣，叉手向佛，白曰：“唯然，世尊加我威力！惟愿善逝加我威力！令我在佛及比丘众前，以如义相应而作赞颂。”

世尊告曰：“傍耆舍，随汝所欲。”

于是，尊者傍耆舍在佛及比丘众前，以如义相应而赞颂曰：

<div class="poem">

今十五请日，集坐五百众，\\
断除诸结缚，无碍有尽仙。\\
清净光明照，解脱一切有，\\
生老病死尽，漏灭所作办。\\
掉悔及疑结，慢有漏已尽，\\
拔断爱结刺，上医无复有。\\
勇猛如师子，一切恐畏除，\\
已度于生死，诸漏已灭讫。\\
犹如转轮王，群臣所围绕，\\
悉领一切地，乃至于大海。\\
如是勇猛伏，无上商人主，\\
弟子乐恭敬，三达离死怖。\\
一切是佛子，永除枝叶节，\\
转无上法轮，稽首第一尊。

</div>

佛说如是，彼诸比丘闻佛所说，欢喜奉行。

--------------

** 第29卷 大品.瞻波经第六

我闻如是：一时，佛游瞻波，在恒伽池边。

尔时，世尊月十五日说从解脱时，于比丘众前敷座而坐。世尊坐已，即便入定，以他心智观察众心；观众心已，至初夜竟，默然而坐。于是，有一比丘即从座起，偏袒著衣，叉手向佛，白曰：“世尊，初夜已讫，佛及比丘众集坐来久，惟愿世尊说从解脱！”

尔时，世尊默然不答。于是，世尊复至中夜默然而坐，彼一比丘再从座起，偏袒著衣，叉手向佛，白曰：“世尊，初夜已过，中夜将讫，佛及比丘众集坐来久，惟愿世尊说从解脱！”

世尊亦再默然不答。于是，世尊复至后夜默然而坐，彼一比丘三从座起，偏袒著衣，叉手向佛，白曰：“世尊，初夜既过，中夜复讫，后夜垂尽，将向欲明，明出不久，佛及比丘众集坐极久，惟愿世尊说从解脱！”

尔时，世尊告彼比丘：“于此众中有一比丘已为不净。”

彼时，尊者大目揵连亦在众中。于是，尊者大目揵连便作是念：“世尊为何比丘而说此众中有一比丘已为不净？我宁可入如其像定，以如其像定他心之智观察众心。”

尊者大目揵连即入如其像定，以如其像定他心之智观察众心。尊者大目揵连便知世尊所为比丘说此众中有一比丘已为不净。于是，尊者大目揵连即从定起，至彼比丘前，牵臂将出，开门置外：“痴人远去！莫于此住！不复得与比丘众会，从今已去，非是比丘。”闭门下钥，还诣佛所，稽首佛足，却坐一面，白曰：“世尊所为比丘说此众中有一比丘已为不净者，我已逐出。世尊，初夜即过，中夜复讫，后夜垂尽，将向欲明，明出不久，佛及比丘众集坐极久，惟愿世尊说从解脱！”

世尊告曰：“大目揵连，彼愚痴人当得大罪，触娆世尊及比丘众。大目揵连，若使如来在不净众说从解脱者，彼人则便头破七分。是故，大目揵连，汝等从今已后说从解脱，如来不复说从解脱。所以者何？如是，大目揵连，或有痴人正知出入，善观分别，屈伸低仰，仪容庠序，善著僧伽梨及诸衣钵，行住坐卧、眠寤语默，皆正知之，似如真梵行，至诸真梵行所，彼或不知。大目揵连，若诸梵行知者，便作是念：‘是沙门污，是沙门辱，是沙门憎，是沙门刺。知已，便当共摈弃之。所以者何？莫令污染诸梵行者。

“大目揵连，犹如居士有良稻田，或有麦田，生草名秽麦，其根相似，茎、节、叶、华皆亦似麦。后生实已，居士见之，便作是念：‘是麦污辱，是麦憎刺。知已便拔，掷弃于外。所以者何？莫令污秽余真好麦。如是，大目揵连，或有痴人正知出入，善观分别，屈伸低仰，仪容庠序，善著僧伽梨及诸衣钵，行住坐卧、眠寤语默，皆正知之，似如真梵行，至诸真梵行所，彼或不知。大目揵连，若诸梵行知者，便作是念：‘是沙门污，是沙门辱，是沙门憎，是沙门刺。知已，便当共摈弃之。所以者何？莫令污染诸梵行者。

“大目揵连，犹如居士秋时扬谷，谷聚之中若有成实者，扬便止住。若不成实及粃糠者，便随风去。居士见已，即持扫帚，扫治令净。所以者何？莫令污杂余净好稻。如是，大目揵连，或有痴人正知出入，善观分别，屈伸低仰，仪容庠序，善著僧伽梨及诸衣钵，行住坐卧、眠寤语默，皆正知之，似如真梵行，至诸真梵行所，彼或不知。大目揵连，若诸梵行知者，便作是念：‘是沙门污，是沙门辱，是沙门憎，是沙门刺。知已，便当共摈弃之。所以者何？莫令污染诸梵行者。

“大目揵连，犹如居士为过泉水故，作通水槽，持斧入林，扣打诸树。若坚实者，其声便小；若空中者，其声便大。居士知已，便斫治节，拟作通水槽，如是，大目揵连，或有痴人正知出入，善观分别，屈伸低仰，仪容庠序，善著僧伽梨及诸衣钵，行住坐卧、眠寤语默，皆正知之，似如真梵行，至诸真梵行所，彼或不知。大目揵连，若诸梵行知者，便作是念：‘是沙门污，是沙门辱，是沙门憎，是沙门刺。知已，便当共摈弃之。所以者何？莫令污染诸梵行者。”

于是，世尊说此颂曰：

<div class="poem">

共会集当知，恶欲憎嫉恚，\\
不语结恨悭，嫉妒谄欺诳，\\
在众诈言息，屏处称沙门，\\
阴作诸恶行，恶见不守护，\\
欺诳妄语言，如是当知彼，\\
往集不与会，摈弃不共止。\\
欺诈诳说多，非息称说息，\\
知时具净行，摈弃远离彼。\\
清净共清净，常当共和合，\\
和合得安隐，如是得苦边。

</div>

佛说如是，彼诸比丘闻佛所说，欢喜奉行。

--------------

** 第29卷 大品.沙门二十亿经第七

我闻如是：一时，佛游舍卫国，在胜林给孤独园。

尔时，尊者沙门二十亿亦游舍卫国，在暗林中，前夜、后夜学习不眠，精勤正住，修习道品。于是，尊者沙门二十亿安静独住，宴坐思惟，心作是念：“若有世尊弟子精勤学习正法、律者，我为第一，然诸漏心不得解脱。我父母家极大富乐，多有钱财，我今宁可舍戒罢道，行欲布施，修诸福业耶！”

尔时，世尊以他心智知尊者沙门二十亿心之所念，便告一比丘：“汝往至彼，呼沙门二十亿来。”

于是，一比丘白曰：“唯然。”即从座起，稽首礼足，绕三匝而去，往至尊者沙门二十亿所而语彼曰：“世尊呼汝。”

尊者沙门二十亿闻比丘语，即诣佛所，稽首作礼，却坐一面。世尊告曰：“沙门，汝实安静独住，宴坐思惟，心作是念：‘若有世尊弟子精勤学习正法、律者，我为第一，然诸漏心不得解脱。我父母家极大富乐，多有钱财，我今宁可舍戒罢道，行欲布施，修诸福业耶！”

彼时，尊者沙门二十亿羞耻惭愧，则无无畏：“世尊知我心之所念。”叉手向佛，白曰：“实尔。”

世尊告曰：“沙门，我今问汝，随所解答。于意云何？汝在家时，善调弹琴，琴随歌音，歌随琴音耶？”

尊者沙门二十亿白曰：“如是，世尊。”

世尊复问：“于意云何？若弹琴弦急，为有和音可爱乐耶？”

沙门答曰：“不也，世尊。”

世尊复问：“于意云何？若弹琴弦缓，为有和音可爱乐耶？”

沙门答曰：“不也，世尊。”

世尊复问：“于意云何？若弹琴调弦不急不缓，适得其中，为有和音可爱乐耶？”

沙门答曰：“如是，世尊。”

世尊告曰：“如是，沙门，极大精进，令心掉乱；不极精进，令心懈怠。是故汝当分别此时，观察此相，莫得放逸。”

尔时，尊者沙门二十亿闻佛所说，善受善持，即从座起，稽首佛足，绕三匝而去；受佛弹琴喻教，在远离独住，心无放逸，修行精勤。彼在远离独住，心无放逸，修行精勤已，族姓子所为，剃除须发，著袈裟衣，至信、舍家、无家、学道者，唯无上梵行讫，于现法中自知、自觉、自作证成就游：生已尽，梵行已立，所作已办，不更受有，知如真。尊者沙门二十亿知法已，至得阿罗诃。彼时，尊者沙门二十亿得阿罗诃已，而作是念：“今正是时，我宁可往诣世尊所，说得究竟智耶！”

于是，尊者沙门二十亿往诣佛所，稽首作礼，却坐一面，白曰：“世尊，若有比丘得无所著，诸漏已尽，梵行已立，所作已办，重担已舍，有结已解，自得善义，正智正解脱者，彼于尔时乐此六处：乐于无欲，乐于远离，乐于无诤，乐于爱尽，乐于受尽，乐心不移动。

“世尊，或有一人而作是念：‘此贤者以依信故，乐于无欲者，不应如是观，但欲尽、恚尽、痴尽，是乐于无欲。世尊，或有一人而作是念：‘此贤者以贪利称誉求供养故，乐于远离者，不应如是观，但欲尽、恚尽、痴尽，是乐于远离。世尊，或有一人而作是念：‘此贤者以依戒故，乐于无诤者，不应如是观，但欲尽、恚尽、痴尽，是乐于无诤，乐于爱尽，乐于受尽，乐心不移动。世尊，若有比丘得无所著，诸漏已尽，梵行已立，所作已办，重担已舍，有结已解，自得善义，正智正解脱者，彼于尔时乐此六处。

“世尊，若有比丘学未得意，求愿无上安隐涅槃者，彼于尔时成就学根及学戒。彼于后时，诸漏已尽而得无漏，心解脱、慧解脱，于现法中自知、自觉、自作证成就游：生已尽，梵行已立，所作已办，不更受有，知如真者，彼于尔时成就无学根及无学戒。世尊，犹幼少童子，彼于尔时成就小根及小戒。彼于后时具足学根者，彼于尔时成就学根及学戒。如是，世尊，若有比丘学未得意，求愿无上安隐涅槃者，彼于尔时成就学根及学戒。彼于后时，诸漏已尽而得无漏，心解脱、慧解说，于现法中自知、自觉、自作证成就游：生已尽，梵行已立，所作已办，不更受有，知如真者，彼于尔时成就无学根及无学戒。

“彼若有眼所知色与对眼者，不能令失此心解脱、慧解脱，心在内住，善制守持，观兴衰法。若有耳所知声、鼻所知香、舌所知味、身所知触、意所知法与对意者，不能令失此心解脱、慧解脱，心在内住，善制守持，观兴衰法。世尊，犹去村不远有大石山，不破不缺不脆，坚住不空合一，若东方有大风雨来，不能令摇，不动转移，亦非东方风移至南方，若南方有大风雨来，不能令摇，不动转移，亦非南方风移至西方；若西方有大风雨来，不能令摇，不动转移，亦非西方风移至北方；若北方有大风雨来，不能令摇，不动转移，亦非北方风移至诸方。如是彼若有眼所知色与对眼者，不能令失此心解脱、慧解脱，心在内住，善制守持，观兴衰法。若有耳所知声、鼻所知香、舌所知味、身所知触、意所知法与对意者，不能令失此心解脱、慧解脱，心在内住，善制守持，观兴衰法。”

于是，尊者沙门二十亿说此颂曰：

<div class="poem">

乐在无欲，心存远离，\\
喜于无诤，受尽欣悦。\\
亦乐受尽，心不移动，\\
得知如真，从是心解。\\
得心解已，比丘息根，\\
作已不观，无所求作。\\
犹如石山，风不能动，\\
色声香味，身触亦然，\\
爱不爱法，不能动心。

</div>

尊者沙门二十亿于佛前说得究竟智已，即从座起，稽首佛足，绕三匝而去。

尔时，世尊，尊者沙门二十亿去后不久，告诸比丘：“诸族姓子，应如是来于我前说得究竟智，如沙门二十亿来于我前说得究竟智，不自誉，不慢他，说义现法随诸处也。莫令如痴增上慢所缠，来于我前说得究竟智，彼不得义，但大烦劳。沙门二十亿来于我前说得究竟智，不自誉，不慢他，说义现法随诸处也。”

佛说如是，彼诸比丘闻佛所说，欢喜奉行。

--------------

** 第29卷 大品.八难经第八

我闻如是：一时，佛游舍卫国，在胜林给孤独园。

尔时，世尊告诸比丘：“人行梵行而有八难、八非时也。云何为八？若时如来、无所著、等正觉、明行成为、善逝、世间解、无上士、道法御、天人师，号佛、众佑，出世说法：趣向止息，趣向灭讫，趣向觉道，为善逝所演。彼人尔时生地狱中，是谓人行梵行第一难、第一非时。

“复次，若时如来、无所著、等正觉、明行成为、善逝、世间解、无上士、道法御、天人师，号佛、众佑，出世说法：趣向止息，趣向灭讫，趣向觉道，为善逝所演。彼人尔时生畜生中，生饿鬼中，生长寿天中，生在边国夷狄之中，无信无恩，无有反复，若无比丘、比丘尼、优婆塞、优婆夷，是谓人行梵行第五难、第五非时。

“复次，若时如来、无所著、等正觉、明行成为、善逝、世间解、无上士、道法御、天人师，号佛、众佑，出世说法：趣向止息，趣向灭讫，趣向觉道，为善逝所演。彼人尔时虽生中国，而聋哑如羊鸣，常以手语，不能知说善恶之义，是谓人行梵行第六难、第六非时。

“复次，若时如来、无所著、等正觉、明行成为、善逝、世间解、无上士、道法御、天人师，号佛、众佑，出世说法：趣向止息，趣向灭讫，趣向觉道，为善逝所演。彼人尔时虽生中国，不聋、不哑，不如羊鸣，不以手语，又能知说善恶之义，然有邪见及颠倒见，如是见、如是说：‘无施、无斋，无有咒说；无善恶业，无善恶业报；无此世彼世；无父无母；世无真人往至善处、善去、善向，此世彼世自知、自觉、自作证成就游。是谓人行梵行第七难、第七非时。

“复次，若时如来、无所著、等正觉、明行成为、善逝、世间解、无上士、道法御、天人师，号佛、众佑，不出于世，亦不说法：趣向止息，趣向灭讫，趣向觉道，为善逝所演。彼人尔时生于中国，不聋、不哑，不如羊鸣，不以手语，又能知说善恶之义，而有正见不颠倒见，如是见、如是说：‘有施、有斋，亦有咒说；有善恶业，有善恶业报；有此世彼世；有父有母；世有真人往至善处、善去、善向，此世彼世自知、自觉、自作证成就游。是谓人行梵行第八难、第八非时。

“人行梵行有一不难、有一是时。云何人行梵行有一不难、有一是时？若时如来、无所著、等正觉、明行成为、善逝、世间解、无上士、道法御、天人师，号佛、众佑，出世说法：趣向止息，趣向灭讫，趣向觉道，为善逝所演。彼人尔时生于中国，不聋、不哑，不如羊鸣，不以手语，又能知说善恶之义，而有正见不颠倒见，如是见、如是说：‘有施、有斋，亦有咒说；有善恶业，有善恶业报；有此世彼世；有父有母；世有真人往至善处、善去、善向，此世彼世自知、自觉、自作证成就游。是谓人行梵行有一不难、有一是时。”

于是，世尊说此颂曰：

<div class="poem">

若得人身者，说最微妙法，\\
若有不得果，必不遇其时。\\
多说梵行难，人在于后世，\\
若得遇其时，是世中甚难。\\
欲得复人身，及闻微妙法，\\
当以精勤学，人自哀愍故。\\
谈说闻善法，莫令失其时，\\
若失此时者，必忧堕地狱。\\
若不遇其时，不闻说善法，\\
如商人失财，受生死无量。\\
若有得人身，闻说正善法，\\
遵奉世尊教，必遭遇其时。\\
若遭遇此时，堪任正梵行，\\
成就无上眼，日亲之所说。\\
彼为常自护，进行离诸使，\\
断灭一切结，降魔魔眷属，\\
彼度于世间，谓得尽诸漏。

</div>

佛说如是，彼诸比丘闻佛所说，欢喜奉行。

--------------

** 第29卷 大品.贫穷经第九

我闻如是：一时，佛游舍卫国，在胜林给孤独园。

尔时，世尊告诸比丘：“世有欲人贫穷，为大苦耶？”

诸比丘白曰：“尔也，世尊。”

世尊复告诸比丘曰：“若有欲人贫穷举贷他家财物，世中举贷他家财物，为大苦耶？

诸比丘白曰：“尔也，世尊。”

世尊复告诸比丘曰：“若有欲人举贷财物，不得时还，白曰长息，世中长息，为大苦耶？”

诸比丘白曰：“尔也，世尊。”

世尊复告诸比丘曰：“若有欲人长息不还，财主责索，世中财主责索，为大苦耶？”

诸比丘白曰：“尔也，世尊。”

世尊复告诸比丘曰：“若有欲人财主责索，不能得偿，财主数往至彼求索，世中财主数往至彼求索，为大苦耶？”

诸比丘白曰：“尔也，世尊。”

世尊复告诸比丘曰：“若有欲人财主数往至彼求索，彼故不还，便为财主之所收缚，世中为财主收缚，为大苦耶？”

诸比丘白曰：“尔也，世尊。”

“是为世中有欲人贫穷是大苦，世中有欲人举贷财物是大苦，世中有欲人举贷长息是大苦，世中有欲人财主责索是大苦，世中有欲人财主数往至彼求索是大苦，世中有欲人为财主收缚是大苦。如是若有于此圣法之中，无信于善法，无禁戒、无博闻、无布施、无智慧于善法，彼虽多有金、银、琉璃、水精、摩尼、白珂、螺璧、珊瑚、琥珀、玛瑙、瑇瑁、砗渠、碧玉、赤石、琁珠，然彼故贫穷，无有力势，是我圣法中说不善贫穷也。

“彼身恶行，口、意恶行，是我圣法中说不善举贷也。彼欲覆藏身之恶行，不自发露，不欲道说，不欲令人诃责，不顺求；欲覆藏口、意恶行，不自发露，不欲道说，不欲令人诃责，不顺求，是我圣法中说不善长息也。彼或行村邑及村邑外，诸梵行者见已，便作是说：‘诸贤，此人如是作、如是行、如是恶、如是不净，是村邑刺。彼作是说：‘诸贤，我不如是作、不如是行、不如是恶、不如是不净，亦非村邑刺。是我圣法中说不善责索也。

“彼或在无事处，或在山林树下，或在空闲居，念三不善念------欲念、恚念、害念，是我圣法中说不善数往求索也。彼作身恶行，口、意恶行，彼作身恶行，口、意恶行已，因此缘此，身坏命终，必至恶处，生地狱中，是我圣法中说不善收缚也。我不见缚更有如是苦、如是重、如是粗、如是不可乐，如地狱、畜生、饿鬼缚也。此三苦缚，漏尽阿罗诃比丘已知灭尽，拔其根本，永无来生。”

于是，世尊说此颂曰：

<div class="poem">

世间贫穷苦，举贷他钱财，\\
举贷钱财已，他责为苦恼。\\
财主往求索，因此收系缚，\\
此缚甚重苦，世间乐于欲。\\
于圣法亦然，若无有正信，\\
无惭及无愧，作恶不善行。\\
身作不善行，口意俱亦然，\\
覆藏不欲说，不乐正教诃。\\
若有数数行，意念则为苦，\\
或村或静处，因是必有悔。\\
身口习诸行，及意之所念，\\
恶业转增多，数数作复作。\\
彼恶业无慧，多作不善已，\\
随所生毕讫，必往地狱缚。\\
此缚最甚苦，雄猛之所离，\\
如法得财利，不负得安隐。\\
施与得欢喜，二俱皆获利，\\
如是诸居士，因施福增多。\\
如是圣法中，若有好诚信，\\
具足成惭愧，庶几无悭贪。\\
已舍离五盖，常乐行精进，\\
成就诸禅定，满具常弃乐。\\
已得无食乐，犹如水浴净，\\
不动心解脱，一切有结尽。\\
无病为涅槃，谓之无上灯，\\
无忧无尘安，是说不移动。

</div>

佛说如是，彼诸比丘闻佛所说，欢喜奉行。

--------------

** 第30卷 大品.行欲经第十

我闻如是：一时，佛游舍卫国，在胜林给孤独园。

尔时，给孤独居士往诣佛所，稽首佛足，却坐一面，白曰：“世尊，世中为有几人行欲？”

世尊告曰：“居士，世中凡有十人行欲。云何为十？

“居士，有一行欲人，非法无道求索财物。彼非法无道求财物已，不自养安隐及父母、妻子、奴婢、作使，亦不供养沙门、梵志，令升上与乐俱而受乐报，生天长寿，如是有一行欲人也。

“复次，居士，有一行欲人，非法无道求索财物。彼非法无道求财物已，能自养安隐及父母、妻子、奴婢、作使，而不供养沙门、梵志，令升上与乐俱而受乐报，生天长寿，如是有一行欲人也。

“复次，居士，有一行欲人，非法无道求索财物。彼非法无道求财物已，能自养安隐及父母、妻子、奴婢、作使，亦供养沙门、梵志，令升上与乐俱而受乐报，生天长寿，如是有一行欲人也。

“复次，居士，有一行欲人，法非法求索财物。彼法非法求财物已，不自养安隐及父母、妻子、奴婢、作使，亦不供养沙门、梵志，令升上与乐俱而受乐报，生天长寿，如是有一行欲人也。

“复次，居士，有一行欲人，法非法求索财物。彼法非法求财物已，能自养安隐及父母、妻子、奴婢、作使，而不供养沙门、梵志，令升上与乐俱而受乐报，生天长寿，如是有一行欲人也。

“复次，居士，有一行欲人，法非法求索财物。彼法非法求财物已，能自养安隐及父母、妻子、奴婢、作使，亦供养沙门、梵志，令升上与乐俱而受乐报，生天长寿，如是有一行欲人也。

“复次，居士，有一行欲人，如法以道求索财物。彼如法以道求财物已，不自养安隐及父母、妻子、奴婢、作使，亦不供养沙门、梵志，令升上与乐俱而受乐报，生天长寿，如是有一行欲人也。

“复次，居士，有一行欲人，如法以道求索财物。彼如法以道求财物已，能自养安隐及父母、妻子、奴婢、作使，而不供养沙门、梵志，令升上与乐俱而受乐报，生天长寿，如是有一行欲行人也。

“复次，居士，有一行欲人，如法以道求索财物。彼如法以道求财物已，能自养安隐及父母、妻子、奴婢、作使，亦供养沙门、梵志，令升上与乐俱而受乐报，生天长寿；得财物已，染著缚缴；缴已染著，不见灾患，不知出要而用，如是有一行欲人也。

“复次，居士，有一行欲人，如法以道求索财物。彼如法以道求财物已，能自养安隐及父母、妻子、奴婢、作使，亦供养沙门、梵志，令升上与乐俱而受乐报，生天长寿；得财物已，不染不著，不缚不缴；不缴已染著，见灾患，知出要而用，如是有一行欲人也。

“居士，若有一行欲人，非法无道求索财物。彼非法无道求财物已，不自养安隐及父母、妻子、奴婢、作使，亦不供养沙门、梵志，令升上与乐俱而受乐报，生天长寿者，此行欲人于诸行欲人为最下也。

“居士，若有一行欲人，法非法求索财物。彼法非法求财物已，自养安隐及父母、妻子、奴婢、作使，亦供养沙门、梵志，令升上与乐俱而受乐报，生天长寿者，此行欲人于诸行欲人为最上也。

“居士，若有一行欲人，如法以道求索财物。彼如法以道求财物已，自养安隐及父母、妻子、奴婢、作使，亦供养沙门、梵志，令升上与乐俱而受乐报，生天长寿；得财物已，不染不著，不缚不缴；不缴已染著，见灾患，知出要而用者，此行欲人于诸行欲人为最第一、最大、最上、最胜、最尊，为最妙也。犹如因牛有乳，因乳有酪，因酪有生酥，因生酥有熟酥，因熟酥有酥精。酥精者，为最第一、最大、最上、最胜、最尊，为最妙也。如是，居士，此行欲人于诸行欲人为最第一、最大、最上、最胜、最尊，为最妙也。”

于是，世尊说此颂曰：

<div class="poem">

若非法求财，及法非法求，\\
不供不自用，亦不施为福，\\
二俱皆有恶，于行欲最下。\\
若如法求财，自身勤所得，\\
供他及自用，亦以施为福，\\
二俱皆有德，于行欲最上。\\
若得出要慧，行欲住在家，\\
见灾患知足，节俭用财物，\\
彼得出欲慧，于行欲最上。

</div>

佛说如是，给孤独居士及诸比丘闻佛所说，欢喜奉行。

--------------

** 第30卷 大品.福田经第十一

我闻如是：一时，佛游舍卫国，在胜林给孤独园。

尔时，给孤独居士往诣佛所，稽首佛足，却坐一面，白曰：“世尊，世中为有几福田人？”

世尊告曰：“居士，世中凡有二种福田人。云何为二？一者、学人，二者、无学人。学人有十八，无学人有九。居士，云何十八学人？信行、法行、信解脱、见到、身证、家家、一种、向须陀洹、得须陀洹、向斯陀含、得斯陀含、向阿那含、得阿那含、中般涅槃、生般涅槃、行般涅槃、无行般涅槃、上流色究竟，是谓十八学人。居士，云何九无学人？思法、升进法、不动法、退法、不退法、护法（护则不退，不护则退）、实住法、慧解脱、俱解脱，是谓九无学人。”

于是，世尊说此颂曰：

<div class="poem">

世中学、无学，可尊可奉敬，\\
彼能正其身，口意亦复然，\\
居士是良田，施彼得大福。

</div>

佛说如是，给孤独居士及诸比丘闻佛所说，欢喜奉行。

--------------

** 第30卷 大品.优婆塞经第十二

我闻如是：一时，佛游舍卫国，在胜林给孤独园。

尔时，给孤独居士与大优婆塞众五百人俱，往诣尊者舍梨子所，稽首作礼，却坐一面；五百优婆塞亦为作礼，却坐一面。给孤独居士及五百优婆塞坐一面已，尊者舍梨子为彼说法，劝发渴仰，成就欢喜；无量方便为彼说法，劝发渴仰，成就欢喜已，即从座起，往诣佛所，稽首佛足，却坐一面。尊者舍梨子去后不久，给孤独居士及五百优婆塞亦诣佛所，稽首佛足，却坐一面。

尊者舍梨子及众坐已定，世尊告曰：“舍梨子，若汝知白衣圣弟子善护行五法及得四增上心，现法乐居，易不难得。舍梨子，汝当记别圣弟子地狱尽，畜生、饿鬼及诸恶处亦尽，得须陀洹，不堕恶法，定趣正觉，极受七有，天上人间七往来已而得苦边。

“舍梨子，云何白衣圣弟子善护行五法？白衣圣弟子者，离杀、断杀，弃舍刀杖，有惭有愧，有慈悲心，饶益一切乃至昆虫，彼于杀生净除其心。白衣圣弟子善护行，此第一法。

“复次，舍梨子，白衣圣弟子离不与取、断不与取，与而后取，乐于与取，常好布施，劝喜无吝，不望其报，不以偷所覆，常自护已，彼于不与取净除其心。白衣圣弟子善护行，此第二法。

“复次，舍梨子，白衣圣弟子离邪淫、断邪淫，彼或有父所护，或母所护，或父母所护，或兄弟所护，或姊妹所护，或妇父母所护，或亲亲所护，或同姓所护，或为他妇女，有鞭罚恐怖，及有名雇赁至华鬘亲；不犯如是女，彼于邪淫净除其心。白衣圣弟子善护行，此第三法。

“复次，舍梨子，白衣圣弟子离妄言、断妄言，真谛言，乐真谛，住真谛不移动，一切可信，不欺世间，彼于妄言净除其心。白衣圣弟子善护行，此第四法。

“复次，舍梨子，白衣圣弟子离酒、断酒，彼于饮酒净除其心。白衣圣弟子善护行，此第五法。

“舍梨子，白衣圣弟子云何得四增上心，现法乐居，易不难得？白衣圣弟子念如来：‘彼如来、无所著、等正觉、明行成为、善逝、世间解、无上士、道法御、天人师，号佛、众佑。如是念如来已，若有恶欲即便得灭，心中有不善、秽污、愁苦、忧戚亦复得灭。白衣圣弟子攀缘如来，心静得喜，若有恶欲即便得灭，心中有不善、秽污、愁苦、忧戚亦复得灭。白衣圣弟子得第一增上心，现法乐居，易不难得。

“复次，舍梨子，白衣圣弟子念法：‘世尊善说法，必至究竟，无烦无热，常有不移动。如是观、如是觉、如是知、如是念法已，若有恶欲即便得灭，心中有不善、秽污、愁苦、忧戚亦复得灭。白衣圣弟子攀缘法，心静得喜，若有恶欲即便得灭，心中有不善、秽污、愁苦、忧戚亦复得灭。白衣圣弟子得此第二增上心。

“复次，舍梨子，白衣圣弟子念众：‘如来圣众善趣正趣，向法次法，顺行如法，彼众实有阿罗诃、趣阿罗诃，有阿那含、趣阿那含，有斯陀含、趣斯陀含，有须陀洹、趣须陀洹，是谓四双八辈。谓如来众成就尸赖，成就三昧，成就般若，成就解脱，成就解脱知见，可敬可重，可奉可供，世良福田。彼如是念如来众，若有恶欲即便得灭，心中有不善、秽污、愁苦、忧戚亦复得灭。白衣圣弟子攀缘如来众，心静得喜，若有恶欲即便得灭，心中有不善、秽污、愁苦、忧戚亦复得灭。白衣圣弟子是谓得第三增上心，现法乐居，易不难得。

“复次，舍梨子，白衣圣弟子自念尸赖：‘此尸赖不缺不穿，无秽无浊，住如地不虚妄，圣所称誉，具善受持。彼如是自念尸赖，若有恶欲即便得灭，心中有不善、秽污、愁苦、忧戚亦复得灭。白衣圣弟子攀缘尸赖，心静得喜，若有恶欲即便得灭，心中有不善、秽污、愁苦、忧戚亦复得灭。白衣圣弟子是谓得第四增上心，现法乐居，易不难得。

“舍梨子，若汝知白衣圣弟子善护行此五法，得此四增上心，现法乐居，易不难得者。舍梨子，汝记别白衣圣弟子地狱尽，畜生、饿鬼及诸恶处亦尽，得须陀洹，不堕恶法，定趣正觉，极受七有，天上人间七往来已而得苦边。”

于是，世尊说此颂曰：

<div class="poem">

慧者住在家，见地狱恐怖，\\
因受持圣法，除去一切恶。\\
不杀害众生，知而能舍离，\\
真谛不妄言，不盗他财物。\\
自有妇知足，不乐他人妻，\\
舍离断饮酒，心乱狂痴本。\\
常当念正觉，思惟诸善法，\\
念众观尸赖，从是得欢喜。\\
欲行其布施，当以望其福，\\
先施于息心，如是成果报。\\
我今说息心，舍梨子善听：\\
若有黑及白，赤色之与黄，\\
尨色爱乐色，牛及诸鸽鸟，\\
随彼所生处，良御牛在前。\\
身力成具足，善速往来快，\\
取彼之所能，莫以色为非。\\
如是此人间，若有所生处，\\
刹帝利梵志，居士本工师，\\
随彼所生处，长老净持戒，\\
世无著善逝，施彼得大果。\\
愚痴无所知，无慧无所闻，\\
施彼得果少，无光无所照。\\
若光有所照，有慧佛弟子，\\
信向善逝者，根生善坚住。\\
彼是生善处，如意往人家，\\
最后得涅槃，如是各有缘。

</div>

佛说如是，尊者舍梨子及诸比丘、给孤独居士、五百优婆塞闻佛所说，欢喜奉行。

--------------

** 第30卷 大品.怨家经第十三

我闻如是：一时，佛游舍卫国，在胜林给孤独园。

尔时，世尊告诸比丘：“有七怨家法而作怨家，谓男女辈瞋恚时来。云何为七？怨家者，不欲令怨家有好色。所以者何？怨家者，不乐怨家有好色。人有瞋恚，习瞋恚，瞋恚所覆，心不舍瞋恚，彼虽好沐浴，名香涂身，然色故恶。所以者何？因瞋恚所覆，心不舍瞋恚故。是谓第一怨家法而作怨家，谓男女辈瞋恚时来。

“复次，怨家者，不欲令怨家安隐眠。所以者何？怨家者，不乐怨家安隐眠。人有瞋恚，习瞋恚，瞋恚所覆，心不舍瞋恚，彼虽卧以御床，敷以氍氀、毾𣰆，覆以锦绮罗縠，有衬体被，两头安枕，加陵伽波惒逻波遮悉多罗那，然故忧苦眠。所以者何？因瞋恚所覆，心不舍瞋恚故。是谓第二怨家法而作怨家，谓男女辈瞋恚时来。

“复次，怨家者，不欲令怨家得大利。所以者何？怨家者，不乐怨家得大利。人有瞋恚，习瞋恚，瞋恚所覆，心不舍瞋恚，彼应得利而不得利，应不得利而得利。彼此二法更互相违，大得不利。所以者何？因瞋恚所覆，心不舍瞋恚故。是谓第三怨家法而作怨家，谓男女辈瞋恚时来。

“复次，怨家者，不欲令怨家有朋友。所以者何？怨家者，不乐怨家有朋友。人有瞋恚，习瞋恚，瞋恚所覆，心不舍瞋恚，彼若有亲朋友，舍离避去。所以者何？因瞋恚所覆，心不舍瞋恚故。是谓第四怨家法而作怨家，谓男女辈瞋恚时来。

“复次，怨家者，不欲令怨家有称誉。所以者何？怨家者，不乐怨家有名称。人有瞋恚，习瞋恚，瞋恚所覆，心不舍瞋恚，彼恶名丑声周闻诸方。所以者何？因瞋恚所覆，心不舍瞋恚故。是谓第五怨家法而作怨家，谓男女辈瞋恚时来。

“复次，怨家者，不欲令怨家极大富。所以者何？怨家者，不乐怨家极大富。人有瞋恚，习瞋恚，瞋恚所覆，心不舍瞋恚，彼作如是身、口、意行，使彼大失财物。所以者何？因瞋恚所覆，心不舍瞋恚故。是谓第六怨家法而作怨家，谓男女辈瞋恚时来。

“复次，怨家者，不欲令怨家身坏命终，必至善处，生于天上。所以者何？怨家者，不乐怨家往至善处。人有瞋恚，习瞋恚，瞋恚所覆，心不舍瞋恚，身、口、意恶行。彼身、口、意恶行已，身坏命终，必至恶处，生地狱中。所以者何？因瞋恚所覆，心不舍瞋恚故。是谓第七怨家法而作怨家，谓男女辈瞋恚时来。此七怨家法而作怨家，谓男女辈瞋恚时来。”

于是，世尊说此颂曰：

<div class="poem">

瞋者得恶色，眠卧苦不安，\\
应获得大财，反更得不利。\\
亲亲善朋友，远离瞋恚人，\\
数数习瞋恚，恶名流诸方。\\
瞋作身口业，恚缠行意业，\\
人为恚所覆，失一切财物。\\
瞋恚生不利，瞋恚生心秽，\\
恐怖生于内，人所不能觉。\\
瞋者不知义，瞋者不晓法，\\
无目盲暗塞，谓乐瞋恚人。\\
恚初发恶色，犹火始起烟，\\
从是生憎嫉，缘是诸人瞋。\\
若瞋者所作，善行及不善，\\
于后瞋恚盛，烦热如火烧。\\
所谓烦热业，及诸法所缠，\\
彼彼我今说，汝等善心听。\\
瞋者逆害父，及于诸兄弟，\\
亦杀姊与妹，瞋者多所残。\\
所生及长养，得见此世间，\\
因彼得存命，此母瞋亦害。\\
无羞无惭愧，瞋缠无所言，\\
人为恚所覆，口无所不说。\\
造作痴罪业，而自夭其命，\\
作时不自觉，因瞋生恐怖。\\
系著自己身，爱乐无极已，\\
虽爱念己身，瞋者亦自害。\\
以刀而自刺，或从岩自投，\\
或以绳自绞，及服诸毒药。\\
如是像瞋恚，是死依于恚，\\
彼彼一切断，用慧能觉了。\\
小小不善业，慧者了能除，\\
当堪耐是行，欲令无恶色。\\
无恚亦无忧，除烟无贡高，\\
调御断瞋恚，灭讫无有漏。

</div>

佛说如是，彼诸比丘闻佛所说，欢喜奉行。

--------------

** 第30卷 大品.教昙弥经第十四

我闻如是：一时，佛游舍卫国，在胜林给孤独园。

尔时，尊者昙弥为生地尊长，作佛图主，为人所宗，凶暴急弊，极为粗恶，骂詈责数于诸比丘，因此故生地诸比丘皆舍离去，不乐住此。于是，生地诸优婆塞见生地诸比丘皆舍离去，不乐住此，便作是念：“此生地诸比丘以何意故，皆舍离去，不乐住此？”生地诸优婆塞闻此生地尊者昙弥------生地尊长，作佛图主，为人所宗，凶暴急弊，极为粗恶，骂詈责数于诸比丘，因此故生地诸比丘皆舍离去，不乐住此。生地诸优婆塞闻已，即共往诣尊者昙弥所，驱逐昙弥，令出生地诸寺中去。

于是，尊者昙弥为生地诸优婆塞所驱，令出生地诸寺中去，即摄衣持钵游行，往诣舍卫国，展转进至舍卫国，住胜林给孤独园。于是，尊者昙弥往诣佛所，稽首佛足，却坐一面，白曰：“世尊，我于生地诸优婆塞无所污、无所说、无所犯，然生地诸优婆塞横驱逐我，令出生地诸寺中去。”

彼时世尊告曰：“止！止！昙弥，何须说此？”

尊者昙弥叉手向佛，再白曰：“世尊，我于生地诸优婆塞无所污、无所说、无所犯，然生地诸优婆塞横驱逐我，令出生地诸寺中去。”

世尊亦再告曰：“昙弥，往昔之时，此阎浮洲有诸商人乘船入海，持视岸鹰行，彼入大海不远，便放视岸鹰。若视岸鹰得至大海岸者，终不还船。若视岸鹰不得至大海岸者，便来还船。如是，昙弥，为生地优婆塞所驱逐，令出生地诸寺故，便还至我所。止！止！昙弥，何须复说此？”

尊者昙弥复三白曰：“世尊，我于生地诸优婆塞无所污、无所说、无所犯，然生地诸优婆塞横驱逐我，令出生地诸寺中去。”

世尊亦复三告曰：“昙弥，汝住沙门法，为生地诸优婆塞所驱逐，令出生地诸寺耶？”

于是，尊者昙弥即从座起，叉手向佛，白曰：“世尊，云何沙门住沙门法？”

世尊告曰：“昙弥，昔时有人寿八万岁。昙弥，人寿八万岁时，此阎浮洲极大富乐，多有人民，村邑相近，如鸡一飞。昙弥，人寿八万岁时，女年五百岁乃嫁。昙弥，人寿八万岁时，有如是病------大便、小便、欲、不食、老。昙弥，人寿八万岁时，有王名高罗婆，聪明智慧，为转轮王，有四种军，整御天下，如法法王成就七宝。彼七宝者，轮宝、象宝、马宝、珠宝、女宝、居士宝、主兵臣宝，是为七。具足千子，颜貌端正，勇猛无畏，能伏他众。彼必统领此一切地乃至大海，不以刀杖，以法治化，令得安隐。

“昙弥，高罗婆王有树，名善住尼拘类树王。昙弥，善住尼拘类树王而有五枝，第一枝者，王所食及皇后；第二枝者，太子食及诸臣；第三枝者，国人民食；第四枝者，沙门、梵志食；第五枝者，禽兽所食。昙弥，善住尼拘类树王果大如二升瓶，味如淳蜜丸。昙弥，善住尼拘类树王果无有护者，亦无更相偷。有一人来，饥渴极羸，颜色憔悴，欲得食果，往至善住尼拘类树王所，饱啖果已，毁折其枝，持果归去。善住尼拘类树王有一天依而居之，彼作是念：‘阎浮洲人异哉无恩，无有反复。所以者何？从善住尼拘类树王饱啖果已，毁折其枝，持果归去，宁令善住尼拘类树王无果，不生果。善住尼拘类树王即无果，亦不生果。

“复有一人来，饥渴极羸，颜色憔悴，欲得啖果，往诣善住尼拘类树王所，见善住尼拘类树王无果，亦不生果，即便往诣高罗婆王所，白曰：‘天王，当知善住尼拘类树王无果，亦不生果。高罗婆王闻已，犹如力士屈伸臂顷，如是高罗婆王于拘楼瘦没，至三十三天，住天帝释前，白曰：‘拘翼，当知善住尼拘类树王无果，亦不生果。于是，天帝释及高罗婆王犹如力士屈伸臂顷，如是天帝释及高罗婆王于三十三天中没，至拘楼瘦，去善住尼拘类树王不远住。天帝释作如其像如意足，以如其像如意足化作大水暴风雨；作大水暴风雨已，善住尼拘类树王拔根倒竖。

“于是，善住尼拘类树王居止树天，因此故，忧苦愁戚，啼泣垂泪，在天帝释前立。天帝释问曰：‘天，汝何意忧苦愁戚，啼泣垂泪，在我前立耶？彼天白曰：‘拘翼，当知大水暴风雨，善住尼拘类树王拔根倒竖。时，天帝释告彼树天曰：‘天，汝树天住树天法，大水暴风雨，善住尼拘类树王拔根倒竖耶？树天白曰：‘拘翼，云何树天住树天法耶？天帝释告曰：‘天，若使人欲得树根，持树根去；欲得树茎、树技、树叶、树华、树果持去者，树天不应瞋恚，不应憎嫉，心不应恨。树天舍意而住树天，如是树天住树天法。”

“天复白曰：‘拘翼，我树天不住树天法。从今日始树天住树天法，愿善住尼拘类树王还复如本。于是，天帝释作如其像如意足，作如其像如意足已，复化作大水暴风雨；化作大水暴风雨已，善住尼拘类树王即复如故。如是，昙弥，若有比丘骂者不骂，瞋者不瞋，破者不破，打者不打。如是，昙弥，沙门住沙门法。”

于是，尊者昙弥即从座起，偏袒著衣，叉手向佛，啼泣垂泪，白曰：“世尊，我非沙门住沙门法，从今日始沙门住沙门法。”

世尊告曰：“昙弥，昔有大师，名曰善眼，为外道仙人之所师宗，舍离欲爱，得如意足。昙弥，善眼大师有无量百千弟子。昙弥，善眼大师为诸弟子说梵世法。昙弥，若善眼大师为说梵世法时，诸弟子等有不具足奉行法者，彼命终已，或生四王天，或生三十三天，或生㷿磨天，或生兜率哆天，或生化乐天，或生他化乐天。昙弥，若善眼大师为说梵世法时，诸弟子等设有具足奉行法者，彼修四梵室，舍离于欲，彼命终已，得生梵天。昙弥，彼时善眼大师而作是念：‘我不应与弟子等同俱至后世，共生一处。我今宁可更修增上慈，修增上慈已，命终得生晃昱天中。

“昙弥，彼时善眼大师则于后时更修增上慈；修增上慈已，命终得生晃昱天中。昙弥，善眼大师及诸弟子学道不虚，得大果报。如善眼大师，如是牟梨破群那、阿罗那遮婆罗门、瞿陀梨舍哆、害提婆罗摩纳、储提摩丽桥鞞陀逻，及萨哆富楼奚哆。

“昙弥，七富楼奚哆师亦有无量百千弟子。昙弥，七富楼奚哆师为诸弟子说梵世法。若七富楼奚哆师为说梵世法时，诸弟子等有不具足奉行法者，彼命终已，或生四王天，或生三十三天，或生㷿磨天，或生兜率哆天，或生化乐天，或生他化乐天。若七富楼奚哆师为说梵世法时，诸弟子等设有具足奉行法者，彼修四梵室，舍离于欲，彼命终已，得生梵天。昙弥，七富楼奚哆师而作是念：‘我不应与弟子等同俱至后世，共生一处。我今宁可更修增上慈，修增上慈已，命终得生晃昱天中。

“昙弥，彼时七富楼奚哆师则于后时更修增上慈；修增上慈已，命终得生晃昱天中。昙弥，七富楼奚哆师及诸弟子学道不虚，得大果报。昙弥，若有骂彼七师及无量百千眷属，打破瞋恚责数者，必受无量罪。若有一成就正见佛弟子比丘得小果，骂詈打破瞋恚责数者，此受罪多于彼。是故，昙弥，汝等各各更迭相护。所以者何？离此过已，更无有失。”

于是，世尊说此颂曰：

<div class="poem">

须涅、牟梨破群那、阿罗那遮婆罗门、瞿陀梨舍哆、害提婆罗摩纳、储提摩丽桥鞞陀逻、萨哆楼富楼奚哆。\\
此在过去世，七师有名德，\\
无爱缚乐悲，欲结尽过去。\\
彼有诸弟子，无量百千数，\\
彼亦离欲结，须臾不究竟。\\
若彼外仙人，善护行苦行，\\
心中怀憎嫉，骂者受罪多。\\
若一得正见，佛子住小果，\\
骂詈责打破，受罪多于彼。\\
是故汝昙弥，各各更相护，\\
所以更相护，重罪无过是。\\
如是甚重苦，亦为圣所恶，\\
必得受恶色，横取邪见处。\\
此是最下人，圣法之所说，\\
谓未离淫欲，得微妙五根，\\
信、精进、念处，正定及正观。\\
如是得此苦，前所受其殃，\\
自受其殃已，于后便害他。\\
若能自护者，彼为能护外，\\
是故当自护，慧者无殃乐。

</div>

佛说如是，尊者昙弥及诸比丘闻佛所说，欢喜奉行。

--------------

** 第30卷 大品.降魔经第十五

我闻如是：一时，佛游婆奇瘦，在鼉山怖林鹿野园中。

尔时，尊者大目揵连教授为佛而作禅屋，露地经行。彼时，魔王化作细形，入尊者大目揵连腹中。于是，尊者大目揵连即作是念：“我今腹重犹如食豆，我宁可入如其像定，以如其像定自观其腹。”是时，尊者大目揵连至经行道头，敷尼师檀，结跏趺坐，入如其像定，以如其像定自观其腹，尊者大目揵连便知魔王在其腹中。

尊者大目揵连即从定寤，语魔王曰：“汝波旬出！汝波旬出！莫触娆如来，亦莫触娆如来弟子，莫于长夜无义无饶益，必生恶处，受无量苦。”

彼时，魔王便作是念：“此沙门不见不知而作是说：‘汝波旬出！汝波旬出！莫触娆如来，亦莫触娆如来弟子，莫于长夜无义无饶益，必生恶处，受无量苦。汝之尊师有大如意足，有大威德，有大福佑，有大威神，彼犹不能速知速见，况复弟子能知见耶？”

尊者大目揵连复语魔王：“我复知汝意，汝作是念：‘此沙门不知不见而作是说：“汝波旬出！汝波旬出！莫触娆如来，亦莫触娆如来弟子，莫于长夜无义无饶益，必生恶处，受无量苦。”汝之尊师有大如意足，有大威德，有大福佑，有大威神，彼犹不能如是速知速见，况复弟子能知见耶？”

彼魔波旬复作是念：“今此沙门知见我故，而作是说耳！”于是，魔波旬化作细形，从口中出，在尊者大目揵连前立。

尊者大目揵连告曰：“波旬，昔有如来名觉砾拘荀大无所著、等正觉，我时作魔，名曰恶。我有妹，名黑，汝是彼子。波旬，因此事故，汝是我外甥。波旬，觉砾拘荀大如来、无所著、等正觉有二大弟子，一者名音，二者名想。

“波旬，以何义故，尊者音名音耶？波旬，尊者音住梵天上，以常音声满千世界，更无有弟子音声与彼等者、相似者、胜者。波旬，以是义故，尊者音名音也。

“波旬，复以何义尊者想名想耶？波旬，尊者想所依游行村邑，过夜平旦，著衣持钵，入村乞食，善护其身，善摄诸根，立于正念。彼乞食已，食讫，中后收举衣钵，澡洗手足，以尼师檀著于肩上，至无事处，或至山林树下，或至闲居静处，敷尼师檀，结跏趺坐，速入想知灭定。彼时，若有放牛羊人、取樵草人，或行路人，入彼山林，见入想知灭定，便作是念：‘今此沙门于无事处坐而命终，我等宁可以燥樵、草拾已，积聚覆其身上而耶维之！即拾樵、草积覆其身，以火燃之，便舍而去。彼尊者想过夜平旦，从定寤起，抖擞衣服，所依村邑游行，如常著衣，持钵入村乞食，善护其身，善摄诸根，立于正念。彼放牛羊人、取樵草人，或行路人，入彼山林人先见者，便作是念：‘今此沙门在无事处坐而命终，我等昨已拾燥樵、草积覆其身，以火烧之，燃已而去。然此贤者更复想也！波旬，以是义故，尊者想名想也。

“波旬，彼时恶魔便作是念：‘此秃沙门以黑所缚，断种无子，彼学禅，伺、增伺、数数伺。犹若如驴，竟日负重，系在枥上，不得麦食，为彼麦故，伺、增伺、数数伺；如是，此秃沙门为黑所缚，断种无子，学禅，伺、增伺、数数伺。犹如猫子在鼠穴边，欲捕鼠故，伺、增伺、数数伺；如是，此秃沙门为黑所缚，断种无子，彼学禅，伺、增伺、数数伺。犹如鸺狐在燥樵积间，为捕鼠故，伺、增伺、数数伺；如是，此秃沙门为黑所缚，断种无子，学禅，伺、增伺、数数伺。犹如鹤鸟在水岸边，为捕鱼故，伺、增伺、数数伺；如是，此秃沙门为黑所缚，断种无子，学禅，伺、增伺、数数伺。彼何所伺？为何义伺？求何等伺？彼调乱狂发败坏。我不知彼何所从来，亦不知彼何所从去，亦不知住止，不知死不知生，我宁可教敕梵志、居士：“汝等共来骂詈精进沙门，打破责数。所以者何？或骂打破责数时，倘能起恶心，令我得其便。”

“波旬，彼时恶魔便教敕梵志、居士，彼梵志、居士骂詈精进沙门，打破责数。彼梵志、居士或以木打，或以石掷，或以杖挝，或伤精进沙门头，或裂坏衣，或破应器。尔时，梵志、居士若有死者，因此缘此，身坏命终，必至恶处，生地狱中。彼生已，作是念：‘我应受此苦，当复更受极苦过是。所以者何？以我等向精进沙门行恶行故。

“波旬，觉砾拘荀大如来、无所著、等正觉弟子用伤其头，裂坏其衣，破其应器已，往诣觉砾拘荀大如来、无所著、等正觉所。尔时，觉砾拘荀大如来、无所著、等正觉无量百千眷属围绕而为说法，觉砾拘荀大如来、无所著、等正觉遥见弟子头伤、衣裂、钵破而来，见已，告诸比丘：‘汝等见不？恶魔教敕梵志、居士：“汝等共来骂詈精进沙门，打破责数。所以者何？或骂打破责数时，倘能起恶心，令我得其便。”比丘，汝等当以心与慈俱，遍满一方成就游。如是二三四方，四维上下，普周一切，心与慈俱，无结无怨，无恚无诤，极广甚大，无量善修，遍满一切世间成就游。如是悲、喜，心与舍俱，无结无怨，无恚无诤，极广甚大，无量善修，遍满，一切世间成就游，令恶魔求便不能得便。

“波旬，觉砾拘荀大如来、无所著、等正觉以此教教诸弟子，彼即受教，心与慈俱，遍满一方成就游。如是二三四方，四维上下，普周一切，心与慈俱，无结无怨，无恚无诤，极广甚大，无量善修，遍满一切世间成就游。如是悲、喜，心与舍俱，无结无怨，无恚无诤，极广甚大，无量善修，遍满一切世间成就游。以此故，彼恶魔求便不能得便。

“波旬，彼时恶魔复作是念：‘我以此事求精进沙门便，而不能得。我宁可教敕梵志、居士：“汝等共来奉敬、供养、礼事精进沙门，或以奉敬，供养、礼事精进沙门，倘能起恶心，令我得其便。”波旬，彼梵志、居士为恶魔所教敕已，即共奉敬、供养、礼事精进沙门，以衣敷地而作是说：‘精进沙门可于上行，精进沙门难行而行，令我长夜得利饶益，安隐快乐！梵志、居士以发布地而作是说：‘精进沙门可于上行，精进沙门难行而行，令我长夜得利饶益，安隐快乐！梵志、居士以手捧持种种饮食，住道边待而作是说：‘精进沙门受是食是，可持是去，随意而用，令我长夜得利饶益，安隐快乐！诸信梵志、居士见精进沙门，敬心扶抱，将入于内，持种种财物与精进沙门，作如是说：‘受是用是，可持是去，随意所用。尔时，梵志、居士若有死者，因此缘此，身坏命终，必至善处，生于天上。生已，作是念：‘我应受是乐，当复更受极乐胜是。所以者何？以我等向精进沙门行善行故。

“波旬，觉砾拘荀大如来、无所著、等正觉弟子得奉敬、供养、礼事已，往诣觉砾拘荀大如来、无所著、等正觉所。是时，觉砾拘荀大如来、无所著、等正觉无量百千眷属围绕而为说法，觉砾拘荀大如来、无所著、等正觉遥见弟子得奉敬、供养、礼事而来，见已，告诸比丘：‘汝等见不？恶魔教敕梵志、居士：“汝等共来奉敬、供养、礼事精进沙门，或以奉敬、供养、礼事精进沙门，倘能起恶心，令我得其便。”比丘，汝等当观诸行无常，观兴衰法，观无欲，观舍离，观灭，观断，令恶魔求便而不能得。波旬，觉砾拘荀大如来、无所著、等正觉以此教教诸弟子，彼即受教，观一切行无常，观兴衰法，观无欲，观舍离，观灭，观断，令恶魔求便而不能得。

“波旬，彼时恶魔复作是念：‘我以此事求精进沙门便，而不能得。我宁可化作年少形，手执大杖，住其道边，打尊者音头，令破血流污面。波旬，觉砾拘荀大如来、无所著、等正觉于后所依村邑游行，彼于平旦著衣持钵，入村乞食，尊者音在后侍从。波旬，尔时恶魔化作年少形，手执大杖，住在道边，击尊者音头破血流污面。波旬，尊者音破头流血已，随从觉砾拘荀大如来、无所著、等正觉后，犹影不离。

“波旬，觉砾拘荀大如来、无所著、等正觉至村邑已，极其身力右旋顾视，犹如龙视，不恐不怖，不惊不惧而观诸方。波旬，觉砾拘荀大如来、无所著、等正觉见尊者音头破血流污面，随佛后行，如影不离，便作是说：‘此恶魔凶暴，大有威力，此恶魔不知厌足。波旬，觉砾拘荀大如来、无所著、等正觉说语未讫，彼时，恶魔便于彼处，其身即堕无缺大地狱。波旬，此大地狱而有四名：一者、无缺，二者、百钉，三者、逆刺，四者、六更。彼大地狱其中有卒，往至恶魔所，语恶魔曰：‘汝今当知，若钉钉等共合者，当知满百年。”

于是，魔波旬闻说此已，即便心悸，恐怖惊惧，身毛皆竖，向尊者大目揵连即说颂曰：

<div class="poem">

云何彼地狱，恶魔昔在中？\\
娆害佛梵行，及犯彼比丘。

</div>

尊者大目揵连即时以偈答魔波旬曰：

<div class="poem">

地狱名无缺，恶魔曾在中，\\
娆害佛梵行，及犯彼比丘。\\
彼铁钉有百，一切各逆刺，\\
地狱名无缺，恶魔昔在中。\\
若有不知者，比丘佛弟子，\\
必得如是苦，受黑业之报。\\
若干种园观，人者在于地，\\
食自然粳米，居止在北洲。\\
大须弥山岩，善修之所熏，\\
修习于解脱，受持最后身。\\
跱立在大泉，宫殿住至劫，\\
金色可爱乐，犹火㷿晃昱。\\
作诸众妓乐，往诣帝释所，\\
本以一屋舍，善觉了为施。\\
若释在前行，升毗阇延殿，\\
见释大欢喜，天女各各舞。\\
若见比丘来，还顾有惭愧，\\
若毗阇延殿，见比丘问义：\\
大仙颇能知，爱尽得解脱？\\
比丘即为答：问者如其义，\\
拘翼我能知，爱尽得解脱。\\
闻彼之所答，释得欢喜乐，\\
比丘多饶益，所说如其义。\\
若毗阇延殿，问帝释天王：\\
此殿名何等，汝释摄持城？\\
释答大仙人，名毗阇延哆，\\
是谓千世界，于千世界中，\\
无有胜此殿，如毗阇延哆，\\
天王天帝释，自在随所游。\\
受乐那游哆，化作一行百，\\
毗阇延殿内，释得自在游。\\
毗阇延大殿，足指能震动，\\
天王眼所观，释得自在游。\\
若鹿子母堂，筑基极深坚，\\
难动不可震，如意足能摇。\\
彼有琉璃地，圣人之所履，\\
滑泽乐更触，布柔软绵褥。\\
爱语共和合，天王常欢喜，\\
善能作妓乐，音节善谐和。\\
诸天来会聚，而说须陀洹，\\
若干无量千，及百诸那术。\\
至三十三天，慧眼者说法，\\
闻彼所说法，欢喜而奉行。\\
我亦有是法，如仙人所说，\\
谓至梵天上，问彼梵天事。\\
梵故有此见，谓见昔时有，\\
我住有常存，恒有不变易。\\
梵天为答彼，大仙我无见，\\
谓见昔时有，我恒常不变。\\
我见此境界，诸梵皆过去，\\
我今何由说，恒常不变易。\\
我见此世间，正觉之所说，\\
随所因缘生，所往而转还。\\
火无有思念，我烧愚痴人，\\
火燃若愚触，必自然得烧。\\
如是汝波旬，触娆于如来，\\
久作不善行，受报亦当久，\\
魔汝莫厌佛，莫娆害比丘。

</div>

<div class="poem">

一比丘降魔，住在于怖林。\\
彼鬼愁忧戚，目连之所诃，\\
恐怖无智慧，即于彼处没。

</div>

尊者大目揵连所说如是，彼魔波旬闻尊者大目揵连所说，欢喜奉行。

--------------

** 第31卷 大品.赖吒和罗经第十六

我闻如是：一时，佛游拘楼瘦，与大比丘众俱，往至鍮芦吒，住鍮芦吒村北尸摄惒园中。

尔时，鍮芦吒梵志、居士闻：沙门瞿昙释种子舍释宗族，出家学道，游拘楼瘦，与大比丘众俱，来至此鍮芦吒，住鍮芦吒村北尸摄惒园中。彼沙门瞿昙有大名称，周闻十方，沙门瞿昙如来、无所著、等正觉、明行成为、善逝、世间解、无上士、道法御、天人师，号佛、众佑。彼于此世，天及魔、梵、沙门、梵志，从人至天，自知、自觉、自作证成就游。彼若说法，初妙、中妙、竟亦妙，有义有文，具足清净，显现梵行。若见如来、无所著、等正觉，尊重礼拜，供养承事者，快得善利！“我等应共往见沙门瞿昙礼拜供养。”

鍮芦吒梵志、居士闻已，各与等类眷属相随，从鍮芦吒出，北行至尸摄惒园，欲见世尊礼拜、供养。往诣佛已，彼鍮芦吒梵志、居士或稽首佛足，却坐一面；或问讯佛，却坐一面；或叉手向佛，却坐一面；或遥见佛已，默然而坐。彼时，鍮芦吒梵志、居士各坐已定，佛为说法，劝发渴仰，成就欢喜；无量方便为彼说法，劝发渴仰，成就欢喜已，默然而住。时，鍮芦吒梵志、居士，佛为说法，劝发渴仰，成就欢喜已，各从座起，稽首佛足，绕佛三匝而去。

彼时，赖吒惒罗居士子故坐不起。于是，赖吒惒罗居士子，鍮芦吒梵志、居士去后不久，即从座起，偏袒著衣，叉手向佛，白曰：“世尊，如我知佛所说法者，若我在家，为锁所锁，不得尽形寿清净行梵行。世尊，愿我得从世尊出家学道而受具足，得作比丘，净修梵行。”

世尊问曰：“居士子，父母听汝于正法、律中至信、舍家、无家、学道耶？”

赖吒惒罗居士子白曰：“世尊，父母未听我于正法、律中至信、舍家、无家、学道。”

世尊告曰：“居士子，若父母不听汝于正法、律中至信、舍家、无家、学道者，我不得度汝出家学道，亦不得授具足。”

赖吒惒罗居士子白曰：“世尊，我当方便从父母求，必令听我于正法、律中至信、舍家、无家、学道。”

世尊告曰：“居士子，随汝所欲。”

于是，赖吒惒罗居士子闻佛所说，善受善持，稽首佛足，绕三匝还归，白曰：“二尊，如我知佛所说法者，若我在家，为锁所锁，不得尽形寿清净行梵行。惟愿二尊听我于正法、律中至信、舍家、无家、学道。”

赖吒惒罗父母告曰：“赖吒惒罗，我今唯有汝一子，极爱怜念，意常爱乐，见无厌足。若汝命终，我尚不欲相弃舍也，况生别离不见汝耶？”

赖吒惒罗居士子复至再三白曰：“二尊，如我知佛所说法者，若我在家，为锁所锁，不得尽形寿清净行梵行。惟愿二尊听我于正法、律中至信、舍家、无家、学道。”

赖吒惒罗居士子父母亦至再三告曰：“赖吒惒罗，我今唯有汝一子，极爱怜念，意常爱乐，见无厌足。若汝命终，我尚不欲相弃舍也，况生别离不见汝耶！”

于是，赖吒惒罗居士子即时卧地：“从今不起，不饮不食，乃至父母听我于正法、律中至信、舍家、无家、学道！”

于是，赖吒惒罗居士子一日不食，至二、三、四，多日不食。

于是，赖吒惒罗居士子父母往至子所，告曰：“赖吒惒罗，汝至柔软，身体极好，常坐卧好床，汝今不知苦耶？赖吒惒罗，汝可速起，行欲布施，快修福业。所以者何？赖吒惒罗，世尊境界甚难甚难！出家学道亦复甚难！”

尔时，赖吒惒罗居士子默然不答。于是，赖吒惒罗居士子父母往至赖吒惒罗亲亲及诸臣所，而作是语：“汝等共来至赖吒惒罗所，劝令从地起。”

赖吒惒罗居士子亲亲及诸臣等即便共至赖吒惒罗所，语曰：“赖吒惒罗，汝至柔软，身体极好，常坐卧好床，汝今不知苦耶？赖吒惒罗，汝可速起，行欲布施，快修福业。所以者何？世尊境界甚难甚难！出家学道亦复甚难！”

彼时，赖吒惒罗居士子默然不答。于是，赖吒惒罗居士子父母至赖吒惒罗居士子善知识、同伴、同时所，而作是语：“汝等共来至赖吒惒罗所，劝令从地起。”

于是，赖吒惒罗居士子善知识、同伴、同时即共往诣赖吒惒罗居士子所，而作是语：“赖吒惒罗，汝至柔软，身体极好，常坐卧好床，汝今不知苦耶？赖吒惒罗，汝可速起，行欲布施，快修福业。所以者何？赖吒惒罗，世尊境界甚难甚难！出家学道亦复甚难！”彼时，赖吒惒罗居士子默然不答。

于是，赖吒惒罗居士子善知识、同伴、同时往至赖吒惒罗居士子父母所，作如是语：“可听赖吒惒罗于正法、律中至信、舍家、无家、学道。若其乐者，于此生中，故可相见。若不乐者，必自来还归父母所。今若不听，定死无疑，当何所益？”

于是，赖吒惒罗居士子父母闻已，语赖吒惒罗居士子善知识、同伴、同时曰：“我今听赖吒惒罗于正法、律中至信、舍家、无家、学道。若学道来还，故可见也。”

赖吒惒罗居士子善知识、同伴、同时即共往诣赖吒惒罗所，便作是语：“居士子，父母听汝于正法、律中至信、舍家、无家、学道。若学道已，还见父母。”

赖吒惒罗居士子闻是语已，便大欢喜，生爱生乐，从地而起，渐养其身。身平复已，从鍮芦吒出，往诣佛所，稽首佛足，白曰：“世尊，父母听我于正法、律中至信、舍家、无家、学道。惟愿世尊，听从世尊出家学道而受具足，得作比丘。”

于是，世尊度赖吒惒罗居士子出家学道，授其具足。授具足已，于鍮芦吒随住数时，于后则便摄衣持钵，游行展转，往至舍卫国，住胜林给孤独园。尊者赖吒惒罗出家学道，受具足已，在远离独住，心无放逸，修行精勤。彼在远离独住，心无放逸，修行精勤已，族姓子所为剃除须发，著袈裟衣，至信、舍家、无家、学道者，唯无上梵行讫，于现法中自知、自觉、自作证成就游：生已尽，梵行已立，所作已办，不更受有，知如真。尊者赖吒惒罗知法已，至得阿罗诃。

于是，尊者赖吒惒罗得阿罗诃已，后或九年、十年，而作是念：“我本已许出家学道，还见父母，我今宁可还赴本要。”于是，尊者赖吒惒罗往诣佛所，稽首佛足，却坐一面，白曰：“世尊，我本有要，出家学道已，还见父母。世尊，我今辞行，往见父母，赴其本要。”

尔时，世尊便作是念：“此赖吒惒罗族姓子，若使舍戒，罢道行欲如本者，必无是处。”世尊知已，告曰：“汝去未度者度，未解脱者令得解脱，未灭讫者令得灭讫。赖吒惒罗，今随汝意。”

彼时，尊者赖吒惒罗闻佛所说，善受善持，即从座起，稽首佛足，绕三匝而去，至己房中，收举卧具，著衣持钵，游行展转，往至鍮芦吒，住鍮芦吒村北尸摄惒园。

于是，尊者赖吒惒罗过夜平旦，著衣持钵，入鍮芦吒而行乞食。尊者赖吒惒罗作如是念：“世尊称叹次第乞食，我今宁可于此鍮芦吒次第乞食。”尊者赖吒惒罗便于鍮芦吒次第乞食，展转至本家。

彼时，尊者赖吒惒罗父在中门住，修理须发。尊者赖吒惒罗父遥见尊者赖吒惒罗来，便作是语：“此秃沙门为黑所缚，断种无子，破坏我家。我有一子，极爱怜念，意常忍乐，见无厌足，彼将去度，当莫与食。”

尊者赖吒惒罗自于父家不得布施，但得责数：“此秃沙门为黑所缚，断种无子，破坏我家。我有一子，极爱怜念，意常爱乐，见无厌足，彼将去度，当莫与食。”

尊者赖吒惒罗知已，便速出去。

彼时，尊者赖吒惒罗父家婢使以箕盛臭烂饮食，欲弃著粪聚中。尊者赖吒惒罗见父婢使以箕盛臭烂饮食，欲弃著粪聚中，便作是语：“汝妹，若此臭烂饮食法应弃者，可著我钵中，我当食之。”

彼时，尊者赖吒惒罗父家婢使以箕中臭烂饮食泻著钵中，泻著钵中时取其二相识，其音声及其手足；取二相已，即往至尊者赖吒惒罗父所，而作是语：“尊今当知，尊子赖吒惒罗还来至此鍮芦吒，可往见之。”

尊者赖吒惒罗父闻已，大欢喜踊跃，左手摄衣，右手摩抆须发，疾往诣尊者赖吒惒罗所。

彼时，尊者赖吒惒罗向壁食此臭烂食。尊者赖吒惒罗父见尊者赖吒惒罗向壁食此臭烂食，作如是说：“汝赖吒惒罗，汝至柔软，身体极好，常食好食。赖吒惒罗，汝云何乃食此臭烂食耶？赖吒惒罗，汝以何意来此鍮芦吒，而不能还至父母家耶？”

尊者赖吒惒罗白曰：“居士，我入父家不得布施，但得责数：‘此秃沙门为黑所缚，断种无子，破坏我家。我唯有一子，至爱怜念，意常爱乐，见无厌足，彼将去度，当莫与食。我闻此已，便速出去。”

尊者赖吒惒罗父即辞谢曰：“赖吒惒罗可忍！赖吒惒罗可忍！我实不知赖吒惒罗还入父家。”

于是，尊者赖吒惒罗父敬心扶抱尊者赖吒惒罗，将入于内，敷座令坐，尊者赖吒惒罗即便就坐。

于是，其父见尊者赖吒惒罗坐已，往至妇所，而作是语：“卿今当知，赖吒惒罗族姓子今来还家，可速办饮食！”

尊者赖吒惒罗母闻已，大欢喜踊跃，速办饮食。办饮食已，疾辇钱出，著中庭地，聚作大积。彼大钱积，一面立人，一面坐人，各不相见。作大钱积已，往诣尊者赖吒惒罗所，作如是语：“赖吒惒罗，是汝母分所有钱财，汝父钱财无量，百千不可复计，今尽付汝。赖吒惒罗，汝可舍戒罢道，行欲布施，快修福业。所以者何？世尊境界甚难甚难！出家学道亦复甚难！”

尊者赖吒惒罗白其母曰：“我今欲有所说，能见听不？”

尊者赖吒惒罗母语曰：“居士子，汝有所说，我当听之。”

尊者赖吒惒罗白其母曰：“当作新布囊，用盛满钱，以车载之，至恒伽江，泻著深处。所以者何？因此钱故，令人忧苦、愁戚、啼哭，不得快乐。”

于是，尊者赖吒惒罗母而作是念：“以此方便不能令子赖吒惒罗舍戒罢道，我宁可至其本妇所，作如是语：‘诸新妇等，汝可以先所著璎珞严饰其身，赖吒惒罗族姓子本在家时极所爱念。以此璎珞速严身已，汝等共往至赖吒惒罗族姓子所，各抱一足而作是说：不审贤郎有何天女胜于我者，而令贤郎舍我为彼修梵行耶？”

于是，其母即至尊者赖吒惒罗其本妇所，作如是语：“诸新妇等，汝可以先所著璎珞严饰其身，赖吒惒罗族姓子本在家时极所爱念。以此璎珞速严身已，汝等共往至赖吒惒罗族姓子所，各抱一足而作是说：不审贤郎有何天女胜于我者，而令贤郎舍我为彼修梵行耶？”

彼时，尊者赖吒惒罗其本妇等即各以先所著璎珞严饰其身，尊者赖吒惒罗本在家时极所爱念。以此璎珞严饰身已，往诣尊者赖吒惒罗所，各抱一足而作是说：“不审贤郎有何天女胜于我者，而令贤郎舍我为彼修梵行耶？”

尊者赖吒惒罗语本妇曰：“诸妹，当知我不为天女故修于梵行，所为修梵行者，彼义已得，佛教所作今已成办。”

尊者赖吒惒罗诸妇等却住一面，啼泣垂泪而作是语：“我非贤郎妹，然贤郎唤我为妹。”

于是，尊者赖吒惒罗回还顾视，白父母曰：“居士，若施食者便以时施，何为相娆？”

尔时，父母即从座起，自行澡水，以上味肴馔，种种丰饶，食啖含消，手自斟酌，极令饱满；食讫收器，行澡水竟，取一小床，别坐听法。尊者赖吒惒罗为父母说法，劝发渴仰，成就欢喜；无量方便为彼说法，劝发渴仰，成就欢喜已，即从座起立，说颂曰：

<div class="poem">

观此严饰形，珍宝璎珞等，\\
右槃萦其发，绀黛画眉目，\\
此欺愚痴人，不诳度彼岸。\\
以众好彩色，庄严臭秽身，\\
此欺愚痴人，不诳度彼岸。\\
众香遍涂体，雌黄黄其足，\\
此欺愚痴人，不诳度彼岸。\\
身服净妙衣，庄严犹幻化，\\
此欺愚痴人，不诳度彼岸。\\
断绝鹿鞙繦，及破坏鹿门，\\
我舍离饵去，谁乐于鹿缚？

</div>

尊者赖吒惒罗说此颂已，以如意足乘虚而去，至鍮芦吒林入彼林中，于鞞醯勒树下敷尼师檀，结跏趺坐。

尔时，拘牢婆王及诸群臣前后围绕，坐于正殿，咨嗟称叹尊者赖吒惒罗：“若我闻赖吒惒罗族姓子来此鍮芦吒者，我必往见。”

于是，拘牢婆王告猎师曰：“汝去按行鍮芦吒林，我欲出猎。”猎师受教，即便按行鍮芦吒林。于是，猎师按行鍮芦吒林，见尊者赖吒惒罗在鞞醯勒树下，敷尼师檀，结跏趺坐，便作是念：“所为拘牢婆王及诸群臣共坐正殿，咨嗟称叹者，今已在此。”

尔时，猎师按行鍮芦吒林已，还诣拘牢婆王所，白曰：“大王，当知我已按行鍮芦吒林，随大王意。大王本所为与诸群臣共坐正殿，咨嗟称叹尊者赖吒惒罗：‘若我闻赖吒惒罗族姓子来此鍮芦吒林者，我必往见。尊者赖吒惒罗族姓子今在鍮芦吒林中鞞醯勒树下，敷尼师檀，结跏趺坐。大王欲见者，便可往也。”

拘牢婆王闻已，告御者曰：“汝速严驾，我今欲往见赖吒惒罗。”

御者受教，即速严驾，讫还白曰：“大王，当知严驾已办，随大王意。”

于是，拘牢婆王即乘车出，往至鍮芦吒林，遥见尊者赖吒惒罗，即便下车，步进往至尊者赖吒惒罗所。尊者赖吒惒罗见拘牢婆王来，而作是说：“大王，今来欲自坐耶？”

拘牢婆王曰：“今我虽到自己境界，然我意欲令赖吒惒罗族姓子请我令坐。”

尊者赖吒惒罗即请拘牢婆王曰：“今有别座，大王可坐。”

于是，拘牢婆王与尊者赖吒惒罗共相问讯，却坐一面，语赖吒惒罗：“若为家衰故出家学道耶？若为无财物故行学道者？赖吒惒罗，拘牢婆王家多有财物，我出财物与赖吒惒罗，劝赖吒惒罗舍戒罢道，行欲布施，快修福业。所以者何？赖吒惒罗，师教甚难！出家学道亦复甚难！”

尊者赖吒惒罗闻已，语曰：“大王，今以不净请我，非清净请。”

拘牢婆王闻已，问曰：“我当云何以清净请赖吒惒罗，非以不净耶？”

尊者赖吒惒罗语曰：“大王，应如是语：‘赖吒惒罗，我国人民安隐快乐，无恐怖、无斗诤，亦无棘刺、无苦使役，米谷丰饶，乞食易得。赖吒惒罗住我国中，我当护如法。大王，如是以净请我，非以不净。”

拘牢婆王闻已，语曰：“我今以净请赖吒惒罗，非以不净。我国人民安隐快乐，无恐怖、无斗诤，亦无棘刺、无苦使役，米谷丰饶，乞食易得。赖吒惒罗住我国中，我当护如法。

“复次，赖吒惒罗，有四种衰，谓衰衰故，剃除须发，著袈裟衣，至信、舍家、无家、学道。云何为四？病衰、老衰、财衰、亲衰。

“赖吒惒罗，云何病衰？或有一人长病疾患，极重甚苦，彼作是念：‘我长病疾患，极重甚苦，我实有欲，不能行欲，我今宁可剃除须发，著袈裟衣，至信、舍家、无家、学道。彼于后时以病衰故，剃除须发，著袈裟衣，至信、舍家、无家、学道，是为病衰。

“赖吒惒罗，云何老衰？或有一人年耆根熟，寿过垂讫，彼作是念：‘我年耆根熟，寿过垂讫，我实有欲，不能行欲，我今宁可剃除须发，著袈裟衣，至信、舍家、无家、学道。彼于后时以老衰故，剃除须发，著袈裟衣，至信、舍家、无家、学道，是谓老衰。

“赖吒惒罗，云何财衰？或有一人贫穷无力，彼作是念：‘我贫穷无力，我今宁可剃除须发，著袈裟衣，至信、舍家、无家、学道。彼于后时以财衰故，剃除须发，著袈裟衣，至信、舍家、无家、学道，是谓财衰。

“赖吒惒罗，云何亲衰？或有一人亲里断种，死亡没尽，彼作是念：‘我亲里断种，死亡没尽，我今宁可剃除须发，著袈裟衣，至信、舍家、无家、学道。彼于后时以亲衰故，剃除须发，著袈裟衣，至信、舍家、无家、学道，是谓亲衰。

“赖吒惒罗昔时无病，安隐成就，平等食道，不冷不热，平正安乐，顺次不诤。由是之故，食啖含消，安隐得化。赖吒惒罗非以病衰故，剃除须发，著袈裟衣，至信、舍家、无家、学道。

“赖吒惒罗往昔之时，年幼童子，发黑清净，身体盛壮，尔时作倡伎乐，极以自娱，庄严其身，常喜游戏。彼时亲属皆不欲使令其学道，父母啼泣，忧戚懊恼，亦不听汝出家学道，然汝剃除须发，著袈裟衣，至信、舍家、无家、学道。赖吒惒罗不以老衰故，剃除须发，著袈裟衣，至信、舍家、无家、学道。

“赖吒惒罗此鍮芦吒第一家、最大家、最胜家、最上家，谓财物也。赖吒惒罗不以财衰故，剃除须发，著袈裟衣，至信、舍家、无家、学道。

“赖吒惒罗此鍮芦吒林间，大豪亲族亲皆存在。赖吒惒罗不以亲衰故，剃除须发，著袈裟衣，至信、舍家、无家、学道。

“赖吒惒罗，此四种衰，或有衰者剃除须发，著袈裟衣，至信、舍家、无家、学道。我见赖吒惒罗都无此衰可使赖吒惒罗剃除须发，著袈裟衣，至信、舍家、无家、学道。赖吒惒罗，知见何等，为闻何等，剃除须发，著架裟衣，至信、舍家、无家、学道？”

尊者赖吒惒罗答曰：“大王，世尊知、见、如来、无所著、等正觉为说四事。我欲忍乐是，我知见闻是，是故剃除须发，著袈裟衣，至信、舍家、无家、学道。云何为四？大王，此世无护，无可依恃；此世一切趣向老法；此世非常，要当舍去；此世无满，无有厌足，为爱走使。”

拘牢婆王问曰：“赖吒惒罗向之所说：‘大王，此世无护，无可依恃。赖吒惒罗，我有儿孙、兄弟、枝党、象军、车军、马军、步军，皆能射御，严毅勇猛；王子力士钵逻骞提摩诃能伽有占相、有策虑、有计算、有善知书、有善谈论；有君臣、有眷属，持咒知咒，彼随诸方，有恐怖者能制止之。若赖吒惒罗所说：‘大王，此世无护，无可依恃。赖吒惒罗，向所说，此有何义耶？”

尊者赖吒惒罗答曰：“大王，我今问王，随所解答。大王，此身颇有病耶？”

拘牢婆王答曰：“赖吒惒罗，今我此身常有风病。”

尊者赖吒惒罗问曰：“大王，风病发时，生极重甚苦者。大王，尔时可得语彼儿孙、兄弟、象军、马军、车军、步军皆能射御严毅勇猛，王子力士钵逻骞提摩诃能伽占相、策虑、计算、知书、善能谈论，君臣、眷属持咒知咒：‘汝等共来暂代我受极重甚苦，令我无病得安乐耶？”

拘牢婆王答曰：“不也。所以者何？我自作业，因业缘业，独受极苦，甚重苦也。”

尊者赖吒惒罗语曰：“大王，以是故，世尊说此世无护，无可依恃。我欲忍乐是，我知见闻是，是故剃除须发，著袈裟衣，至信、舍家、无家、学道。”

拘牢婆王语曰：“若赖吒惒罗所说：‘大王，此世无护，无可依恃。赖吒惒罗，我亦欲是忍乐于是。所以者何？此世真实无护，无可依恃。”

拘牢婆王复问曰：“若赖吒惒罗所说：‘大王，此世一切趣向老法。赖吒惒罗向所说，此复有何义？”

尊者赖吒惒罗答曰：“大王，我今问王，随所解答。若大王年或二十四、或二十五者。于意云何？尔时速疾何如于今？尔时筋力、形体、颜色何如于今？”

拘牢婆王答曰：“赖吒惒罗，若我时年或二十四、或二十五，自忆尔时，速疾、筋力、形体、颜色无胜我者。赖吒惒罗，我今极老，诸根衰熟，寿过垂讫，年满八十，不复能起。”

尊者赖吒惒罗语曰：“大王，以是故，世尊说此世一切趣向老法。我欲忍乐是，我知见闻是，是故剃除须发，著袈裟衣，至信、舍家、无家、学道。”

拘牢婆王语曰：“若赖吒惒罗所说：‘大王，此世一切趣向老法。我亦欲是忍乐于是。所以者何？此世真实一切趣向老法。”

拘牢婆王复问曰：“若赖吒惒罗所说：‘大王，此世无常，要当舍去。赖吒惒罗向所说，此复有何义？”

尊者赖吒惒罗语曰：“大王，我今问王，随所解答。大王，有丰拘楼国及丰后宫、丰仓库耶？”

拘牢婆王答曰：“如是。”

尊者赖吒惒罗复问曰：“大王，有丰拘楼国及丰后宫、丰仓库者，若时有法来不可依，忍乐破坏，一切世无不归死者，尔时丰拘楼国及丰后宫、丰仓库者，可得从此世持至后世耶？”

拘牢婆王答曰：“不也。所以者何？我独无二，亦无伴侣从此世至后世也。”

尊者赖吒惒罗语曰：“大王，以是故，世尊说此世无常，要当舍去。我欲忍乐是，我知见闻是，是故剃除须发，著袈裟衣，至信、舍家、无家、学道。”

拘牢婆王语曰：“若赖吒惒罗所说‘大王，此世无常，要当舍去者，我亦欲是忍乐于是。所以者何？此世真实无常，要当舍去。”

拘牢婆王复问曰：“若赖吒惒罗所说：‘大王，此世无满，无有厌足，为爱走使。赖吒惒罗向所说，此复有何义？”

尊者赖吒惒罗答曰：“大王，我今问王，随所解答。大王，有丰拘楼国及丰后宫、丰仓库耶？”

拘牢婆王答曰：“如是。”

尊者赖吒惒罗复问曰：“大王，有丰拘楼国及丰后宫、丰仓库者，若于东方有一人来，可信可任，不欺诳世，来语王言：‘我从东方来，见彼国土极大富乐，多有人民。大王，可得彼国尔所财物、人民、力役，欲得彼国整御之耶？”

拘牢婆王答曰：“赖吒惒罗，若我知有如是丰国，尔所财物、人民、力役，得彼人民整御治者，我必取之。”

“如是南方、西方、北方，从大海岸若有人来，可信可任，不欺诳世，来语王言：‘我从大海彼岸来，见彼国土极大富乐，多有人民。大王，可得彼国尔所财物、人民、力役，欲得彼国整御之耶？”

拘牢婆王答曰：“赖吒惒罗，若我知有如是丰国，尔所财物、人民、力役，得彼人民整御治者，我必取之。”

尊者赖吒惒罗语曰：“大王，以是故，世尊说此世无满，无有厌足，为爱走使。我欲忍乐是，我知见闻是，是故剃除须发，著袈裟衣，至信、舍家、无家、学道。”

拘牢婆王语曰：“若赖吒惒罗所说：‘大王，此世无满，无有厌足，为爱走使。我亦欲是忍乐于是。所以者何？此世真实无满，无有厌足，为爱走使。”

尊者赖吒惒罗语曰：“大王，世尊知、见、如来、无所著、等正觉为我说此四事。我欲忍乐是，我知见闻是，是故剃除须发，著袈裟衣，至信、舍家、无家、学道。”

于是，尊者赖吒惒罗说此颂曰：

<div class="poem">

我见世间人，有财痴不施，\\
得财复更求，悭贪积聚物。\\
王者得天下，整御随其力，\\
海内无厌足，复求于海外。\\
王及诸人民，未离欲命尽，\\
散发妻子哭，呜呼苦难伏。\\
衣被而埋藏，或积薪火烧，\\
缘行至后世，烧已无慧念。\\
死后财不随，妻子及奴婢，\\
货富俱共同，愚智亦复然。\\
智者不怀忧，唯愚抱悒戚，\\
是故智慧胜，逮得正觉道。\\
深著于有有，愚痴作恶行，\\
于法非法行，以力强夺他。\\
少智习效他，愚多作恶行，\\
趣胎至后世，数数受生死。\\
已受出生世，独作众恶事，\\
如贼他所缚，自作恶所害。\\
如是此众生，至到于后世，\\
为己所作业，自作恶所害。\\
如果熟自堕，老少亦如斯，\\
欲庄美爱乐，心趣好恶色。\\
为欲所缚害，因欲恐怖生，\\
王我见此觉，知是沙门妙。

</div>

尊者赖吒惒罗所说如是，拘牢婆王闻尊者赖吒惒罗所说，欢喜奉行。

--------------

** 第32卷 大品.优婆离经第十七

我闻如是：一时，佛游那难陀，在波婆离奈林。尔时，长苦行尼揵中后彷佯，往诣佛所，共相问讯，却坐一面。于是，世尊问曰：“苦行尼揵亲子施设几行，令不行恶业、不作恶业？”

长苦行尼揵答曰：“瞿昙，我尊师尼揵亲子不为我等施设于行，令不行恶业、不作恶业；但为我等施设于罚，令不行恶业、不作恶业。”

世尊又复问曰：“苦行尼揵亲子施设几罚，令不行恶业、不作恶业？”

长苦行尼揵答曰：“瞿昙，我尊师尼揵亲子为我等辈施设三罚，令不行恶业、不作恶业。云何为三？身罚、口罚及意罚也。”

世尊又复问曰：“苦行，云何身罚异、口罚异、意罚异耶？”

长苦行尼揵答曰：“瞿昙，我等身罚异、口罚异、意罚异也。”

世尊又复问曰：“苦行，此三罚如是相似，尼揵亲子施设何罚为最重，令不行恶业、不作恶业？为身罚、口罚？为意罚耶？”

长苦行尼揵答曰：“瞿昙，此三罚如是相似，我尊师尼揵亲子施设身罚为最重，令不行恶业、不作恶业。口罚不然，意罚最下，不及身罚极大甚重。”

世尊又复问曰：“苦行，汝说身罚为最重耶？”

长苦行尼揵答曰：“瞿昙，身罚最重。”

世尊复再三问曰：“苦行，汝说身罚为最重耶？”

长苦行尼揵亦再三答曰：“瞿昙，身罚最重。”

于是，世尊再三审定长苦行尼揵如此事已，便默然住。

长苦行尼揵问曰：“沙门瞿昙施设几罚，令不行恶业、不作恶业？”

尔时，世尊答曰：“苦行，我不施设罚，令不行恶业、不作恶业；我但施设业，令不行恶业、不作恶业。”

长苦行尼揵问曰：“瞿昙施设几业，令不行恶业、不作恶业？”

世尊又复答曰：“苦行，我施设三业，令不行恶业、不作恶业。云何为三？身业、口业及意业也。”

长苦行尼揵问曰：“瞿昙，身业异、口业异、意业异耶？”

世尊又复答曰：“苦行，我身业异、口业异、意业异也。”

长苦行尼揵问曰：“瞿昙，此三业如是相似，施设何业为最重，令不行恶业、不作恶业？为身业、口业？为意业耶？”

世尊又复答曰：“苦行，此三业如是相似，我施设意业为最重，令不行恶业、不作恶业。身业、口业则不然也。”

长苦行尼揵问曰：“瞿昙施设意业为最重耶？”

世尊又复答曰：“苦行，我施设意业为最重也。”

长苦行尼揵复再三问曰：“瞿昙施设意业为最重耶？”

世尊亦再三答曰：“苦行，我施设意业为最重也。”

于是，长苦行尼揵再三审定世尊如此事已，即从座起，绕世尊三匝而退还去，往诣尼揵亲子所。

尼揵亲子遥见长苦行尼揵来，即便问曰：“苦行，从何处来？”

长苦行尼揵答曰：“尊，我从那难陀波婆离奈林沙门瞿昙处来。”

尼揵亲子问曰：“苦行，颇共沙门瞿昙有所论耶？”

长苦行尼揵答曰：“共论。”

尼揵亲子告曰：“苦行，若共沙门瞿昙有所论者，尽为我说，我或能知彼之所论。”

于是，长苦行尼揵共世尊有所论者尽向彼说，尼揵亲子闻便叹曰：“善哉！苦行，谓汝于师行弟子法，所作智辩聪明决定，安隐无畏成就调御，逮大辩才，得甘露幢，于甘露界自作证成就游。所以者何？谓汝向沙门瞿昙施设身罚为最重，令不行恶业、不作恶业。口罚不然，意罚最下，不及身罚极大甚重。”

是时，优婆离居士与五百居士俱集在众中，叉手向尼揵亲子。于是，优婆离居士语长苦行尼揵曰：“尊已再三审定沙门瞿昙如此事耶？”

长苦行尼揵答曰：“居士，我已再三审定沙门瞿昙如此事也。”

优婆离居士语长苦行尼揵曰：“我亦能至再三审定沙门瞿昙如此事已，随所牵挽。犹如力士执长髦羊，随所牵挽；我亦如是，能至再三审定沙门瞿昙如此事已，随所牵挽。犹如力士手执髦裘，抖擞去尘；我亦如是，能至再三审定沙门瞿昙如此事已，随所牵挽。犹如沽酒师、沽酒弟子取漉酒囊，著深水中，随意所欲，随所牵挽；我亦如是，能至再三审定沙门瞿昙如此事已，随所牵挽。犹龙象王年满六十，而以骄傲摩诃能加牙足体具，筋力炽盛，力士将去以水洗髀、洗脊、洗胁、洗腹、洗牙、洗头及水中戏；我亦如是，能至再三审定沙门瞿昙如此事已，随其所洗。我往诣沙门瞿昙所，共彼谈论，降伏已还。”

尼揵亲子语优婆离居士曰：“我亦可伏沙门瞿昙，汝亦可也，长苦行尼揵亦可也。”

于是，长苦行尼揵白尼揵亲子曰：“我不欲令优婆离居士往诣沙门瞿昙所。所以者何？沙门瞿昙知幻化咒，能咒化作弟子比丘、比丘尼、优婆塞、优婆私，恐优婆离居士受沙门瞿昙化，化作弟子。”

尼揵亲子语曰：“苦行，若优婆离居士受沙门瞿昙化作弟子者，终无是处；若沙门瞿昙受优婆离居士化作弟子者，必有是处。”

优婆离居士再三白尼揵亲子曰：“我今往诣沙门瞿昙所，共彼谈论，降伏已还。”

尼揵亲子亦再三答曰：“汝可速往，我亦可伏沙门瞿昙，汝亦可也，长苦行尼揵亦可也。”

长苦行尼揵复再三白曰：“我不欲令优婆离居士往诣沙门瞿昙所。所以者何？沙门瞿昙知幻化咒，能咒化作弟子比丘、比丘尼、优婆塞、优婆私，恐优婆离居士受沙门瞿昙化，化作弟子。”

尼揵亲子语曰：“苦行，若优婆离居士受沙门瞿昙化作弟子者，终无是处；若沙门瞿昙受优婆离居士化作弟子者，必有是处。优婆离居士，汝去随意！”

于是，优婆离居士稽首尼揵亲子足，绕三匝而去；往诣佛所，共相问讯，却坐一面，问曰：“瞿昙，今日长苦行尼揵来至此耶？”

世尊答曰：“来也，居士。”

优婆离居士问曰：“瞿昙，颇共长苦行尼揵有所论耶？”

世尊答曰：“有所论也。”

优婆离居士语曰：“瞿昙，若共长苦行尼揵有所论者，尽为我说。若我闻已，或能知之。”

于是，世尊共长苦行尼揵有所论者，尽向彼说。

尔时，优婆离居士闻便叹曰：“善哉！苦行，谓于尊师行弟子法，所作智辩聪明决定，安隐无畏成就调御，逮大辩才，得甘露幢，于甘露界自作证成就游。所以者何？谓向沙门瞿昙施设身罚最重，令不行恶业、不作恶业。口罚不然，意罚最下，不及身罚极大甚重。”

彼时，世尊告曰：“居士，我欲与汝共论此事。汝若住真谛者，以真谛答。”

优婆离居士报曰：“瞿昙，我住真谛，以真谛答。沙门瞿昙，但当与我共论此事。”

世尊问曰：“居士，于意云何？若有尼揵来，好喜于布施，乐行于布施，无戏、乐不戏，为极清净，极行咒也。若彼行来时，多杀大小虫。云何，居士，尼揵亲子于此杀生施设报耶？”

优婆离居士答曰：“瞿昙，若思者有大罪，若无思者无大罪也。”

世尊问曰：“居士，汝说思为何等耶？”

优婆离居士答曰：“瞿昙，意业是也。”

世尊告曰：“居士，汝当思量而后答也。汝之所说，前与后违，后与前违，则不相应。居士，汝在此众自说：‘瞿昙，我住真谛，以真谛答。沙门瞿昙，但当与我共论此事。居士，于意云何？若有尼揵来饮汤断冷水，彼无汤时，便欲饮冷水，不得冷水，彼便命终。居士，尼揵亲子云何可说彼尼揵所生耶？”

优婆离居士答曰：“瞿昙，有天名意著，彼尼揵命终，若意著死者，必生彼处。”

世尊告曰：“居士，汝当思量而后答也。汝之所说，前与后违，后与前违，则不相应。汝在此众自说：‘瞿昙，我住真谛，以真谛答。沙门瞿昙，但当与我共论此事。居士，于意云何？若使有人持利刀来，彼作是说：‘我于此那难陀内一切众生，于一日中斫剉斩截、剥裂削割，作一肉聚，作一肉积。居士，于意云何？彼人宁能于此那难陀内一切众生，于一日中斫剉斩截、剥裂削割，作一肉聚，作一肉积耶？”

优婆离居士答曰：“不也。所以者何？此那难陀内极大富乐，多有人民，是故彼人于此那难陀内一切众生，必不能得于一日中斫剉斩截、剥裂削割，作一肉聚，作一肉积。瞿昙，彼人唐大烦劳。”

“居士，于意云何？若有沙门、梵志来，有大如意足，有大威德，有大福佑，有大威神，心得自在。彼作是说：‘我以发一瞋念，令此一切那难陀内烧使成灰。居士，于意云何？彼沙门、梵志宁能令此一切那难陀内烧成灰耶？”

优婆离居士答曰：“瞿昙，何但一那难陀？何但二、三、四？瞿昙，彼沙门、梵志有大如意足，有大威德，有大福佑，有大威神，心得自在，若发一瞋念，能令一切国一切人民烧使成灰，况一那难陀耶？”

世尊告曰：“居士，汝当思量而后答也。汝之所说，前与后违，后与前违，则不相应。汝在此众自说：‘瞿昙，我住真谛，以真谛答。沙门瞿昙，但当与我共论此事。”

世尊问曰：“居士，汝颇曾闻大泽无事、麒鳞无事、糜鹿无事、静寂无事、空野无事、无事即无事耶？”

优婆离居士答曰：“瞿昙，我闻有也。”

“居士，于意云何？彼为谁大泽无事、麒麟无事、糜鹿无事、静寂无事、空野无事、无事即无事耶？”

优婆离居士默然不答，世尊告曰：“居士，速答！居士，速答！今非默然时。居士在此众自说：‘瞿昙，我住真谛，以真谛答。沙门瞿昙，但当与我共论此事。”

于是，优婆离居士须臾默然已，语曰：“瞿昙，我不默然，我但思惟于此义耳！瞿昙，彼愚痴尼揵不善晓了，不能解知，不识良田，而不自审，长夜欺我，为彼所误，谓向沙门瞿昙施设身罚最重，令不行恶业、不作恶业，口罚、意罚而不如也。如我从沙门瞿昙所说知义，仙人发一瞋念，能令大泽无事、麒麟无事、糜鹿无事、寂静无事、空野无事、无事即无事。世尊，我已知。善逝，我已解。我今自归于佛、法及比丘众，惟愿世尊受我为优婆塞！从今日始，终身自归，乃至命尽。”

世尊告曰：“居士，汝默然行，勿得宣言，如是胜人默然为善。”

优婆离居士白曰：“世尊，我以是故，复于世尊重加欢喜。所以者何？谓世尊作如是说：‘居士，汝默然行，勿得宣言，如是胜人默然为善。世尊，若我更为余沙门、梵志作弟子者，彼等便当持幢、幡、盖，遍行宣令于那难陀，作如是说：‘优婆离居士为我作弟子！优婆离居士为我作弟子！然世尊作是说：‘居士，汝默然行，勿得宣言，如是胜人默然为善。”

优婆离居士白曰：“世尊，从今日始，不听诸尼揵入我家门，唯听世尊四众弟子比丘、比丘尼、优婆塞、优婆私入。”

世尊告曰：“居土，彼尼揵等，汝家长夜所共尊敬，若其来者，汝当随力供养于彼。”

优婆离白曰：“世尊，我以是故，复于世尊倍加欢喜。所以者何？谓世尊作如是说：‘居士，彼尼揵等，汝家长夜所共尊敬，若其来者，汝当随力供养于彼。世尊，我本闻世尊作如是说：‘当施与我，莫施与他；当施与我弟子，莫施与他弟子。若施与我者，当得大福；若施与他，不得大福。施与我弟子，当得大福；施与他弟子，不得大福。”

世尊告曰：“居士，我不如是说：‘当施与我，莫施与他；施与我弟子，莫施与他弟子。若施与我者，当得大福；若施与他，不得大福。施与我弟子，当得大福；若施与他弟子，不得大福。居士，我说如是：‘施与一切，随心欢喜。但施与不精进者，不得大福；施与精进者，当得大福。”

优婆离居士白曰：“世尊，愿无为也。我自知施与尼揵、不施与尼揵。世尊，我今再自归佛、法及比丘众，惟愿世尊受我为优婆塞，从今日始，终身自归，乃至命尽。”

于是，世尊为优婆离居士说法，劝发渴仰，成就欢喜；无量方便为彼说法，劝发渴仰，成就欢喜已，如诸佛法，先说端正法，闻者欢悦，谓说施、说戒、说生天法，毁咨欲为灾患，生死为秽，称叹无欲为妙，道品白净。世尊为彼说如是法已，佛知彼有欢喜心、具足心、柔软心、堪耐心、升上心、一向心、无疑心、无盖心，有能有力，堪受正法，谓如诸佛所说正要，世尊便为彼说苦、集、灭、道。优婆离居士即于坐中见四圣谛苦、集、灭、道，犹如白素易染为色，如是优婆离居士即于坐中见四圣谛苦、集、灭、道。

于是，优婆离居士见法得法，觉白净法，断疑度惑，更无余尊，不复从他，无有犹豫，已住果证，于世尊法得无所畏；即从座起，为佛作礼：“世尊，我今三自归佛、法及比丘众，惟愿世尊受我为优婆塞！从今日始，终身自归，乃至命尽。”

于是，优婆离居士闻佛所说，善受善持，稽首佛足，绕三匝而归，敕守门者：“汝等当知，我今则为世尊弟子，从今日始，诸尼揵来，莫听入门，唯听世尊四众弟子比丘、比丘尼、优婆塞、优婆私入。若尼揵来者，当语彼言：‘尊者，优婆离居士今受佛化，化作弟子，则不听诸尼揵入门，唯听世尊四众弟子比丘、比丘尼、优婆塞、优婆私入。若须食者，便可住此，当出食与。”

于是，长苦行尼揵闻优婆离居士受沙门瞿昙化，化作弟子，则不听诸尼揵入门，唯听沙门瞿昙弟子比丘、比丘尼、优婆塞、优婆私入。长苦行尼揵闻已，往诣尼揵亲子所，白曰：“尊，此是我本所说。”

尼揵亲子问曰：“苦行，何者是汝本所说耶？”

长苦行尼揵答曰：“尊，我本所说，不欲令优婆离居士往诣沙门瞿昙所。所以者何？沙门瞿昙知幻化咒，能咒化作弟子比丘、比丘尼、优婆塞、优婆私，恐优婆离居士受沙门瞿昙化，化作弟子。尊，优婆离居士今已受沙门瞿昙化，化作弟子已，不听诸尼揵入门，唯听沙门瞿昙弟子比丘、比丘尼、优婆塞、优婆私入。”

尼揵亲子语曰：“苦行，若优婆离居士受沙门瞿昙化作弟子者，终无是处；若沙门瞿昙受优婆离居士化作弟子者，必有是处。”

长苦行尼揵复白曰：“尊，若不信我所说者，尊自可往，亦可遣使。”

于是，尼揵亲子告曰：“苦行，汝可自往，诣彼看之，为优婆离居士受沙门瞿昙化作弟子耶？为沙门瞿昙受优婆离居士化作弟子耶？”

长苦行尼揵受尼揵亲子教已，往诣优婆离居士家。守门人遥见长苦行尼揵来，而作是说：“尊者，优婆离居士今受佛化，化作弟子，则不听诸尼揵入门，唯听世尊四众弟子比丘、比丘尼、优婆塞、优婆私入。若欲得食者，便可住此，当出食与。”

长苦行尼揵语曰：“守门人，我不用食。”

长苦行尼揵知此事已，奋头而去，往诣尼揵亲子所，白曰：“尊，此是如我本所说。”

尼揵亲子问曰：“苦行，何者是汝本所说耶？”

长苦行尼揵答曰：“尊，我本所说，不欲令优婆离居士往诣沙门瞿昙所。所以者何？沙门瞿昙知幻化咒，能咒化作弟子比丘、比丘尼、优婆塞、优婆私，恐优婆离居士受沙门瞿昙化，化作弟子。尊，优婆离居士今已受沙门瞿昙化，化作弟子已，不听诸尼揵入门，唯听沙门瞿昙弟子比丘、比丘尼、优婆塞、优婆私入。”

尼揵亲子告曰：“苦行，若优婆离居士受沙门瞿昙化作弟子者，终无是处；若沙门瞿昙受优婆离居士化作弟子者，必有是处。”

长苦行尼揵白曰：“尊，若不信我所说者，愿尊自往！”

于是，尼揵亲子与大尼揵众五百人俱，往诣优婆离居士家。守门人遥见尼揵亲子与大尼揵众五百人俱来，而作是说：“尊者，优婆离居士今受佛化，化作弟子，则不听诸尼揵入门，唯听世尊四众弟子比丘、比丘尼、优婆塞、优婆私入。若欲得食者，便可住此，当出食与。”

尼揵亲子语曰：“守门人，我不用食，但欲得见优婆离居士。”

守门人语曰：“愿尊住此，我今入白尊者优婆离居士。”

彼守门人即入白曰：“居士，当知尼揵亲子与大尼揵众五百人俱住在门外，作如是语：‘我欲得见优婆离居士。”

优婆离居士告守门人：“汝至中门，敷设床座，讫还白我。”

守门人受教，往至中门，敷设床座讫，还白曰：“居士，当知敷床已讫，惟愿居士自当知时！”

优婆离居士将守门人往至中门，若有床座，极高广大，极净好敷，谓优婆离居士本抱尼揵亲子所令坐者。优婆离居士自处其上，结跏趺坐，告守门人：“汝出往至尼揵亲子所，作如是语：‘尊人，优婆离居士言，尊人欲入者，自可随意。”

彼守门人受教即出，至尼揵亲子所，作如是语：“尊人，优婆离居士言，尊人欲入者，自可随意。”

于是，尼揵亲子与大尼揵众五百人俱入至中门。

优婆离居士遥见尼揵亲子与大尼揵众五百人俱入，而作是语：“尊人，有座，欲坐随意！”

尼揵亲子语曰：“居士，汝应尔耶？自上高座，结跏趺坐，与人共语，如出家者学道无异？”

优婆离居士语曰：“尊人，我自有物，欲与便与，不与便不与。此座我有，是故我言：‘有座，欲坐随意。”

尼揵亲子敷座而坐，语曰：“居士，何以故尔？欲降伏沙门瞿昙而反自降伏来？犹如有人求眼入林，而失眼还；如是，居士欲往降伏沙门瞿昙，反为沙门瞿昙所降伏来。犹如有人以渴入池，而反渴还；居士亦然，欲往降伏沙门瞿昙，而反自降伏还。居士，何以故尔？”

优婆离居士语曰：“尊人，听我说喻，慧者闻喻则解其义。尊人，譬一梵志，有年少妇，彼妇怀妊，语其夫曰：‘我今怀妊，君去至市，可为儿买好戏具来。时，彼梵志语其妇曰：‘但令卿得安隐产已，何忧无耶？若生男者，当为卿买男戏具来；若生女者，亦当为买女戏具来。妇至再三语其夫曰：‘我今怀妊，君去至市，速为儿买好戏具来。梵志亦至再三语其妇曰：‘但令卿得安隐产已，何忧无耶？若生男者，当为卿买男戏具来；若生女者，亦当为买女戏具来。

“彼梵志者极怜念妇，即便问曰：‘卿欲为儿买何戏具？妇报之曰：‘君去为儿买猕猴子好戏具来。梵志闻已，往至市中买猕猴子戏具，持还语其妇曰：‘我已为儿买猕猴子戏具来还。其妇见已，嫌色不好，即语夫曰：‘君可持此猕猴戏具往至染家，染作黄色，令极可爱，捣使光生。梵志闻已，即时持此猕猴戏具，往至染家而语之曰：‘为我染此猕猴戏具，作好黄色，令极可爱，捣使光生。尔时，染家便语梵志：‘猕猴戏具染作黄色，令极可爱，此可尔也，然不可捣使光泽生。于是，染家说此颂曰：

<div class="poem">

‘猕猴忍受色，不能堪忍捣，\\
若捣则命终，终不可椎打，\\
此是臭秽囊，猕猴满不净。

</div>

“尊人，当知尼揵所说亦复如是，不能堪忍受他难问，亦不可得思惟观察，唯但染愚，不染慧也。尊人，复听：犹如清净波罗奈衣，主持往至于彼染家，而语之曰：‘为染此衣，作极好色，令可爱也，亦为极捣，使光泽生。彼时染家语衣主曰：‘此衣可染，作极好色，令可爱也，亦可极捣，使光泽生。于是，染家说此颂曰：

<div class="poem">

‘如波罗奈衣，白净忍受色，\\
捣已则柔软，光色增益好。

</div>

“尊人，当知诸如来、无所著、等正觉所说亦复如是，极能堪忍受他难问，亦快可得思惟观察，唯但染慧，不染愚也。”

尼揵亲子语曰：“居士为沙门瞿昙幻咒所化。”

优婆离居士语曰：“尊人，善幻化咒，极善幻化咒。尊人，彼幻化咒令我父母长夜得利饶益，安隐快乐，及其妻子、奴婢、作使、那难陀国王及一切世间，天及魔、梵、沙门、梵志，从人至天，令彼长夜得利饶益，安隐快乐。”

尼揵亲子语曰：“居士，举那难陀知优婆离居士是尼揵弟子，今者竟为谁弟子耶？”

于是，优婆离居士即从座起，右膝著地，若方有佛，叉手向彼，语曰：“尊人，听我所说也：

<div class="poem">

雄猛离愚痴，断秽整降伏，\\
无敌微妙思，学戒禅智慧，\\
安隐无有垢，佛弟子婆离。\\
大圣修习已，得德说自在，\\
善念妙正观，不高亦不下，\\
不动常自在，佛弟子婆离。\\
无曲常知足，舍离悭得满，\\
作沙门成觉，后身尊大士，\\
无比无有尘，佛弟子婆离。\\
无疾不可量，甚深得牟尼，\\
常安隐勇猛，住法微妙思，\\
调御常不戏，佛弟子婆离。\\
大龙乐住高，结尽得解脱，\\
应辩才清净，慧生离忧戚，\\
不还有释迦，佛弟子婆离。\\
正法禅思惟，无有娆清净，\\
常笑无有恚，乐离得第一，\\
无畏常专精，佛弟子婆离。\\
七仙无与等，三达逮得梵，\\
净浴如明灯，得息止怨结，\\
勇猛极清净，佛弟子婆离。\\
得息慧如地，大慧除世贪，\\
可祠无上眼，上士无与等，\\
御者无有恚，佛弟子婆离。\\
断望无上善，善调无比御，\\
无上常欢喜，无疑有光明，\\
断慢无上觉，佛弟子婆离。\\
断爱无比觉，无烟无有焰，\\
如去为善逝，无比无与等，\\
名称已逮正，佛弟子婆离。\\
此是百叹佛，本未曾思惟，\\
优婆离所说，诸天来至彼，\\
善助加诸辩，如法如其人，\\
尼揵亲子问，佛十力弟子。

</div>

尼揵亲子问曰：“居士，汝以何意称叹沙门瞿昙耶？”

优婆离居士报曰：“尊人，听我说喻，慧者闻喻则解其义。犹善鬘师、鬘师弟子采种种华，以长綖结作种种鬘；如是，尊人，如来、无所著、等正觉有无量称叹，我之所尊，以故称叹。”

说此法时，优婆离居士远尘离垢，诸法法眼生。尼揵亲子即吐热血，至波惒国，以此恶患，寻便命终。

佛说如是，优婆离居士闻佛所说，欢喜奉行。

--------------

** 第33卷 大品.释问经第十八

我闻如是：一时，佛游摩竭陀国，在王舍城东奈林村北鞞陀提山因陀罗石室。

尔时，天王释闻佛游摩竭陀国，在王舍城东奈林村北鞞陀提山因陀罗石室。时，天王释告五结乐子：“我闻世尊游摩竭陀国，在王舍城东奈林村北鞞陀提山因陀罗石室。五结，汝来共往见佛。”

五结乐子白曰：“唯然。”

于是，五结乐子挟琉璃琴从天王释行。三十三天闻天王释其意至重，欲往见佛，三十三天亦复侍从天王释行。于是，天王释及三十三天、五结乐子犹如力士屈伸臂顷，于三十三天忽没不现已，住摩竭陀国王舍城东奈林村北鞞陀提山，去石室不远。

尔时，鞞陀提山光耀极照，明如火焰。彼山左右居民见之，便作是念：“鞞陀提山火烧普燃。”

时，天王释住一处已，告曰：“五结，世尊如是住无事处山林树下，乐居高岩，寂无音声，远离，无恶，无有人民，随顺宴坐，有大威德。诸天共俱，乐彼远离，宴坐安隐，快乐游行，我等未通，不应便前。五结，汝往先通，我等然后当进。”

五结乐子白曰：“唯然。”

于是，五结乐子受天王释教已，挟琉璃琴即先往至因陀罗石室，便作是念：“知此处离佛不近不远，令佛知我，闻我音声。”住彼处已，调琉璃琴，作欲相应偈、龙相应偈、沙门相应偈、阿罗诃相应偈，而歌颂曰：

<div class="poem">

贤礼汝父母，月及耽浮楼，\\
谓生汝殊妙，令我发欢心。\\
烦热求凉风，渴欲饮冷水，\\
如是我爱汝，犹罗诃爱法。\\
如收水甚难，著欲亦复然，\\
无量生共会，如施与无著。\\
池水清且凉，底有金粟沙，\\
如龙象热逼，入此池水浴。\\
犹如钩牵象，我意为汝伏，\\
所行汝不觉，窈窕未得汝。\\
我意极著汝，烦冤烧我心，\\
是故我不乐，如人入虎口。\\
如释子思禅，常乐在于一，\\
如牟尼得觉，得汝妙净然。\\
如牟尼所乐，无上正尽觉，\\
如是我所乐，常求欲得汝。\\
如病欲得药，如饥欲得食，\\
贤汝止我心，犹如水灭火。\\
若我所作福，供养诸无著，\\
彼是悉净妙，我共汝受报。\\
愿我共汝终，不离汝独活，\\
我宁共汝死，不用相离生。\\
释为与我愿，三十三天尊，\\
汝人无上尊，是我愿最坚。\\
是故礼大雄，稽首人最上，\\
断绝诸爱刺，我礼日之亲。

</div>

于是，世尊从三昧起，赞叹五结乐子曰：“善哉！善哉！五结，汝歌音与琴声相应，琴声与歌音相应，歌音不出琴声外，琴声不出歌音外。五结，汝颇忆昔时歌颂此欲相应偈、龙相应偈、沙门相应偈、阿罗诃相应偈耶？”

五结乐子白曰：“世尊，唯大仙人自当知之。大仙人，昔时世尊初得觉道，游郁鞞罗尼连禅河岸，阿阇惒罗尼拘类树下。尔时，耽浮楼乐王女，名贤月色，有天名结，摩兜丽御车子，求欲彼女。大仙人，彼当求欲于彼女时，我亦复求欲得彼女。然，大仙人，求彼女时竟不能得，我于尔时住彼女后，便歌颂此欲相应偈、龙相应偈、沙门相应偈、阿罗诃相应偈。大仙人，我歌颂此偈时，彼女回顾，怡然含笑而语我曰：‘五结，我未曾见彼佛世尊，然我已从三十三天闻彼世尊、如来、无所著、等正觉、明行成为、善逝、世间解、无上士、道法御、天人师，号佛、众佑。五结，若汝能数称叹世尊者，可与汝共事。大仙人，我唯一共会，自后不复见。”

于是，天王释而作是念：“五结乐子已令世尊从定觉起已，通我于善逝。”彼时，天王释告曰：“五结，汝即往彼，为我稽首佛足，问讯世尊圣体康强，安快无病，起居轻便，气力如常耶？作如是语：‘大仙人，天王释稽首佛足，问讯世尊圣体康强，安快无病，起居轻便，气力如常耶？大仙人，天王释及三十三天欲见世尊。”

五结乐子白曰：“唯然。”

于是，五结乐子舍琉璃琴，叉手向佛，白曰：“世尊，唯大仙人，天王释稽首佛足，问讯世尊圣体康强，安快无病，起居轻便，气力如常耶？大仙人，天王释及三十三天欲见世尊。”

尔时，世尊告曰：“五结，今天王释安隐快乐，及诸天、人、阿修罗、揵沓惒、罗刹及余种种身安隐快乐。五结，天王释欲见我者，随其所欲。”

于是，五结乐子闻佛所说，善受善持，稽首佛足，绕三匝而去；往诣天王释所，白曰：“天王，我已为白世尊，世尊今待天王，惟愿天王自当知时！”

于是，天王释及三十三天、五结乐子往诣佛所。时，天王释稽首佛足，再三自称名姓言：“唯大仙人，我是天王释，我是天王释。”

世尊告曰：“如是！如是！拘翼，汝是天王释。”

时，天王释再三自称名姓，稽首佛足，却住一面。三十三天及五结乐子亦稽首佛足，却住一面。时，天王释白曰：“唯大仙人，我去世尊近远坐耶？”

世尊告曰：“汝近我坐。所以者何？汝有大天眷属。”

于是，天王释稽首佛足，却坐一面。三十三天及五结乐子亦稽首佛足，却坐一面。尔时，因陀罗石室忽然广大。所以者何？佛之威神及诸天威德。

时，天王释坐已，白曰：“唯大仙人，我于长夜欲见世尊，欲请问法。大仙人，往昔一时世尊游舍卫国，住石岩中。大仙人，我尔时自为及为三十三天，乘千象车，往至鞞沙门大王家。尔时，鞞沙门大王家有妾，名盘阇那。尔时，世尊入定寂然，彼妾叉手礼世尊足。大仙人，我语彼曰：‘妹，我今非往见世尊时，世尊入定。若世尊从定寤者，妹便为我稽首佛足，问讯世尊圣体康强，安快无病，起居轻便，气力如常耶？作如是说：“唯大仙人，天王释稽首佛足，问讯世尊圣体康强，安快无病，起居轻便，气力如常耶？”大仙人，彼妹为我稽首佛足，问讯世尊，世尊为忆不耶？”

世尊告曰：“拘翼，彼妹为汝稽首我足，具宣汝意，问讯于我，我亦忆。拘翼，当汝去时，闻此音声，便从定寤。”

“大仙人，昔时我闻：若如来、无所著、等正觉、明行成为、善逝、世间解、无上士、道法御、天人师，号佛、众佑出于世时，增诸天众，减阿修罗。大仙人，我自眼见世尊弟子比丘从世尊修习梵行，舍欲离欲，身坏命终，得至善处，生于天中。大仙人，瞿毗释女是世尊弟子，亦从世尊修习梵行，憎恶是女身，爱乐男形，转女人身，受男子形，舍欲离欲，身坏命终，得生妙处三十三天，为我作子。彼既生已，诸天悉知：瞿婆天子有大如意足，有大威德，有大福佑，有大威神。

“大仙人，我复见有世尊弟子三比丘等，亦从世尊修习梵行，不舍离欲，身坏命终，生余下贱伎乐宫中。彼既生已，日日来至三十三天供事诸天，奉侍瞿婆天子。天子见彼已，而说颂曰：

<div class="poem">

与眼优婆私，我字名瞿毗，\\
奉敬佛及法，净意供养众。\\
我已蒙佛恩，释子大佑德，\\
妙生三十三，彼知佑天子。\\
见彼本比丘，受生伎乐神，\\
叉手面前立，瞿婆为说偈。\\
是本瞿昙子，我本为人时，\\
来至到我家，饮食好供养。\\
汝本与圣等，行无上梵行，\\
今为他所使，日来奉事天。\\
我本承事汝，闻圣善说法，\\
得信成就戒，妙生三十三。\\
汝本受奉事，行无上梵行，\\
今为他所使，日来奉事天。\\
汝以何为面？受持佛法已，\\
反背不向法，是眼觉善说。\\
我昔见汝等，今生下伎乐，\\
自行非法行，自生于非法。\\
我本在居家，观我今胜德，\\
转女成天子，自在五欲乐。\\
彼诃瞿昙子，厌已叹瞿昙：\\
我今当进行，天子真谛说。\\
二于彼勤行，忆瞿昙法律，\\
知欲有灾患，即彼舍离欲。\\
彼为欲结缚，即得舍远离，\\
如象断羁绊，度三十三天。\\
因陀罗天梵，一切皆来集，\\
即彼坐上去，雄猛舍尘欲。\\
帝释见已厌，胜天天中天，\\
彼本生下贱，度三十三天。\\
厌已妙息言，瞿婆后说曰：\\
人中有佛胜，释牟尼知欲。\\
彼子中失念，我诃更复得，\\
于三中之一，则生伎乐中。\\
二成等正道，在天定根乐，\\
汝说如是法，弟子无有惑。\\
度漏断邪疑，礼佛胜伏根，\\
若彼觉诸法，二得升进处。\\
彼得升进已，生于梵天中，\\
我等知彼法，大仙来至此。

</div>

尔时，世尊便作是念：“此鬼长夜无有谀谄，亦无欺诳，无幻质直。若有问者，尽欲知故，不欲触娆，彼之所问亦复如是，我宁可说甚深阿毗昙。”世尊知已，为天王释说此颂曰：

<div class="poem">

于现法乐故，亦为后世乐，\\
拘翼自恣问，随意之所乐，\\
彼彼之所问，尽当为决断。\\
世尊已见听，日天求见义，\\
在摩竭陀国，贤婆娑婆问。

</div>

于是，天王释白曰：“世尊，天、人、阿修罗、揵沓惒、罗刹及余种种身各各有几结耶？”

世尊闻已，答曰：“拘翼，天、人、阿修罗、揵沓惒、罗刹及余种种身各各有二结，悭及嫉也。彼各各作是念：‘令我无杖、无结、无怨、无恚、无诤、无斗、无苦，安乐游行。彼虽作是念，然故有杖、有结、有怨、有恚、有诤、有斗、有苦，无安乐游行。”

时，天王释闻已，白曰：“唯然，世尊。唯然，善逝。唯然，大仙人，天、人、阿修罗、揵沓惒、罗刹及余种种身各各有二结，彼作是念：‘令我无杖、无结、无怨、无恚、无诤、无斗、无苦，安乐游行。彼虽作是念，然故有杖、有结、有怨、有恚、有诤、有斗、有苦，无安乐游行。唯然，世尊。唯然，善逝。唯然，大仙人，如佛所说法，我悉知之，我断疑度惑，无有犹豫，闻佛所说故。”

时，天王释闻佛所说，欢喜奉行。

复问曰：“大仙人，悭、嫉者，何因何缘？为从何生？由何而有？复何因由无悭、嫉耶？”

世尊闻已，答曰：“拘翼，悭、嫉者，因爱、不爱，缘爱、不爱，从爱、不爱生，由爱、不爱有。若无爱、不爱者，则无悭、嫉也。”

时，天王释闻已，白曰：“唯然，世尊。唯然，善逝。唯然，大仙人，悭、嫉者，因爱、不爱，缘爱、不爱，从爱、不爱生，由爱、不爱有。若无爱、不爱者，则无悭、嫉也。唯然，世尊。唯然，善逝。唯然，大仙人，如佛所说法，我悉知之，我断疑度惑，无有犹豫，闻佛所说故。”

时，天王释闻佛所说，欢喜奉行。

复问曰：“大仙人，爱、不爱者，何因何缘？为从何生？由何而有？复何因由无爱、不爱耶？”

世尊闻已，答曰：“拘翼，爱、不爱者，因欲缘欲，从欲而生，由欲故有。若无欲者，则无爱、不爱。”

时，天王释闻已，白曰：“唯然，世尊。唯然，善逝。唯然，大仙人，爱、不爱者，因欲缘欲，从欲而生，由欲故有。若无欲者，则无爱、不爱。唯然，世尊。唯然，善逝。唯然，大仙人，如佛所说法，我悉知之，我断疑度惑，无有犹豫，闻佛所说故。”

时，天王释闻佛所说，欢喜奉行。

复问曰：“大仙人，欲者，何因何缘？为从何生？由何而有？复何因由无有欲耶？”

世尊闻已，答曰：“拘翼，欲者，因念缘念，从念而生，由念故有。若无念者，则无有欲。”

时，天王释闻已，白曰：“唯然，世尊。唯然，善逝。唯然，大仙人，欲者，因念缘念，从念而生，由念故有。若无念者，则无有欲。唯然，世尊。唯然，善逝。唯然，大仙人，如佛所说法，我悉知之，我断疑度惑，无有犹豫，闻佛所说故。”

时，天王释闻佛所说，欢喜奉行。

复问曰：“大仙人，念者，何因何缘？为从何生？由何而有？复何因由无有念耶？”

世尊闻已，答曰：“拘翼，念者，因思缘思，从思而生，由思故有。若无思者，则无有念。由念故有欲，由欲故有爱、不爱，由爱、不爱故有悭、嫉，由悭、嫉故有刀杖、斗诤、憎嫉、谀谄、欺诳、妄言、两舌，心中生无量恶不善之法，如是此纯大苦阴生。若无思者，则无有念；若无念者，则无有欲；若无欲者，则无爱、不爱；若无爱、不爱者，则无悭、嫉；若无悭、嫉者，则无刀杖、斗诤、憎嫉、谀谄、欺诳、妄言、两舌，心中不生无量恶不善之法，如是此纯大苦阴灭。”

时，天王释闻已，白曰：“唯然，世尊。唯然，善逝。唯然，大仙人，念者，因思缘思，从思而生，由思故有。若无思者，则无有念。由念故有欲，由欲故有爱、不爱，由爱、不爱故有悭、嫉，由悭、嫉故有刀杖、斗诤、憎嫉、谀谄、欺诳、妄言、两舌，心中生无量恶不善之法，如是此纯大苦阴生。若无思者，则无有念；若无念者，则无有欲；若无欲者，则无爱、不爱；若无爱、不爱者，则无悭、嫉；若无悭、嫉者，则无刀杖、斗诤、憎嫉、谀谄、欺诳、妄言、两舌，心中不生无量恶不善之法，如是此纯大苦阴灭。唯然，世尊。唯然，善逝。唯然，大仙人，如佛所说法，我悉知之，我断疑度惑，无有犹豫，闻佛所说故。”

时，天王释闻佛所说，欢喜奉行。

复问曰：“大仙人，何者灭戏道迹？比丘何行趣向灭戏道迹耶？”

世尊闻已，答曰：“拘翼，灭戏道迹者，谓八支圣道，正见乃至正定为八。拘翼，是谓灭戏道迹。比丘者，行此趣向灭戏道迹。”

时，天王释闻已，白曰：“唯然，世尊。唯然，善逝。唯然，大仙人，灭戏道迹者，谓八支圣道，正见乃至正定为八。大仙人，是为灭戏道迹。比丘者，行此趣向灭戏道迹。唯然，世尊。唯然，善逝。唯然，大仙人，如佛所说法，我悉知之，我断疑度惑，无有犹豫，闻佛所说故。”

时，天王释闻佛所说，欢喜奉行。

复问曰：“大仙人，比丘者，趣向灭戏道迹，断几法，行几法耶？”

世尊闻已，答曰：“拘翼，比丘者，趣向灭戏道迹，断三法，修行三法。云何为三？一曰、念，二曰、言，三曰、求。拘翼，念者，我说有二种：可行、不可行。若念不可行者，我即断彼；若念可行者，我为彼知时，有念有智，为成就彼念故。言亦如是。拘翼，求者，我说亦有二种：可行、不可行。若求不可行者，我即断彼；若求可行者，我为彼知时，有念有智，成就彼求故。”

时，天王释闻已，白曰：“唯然，世尊。唯然，善逝。唯然，大仙人，比丘者，趣向灭戏道迹，断三法，修行三法。云何为三？一曰、念，二曰、言，三曰、求。大仙人说念有二种：可行、不可行，若念增长恶不善法，减损善法者，大仙人便断彼；若念减损恶不善法，增长善法者，大仙人为彼知时，有念有智，成就彼念故。言亦如是。大仙人说求亦有二种：可行、不可行。若求增长恶不善法，减损善法者，大仙人便断彼；若求减损恶不善法，增长善法者，大仙人为彼知时，有念有智，成就彼求故。唯然，世尊。唯然，善逝。唯然，大仙人，如佛所说法，我悉知之，我断疑度惑，无有犹豫，闻佛所说故。”

时，天王释闻佛所说，欢喜奉行。

复问曰：“大仙人，比丘者，趣向灭戏道迹有几法，护从解脱行几法耶？”

世尊闻已，答曰：“拘翼，比丘者，趣向灭戏道迹有六法，护从解脱行六法也。云何为六？眼视色，耳闻声，鼻嗅香，舌尝味，身觉触，意知法。拘翼，眼视色者，我说有二种：可行、不可行。若眼视色不可行者，我即断彼；若眼视色可行者，我为彼知时，有念有智，成就彼故。如是耳闻声、鼻嗅香、舌尝味、身觉触、意知法者，我说亦有二种：可行、不可行。若意知法不可行者，我即断彼；若意知法可行者，我为彼知时，有念有智，成就彼故。”

时，天王释闻已，白曰：“唯然，世尊。唯然，善逝。唯然，大仙人，比丘者，趣向灭戏道迹者有六法，护从解脱行六法。云何为六？眼视色，耳闻声，鼻嗅香，舌尝味，身觉触，意知法。大仙人说眼视色者，有二种：可行、不可行。若眼视色增长恶不善法，减损善法者，大仙人即断彼；若眼视色减损恶不善法，增长善法者，大仙人为彼知时，有念有智，成就彼故。如是耳闻声、鼻嗅香、舌尝味、身觉触，大仙人说意知法者，亦有二种：可行、不可行。若意知法增长恶不善法，减损善法者，大仙人即断彼；若意知法减损恶不善法，增长善法者，大仙人为彼知时，有念有智，成就彼故。唯然，世尊。唯然，善逝。唯然，大仙人，如佛所说法，我悉知之，我断疑度惑，无有犹豫，闻佛所说故。”

时，天王释闻佛所说，欢喜奉行。

复问曰：“大仙人，比丘者，趣向灭戏道迹，命存一时顷，复断几法，行几法耶？”

世尊闻已，答曰：“拘翼，比丘者，趣向灭戏道迹，命存一时顷，复断三法，行三法。云何为三？一曰、喜，二曰、忧，三曰、舍。拘翼，喜者，我说有二种：可行、不可行。若喜不可行者，我即断彼；若喜可行者，我为彼知时，有念有智，成就彼故。忧亦如是。拘翼，舍者，我说亦有二种：可行、不可行。若舍不可行者，我即断彼；若舍可行者，我为彼知时，有念有智，成就彼故。”

时，天王释闻已，白曰：“唯然，世尊。唯然，善逝。唯然，大仙人，比丘者，趣向灭戏道迹，命存一时顷，断三法，行三法。云何为三？一曰、喜，二曰、忧，三曰、舍。大仙人说喜者，有二种：可行、不可行。若喜增长恶不善法，减损善法者，大仙人即断彼；若喜减损恶不善法，增长善法者，大仙人为彼知时，有念有智，成就彼故。忧亦如是。大仙人说舍者，亦有二种：可行、不可行。若舍增长恶不善法，减损善法者，大仙人即断彼；若舍减损恶不善法，增长善法者，大仙人为彼知时，有念有智，成就彼故。唯然，世尊。唯然，善逝。唯然，大仙人，如佛所说法，我悉知之，我断疑度惑，无有犹豫，闻佛所说故。”

时，天王释闻佛所说，欢喜奉行。

复问曰：“大仙人，一切沙门、梵志同一说、一欲、一爱、一乐、一意耶？”

世尊闻已，答曰：“拘翼，一切沙门、梵志不同一说、一欲、一爱、一乐、一意也。”

时，天王释复问曰：“大仙人，一切沙门、梵志以何等故，不同一说、一欲、一爱、一乐、一意耶？”

世尊闻已，答曰：“拘翼，此世有若干种界，有无量界，彼随所知界，即彼界随其力，随其方便，一向说此为真谛，余者虚妄。拘翼，是故一切沙门、梵志不同一说、一欲、一爱、一乐、一意耳！”

时，天王释闻已，白曰：“唯然，世尊。唯然，善逝。唯然，大仙人，此世有若干种界，有无量界，彼随所知界，即彼界随其力，随其方便，一向说此为真谛，余者虚妄。大仙人，以是故，一切沙门、梵志不同一说、一欲、一爱、一乐、一意耳！唯然，世尊。唯然，善逝。唯然，大仙人，如佛所说法，我悉知之，我断疑度惑，无有犹豫，闻佛所说故。”

时，天王释闻佛所说，欢喜奉行。

复问曰：“大仙人，一切沙门、梵志得至究竟，究竟白净、究竟梵行、究竟梵行讫耶？”

世尊闻已，答曰：“拘翼，不必一切沙门、梵志得至究竟，究竟白净、究竟梵行、究竟梵行讫。”

时，天王释复问曰：“大仙人，以何等故，不必一切沙门、梵志得至究竟，究竟白净、究竟梵行、究竟梵行讫耶？”

世尊闻已，答曰：“拘翼，若有沙门、梵志于无上爱尽，不正善心解脱者，彼不至究竟，不究竟白净，不究竟梵行，不究竟梵行讫。拘翼，若有沙门、梵志于无上爱尽，正善心解脱者，彼至究竟、究竟白净、究竟梵行、究竟梵行讫。”

时，天王释闻已，白曰：“唯然，世尊。唯然，善逝。唯然，大仙人，若有沙门、梵志于无上爱尽，不正善心解脱者，彼不至究竟，不究竟白净，不究竟梵行，不究竟梵行讫。大仙人，若有沙门、梵志，于无上爱尽，正善心解脱者，彼至究竟，究竟白净、究竟梵行、究竟梵行讫。唯然，世尊。唯然，善逝。唯然，大仙人，如佛所说法，我悉知之，我断疑度惑，无有犹豫，闻佛所说故。”

时，天王释闻佛所说，善受善持，白曰：“大仙人，我于长夜有疑惑刺，世尊今日而拔出之。所以者何？谓如来、无所著、等正觉故。”

世尊问曰：“拘翼，汝颇忆昔时曾问余沙门、梵志如此事耶？”

时，天王释答曰：“世尊，唯大仙人自当知之。大仙人，三十三天集在法堂，各怀愁戚，数数叹说：‘我等若值如来、无所著、等正觉者，必当往见。大仙人，然我等不得值如来、无所著、等正觉已，便行具足五欲功德。大仙人，我等放逸，行放逸已，大威德天子于极妙处，即便命终。大仙人，我见大威德天子于极妙处，即命终时，便生极厌，身毛皆竖：‘莫令我于此处速命终！”

“大仙人，我因此厌、因此忧戚故，若见余沙门、梵志在无事处山林树下，乐居高岩，寂无音声，远离，无恶，无有人民，随顺宴坐，彼乐远离，宴坐安隐，快乐游行。我见彼已，便谓是如来、无所著、等正觉，即往奉见。彼不识我，而问我言：‘汝为是谁？我时答彼：‘大仙人，我是天王释。大仙人，我是天王释。彼复问我：‘我曾见释，亦见释种姓，以何等故名为释？以何等故为释种姓？我便答彼：‘大仙人，若有来问我事者，我便随所能、随其力而答彼，是故我名为释。彼作是说：‘我等若随其事以问释者，释亦随其事答我。彼问我事，我不问彼；彼归命我，我不归命彼。大仙人，从彼沙门、梵志竟不得威仪法教，况复得如是问耶？”

时，天王释而说颂曰：

<div class="poem">

释往释往已，释今作是说，\\
远离意所念，除疑诸犹豫。\\
久远行于世，推求索如来，\\
见沙门梵志，在远离宴坐，\\
谓是正尽觉，往奉敬礼事。\\
云何得升进？如是我问彼，\\
问已不能知，圣道及道迹。\\
世尊今为我，若意有所疑，\\
所念及所思，其意之所行，\\
知心隐及现，明者为我说。\\
尊佛尊为师，尊无著牟尼，\\
尊断诸结使，自度度众生。\\
觉者第一觉，御者最上御，\\
息者尊妙息，大仙自度度。\\
故我礼大雄，稽首人最上，\\
断绝诸爱刺，我礼日之亲。

</div>

于是，世尊问曰：“拘翼，汝颇忆昔时，得如是离，得如是欢喜，谓于我得法喜耶？”

时，天王释答曰：“世尊，唯大仙人自当知之。大仙人，昔一时天及阿修罗而共斗战。大仙人，天及阿修罗共斗战时，我作是念：‘令天得胜破阿修罗，诸天食及阿修罗食，尽令三十三天食。大仙人，天及阿修罗共斗战时，天便得胜，破阿修罗，诸天食及阿修罗食，尽令三十三天食。大仙人，尔时有离有喜，杂刀杖、结怨、斗诤、憎嫉；不得神通，不得觉道，不得涅槃。大仙人，今日得离得喜，不杂刀杖、结怨、斗诤、憎嫉；得通得觉，亦得涅槃。”

世尊问曰：“拘翼，汝何因得离得喜？谓于我得法喜耶？”

时，天王释答曰：“大仙人，我作是念：‘我于此命终，生于人间，彼若有族，极大富乐，资财无量，畜牧、产业不可称计，封户、食邑种种具足，谓刹利长者族、梵志长者族、居士长者族及余族，极大富乐，资财无量，畜牧、产业不可称计，封户、食邑种种具足。生如是族已，成就诸根，如来所说法、律有得信者；得信已，剃除须发，著袈裟衣，至信、舍家、无家、学道。学智，学智已，若得智者，便得究竟智，得究竟边。学智，学智已，若得智、不得究竟智者，若有诸天，有大福佑，色像巍巍，光耀暐烨，极有威力，安隐快乐，长住宫殿，生于最上，我生彼中。”

于是，天王释而说颂曰：

<div class="poem">

舍离于天身，来下生人间，\\
不愚痴入胎，随我意所乐。\\
得身具足已，逮质直正道，\\
行具足梵行，常乐于乞食。

</div>

“学智，学智已，若得智者，便得究竟智，得究竟边。学智，学智已，若得智、不得究竟智者，当作最上妙天，诸天闻名，色究竟天，往生彼中。大仙人，愿当得阿那含。大仙人，我今定得须陀洹。”

世尊问曰：“拘翼，汝何因得此极好、极高、极广差降，而自称说得须陀洹耶？”

时，天王释以偈答曰：

<div class="poem">

不更有余尊，唯世尊境界，\\
得最上差降，未曾有此处。\\
大仙我此坐，即于此天身，\\
我更得增寿，如是自眼见。

</div>

说此法时，天王释远尘离垢，诸法法眼生，及八万诸天亦远尘离垢，诸法法眼生。于是，天王释见法得法，觉白净法，断疑度惑，更无余尊，不复从他，无有犹豫，已住果证，于世尊法得无所畏；即从座起，稽首佛足，白曰：“世尊，我今自归佛、法及比丘众，惟愿世尊受我为优婆塞！从今日始，终身自归，乃至命尽。”

于是，天王释称叹五结乐子曰：“善哉！善哉！汝五结大益于我。所以者何？由汝故，佛从定寤。以汝先使世尊从定寤故，令我等后得见佛。五结，我从此归，以耽浮楼伎乐王女贤月色嫁与汝作妇，及其父乐王本国拜与汝作伎乐王。”

于是，天王释告三十三天曰：“汝等共来，若我等本为梵天，住梵天上，再三恭敬礼事者，彼今尽为世尊恭敬礼事。所以者何？世尊梵天，梵天当造化最尊生众生有及当有彼所，可知尽知，可见尽见。”

于是，天王释及三十三天、五结乐子若本为梵天，住梵天上，再三恭敬礼事者，彼尽为世尊恭敬礼事，稽首如来、无所著、等正觉。于是，天王释及三十三天、五结乐子再三为世尊恭敬礼事，稽首佛足，绕三匝已，即于彼处忽没不现。

尔时，梵天色像巍巍，光耀暐烨，夜将向旦，往诣佛所，稽首佛足，却住一面，即时以偈白世尊曰：

<div class="poem">

为多饶益义，见利义曰天，\\
贤住摩竭国，婆裟婆问事。

</div>

大仙人说此法时，天王释远尘离垢，诸法法眼生，及八万诸天亦远尘离垢，诸法法眼生。

于是，世尊告梵天曰：“如是！如是！如梵天所说：

<div class="poem">

为多饶益义，见利义曰天，\\
贤住摩竭国，婆娑婆问事。

</div>

“梵天，我说法时，天王释远尘离垢，诸法法眼生，及八万诸天亦远尘离垢，诸法法眼生。”

佛说如是，时天王释及三十三天、五结乐子并大梵天闻佛所说，欢喜奉行。

--------------

** 第33卷 大品.善生经第十九

我闻如是：一时，佛游王舍城，在饶虾蟆林。尔时，善生居士子，父临终时，因六方故，遗敕其子，善教善诃曰：“善生，我命终后，汝当叉手向六方礼：东方若有众生者，我尽恭敬、供养、礼事彼，我尽恭敬、供养、礼事彼已，彼亦当恭敬、供养、礼事我。如是南方、西方、北方、下方、上方，若有众生者，我尽恭敬、供养、礼事彼，我尽恭敬、供养、礼事彼已，彼亦当恭敬、供养、礼事我。”

善生居士子闻父教已，白父曰：“唯，当如尊敕。”

于是，善生居士子，父命终后，平旦沐浴，著新刍磨衣，手执生拘舍叶，往至水边，叉手向六方礼：“东方若有众生者，我尽恭敬、供养、礼事彼，我尽恭敬、供养、礼事彼已，彼亦当恭敬、供养、礼事我。如是南方、西方、北方、下方、上方，若有众生者，我尽恭敬、供养、礼事彼，我尽恭敬、供养、礼事彼已，彼亦当恭敬、供养、礼事我。”

彼时，世尊过夜平旦，著衣持钵，入王舍城而行乞食。世尊入王舍城乞食时，遥见善生居士子平旦沐浴，著新刍磨衣，手执生拘舍叶，往至水边，叉手向六方礼：“东方若有众生者，我尽恭敬、供养、礼事彼，我尽恭敬、供养、礼事彼已，彼亦当恭敬、供养、礼事我。如是南方、西方、北方、下方、上方，若有众生者，我尽恭敬、供养、礼事彼，我尽恭敬、供养、礼事彼已，彼亦当恭敬、供养、礼事我。”

世尊见已，往至善生居士子所，问曰：“居士子，受何沙门、梵志教？教汝恭敬、供养、礼事，平旦沐浴，著新刍磨衣，手执生拘舍叶，往至水边，叉手向六方礼：东方若有众生者，我尽恭敬、供养、礼事彼，我尽恭敬、供养、礼事彼已，彼亦当恭敬、供养、礼事我。如是南方、西方、北方、下方、上方，若有众生者，我尽恭敬、供养、礼事彼，我尽恭敬、供养、礼事彼已，彼亦当恭敬、供养、礼事我耶？”

善生居士子答曰：“世尊，我不受余沙门、梵志教也。世尊，我父临命终时，因六方故，遗敕于我，善教善诃曰：‘善生，我命终后，汝当叉手向六方礼：东方若有众生者，我尽恭敬、供养、礼事彼，我尽恭敬、供养、礼事彼已，彼亦当恭敬、供养、礼事我。如是南方、西方、北方、下方、上方，若有众生者，我尽恭敬、供养、礼事彼，我尽恭敬、供养、礼事彼已，彼亦当恭敬、供养、礼事我。世尊，我受父遗教，恭敬、供养、礼事故，平旦沐浴，著新刍磨衣，手执生拘舍叶，往至水边，叉手向六方礼：东方若有众生者，我尽恭敬、供养、礼事彼，我尽恭敬、供养、礼事彼已，彼亦当恭敬、供养、礼事我。如是南方、西方、北方、下方、上方，若有众生者，我尽恭敬、供养、礼事彼，我尽恭敬、供养、礼事彼已，彼亦当恭敬、供养、礼事我。”

世尊闻已，告曰：“居士子，我说有六方，不说无也。居士子，若有人善别六方，离四方恶不善业垢，彼于现法可敬可重，身坏命终，必至善处，上生天中。居士子，众生有四种业、四种秽。云何为四？居士子，杀生者，是众生业种、秽种；不与取、邪淫、妄言者，是众生业种、秽种。”

于是，世尊说此颂曰：

<div class="poem">

杀生不与取，邪淫犯他妻，\\
所言不真实，慧者不称誉。

</div>

“居士子，人因四事故，便得多罪。云何为四？行欲、行恚、行怖、行痴。”

于是，世尊说此颂曰：

<div class="poem">

欲恚怖及痴，行恶非法行，\\
彼必灭名称，如月向尽没。

</div>

“居士子，人因四事故，便得多福。云何为四？不行欲、不行恚、不行怖、不行痴。”

于是，世尊说此颂曰：

<div class="poem">

断欲无恚怖，无痴行法行，\\
彼名称普闻，如月渐盛满。

</div>

“居士子，求财物者，当知有六非道。云何为六？一曰、种种戏求财物者为非道，二曰、非时行求财物者为非道，三曰、饮酒放逸求财物者为非道，四曰、亲近恶知识求财物者为非道，五曰、常喜妓乐求财物者为非道，六曰、懒惰求财物者为非道。

“居士子，若人种种戏者，当知有六灾患。云何为六？一者、负则生怨，二者、失则生耻，三者、负则眠不安，四者、令怨家怀喜，五者、使宗亲怀忧，六者、在众所说人不信用。居士子，人博戏者，不经营作事；作事不营，则功业不成；未得财物，则不能得；本有财物，便转消耗。

“居士子，人非时行者，当知有六灾患。云何为六？一者、不自护，二者、不护财物，三者、不护妻子，四者、为人所疑，五者、多生苦患，六者、为人所谤。居士子，人非时行者，不经营作事；作事不营，则功业不成；未得财物，则不能得；本有财物，便转消耗。

“居士子，若人饮酒放逸者，当知有六灾患：一者、现财物失，二者、多有疾患，三者、增诸斗诤，四者、隐藏发露，五者、不称不护，六者、灭慧生痴。居士子，人饮酒放逸者，不经营作事；作事不营，则功业不成；未得财物，则不能得；本有财物，便转消耗。

“居士子，若人亲近恶知识者，当知有六灾患。云何为六？一者、亲近贼，二者、亲近欺诳，三者、亲近狂醉，四者、亲近放恣，五者、逐会嬉戏，六者、以此为亲友，以此为伴侣。居士子，若人亲近恶如识者，不经营作事；作事不营，则功业不成；未得财物，则不能得；本有财物，便转消耗。

“居士子，若人喜伎乐者，当知有六灾患。云何为六？一者、喜闻歌，二者、喜见舞，三者、喜往作乐，四者、喜见弄铃，五者、喜拍两手，六者、喜大聚会。居士子，若人喜伎乐者，不经营作事；作事不营，则功业不成；未得财物，则不能得；本有财物，便转消耗。

“居士子，若有懒惰者，当知有六灾患。云何为六？一者、大早不作业，二者、大晚不作业，三者、大寒不作业，四者、大热不作业，五者、大饱不作业，六者、大饥不作业。居士子，若人懒惰者，不经营作事；作事不营，则功业不成；未得财物，则不能得；本有财物，便转消耗。”

于是，世尊说此颂曰：

<div class="poem">

种种戏逐色，嗜酒喜作乐，\\
亲近恶知识，懒惰不作业，\\
放恣不自护，此处坏败人。\\
行来不防护，邪淫犯他妻，\\
心中常结怨，求愿无有利，\\
饮酒念女色，此处坏败人。\\
重作不善行，佷戾不受教，\\
骂沙门梵志，颠倒有邪见，\\
凶暴行黑业，此处坏败人。\\
自乏无财物，饮酒失衣被，\\
负债如涌泉，彼必坏门族。\\
数往至酒炉，亲近恶朋友，\\
应得财不得，是伴党为乐。\\
多有恶朋友，常随不善伴，\\
今世及后世，二俱得败坏。\\
人习恶转减，习善转兴盛，\\
习胜者转增，是故当习胜。\\
习升则得升，常逮智慧升，\\
转获清净戒，及与微妙止。\\
昼则喜眠卧，夜则好游行，\\
放逸常饮酒，居家不得成。\\
大寒及大热，谓有懒惰人，\\
至竟不成业，终不获财利。\\
若寒及大热，不计犹如草，\\
若人作是业，彼终不失乐。

</div>

“居士子，有四不亲而似亲。云何为四？一者、知事非亲似如亲，二者、面前爱言非亲似如亲，三者、言语非亲似如亲，四者、恶趣伴非亲似如亲。居士子，因四事故，知事非亲似如亲。云何为四？一者、以知事夺财，二者、以少取多，三者、或以恐怖，四者、或为利狎习。”

于是，世尊说此颂曰：

<div class="poem">

人以知为事，言语至柔软，\\
怖为利狎习，知非亲如亲，\\
常当远离彼，如道有恐怖。

</div>

“居士子，因四事故，面前爱言非亲似如亲。云何为四？一者、制妙事，二者、教作恶，三者、面前称誉，四者、背说其恶。”

于是，世尊说此颂曰：

<div class="poem">

若制妙善法，教作恶不善，\\
对面前称誉，背后说其恶，\\
若知妙及恶，亦复觉二说，\\
是亲不可亲，知彼人如是，\\
常当远离彼，如道有恐怖。

</div>

“居士子，因四事故，言语非亲似如亲。云何为四？一者、认过去事，二者、必辩当来事，三者、虚不真说，四者、现事必灭，我当作不作认说。”

于是，世尊说此颂曰：

<div class="poem">

认过及未来，虚论现灭事，\\
当作不作说，知非亲如亲，\\
常当远离彼，如道有恐怖。

</div>

“居士子，因四事故，恶趣伴非亲似如亲。云何为四？一者、教种种戏，二者、教非时行，三者、教令饮酒，四者、教亲近恶知识。”

于是，世尊说此颂曰：

<div class="poem">

教若干种戏，饮酒犯他妻，\\
习下不习胜，彼灭如月尽，\\
常当远离彼，如道有恐怖。

</div>

“居士子，善亲当知有四种。云何为四？一者、同苦乐，当知是善亲；二者、愍念，当知是善亲；三者、求利，当知是善亲；四者、饶益，当知是善亲。居士子，因四事故同苦乐，当知是善亲。云何为四？一者、为彼舍己，二者、为彼舍财，三者、为彼舍妻子，四者、所说堪忍。”

于是，世尊说此颂曰：

<div class="poem">

舍欲财妻子，所说能堪忍，\\
知亲同苦乐，慧者当狎习。

</div>

“居士子，因四事故愍念，当知是善亲。云何为四？一者、教妙法，二者、制恶法，三者、面前称说，四者、却怨家。”

于是，世尊说此颂曰：

<div class="poem">

教妙善制恶，面称却怨家，\\
知善亲愍念，慧者当狎习。

</div>

“居士子，因四事故求利，当知是善亲。云何为四？一者、密事发露，二者、密不覆藏，三者、得利为喜，四者、不得利不忧。”

于是，世尊说此颂曰：

<div class="poem">

密事露不藏，利喜无不忧，\\
知善亲求利，慧者当狎习。

</div>

“居士子，因四事故饶益，当知是善亲。云何为四？一者、知财物尽，二者、知财物尽已便给与物，三者、见放逸教诃，四者、常以愍念。”于是，世尊说此颂曰：

<div class="poem">

知财尽与物，放逸教愍念，\\
知善亲饶益，慧者当狎习。

</div>

“居士子，圣法、律中有六方：东方、南方、西方、北方、下方、上方。居士子，如东方者，如是子观父母，子当以五事奉敬供养父母。云何为五？一者、增益财物，二者、备办众事，三者、所欲则奉，四者、自恣不违，五者、所有私物尽以奉上。子以此五事奉敬供养父母，父母亦以五事善念其子。云何为五？一者、爱念儿子，二者、供给无乏，三者、令子不负债，四者、婚娶称可，五者、父母可意所有财物尽以付子。父母以此五事善念其子。居士子，如是东方二俱分别。居士子，圣法、律中东方者，谓子、父母也。居士子，若慈孝父母者，必有增益，则无衰耗。

“居士子，如南方者，如是弟子观师，弟子当以五事恭敬供养于师。云何为五？一者、善恭顺，二者、善承事，三者、速起，四者、所作业善，五者、能奉敬师。弟子以此五事恭敬供养于师，师亦以五事善念弟子。云何为五？一者、教技术，二者、速教，三者、尽教所知，四者、安处善方，五者、付嘱善知识。师以此五事善念弟子。居士子，如是南方二俱分别。居士子，圣法、律中南方者，谓弟子、师也。居士子，若人慈顺于师者，必有增益，则无衰耗。

“居士子，如西方者，如是夫观妻子，夫当以五事爱敬供给妻子。云何为五？一者、怜念妻子，二者、不轻慢，三者、为作璎珞严具，四者、于家中得自在，五者、念妻亲亲。夫以此五事爱敬供给妻子，妻子当以十三事善敬顺夫。云何十三？一者、重爱敬夫，二者、重供养夫，三者、善念其夫，四者、摄持作业，五者、善摄眷属，六者、前以瞻侍，七者、后以爱行，八者、言以诚实，九者、不禁制门，十者、见来赞善，十一者、敷设床待，十二者、施设净美丰饶饮食，十三者、供养沙门、梵志。妻子以此十三事善敬顺夫。居士子，如是西方二俱分别。居士子，圣法、律中西方者，谓夫、妻子也。居士子，若人慈愍妻子者，必有增益，则无衰耗。

“居士子，如北方者，如是大家观奴婢、使人，大家当以五事愍念给恤奴婢、使人。云何为五？一者、随其力而作业，二者、随时食之，三者、随时饮之，四者、及日休息，五者、病给汤药。大家以此五事愍念给恤奴婢、使人，奴婢、使人当以九事善奉大家。云何为九？一者、随时作业，二者、专心作业，三者、一切作业，四者、前以瞻侍，五者、后以爱行，六者、言以诚实，七者、急时不远离，八者、行他方时则便赞叹，九者、称大家庶几。奴婢、使人此以九事善奉大家。居士子，如是北方二俱分别。居士子，圣法、律中北方者，谓大家、奴婢、使人也。居士子，若有人慈愍奴婢、使人者，必有增益，则无衰耗。

“居士子，如下方者，如是亲友观亲友臣，亲友当以五事爱敬供给亲友臣。云何为五？一者、爱敬，二者、不轻慢，三者、不欺诳，四者、施与珍宝，五者、拯念亲友臣。亲友以此五事爱敬供给亲友臣，亲友臣亦以五事善念亲友。云何为五？一者、知财物尽，二者、知财物尽已供给财物，三者、见放逸教诃，四者、爱念，五者、急时可归依。亲友臣以此五事善念亲友。居士子，如是下方二俱分别。居士子，圣法、律中下方者，谓亲友、亲友臣也。居士子，若人慈愍亲友臣者，必有增益，则无衰耗。

“居士子，如上方者，如是施主观沙门、梵志，施主当以五事尊敬供养沙门、梵志。云何为五？一者、不禁制门，二者、见来赞善，三者、敷设床待，四者、施设净美丰饶饮食，五者、拥护如法。施主以此五事尊敬供养沙门、梵志，沙门、梵志亦以五事善念施主。云何为五？一者、教信、行信、念信，二者、教禁戒，三者、教博闻，四者、教布施，五者、教慧、行慧、立慧。沙门、梵志以此五事善念施主。居士子，如是上方二俱分别。居士子，圣法、律中上方者，谓施主、沙门、梵志也。居士子，若人尊奉沙门、梵志者，必有增益，则无衰耗。

“居士子，有四摄事。云何为四？一者、惠施，二者、爱言，三者、行利，四者、等利。”

于是，世尊说此颂曰：

<div class="poem">

惠施及爱言，常为他行利，\\
众生等同利，名称普远至。\\
此则摄持世，犹如御车人，\\
若无摄持者，母不因其子，\\
得供养恭敬，父因子亦然，\\
若有此法摄，故得大福佑。\\
照远犹日光，速利翻捷疾，\\
不粗说聪明，如是得名称。\\
定护无贡高，速利翻捷疾，\\
成就信尸赖，如是得名称。\\
常起不懒惰，喜施人饮食，\\
将去调御正，如是得名称。\\
亲友臣同恤，爱乐有齐限，\\
谓摄在亲中，殊妙如师子。\\
初当学技术，于后求财物，\\
后求财物已，分别作四分，\\
一分作饮食，一分作田业，\\
一分举藏置，急时赴所须，\\
耕作商人给，一分出息利。\\
第五为取妇，第六作屋宅，\\
家若具六事，不增快得乐，\\
彼必饶钱财，如海中水流。\\
彼如是求财，犹如蜂采华，\\
长夜求钱财，当自受快乐。\\
出财莫令远，亦勿令普漫，\\
不可以财与，凶暴及豪强。\\
东方为父母，南方为师尊，\\
西方为妻子，北方为奴婢，\\
下方亲友臣，上沙门梵志。\\
愿礼此诸方，二俱得大称，\\
礼此诸方已，施主得生天。

</div>

佛说如是，善生居士子闻佛所说，欢喜奉行。

--------------

** 第34卷 大品.商人求财经第二十

我闻如是：一时，佛游舍卫国，在胜林给孤独园。

尔时，世尊告诸比丘：“乃往昔时，阎浮洲中诸商人等皆共集会在贾客堂，而作是念：‘我等宁可乘海装船，入大海中取财宝来，以供家用。复作是念：‘诸贤入海，不可豫知安隐、不安隐，我等宁可各各备办浮海之具，谓羖羊皮囊、大瓠、押筏。彼于后时各各备办浮海之具羖羊皮囊、大瓠、押筏，便入大海。彼在海中为摩竭鱼王破坏其船，彼商人等各各自乘浮海之具羖羊皮囊、大瓠、押筏，浮向诸方。

“尔时，海东大风卒起，吹诸商人至海西岸。彼中逢见诸女人辈，极妙端正，一切严具以饰其身。彼女见已，便作是语：‘善来！诸贤。快来！诸贤。此间极乐最妙好处，园观浴池、坐卧处所、林木蓊郁，多有钱财、金银、水精、琉璃、摩尼、真珠、碧玉、白珂、砗磲、珊瑚、琥珀、玛瑙、玳瑁、赤石、琁珠，尽与诸贤。当与我等共相娱乐，莫令阎浮洲商人南行，乃至于梦。彼商人等皆与妇人共相娱乐。彼商人等因共妇人合会，生男或复生女。彼于后时，阎浮洲有一智慧商人独住静处，而作是念：‘以何等故，此妇人辈制于我等不令南行耶？我宁可伺共居妇人，知彼眠已，安徐而起，当窃南行。

“彼阎浮洲一智慧商人则于后，伺其居妇人，知彼眠已，安徐而起，即窃南行。彼阎浮洲一智慧商人既南行已，遥闻大音高声唤叫，众多人声啼哭懊恼，唤父呼母，呼唤妻子及诸爱念亲亲朋友：‘好阎浮洲安隐快乐，不复得见。彼商人闻已，极大恐怖，身毛皆竖：‘莫令人及非人触娆我者。于是，阎浮洲一智慧商人自制恐怖，复进南行。彼阎浮洲一智慧商人进行南已，忽见东边有大铁城，见已，遍观不见其门，乃至可容猫子出处。

“彼阎浮洲一智慧商人见铁城北有大丛树，即往至彼大丛树所，安徐缘上，上已，问彼大众人曰：‘诸贤，汝等何故啼哭懊恼、唤父呼母、呼唤妻子及诸爱念亲亲朋友：好阎浮洲安隐快乐，不复得见耶？时，大众人便答彼曰：‘贤者，我等是阎浮洲诸商人也，皆共集会在贾客堂，而作是念：“我等宁可乘海装船，入大海中取财宝，求以供家用。”贤者，我等复作是念：“诸贤，我等入海，不可豫知安隐不安隐，我等宁可各各备办浮海之具，谓羖羊皮囊、大瓠、押筏。”贤者，我于后时各各备办浮海之具，谓羖羊皮囊、大瓠、押筏，便入大海。贤者，我等在海中，为摩竭鱼王破坏其船。贤者，我等商人各各自乘浮海之具羖羊皮囊、大瓠、押筏，浮向诸方。尔时，海东大风卒起，吹我等商人至海西岸。彼中逢见诸女人辈，极妙端正，一切严具以饰其身。彼女见已，便作是语：“善来！诸贤。快来！诸贤。此间极乐最妙好处，园观浴池、坐卧处所、林木蓊郁，多有钱财、金银、水精、琉璃、摩尼、真珠、碧玉、白珂、砗磲、珊瑚、琥珀、玛瑙、玳瑁、赤石、琁珠，尽与诸贤。当与我等共相娱乐，莫令阎浮洲商人南行，乃至于梦。”贤者，我等与彼妇人共相娱乐。我等因共妇人合会，生男或复生女。贤者，若彼妇人不闻阎浮洲余诸商人在于海中，为摩竭鱼王破坏船者，则与我等共相娱乐。贤者，若彼妇人闻阎浮洲有诸商人在于海中，为摩竭鱼王破坏船者，便食我等，极遭逼迫。若食人时，有余发毛及爪齿者，彼妇人等尽取食之。若食人时，有血滴地，彼妇人等便以手爪掘地深四寸，取而食之。贤者，当知我等阎浮洲商人本有五百人，于中已啖二百五十，余有二百五十今皆在此大铁城中。贤者，汝莫信彼妇人语，彼非真人，是罗刹鬼耳！

“于是，阎浮洲一智慧商人于大丛树安徐下已，复道而还彼妇人所本共居处，知彼妇人故眠未寤，即于其夜，彼阎浮洲一智慧商人速往至彼阎浮洲诸商人所，便作是语：‘汝等共来，当至静处。汝各独往，勿将儿去，当共在彼，密有所论。彼阎浮洲诸商人等共至静处，各自独去，不将儿息。

“于是，阎浮洲一智慧商人语曰：‘诸商人，我则独住于安静处，而作是念：“以何等故，此妇人辈制于我等不今南行耶？我宁可伺共居妇人，知彼眠已，安徐而起，当窃南行。”于是，我便伺共居妇人，知彼眠已，我安徐起，即窃南行。我南行已，遥闻大音高声唤叫，众多人声啼哭懊恼，唤父呼母，呼唤妻子及诸爱念亲亲朋友：“好阎浮洲安隐快乐，不复得见。”我闻是已，极大恐怖，身毛皆竖：“莫令人及非人触娆我者。”于是，我便自制恐怖，复进南行。进南行已，忽见东边有大铁城。见已，遍观不见其门，乃至可容猫子出处。我复见于大铁城北有大丛树，即往至彼大丛树所，安徐缘上。上已，问彼大众人曰：“诸贤，汝等何故啼哭懊恼、唤父呼母、呼唤妻子及诸爱念亲亲朋友：好阎浮洲安隐快乐，不复得见耶？”彼大众人而答我曰：“贤者，我等是阎浮洲诸商人，皆共集会在贾客堂，而作是念：我等宁可乘海装船，入大海中取财宝来以供家用。贤者，我等复作是念：诸贤，我等入海，不可豫知安隐不安隐，我等宁可各各备办浮海之具，谓羖羊皮囊、大瓠、押筏。贤者，我等后时各各备办浮海之具，谓羖羊皮囊、大瓠、押筏，便入大海。贤者，我等在海中，为摩竭鱼王破坏其船。贤者，我等商人各各自乘浮海之具羖羊皮囊、大瓠、押筏，浮向诸方。尔时，海东大风卒起，吹我等商人至海西岸。彼中逢见诸女人辈，极妙端正，一切严具以饰其身。彼女见已，便作是语：善来！诸贤。快来！诸贤。此间极乐最妙好处，园观浴池、坐卧处所、林木蓊郁，多有钱财、金银、水精、琉璃、摩尼、真珠、碧玉、白珂、砗磲、珊瑚、琥珀、玛瑙、玳瑁、赤石、琁珠，尽与诸贤，当与我等共相娱乐，莫令阎浮洲商人南行，乃至于梦。贤者，我等与彼妇人共相娱乐，我等因共妇人合会，生男或复生女。贤者，若彼妇人不闻阎浮洲更有商人在于海中，为摩竭鱼王破坏船者，则与我等共相娱乐。贤者，若彼妇人闻阎浮洲更有商人在于海中，为摩竭鱼王破坏船者，便食我等，极遭逼迫。若食人时，有余发毛及爪齿者，彼妇人等尽取食之。若食人时，有血滴地，彼妇人等便以手爪掘地深四寸，取而食之。贤者，当知我等阎浮洲商人本有五百人，于中已啖二百五十，余有二百五十，今皆在此大铁城中。贤者，汝莫信彼妇人语，彼非真人，是罗刹鬼耳！”

“于是，阎浮洲诸商人问彼阎浮洲一智慧商人曰：‘贤者不问彼大众人：诸贤，颇有方便令我等及汝等从此安隐度至阎浮洲耶？阎浮洲一智慧商人答曰：‘诸贤，我时脱，不如是问也。于是，阎浮洲诸商人语曰：‘贤者，还去至本共居妇人处已，伺彼眠时，安徐而起，更窃南行。复往至彼大众人所问曰：诸贤，颇有方便令我等及汝等从此安隐度至阎浮洲耶？于是，阎浮洲一智慧商人为诸商人默然而受。

“是时，阎浮洲一智慧商人还至共居妇人处已，伺彼眠时，安徐而起，即窃南行。复往至彼大众人所，问曰：‘诸贤，颇有方便令我等及汝等从此安隐度至阎浮洲耶？彼大众人答曰：‘贤者，更无方便令我等从此安隐度至阎浮洲。贤者，我作是念：“我等当共破掘此墙，还归本所。”适发心已，此墙转更倍高于常。贤者，是谓方便令我等不得从此安隐度至阎浮洲。贤者，别有方便可令汝等从此安隐度至阎浮洲，我等永无方便。诸贤，我等闻天于空中唱曰：“阎浮洲诸商人愚痴不定，亦不善解。所以者何？不能令十五日说从解脱时而南行。”彼有䭷马王，食自然粳米，安隐快乐，充满诸根，再三唱曰：“谁欲度彼岸？谁欲使我脱？谁欲使我将从此安隐度至阎浮洲耶？”汝等可共诣䭷马王而作是语：“我等欲得度至彼岸，愿脱我等，愿将我等从此安隐度至阎浮洲！”贤者，是谓方便令汝等从此安隐度至阎浮洲。商人汝来，可往至彼䭷马王所，而作是语：“我等欲得度至彼岸，愿脱我等，愿将我等从此安隐度至阎浮洲！”

“于是，阎浮洲有一智慧商人语曰：‘诸商人，今时往诣䭷马王所，而作是语：“我等欲得度至彼岸，愿脱我等，愿将我等从此安隐度至阎浮洲！”诸商人随诸天意，诸商人若使十五日说从解脱时，䭷马王食自然粳米，安隐快乐，充满诸根，再三唱曰：“谁欲度彼岸？谁欲从我脱？谁欲使我将从此安隐度至阎浮洲耶？”我等尔时即往彼所，而作是语：“我等欲得度至彼岸，愿脱我等，愿将我等从此安隐度至阎浮洲！”

“于是，䭷马王后十五日说从解脱时，食自然粳米，安隐快乐，充满诸根，再三唱曰：‘谁欲得度彼岸？我当脱彼，我当将彼从此安隐度至阎浮洲。时，阎浮洲诸商人闻已，即便往诣䭷马王所而作是语：‘我等欲得度至彼岸，愿脱我等，愿将我等从此安隐度至阎浮洲！时，䭷马王语曰：‘商人，彼妇人等必当抱儿共相将来而作是语：“诸贤，善来还此，此间极乐最妙好处，园观浴池、坐卧处所、林木蓊郁，多有钱财、金银、水精、琉璃、摩尼、真珠、碧玉、白珂、砗磲、珊瑚、琥珀、玛瑙、玳瑁、赤石、琁珠，尽与诸贤，当与我等共相娱乐，设不用我者，当怜念儿子。”若彼商人而作是念“我有男女，我有极乐最妙好处，园观浴池、坐卧处所、林木蓊郁，我多有钱财、金银、水精、琉璃、摩尼、真珠、碧玉、白珂、砗磲、珊瑚、琥珀、玛瑙、玳瑁、赤石、琁珠”者，彼虽骑我正当背中，彼必颠倒，落堕于水，便当为彼妇人所食，当遭逼迫。若食人时，有余发毛及爪齿者，彼妇人便当尽取食之。复次，若食人时，有血滴地，彼妇人等便以手爪掘地深四寸，取而食之。若彼商人不作是念“我有男女，我有极乐最妙好处，园观浴池、坐卧处所、林木蓊郁，我多有钱财、金银、水精、琉璃、摩尼、真珠、碧玉、白珂、砗磲、珊瑚、琥珀、玛瑙、玳瑁、赤石、琁珠”者，彼虽持我身上一毛，彼必安隐度至阎浮洲。”

于是，世尊告诸比丘：“彼妇人等抱儿子来，而作是语：‘诸贤，善来还此，此间极乐最妙好处，园观浴池、坐卧处所、林木蓊郁，多有钱财、金银、水精、琉璃、摩尼、真珠、碧玉、白珂、砗磲、珊瑚、琥珀、玛瑙、玳瑁、赤石、琁珠，尽与诸贤，当与我等共相娱乐。若彼商人而作是念‘我有男女，我有极乐最妙好处，园观浴池、坐卧处所、林木蓊郁，我多有钱财、金银、水精、琉璃、摩尼、真珠、碧玉、白珂、砗磲、珊瑚、琥珀、玛瑙、玳瑁、赤石、琁珠者，彼虽得骑䭷马王脊正当背中，彼必颠倒，落堕于水，便当为彼妇人所食，当遭逼迫。若食人时，有余发毛及爪齿者，彼妇人等尽取食之。复次，食彼人时，有血滴地，彼妇人等便以手爪掘地深四寸，取而食之。若彼商人不作是念‘我有男女，我有极乐最妙好处，园观浴池、坐卧处所、林木蓊郁，我多有钱财、金银、水精、琉璃、摩尼、真珠、碧玉、白珂、砗磲、珊瑚、琥珀、玛瑙、玳瑁、赤石、琁珠者，彼虽持䭷马王一毛者，彼必安隐度至阎浮洲。

“诸比丘，我说此喻，欲令知义，此说是义。我法善说，发露极广，善护无有空缺，如桥筏浮具，遍满流布，乃至天人；如是我法善说，发露极广，善护无有空缺，如桥筏浮具，遍满流布，乃至天人。若有比丘作如是念‘眼是我，我有眼；耳、鼻、舌、身、意是我，我有意者，彼比丘必被害，犹如商人为罗刹所食。

“我法善说，发露极广，善护无有空缺，如桥筏浮具，遍满流布，乃至天人；如是我法善说，发露极广，善护无有空缺，如桥筏浮具，遍满流布，乃至天人。若有比丘作如是念‘眼非是我，我无有眼；耳、鼻、舌、身、意非是我，我无有意者，彼比丘得安隐去，犹如商人乘䭷马王安隐得度。

“我法善说，发露极广，善护无有空缺，如桥筏浮具，遍满流布，乃至天人；如是我法善说，发露极广，善护无有空缺，如桥筏浮具，遍满流布，乃至天人。若有比丘作如是念‘色是我，我有色；声、香、味、触、法是我，我有法者，彼比丘必被害，犹如商人为罗刹所食。

“我法善说，发露极广，善护无有空缺，如桥筏浮具，遍满流布，乃至天人；如是我法善说，发露极广，善护无有空缺，如桥筏浮具，遍满流布，乃至天人。若有比丘作如是念‘色非是我，我无有色；声、香、味、触、法非是我，我无有法者，彼比丘得安隐去，犹如商人乘䭷马王安隐得度。

“我法善说，发露极广，善护无有空缺，如桥筏浮具，遍满流布，乃至天人；如是我法善说，发露极广，善护无有空缺，如桥筏浮具，遍满流布，乃至天人。若有比丘作如是念‘色阴是我，我有色阴；觉、想、行、识阴是我，我有识阴者，彼比丘必被害，犹如商人为罗刹所食。

“我法善说，发露极广，善护无有空缺，如桥筏浮具，遍满流布，乃至天人；如是我法善说，发露极广，善护无有空缺，如桥筏浮具，遍满流布，乃至天人。若有比丘作如是念‘色阴非是我，我无有色阴；觉、想、行、识阴非是我，我无有识阴者，彼比丘得安隐去，犹如商人乘䭷马王安隐得度。

“我法善说，发露极广，善护无有空缺，如桥筏浮具，遍满流布，乃至天人；如是我法善说，发露极广，善护无有空缺，如桥筏浮具，遍满流布，乃至天人。若有比丘作如是念‘地是我，我有地；水、火、风、空、识是我，我有识者，彼比丘必被害，犹如商人为罗刹所食。

“我法善说，发露极广，善护无有空缺，如桥筏浮具，遍满流布，乃至天人；如是我法善说，发露极广，善护无有空缺，如桥筏浮具，遍满流布，乃至天人。若有比丘作如是念‘地非是我，我无有地；水、火、风、空、识非是我，我无有识者，彼比丘得安隐去，犹如商人乘䭷马王安隐得度。”

于是，世尊说此颂曰：

<div class="poem">

若有不信于，佛说正法律，\\
彼人必被害，如为罗刹食。\\
若人有信于，佛说正法律，\\
彼得安隐度，如乘䭷马王。

</div>

佛说如是，彼诸比丘闻佛所说，欢喜奉行。

--------------

** 第34卷 大品.世间经第二十一

我闻如是：一时，佛游舍卫国，在胜林给孤独园。

尔时，世尊告诸比丘：“如来自觉世间，亦为他说，如来知世间。如来自觉世间集，亦为他说，如来断世间集。如来自觉世间灭，亦为他说，如来世间灭作证。如来自觉世间道迹，亦为他说，如来修世间道迹。若有一切尽普正，有彼一切如来知见觉得。所以者何？如来从昔夜觉无上正尽之觉，至于今日夜，于无余涅槃界，当取灭讫。于其中间，若如来口有所言说，有所应对者，彼一切是真谛，不虚不离于如，亦非颠倒，真谛审实。若说师子者，当知说如来。所以者何？如来在众有所讲说，谓师子吼，一切世间，天及魔、梵、沙门、梵志，从人至天，如来是梵有，如来至冷有，无烦亦无热，真谛不虚有。”

于是，世尊说此颂曰：

<div class="poem">

知一切世间，出一切世间，\\
说一切世间，一切世如真。\\
彼最上尊雄，能解一切缚，\\
得尽一切业，生死悉解脱。\\
是天亦是人，若有归命佛，\\
稽首礼如来，甚深极大海。\\
知已亦修敬，诸天香音神，\\
彼亦稽首礼，谓随于死者。\\
稽首礼智士，归命人之上，\\
无忧离尘安，无碍诸解脱。\\
是故当乐禅，住远离极定，\\
当自作灯明，无我必失时，\\
失时有忧戚，谓堕地狱中。

</div>

佛说如是，彼诸比丘闻佛所说，欢喜奉行。

--------------

** 第34卷 大品.福经第二十二

我闻如是：一时，佛游舍卫国，在胜林给孤独园。

尔时，世尊告诸比丘：“莫畏于福，爱乐意所念。所以者何？福者是说乐，畏于福，不爱乐意所念。所以者何？非福者，是说苦。何以故？我忆往昔长夜作福，长夜受报，爱乐意所念。我往昔时七年行慈，七反成败，不来此世。世败坏时，生晃昱天；世成立时，来下生空梵宫殿中。于彼梵中，作大梵天。余处千返作自在天王，三十六返作天帝释，复无量返作刹利顶生王。

“比丘，我作刹利顶生王时，有八万四千大象，被好乘具，众宝校饰，白珠珞覆，于娑贺象王为首。比丘，我作刹利顶生王时，有八万四千马，被好乘具，众宝严饰，金银交络，䭷马王为首。比丘，我作刹利顶生王时，有八万四千车，四种校饰，庄以众好，师子、虎豹斑文之皮织成杂色，种种校饰，极利疾，名乐声车为首。比丘，我作刹利顶生王时，有八万四千大城，极大富乐，多有人民，拘舍惒提王城为首。比丘，我作刹利顶生王时，有八万四千楼，四种宝楼金、银、琉璃及水精，正法殿为首。

“比丘，我作刹利顶生王时，有八万四千御座，四种宝座金、银、琉璃及水精，敷以氍氀、毾𣰆，覆以锦绮罗縠，有衬体被，两头安枕，加陵伽波惒罗波遮悉哆罗那。比丘，我作刹利顶生王时，有八万四千双衣，有初摩衣，有锦缯衣，有劫贝衣，有加陵伽波惒罗衣。比丘，我作刹利顶生王时，有八万四千女，身体光泽，皦洁明净，美色过人，小不及天，恣容端正，睹者欢悦，众宝璎珞严饰具足，尽刹利种女，余族无量。

“比丘，我作刹利顶生王时，有八万四千种食，昼夜常供，为我故设，欲令我食。比丘，彼八万四千种食中，有一种食，极美净洁，无量种味，是我常所食。比丘，彼八万四千女中，有一刹利女，最端正姝妙，常奉侍我。比丘，彼八万四千双衣中，有一双衣，或初摩衣，或锦缯衣，或劫贝衣，或加陵伽波惒罗衣，是我常所著。比丘，彼八万四千御座中，有一御座，或金或银，或琉璃，或水精，敷以氍氀、毾𣰆，覆以锦绮罗縠，有衬体被，两头安枕，加陵伽波惒罗波遮悉哆逻那，是我常所卧。

“比丘，彼八万四千楼观中，有一楼观，或金或银，或琉璃，或水精，名正法殿，是我常所住。比丘，彼八万四千大城中，有一城极大富乐，多有人民，名拘舍惒提，是我常所居。比丘，彼八万四千车中而有一车，庄以众好，师子、虎豹斑文之皮织成杂色，种种庄饰，极利疾，名乐声车，是我常所载，至观望园观。比丘，彼八万四千马中而有一马，体绀青色，头像如乌，名䭷马王，是我常所骑，至观望园观。比丘，彼八万四千大象中而有一象，举体极白，七支尽正，名于娑贺象王，是我常所乘，至观望园观。

“比丘，我作此念：‘是何业果？为何业报？令我今日有大如意足，有大威德，有大福佑，有大威神？比丘，我复作此念：‘是三业果，为三业报，令我今日有大如意足，有大威德，有大福佑，有大威神：一者、布施，二者、调御，三者、守护。”

于是，世尊说此颂曰：

<div class="poem">

观此福之报，妙善多饶益。\\
比丘我在昔，七年修慈心，\\
七反成败劫，不来还此世。\\
世间败坏时，生于晃昱天，\\
世间转成时，生于梵天中。\\
在梵为大梵，千生自在天，\\
三十六为释，无量百顶王。\\
刹利顶生王，为人之最尊，\\
如法非刀杖，政御于天下。\\
如法不加枉，正安乐教授，\\
如法转相传，遍一切大地。\\
大富多钱财，生于如是族，\\
财谷具足满，成就七宝珍。\\
因此大福佑，所生得自在，\\
诸佛御于世，彼佛之所说。\\
知此甚奇特，见神通不少，\\
谁知而不信，如是生于冥。\\
是故当自为，欲求大福佑，\\
当恭敬于法，常念佛法律。

</div>

佛说如是，彼诸比丘闻佛所说，欢喜奉行。

--------------

** 第34卷 大品.息止道经第二十三

我闻如是：一时，佛游舍卫国，在胜林给孤独园。

尔时，世尊告诸比丘：“年少比丘始成就戒，当以数数诣息止道观相：骨相、青相、腐相、食相、骨锁相。彼善受善持此相已，还至住处，澡洗手足，敷尼师檀，在于床上结跏趺坐，即念此相：骨相、青相、腐相、食相、骨锁相。所以者何？若彼比丘修习此相，速除心中欲恚之病。”

于是，世尊说此颂曰：

<div class="poem">

若年少比丘，学未得止意，\\
当诣息止道，欲除其淫欲。\\
心中无恚诤，慈愍于众生，\\
遍满一切方，往至观诸身。\\
当观于青相，及以烂腐坏，\\
观鸟虫所食，骨骨节相连。\\
修习如是相，还归至本处，\\
澡洗于手足，敷床正基坐。\\
当以观真实，内身及外身，\\
盛满大小便，心肾肝肺等。\\
若欲分卫食，到人村邑间，\\
如将铠缠络，常正念在前。\\
若见色可爱，清净欲相应，\\
见已观如真，正念佛法律。\\
此中无骨筋，无肉亦无血，\\
无肾心肝肺，无有涕唾脑。\\
一切地皆空，水种亦复然，\\
空一切火种，风种亦复空。\\
若所有诸觉，清净欲相应，\\
彼一切息止，如慧之所观。\\
如是行精勤，常念不净想，\\
永断淫怒痴，除一切无明，\\
兴起清净明，比丘得苦边。

</div>

佛说如是，彼诸比丘闻佛所说，欢喜奉行。

--------------

** 第34卷 大品.至边经第二十四

我闻如是：一时，佛游含卫国，在胜林给孤独园。

尔时，世尊告诸比丘：“于生活中下极至边，谓行乞食。世间大讳，谓为秃头手擎钵行，彼族姓子为义故受。所以者何？以厌患生老病死、愁戚啼哭、忧苦懊恼，或得此淳具足大苦阴边。汝等非如是心出家学道耶？”

时，诸比丘白曰：“如是。”

世尊复告诸比丘曰：“彼愚痴人以如是心出家学道，而行伺欲染著至重，浊缠心中，憎嫉无信，懈怠失正念，无正定，恶慧心狂，掉乱诸根，持戒极宽，不修沙门，不增广行。犹人以墨浣墨所污，以血除血，以垢除垢，以浊除浊，以厕除厕，但增其秽，从冥入冥，从暗入暗；我说彼愚痴人持沙门戒亦复如是，谓彼人行伺欲染著至重，浊缠心中，憎嫉无信，懈怠失正念，无正定，恶慧心狂，掉乱诸根，持戒极宽，不修沙门，不增广行。犹无事处烧人残木，彼火烬者，非无事所用，亦非村邑所用；我说彼愚痴人持沙门戒亦复如是，谓彼人行伺欲染著至重，浊缠心中，憎嫉无信，懈怠失正念，无正定，恶慧心狂，掉乱诸根，持戒极宽，不修沙门，不增广行。”

于是，世尊说此颂曰：

<div class="poem">

愚痴失欲乐，复失沙门义，\\
俱忘失二边，犹烧残火烬。\\
犹如无事处，烧人残火烬，\\
无事村不用，人著欲亦然，\\
犹烧残火烬，俱忘失二边。

</div>

佛说如是，彼诸比丘闻佛所说，欢喜奉行。

--------------

** 第34卷 大品.喻经第二十五

我闻如是：一时，佛游舍卫国，在胜林给孤独园。

尔时，世尊告诸比丘：“若有无量善法可得，彼一切以不放逸为本，不放逸为习，因不放逸生，不放逸为首。不放逸者，于诸善法为最第一。犹作田业，彼一切因地、依地、立地，得作田业。如是，若有无量善法可得，彼一切以不放逸为本，不放逸为习，因不放逸生，不放逸为首。不放逸者，于诸善法为最第一。犹种子，村及与鬼村，百谷药木得生长养，彼一切因地、依地、立地，得生长养。

“如是，若有无量善法可得，彼一切以不放逸为本，不放逸为习，因不放逸生，不放逸为首。不放逸者，于诸善法为最第一。犹诸根香，沉香为第一；犹诸树香，赤栴檀为第一；犹诸水华，青莲华为第一；犹诸陆华，须摩那华为第一；犹诸兽迹，彼一切悉入象迹中，象迹尽摄，彼象迹者为最第一，谓广大故。如是，若有无量善法可得，彼一切以不放逸为本，不放逸为习，因不放逸生，不放逸为首。不放逸者，于诸善法为最第一。犹诸兽中，彼师子王为最第一；犹如列阵共斗战时，唯要誓为第一；犹楼观椽，彼一切皆依承椽梁立，承椽梁、承椽梁皆摄持之，承椽梁者为最第一，谓尽摄故。

“如是，若有无量善法可得，彼一切以不放逸为本，不放逸为习，因不放逸生，不放逸为首。不放逸者，于诸善法为最第一。犹如诸山，须弥山王为第一；犹如诸泉，大海摄水，大海为第一；犹诸大身，阿须罗王为第一；犹诸瞻侍，魔王为第一；犹诸行欲，顶生王为第一；犹如诸小王，转轮王为第一；犹如虚空诸星，宿月殿为第一；犹诸彩衣，白练为第一；犹诸光明，慧光明为第一；犹如诸众，如来弟子众为第一；犹如诸法，有为及无为，爱尽、无欲、灭尽、涅槃为第一；犹诸众生，无足、二足、四足、多足，色、无色、有想、无想乃至非有想非无想，如来于彼为极第一，为大为上，为最为胜，为尊为妙；犹如因牛有乳，因乳有酪，因酪有生酥，因生酥有熟酥，因熟酥有酥精，酥精为第一，为大为上，为最为胜，为尊为妙。如是若有诸众生，无足、二足、四足、多足，色、无色、有想、无想，乃至非有想非无想，如来于彼为极第一，为大为上，为最为胜，为尊为妙。”

于是，世尊说此颂曰：

<div class="poem">

若有求财物，极好转增多，\\
称誉不放逸，事无事慧说。\\
有不放逸者，必取二俱义，\\
即此世能获，后世亦复得。\\
雄猛观诸义，慧者必解脱。

</div>

佛说如是，彼诸比丘闻佛所说，欢喜奉行。

大品第十一竟。

--------------

