#+OPTIONS: toc:nil num:nil
*  梵志品.第十二（有二十经）（第三念诵）

雨势、歌罗、数，瞿默、象迹喻，

闻德、何苦、欲，郁瘦、阿摄惒。

#+TOC: headlines 2

**  第35卷 梵志品.雨势经第一
我闻如是：一时，佛游王舍城，在鹫岩山中。

尔时，摩竭陀王未生怨鞞陀提子，与跋耆相憎，常在眷属数作是说：“跋耆国人有大如意足，有大威德，有大福佑，有大威神。我当断灭跋耆人种，破坏跋耆，令跋耆人遭无量厄。”

于是，摩竭陀王未生怨鞞陀提子闻世尊游王舍城，在鹫岩山中，便告大臣雨势曰：“我闻沙门瞿昙游王舍城，在鹫岩山中。雨势，汝往至沙门瞿昙所，汝持我名问讯圣体安快无病，气力如常耶？当作是语：‘瞿昙，摩竭陀王未生怨鞞陀提子问讯圣体安快无病，气力如常耶？瞿昙，摩竭陀王未生怨鞞陀提子与跋耆相憎，常在眷属数作是说：“跋耆国人有大如意足，有大威德，有大福佑，有大威神。我当断灭跋耆人种，破坏跋耆，令跋耆人遭无量厄。”沙门瞿昙当何所说？'雨势，若沙门瞿昙有所说者，汝善受持。所以者何？如是之人，终不妄说。”

大臣雨势受王教已，乘最好乘，与五百乘俱出王舍城，即便往诣鹫岩山中。登鹫岩山，下车步进，往诣佛所，便与世尊共相问讯，却坐一面，白曰：“瞿昙，摩竭陀王未生怨鞞陀提子问讯圣体安快无病，气力如常耶？瞿昙，摩竭陀王未生怨鞞陀提子与跋耆相憎，常在眷属数作是说：‘跋耆国人有大如意足，有大威德，有大福佑，有大威神。我当断灭跋耆人种，破坏跋耆，令跋耆人遭无量厄。'沙门瞿昙当何所说？”

世尊闻已，告曰：“雨势，我昔曾游于跋耆国，彼国有寺名遮惒逻。雨势，尔时我为跋耆国人说七不衰法，跋耆国人则能受行七不衰法。雨势，若跋耆国人行七不衰法而不犯者，跋耆必胜，则为不衰。”

大臣雨势白世尊曰：“沙门瞿昙略说此事，不广分别，我等不能得解此义。愿沙门瞿昙广分别说，当令我等得知此义。”

世尊告曰：“雨势，谛听！善思念之，我当为汝广说此义。”

大臣雨势受教而听。

是时，尊者阿难执拂持佛，世尊回顾问曰：“阿难，颇闻跋耆数数集会，多聚集耶？”

尊者阿难白曰：“世尊，我闻跋耆数数集会，多聚集也！”

世尊即告大臣雨势：“若彼跋耆数数集会，多聚集者，跋耆必胜，则为不衰。”

世尊复问尊者阿难：“颇闻跋耆共俱集会，俱作跋耆事，共俱起耶？”

尊者阿难白曰：“世尊，我闻跋耆共俱集会，俱作跋耆事，共俱起也！”

世尊复告大臣雨势：“若彼跋耆共俱集会，俱作跋耆事，共俱起者，跋耆必胜，则为不衰。”

世尊复问尊者阿难：“颇闻跋耆未施设者不更施设，本所施设而不改易，旧跋耆法善奉行耶？”

尊者阿难白曰：“世尊，我闻跋耆未施设者不更施设，本所施设而不改易，旧跋耆法善奉行也！”

世尊复告大臣雨势：“若彼跋耆未施设者不更施设，本所施设而不改易，旧跋耆法善奉行者，跋耆必胜，则为不衰。”

世尊复问尊者阿难：“颇闻跋耆不以力势而犯他妇、他童女耶？”

尊者阿难白曰：“世尊，我闻跋耆不以力势而犯他妇、他童女也！”

世尊复告大臣雨势：“若彼跋耆不以力势而犯他妇、他童女者，跋耆必胜，则为不衰。”

世尊复问尊者阿难：“颇闻跋耆有名德尊重者，跋耆悉共宗敬、恭奉、供养，于彼闻教则受耶？”

尊者阿难白曰：“世尊，我闻跋耆有名德尊重者，跋耆悉共宗敬、恭奉、供养，于彼闻教则受。”

世尊复告大臣雨势：“若彼跋耆有名德尊重者，跋耆悉共宗敬、恭奉、供养，于彼闻教则受者，跋耆必胜，则为不衰。”

世尊复问尊者阿难：“颇闻跋耆所有旧寺，跋耆悉共修饰，遵奉、供养、礼事，本之所施常作不废，本之所为不减损耶？”

尊者阿难白曰：“世尊，我闻跋耆所有旧寺，跋耆悉共修饰，遵奉、供养、礼事，本之所施常作不废，本之所为不减损也！”

世尊复告大臣雨势：“若彼跋耆所有旧寺，跋耆悉共修饰，遵奉、供养、礼事，本之所施常作不废，本之所为不减损者，跋耆必胜，则为不衰。”

世尊复问尊者阿难：“颇闻跋耆悉共拥护诸阿罗诃，极大爱敬，常愿未来阿罗诃者而欲令来，既已来者乐恒久住，常使不乏衣被、饮食、床榻、汤药诸生活具耶？”

尊者阿难白曰：“世尊，我闻跋耆悉共拥护诸阿罗诃，极大爱敬，常愿未来阿罗诃者而欲令来，既已来者乐恒久住，常使不乏衣被、饮食、床榻、汤药诸生活具！”

世尊复告大臣雨势：“若彼跋耆悉共拥护诸阿罗诃，极大爱敬，常愿未来阿罗诃者而欲令来，既已来者乐恒久住，常使不乏衣被、饮食、床榻、汤药诸生活具者，跋耆必胜，则为不衰。雨势，跋耆行此七不衰法，诸受持此七不衰法者，跋耆必胜，则为不衰。”

于是，大臣雨势即从座起，偏袒著衣，叉手向佛，白曰：“瞿昙，设彼跋耆成就一不衰法者，摩竭陀王未生怨鞞陀提子不能伏彼，况复具七不衰法耶？瞿昙，我国事多，请退还归。”

世尊报曰：“欲去随意！”

于是，大臣雨势闻佛所说，则善受持，起绕世尊三匝而去。

大臣雨势去后不久，于是，世尊回顾告曰：“阿难，若有比丘依鹫岩山处处住者，宣令一切尽集讲堂，一切集已，便来白我。”

尊者阿难即受佛教：“唯然，世尊。”

是时，尊者阿难便行宣令，若有比丘依鹫岩山处处住者，今令一切尽集讲堂。一切集已，还诣佛所，稽首作礼，却住一面，白曰：“世尊，我已宣令，若有比丘依鹫岩山处处住者，悉令一切尽集讲堂。今皆已集，惟愿世尊自知其时！”

于是，世尊将尊者阿难往诣讲堂，于比丘众前敷座而坐，告诸比丘：“今为汝说七不衰法，汝等谛听！善思念之。”

时，诸比丘白曰：“唯然。”

佛言：“云何为七？若比丘数数集会，多聚集者，比丘必胜，则法不衰。若比丘共齐集会，俱作众事，共俱起者，比丘必胜，则法不衰。若比丘未施设事不更施设，本所施设而不改易，我所说戒善奉行者，比丘必胜，则法不衰。若比丘此未来有爱喜欲共俱，爱乐彼彼有起不随者，比丘必胜，则法不衰。若比丘有长老上尊俱学梵行，比丘悉共宗敬、恭奉、供养，于彼闻教则受者，比丘必胜，则法不衰。若比丘有无事处山林高岩，闲居静处，寂无音声，远离，无恶，无有人民，随顺宴坐，乐住不离者，比丘必胜，则法不衰。若比丘悉共拥护诸梵行者，至重爱敬，常愿未来诸梵行者而欲令来，既已来者乐恒久住，常使不乏衣被、饮食、床榻、汤药诸生活具者，比丘必胜，则法不衰。若比丘行此七不衰法，受持不犯者，比丘必胜，则法不衰。”

于是，世尊复告诸比丘曰：“我为汝等更说七不衰法，汝等谛听！善思念之。”

时，诸比丘白曰：“唯然。”

佛言：“云何为七？若比丘尊师，恭敬、极重供养、奉事者，比丘必胜，则法不衰。若比丘法、众、戒、不放逸、供给、定，恭敬、极重供养、奉事者，比丘必胜，则法不衰。若比丘行此七不衰法，受持不犯者，比丘必胜，则法不衰。”

世尊复告诸比丘曰：“我为汝等更说七不衰法，汝等谛听！善思念之。”

时，诸比丘白曰：“唯然。”

佛言：“云何为七？若比丘不行于业，不乐于业，不习业者，比丘必胜，则法不衰。不行哗说，不乐哗说，不习哗说者；不行聚会，不乐聚会，不习聚会者；不行杂合，不乐杂合，不习杂合者；不行睡眠，不乐睡眠，不习睡眠者；不为利，不为誉，不为他人行梵行者；不为暂尔，不为德胜，于其中间舍方便，令德胜者，比丘必胜，则法不衰。若比丘行此七不衰法，受持不犯者，比丘必胜，则法不衰。”

世尊复告诸比丘曰：“我为汝等更说七不衰法，汝等谛听！善思念之。”

时，诸比丘白曰：“唯然。”

佛言：“云何为七？若比丘成就信财、戒财、惭财、愧财、博闻财、施财，成就慧财者，比丘必胜，则法不衰。若比丘行此七不衰法，受持不犯者，比丘必胜，则法不衰。”

世尊复告诸比丘曰：“我为汝等更说七不衰法，汝等谛听！善思念之。”

时，诸比丘白曰：“唯然。”

佛言：“云何为七？若比丘成就信力、精进力、惭力、愧力、念力、定力，成就慧力者，比丘必胜，则法不衰。若比丘行此七不衰法，受持不犯者，比丘必胜，则法不衰。”

世尊复告诸比丘曰：“我为汝等更说七不衰法，汝等谛听！善思念之。”

时，诸比丘白曰：“唯然。”

佛言：“云何为七？若比丘修念觉支，依舍离、依无欲、依灭尽，趣向出要，择法、精进、喜、息、定，修舍觉支，依舍离、依无欲、依灭尽，趣向出要者，比丘必胜，则法不衰。若比丘行此七不衰法，受持不犯者，比丘必胜，则法不衰。”

世尊复告诸比丘曰：“我为汝等更说七不衰法，汝等谛听！善思念之。”

时，诸比丘白曰：“唯然。”

佛言：“云何为七？若比丘应与面前律与面前律，应与忆律与忆律，应与不痴律与不痴律，应与自发露与自发露，应与居与居，应与展转与展转，众中起诤，当以如弃粪扫，止诤法止之者，比丘必胜，则法不衰。若比丘行此七不衰法，受持不犯者，比丘必胜，则法不衰。”

世尊复告诸比丘曰：“今为汝等说六慰劳法，汝等谛听！善思念之。”

时，诸比丘白曰：“唯然。”

佛言：“云何为六？以慈身业向诸梵行，是慰劳法，爱法乐法，令爱令重，令奉令敬，令修令摄，得沙门，得一心，得精进，得涅槃。如是慈口业、慈意业。若有法利，如法得利，自所饭食，至在钵中。如是利分，布施诸梵行，是慰劳法，爱法乐法，令爱令重，令奉令敬，令修令摄，得沙门，得一心，得精进，得涅槃。若有戒不缺、不穿、无秽、无黑，如地不随他，圣所称誉，具善受持。如是戒分，布施诸梵行，是慰劳法，爱法乐法，令爱令重，令奉令敬，令修令摄，得沙门，得一心，得精进，得涅槃。若有见是圣出要，明了深达，能正尽苦。如是见分，布施诸梵行，是慰劳法，爱法乐法，令爱令重，令奉令敬，令修令摄，得沙门，得一心，得精进，得涅槃。我向所言六慰劳法者，因此故说。”

佛说如是，彼诸比丘闻佛所说，欢喜奉行。

--------------

** 第35卷 梵志品.伤歌逻经第二

我闻如是：一时，佛游舍卫国，在胜林给孤独园。

尔时，伤歌逻摩纳中后彷佯，往诣佛所，共相问讯，却坐一面，白曰：“瞿昙，我欲有所问，听乃敢陈。”

世尊告曰：“摩纳，若有疑者，恣汝所问。”

伤歌逻摩纳即便问曰：“瞿昙，梵志如法行乞财物，或自作斋，或教作斋。瞿昙，若自作斋，教作斋者，彼一切行无量福迹，以因斋故。沙门瞿昙弟子随族剃除须发，著袈裟衣，至信、舍家、无家、学道，自调御，自息止，自灭讫，如是沙门瞿昙弟子随族行一福迹，不行无量福迹，因学道故。”

尔时，尊者阿难执拂侍佛。于是，尊者阿难问曰：“摩纳，此二道迹，何者最上、最妙、最胜耶？”

伤歌逻摩纳语曰：“阿难，沙门瞿昙及阿难我俱恭敬、尊重、奉祠。”

尊者阿难复语曰：“摩纳，我不问汝恭敬、尊重、奉祠谁，我但问汝此二道迹，何者最上、最妙、最胜耶？”

尊者阿难至再三问曰：“摩纳，此二道迹，何者最上、最妙、最胜耶？”

伤歌逻摩纳亦再三语曰：“阿难，沙门瞿昙及阿难我俱恭敬、尊重、奉祠。”

尊者阿难复语曰：“摩纳，我不问汝恭敬、尊重、奉祠谁，我但问汝此二道迹，何者最上、最妙、最胜耶？”

于是，世尊便作是念：“此伤歌逻摩纳为阿难所屈，我宁可救彼。”世尊知已，告曰：“摩纳，昔日王及群臣普集大会，共论何事？以何事故共集会耶？”

伤歌逻摩纳答曰：“瞿昙，昔日王及群臣普集大会，共论如此事：‘何因何缘，昔沙门瞿昙施设少戒，然诸比丘多得道者？何因何缘，今沙门瞿昙施设多戒，然诸比丘少得道耶？'瞿昙，昔日王及群臣普集大会，共论此事，以此事故共集会耳！”

尔时，世尊告曰：“摩纳，我今问汝，随所解答。于意云何？若使有一沙门梵志自行如是道、如是迹，行此道、行此迹已，诸漏已尽，得无漏，心解脱，慧解脱，自知、自觉、自作证成就游：生已尽，梵行已立，所作已办，不更受有，知如真。彼为他说：‘我自行如是道、如是迹，行此道、行此迹已，诸漏已尽，得无漏，心解脱，慧解脱，自知、自觉、自作证成就游：生已尽，梵行已立，所作已办，不更受有，知如真。汝等共来亦自行如是道、如是迹，行此道、行此迹已，诸漏已尽，得无漏，心解脱，慧解脱，自知、自觉、自作证成就游：生已尽，梵行已立，所作已办，不更受有，知如真。'彼亦自行如是道、如是迹，行此道、行此迹已，诸漏已尽，得无漏，心解脱，慧解脱，自知、自觉、自作证成就游：生已尽，梵行已立，所作已办，不更受有，知如真。彼为他说，他为他说，如是展转无量百千。于摩纳意云何？我弟子随族剃除须发，著袈裟衣，至信、舍家、无家、学道，行一福迹，不行无量福迹，因学道故耶？”

伤歌逻摩纳答曰：“瞿昙，如我解沙门瞿昙所说义，彼沙门瞿昙弟子随族剃除须发，著袈裟衣，至信、舍家、无家、学道，行无量福迹，不行一福迹，因学道故。”

世尊复告伤歌逻曰：“有三示现：如意足示现、占念示现、教训示现。

“摩纳，云何如意足示现？有一沙门梵志，有大如意足，有大威德，有大福佑，有大威神。于如意足心得自在，行无量如意足之功德，谓分一为众，合众为一，一则住一，有知有见，不碍石壁，犹如行空，没地如水，履水如地，结跏趺坐，上升虚空，犹如鸟翔。今此日月有大如意足，有大威德，有大福佑，有大威神，以手扪摸，身至梵天。摩纳，是谓如意足示现。

“摩纳，云何占念示现？有一沙门梵志，以他相占他意，有是意、如是意、实有是意；无量占不少占，彼一切真谛而无有虚设。不以他相占他意者，但以闻天声及非人声而占他意，有是意、如是意、实有是意；无量占不少占，彼一切真谛而无有虚设。不以他相占他意，亦不闻天声及非人声占他意者，但以他念、他思、他说，闻声已，占他意，有是意、如是意、实有是意；无量占不少占，彼一切真谛而无有虚设。不以他相占他意，亦不以闻天声及非人声占他意，亦不以他念、他思、他说，闻声已，占他意者，但以见他入无觉无观定，见已，作是念：‘如此贤者不念不思，如意所愿。'彼贤者从此定寤，如是念，彼从此定寤，即如是如是念。彼亦占过去，亦占未来，亦占现在，久所作，久所说，亦占安静处，住安静处，亦占至心、心所有法。摩纳，是谓占念示现。

“摩纳，云何教训示现？有一沙门梵志自行如是道、如是迹，行此道、行此迹已，诸漏已尽，得无漏，心解脱，慧解脱，自知、自觉、自作证成就游：生已尽，梵行已立，所作已办，不更受有，知如真。彼为他说：‘我自行如是道、如是迹，行此道、行此迹已，诸漏已尽，得无漏，心解说，慧解脱，自知、自觉、自作证成就游：生已尽，梵行已立，所作已办，不更受有，知如真。汝等共来，亦自行如是道、如是迹，行此道、行此迹已，诸漏已尽，得无漏，心解脱，慧解脱，自知、自觉、自作证成就游：生已尽，梵行已立，所作已办，不更受有，知如真。'彼亦自行如是道、如是迹，行此道、行此迹已，诸漏已尽，得无漏，心解脱，慧解脱，自知、自觉、自作证成就游：生已尽，梵行已立，所作已办，不更受有，知如真。彼为他说，他为他说，如是展转无量百千。摩纳，是谓教训示现。此三示现，何者示现最上、最妙、最胜耶？”

伤歌逻摩纳答曰：“瞿昙，若有沙门、梵志有大如意足，有大威德，有大福佑，有大威神，于如意足心得自在，乃及身至梵天者。瞿昙，此自作自有，自受其报。瞿昙，于诸示现，此示现大法。瞿昙，若有沙门、梵志以他相占他意，乃至占心、心所有法者。瞿昙，此亦自作自有，自受其报。瞿昙，于诸示现，此亦示现大法。瞿昙，若有沙门、梵志自行如是道、如是迹，行此道、行此迹已，诸漏已尽，得无漏，心解脱，慧解脱，自知、自觉、自作证成就游：生已尽，梵行已立，何作已办，不更受有，知如真。彼为他说，他为他说，如是展转无量百千者。瞿昙，于三示现，此示现最上、最妙、最胜。”

世尊复问伤歌逻曰：“于三示现，称叹何示现？”

伤歌逻摩纳答曰：“瞿昙，于三示现，我称说沙门瞿昙。所以者何？沙门瞿昙有大如意足，有大威德，有大福佑，有大威神，心得自在，乃及身至梵天；沙门瞿昙以他相占他意，乃至占心、心所有法；沙门瞿昙示现如是道、如是迹，行此道、行此迹已，诸漏已尽，得无漏，心解脱，慧解脱，自知、自觉、自作证成就游：生已尽，梵行已立，所作已办，不更受有，知如真。沙门瞿昙为他说，他为他说，如是展转无量百千。瞿昙，是故于三示现，我称叹沙门瞿昙。”

于是，世尊告曰：“摩纳，汝善达此论。所以者何？我有大如意足，有大威德，有大福佑，有大威神，于如意足心得自在，乃及身至梵天。摩纳，我以他相占他意，乃至占心、心所有法。摩纳，我自行如是道、如是迹，行此道、行此迹已，诸漏已尽，得无漏，心解脱，慧解脱，自知、自觉、自作证成就游：生已尽，梵行已立，所作已办，不更受有，知如真。我为他说，他为他说，如是展转无量百千。摩纳，是故汝善达此论，汝当如是善受善持。所以者何？此所说义，应当如是。”

于是，伤歌逻摩纳白曰：“世尊，我已知。善逝，我已解。世尊，我今自归于佛、法及比丘众，惟愿世尊受我为优婆塞！从今日始，终身自归，乃至命尽。”

佛说如是，伤歌逻摩纳、尊者阿难及诸比丘闻佛所说，欢喜奉行。

--------------

** 第35卷 梵志品.算数目揵连经第三

我闻如是：一时，佛游舍卫国，在东园鹿子母堂。

尔时，算数梵志目揵连中后彷佯，往诣佛所，共相问讯，却坐一面，白曰：“瞿昙，我欲有所问，听乃敢陈。”

世尊告曰：“目揵连，恣汝所问，莫自疑难。”

算数目揵连则便问曰：“瞿昙，此鹿子母堂渐次第作，转后成讫。瞿昙，此鹿子母堂磴梯，初升一磴，后二、三、四。瞿昙，如是此鹿子母堂渐次第上。瞿昙，此御象者，亦渐次第调御成讫，谓因钩故。瞿昙，此御马者，亦渐次第调御成讫，谓因钩故。瞿昙，此刹利亦渐次第至成就讫，谓因捉弓箭故。瞿昙，此诸梵志亦渐次第至成就讫，谓因学经书故。瞿昙，我等学算数，以算数存命，亦渐次第至成就讫。若有弟子，或男或女，始教一一数，二、二、三、三、十、百、千、万，次第至上。瞿昙，如是我等学算数，以算数存命，渐次第至成讫。沙门瞿昙，此法、律中，云何渐次第作至成就讫？”

世尊告曰：“目揵连，若有正说渐次第作，乃至成讫，目揵连，我法、律中谓正说。所以者何？目揵连，我于此法、律渐次第作至成就讫。

“目揵连，若年少比丘初来学道，始入法、律者，如来先教：‘比丘，汝来身护命清净，口、意护命清净。'

“目揵连，若比丘身护命清净，口、意护命清净者，如来复上教：‘比丘，汝来观内身如身，至观觉、心、法如法。'

“目揵连，若比丘观内身如身，至观觉、心、法如法者，如来复上教：‘比丘，汝来观内身如身，莫念欲相应念，至观觉、心、法如法，莫念非法相应念。'

“目揵连，若比丘观内身如身，不念欲相应念，至观觉、心、法如法，不念非法相应念者，如来复上教：‘比丘，汝来守护诸根，常念闭塞，念欲明达，守护念心而得成就，恒起正知。若眼见色，然不受相，亦不味色，谓忿诤故，守护眼根；心中不生贪伺、忧戚、恶不善法，趣向彼故，守护眼根。如是耳、鼻、舌、身，若意知法，然不受相，亦不味法，谓忿诤故，守护意根；心中不生贪伺、忧戚、恶不善法，趣向彼故，守护意根。'

“目揵连，若比丘守护诸根，常念闭塞，念欲明达，守护念心而得成就，恒起正知。若眼见色，然不受相，亦不味色，谓忿诤故，守护眼根；心中不生贪伺、忧戚、恶不善法，趣向彼故，守护眼根。如是耳、鼻、舌、身，若意知法，然不受相，亦不味法，谓忿诤故，守护意根；心中不生贪伺、忧戚、恶不善法，趣向彼故，守护意根者，如来复上教：‘比丘，汝来正知出入，善观分别，屈伸低仰，仪容庠序，善著僧伽梨及诸衣钵，行住坐卧、眠寤语默，皆正知之。'

“目揵连，若比丘正知出入，善观分别，屈伸低仰，仪容庠序，善著僧伽梨及诸衣钵，行住坐卧、眠寤语默，皆正知者，如来复上教：‘比丘，汝来独住远离，在无事处，或至树下空安静处、山岩石室、露地穰积，或至林中，或住在冢间。汝已在无事处，或至树下空安静处、敷尼师檀，结跏趺坐，正身正愿，反念不向，断除贪伺，心无有诤。见他财物、诸生活具，莫起贪伺，欲令我得，汝于贪伺净除其心。如是瞋恚、睡眠、掉悔、断疑、度惑，于诸善法无有犹豫，汝于疑惑净除其心。汝断此五盖、心秽、慧羸，离欲、离恶不善之法，至得第四禅成就游。'目揵连，若比丘离欲、离恶不善之法，至得第四禅成就游者，目揵连，如来为诸年少比丘多有所益，谓训诲教诃。目揵连，若有比丘、长老、上尊、旧学梵行，如来复上教，谓究竟讫一切漏尽。”

算数目揵连即复问曰：“沙门瞿昙，一切弟子如是训诲，如是教诃，尽得究竟智必涅槃耶？”

世尊答曰：“目揵连，不一向得，或有得者，或不得者。”

算数目揵连复更问曰：“瞿昙，此中何因何缘有涅槃、有涅槃道，沙门瞿昙现在导师，或有比丘如是训诲，如是教诃，得究竟涅槃，或复不得耶？”

世尊告曰：“目揵连，我还问汝，随所解答。目揵连，于意云何？汝知王舍城处，谙彼道耶？”

算数目揵连答曰：“唯然，我知王舍城处，亦谙彼道。”

世尊问曰：“目揵连，若有人来欲见彼王，至王舍城，其人问汝：‘我欲见王，至王舍城。算数目揵连知王舍城处，谙彼道径，可示语我耶？'汝告彼人曰：‘从此东行至彼某村，从某村去当至某邑，如是展转至王舍城。若王舍城外有好园林，其地平正，楼观浴池，若干华树，狭长流河，又有清泉尽见尽知。'彼人闻汝语，受汝教已，从此东行，须臾不久，便舍正道，从恶道还；若王舍城外有好园林，其地平正，楼观浴池，若干华树，狭长流河，又有清泉，彼尽不见，亦不知也。

“复有人来欲见彼王，至王舍城，其人问汝：‘我欲见王，至王舍城。算数目揵连知王舍城处，谙彼道径，可示语我耶？'汝告彼人曰：‘从此东行至彼某村，从某村去当至某邑，如是展转至王舍城。若王舍城外有好园林，其地平正，楼观浴池，若干华树，狭长流河，又有清泉，尽见尽知。'彼人闻汝语，受汝教已，即从此东行至彼某村，从某村去得至某邑，如是展转至王舍城；若王舍城外有好园林，其地平正，楼观浴池，若干华树，狭长流河，又有清泉，尽见尽知。

“目揵连，此中何因何缘有彼王舍城，有王舍城道，汝现在导师，彼第一人随受汝教，于后不久，舍平正道，从恶道还；若王舍城外有好园林，其地平正，楼观浴池，若干华树，狭长流河，又有清泉，彼尽不见，亦不知耶？彼第二人随受汝教，从平正道展转得至于王舍城；若王舍城外有好园林，其地平正，楼观浴池，若干华树，狭长流河，又有清泉，彼尽见尽知耶？”

算数目揵连答曰：“瞿昙，我都无事。有彼王舍城，有王舍城道，我现在导师，彼第一人不随我教，舍平正道，从恶道还；若王舍城外有好园林，其地平正，楼观浴池，若干华树，狭长流河，又有清泉，彼尽不见，亦不知耳！彼第二人随顺我教，从平正道展转得至于王舍城；若王舍城外有好园林，其地平正，楼观浴池，若干华树，狭长流河，又有清泉，彼尽见尽知耳！”

世尊告曰：“如是，目揵连，我亦无事。有彼涅槃、有涅槃道，我为导师，为诸比丘如是训诲，如是教诃，得究竟涅槃，或有不得。目揵连，但各自随比丘所行，尔时世尊便记彼行，谓究竟漏尽耳！”

算数目揵连白曰：“瞿昙，我已知。瞿昙，我已解。瞿昙，犹如良地有娑罗林，彼中有守娑罗林人，明健不懈，诸娑罗根以时锄掘，平高填下，粪沃溉灌，不失其时。若其边有秽恶草生，尽拔弃之；若有横曲不调直者，尽落治之。若有极好中直树者，便权养护，随时锄掘，粪沃溉灌，不失其时，如是良地娑罗树林转茂盛好。瞿昙，如是有人谀谄、欺诳、极不庶几无信、懈怠、无念、无定、恶慧、心狂、诸根掉乱，持戒宽缓，不广修沙门。瞿昙，如是之人不能共事。所以者何？瞿昙，如是人者，秽污梵行。瞿昙，若复有人不有谀谄，亦不欺诳，庶几有信，精进不懈，有念、有定，亦有智慧，极恭敬戒，广修沙门。瞿昙，如是之人，能共事也。所以者何？瞿昙，如是人者，清净梵行。

“瞿昙，犹诸根香，沉香为第一。所以者何？瞿昙，彼沉香者，于诸根香为最上故。瞿昙，犹诸娑罗树香，赤栴檀为第一。所以者何？瞿昙，赤旃檀者于诸娑罗树香为最上故。瞿昙，犹诸水华，青莲华为第一。所以者何？瞿昙，青莲华者于诸水华为最上故。瞿昙，犹诸陆华，修摩那华为第一。所以者何？瞿昙，修摩那华者于诸陆华为最上故。瞿昙，犹如世中诸有论士，沙门瞿昙为最第一。所以者何？沙门瞿昙论士能伏一切外道异学故。世尊，我今自归于佛、法及比丘众，惟愿世尊受我为优婆塞！从今日始，终身自归，乃至命尽。”

佛说如是，算数目揵连及诸比丘闻佛所说，欢喜奉行。

--------------

** 第36卷 梵志品.瞿默目揵连经第四

我闻如是：一时，佛般涅槃后不久，尊者阿难游王舍城。

尔时，摩竭陀大臣雨势治王舍城，为防跋耆故。于是，摩竭陀大臣雨势遣瞿默目揵连田作人，往至竹林迦兰哆园。

尔时，尊者阿难过夜平旦，著衣持钵，为乞食故，入王舍城。于是，尊者阿难作是念：“且置王舍城乞食，我宁可往诣瞿默目揵连田作人所。”于是，尊者阿难往诣瞿默目揵连田作人所。

梵志瞿默目揵连遥见尊者阿难来，即从座起，偏袒著衣，叉手向尊者阿难，白曰：“善来！阿难，久不来此，可坐此座。”

尊者阿难即坐彼座，梵志瞿默目揵连与尊者阿难共相问讯，却坐一面，白曰：“阿难，欲有所问，听我问耶？”

尊者阿难报曰：“目揵连，汝便可问，我闻当思。”

则便问曰：“阿难，颇有一比丘与沙门瞿昙等耶？”

尊者阿难与梵志瞿默目揵连共论此事时，尔时，摩竭陀大臣雨势慰劳田作人，往诣梵志瞿默目揵连田作人所。

摩竭陀大臣雨势遥见尊者阿难坐在梵志瞿默目揵连田作人中，往诣尊者阿难所，共相问讯，却坐一面，问曰：“阿难，与梵志瞿默目揵连共论何事？以何事故共会此耶？”

尊者阿难答曰：“雨势，梵志瞿默目揵连问我：‘阿难，颇有一比丘与沙门瞿昙等耶？'”

摩竭陀大臣雨势复问曰：“阿难，云何答彼？”

尊者阿难答曰：“雨势，都无一比丘与世尊等等。”

摩竭陀大臣雨势复问曰：“唯然，阿难，无一比丘与世尊等等。颇有一比丘为沙门瞿昙在时所立，此比丘我般涅槃后，为诸比丘所依，谓令汝等今所依耶？”

尊者阿难答曰：“雨势，都无一比丘为世尊所知、见，如来、无所著、等正觉在时所立，此比丘我般涅槃后，为诸比丘所依，谓令我等今所依者。”

摩竭陀大臣雨势复问曰：“阿难，唯然，无一比丘与沙门瞿昙等等；亦无一比丘为沙门瞿昙在时所立，此比丘我般涅槃后，为诸比丘所依，谓令汝等今所依者。颇有一比丘与众共和集拜，此比丘世尊般涅槃后，为诸比丘所依，谓令汝等今所依。”

尊者阿难答曰：“雨势，亦无一比丘与众共和集拜，此比丘世尊般涅槃后，为诸比丘所依，谓令我等今所依者。”

摩竭陀大臣雨势复问曰：“阿难，唯然，无一比丘与沙门瞿昙等等；亦无一比丘为沙门瞿昙在时所立，此比丘我般涅槃后，为诸比丘所依，谓令汝等今所依者；亦无一比丘与众共和集拜，此比丘世尊般涅槃后，为诸比丘所依，谓令汝等今所依者。阿难，若尔者，汝等无所依，共和合、不诤、安隐，同一一教，合一水乳，快乐游行，如沙门瞿昙在时耶？

尊者阿难告曰：“雨势，汝莫作是说，言我等无所依。所以者何？我等有所依耳！”

摩竭陀大臣雨势白曰：“阿难，前后所说何不相应？阿难向如是说：无一比丘与世尊等等；亦无一比丘为世尊所知、见，如来、无所著、等正觉在时所立，此比丘我般涅槃后，为诸比丘所依，谓令我等今所依者；亦无一比丘与众共和集拜，此比丘世尊般涅槃后，为诸比丘所依，谓令我等今所依者。阿难，何因何缘今说我有所依耶？”

尊者阿难答曰：“雨势，我等不依于人而依于法。雨势，我等若依村邑游行，十五日说从解脱时，集坐一处。若有比丘知法者，我等请彼比丘为我等说法。若彼众清净者，我等一切欢喜奉行彼比丘所说；若彼众不清净者，随法所说，我等教作是。”

摩竭陀大臣雨势白曰：“阿难，非汝等教作是，但法教作是。阿难，如是少法、多法可得久住者。如是阿难等共和合、不诤、安隐，同一一教，合一水乳，快乐游行，如沙门瞿昙在时。”

摩竭陀大臣雨势复问曰：“阿难，颇有可尊敬耶？”

尊者阿难答曰：“雨势，有可尊敬。”

雨势白曰：“阿难，前后所说何不相应？阿难向如是说：无一比丘与世尊共等等；亦无一比丘为世尊在时所立，此比丘我般涅槃后，为诸比丘所依，谓令我等今所依者；亦无一比丘与众共和集拜，此比丘世尊般涅槃后，为诸比丘所依，谓令我等今所依者。阿难，汝何因何缘今说有可尊敬耶？”

尊者阿难答曰：“雨势，世尊知、见，如来、无所著、等正觉说有十法而可尊敬。我等若见比丘有此十法者，则共爱敬、尊重、供养、宗奉，礼事于彼比丘。云何为十？

“雨势，比丘修习禁戒，守护从解脱，又复善摄威仪礼节，见纤芥罪，常怀畏怖，受持学戒。雨势，我等若见比丘极行增上戒者，则共爱敬、尊重、供养、宗奉，礼事于彼比丘。

“复次，雨势，比丘广学多闻，守持不忘，积聚博闻，所谓法者，初妙、中妙、竟亦妙，有义有文，具足清净，显现梵行，如是诸法广学，多闻诵习至千，意所推观，明见深达。雨势，我等若见比丘极多闻者，则共爱敬、尊重、供养、宗奉，礼事于彼比丘。

“复次，雨势，比丘作善知识，作善朋友，作善伴党。雨势，我等若见比丘极善知识者，则共爱敬、尊重、供养、宗奉，礼事于彼比丘。

“复次，雨势，比丘乐住远离，成就二远离，身及心也。雨势，我等若见比丘极乐住远离者，则共爱敬、尊重、供养、宗奉，礼事于彼比丘。

“复次，雨势，比丘乐于宴坐，内行正止，亦不离伺，成就于观，增长空行。雨势，我等若见比丘极乐宴坐者，则共爱敬、尊重、供养、宗奉，礼事于彼比丘。

“复次，雨势，比丘知足，衣取覆形，食取充躯，随所游至，与衣钵俱，行无顾恋，犹如鹰鸟，与两翅俱，飞翔空中。如是比丘知足，衣取覆形，食取充躯，随所游至，与衣钵俱，行无顾恋。雨势，我等若见比丘极知足者，则共爱敬、尊重、供养、宗奉，礼事于彼比丘。

“复次，雨势，比丘常行于念，成就正念，久所曾习，久所曾闻，恒忆不忘。雨势，我等若见比丘极有正念者，则共爱敬、尊重、供养、宗奉，礼事于彼比丘。

“复次，雨势，比丘常行精进，断恶不善，修诸善法，恒自起意，专一坚固，为诸善本，不舍方便。雨势，我等若见比丘极精勤者，则共爱敬、尊重、供养、宗奉，礼事于彼比丘。

“复次，雨势，比丘修行智慧，观兴衰法，得如此智，圣慧明达，分别晓了，以正尽苦。雨势，我等若见比丘极行慧者，则共爱敬、尊重、供养、宗奉，礼事于彼比丘。

“复次，雨势，比丘诸漏已尽，而得无漏，心解脱，慧解脱，自知、自觉、自作证成就游：生已尽，梵行已立，所作已办，不更受有，知如真。雨势，我等若见比丘诸漏尽者，则共爱敬、尊重、供养、宗奉，礼事于彼比丘。

“雨势，世尊知见，如来、无所著、等正觉说此十法而可尊敬。雨势，我等若见比丘行此十法者，则共爱敬、尊重、供养、宗奉，礼事于彼比丘。”

于是，彼大众放高大音声：“可修直道，非不可修。若修直道，非不可修者，随世中阿罗诃爱敬、尊重、供养、礼事。若诸尊可修直道而能修者，是故世中阿罗诃爱敬、尊重、供养、礼事。”

于是，摩竭陀大臣雨势及其眷属问曰：“阿难，今游何处？”

尊者阿难答曰：“我今游行此王舍城竹林迦兰哆园。”

“阿难，竹林迦兰哆园至可爱乐，整顿可喜，昼不喧闹，夜则静寂，无有蚊虻，亦无蝇蚤，不寒不热。阿难，乐住竹林迦兰哆园耶？”

尊者阿难答曰：“如是，雨势。如是，雨势。竹林迦兰哆园至可爱乐，整顿可喜，昼不喧闹，夜则静寂，无有蚊虻，亦无蝇蚤，不寒不热。雨势，我乐住竹林迦兰哆园中。所以者何？以世尊拥护故。”

是时，婆难大将在彼众中，婆难大将白曰：“如是，雨势。如是，雨势。竹林迦兰哆园至可爱乐，整顿可喜。昼不喧闹，夜则静寂，无有蚊虻，亦无蝇蚤，不寒不热，彼尊者乐住竹林迦兰哆园。所以者何？此尊者行伺、乐伺故。”

摩竭陀大臣雨势闻已，语曰：“婆难大将，沙门瞿昙昔时游行金鞞罗乐园中。婆难大将，尔时我数往诣彼，见沙门瞿昙。所以者何？沙门瞿昙行伺、乐伺，称叹一切伺。”

尊者阿虽闻已，告曰：“雨势，莫作是说：‘沙门瞿昙称说一切伺。'所以者何？世尊或称说伺，或不称说。”

摩竭陀大臣雨势复问曰：“阿难，沙门瞿昙不称说伺，不称说何等伺？”

尊者阿难答曰：“雨势，或有一贪欲所缠而起贪欲，不知出要如真，彼为贪欲所障碍故，伺、增伺而重伺。雨势，是谓第一伺，世尊不称说。复次，雨势，或有一瞋恚所缠而起瞋恚，不知出要如真，彼为瞋恚所障碍故，伺、憎伺而重伺。雨势，是谓第二伺，世尊不称说。复次，雨势，睡眠所缠而起睡眠，不如出要如真，彼为睡眠所障碍故，伺、增伺而重伺。雨势，是谓第三伺，世尊不称说。复次，雨势，疑惑所缠而起疑惑，不知出要如真，彼为疑惑所障碍故，伺、增伺而重伺。雨势，是谓第四伺，世尊不称说。雨势，世尊不称说此四伺。”

摩竭陀大臣雨势白曰：“阿难，此四伺可憎可憎处，沙门瞿昙不称说。所以者何？正尽觉故。”

摩竭陀大臣雨势复问曰：“阿难，何等伺沙门瞿昙所称说？”

尊者阿难答曰：“雨势，比丘者，离欲、离恶不善之法，至得第四禅成就游。雨势，世尊称说此四伺。”

摩竭陀大臣雨势白曰：“阿难，此四伺可称可称处，沙门瞿昙所称。所以者何？以正尽觉故。阿难，我事烦猥，请退还归。”

尊者阿难告曰：“欲还随意。”

于是，摩竭陀大臣雨势闻尊者阿难所说，善受善持，即从座起，绕尊者阿难三匝而去。

是时，梵志瞿默目揵连于摩竭陀大臣雨势去后不久，白曰：“阿难，我所问事，都不答耶？”

尊者阿难告曰：“目揵连，我实不答。”

梵志瞿默目揵连白曰：“阿难，我更有所问，听我问耶？”

尊者阿难答曰：“目揵连，汝便可问，我闻当思。”

梵志瞿默目揵连即问曰：“阿难，若如来、无所著、等正觉解脱及慧解脱、阿罗诃解脱，此三解脱有何差别？有何胜如？”

尊者阿难答曰：“目揵连，若如来、无所著、等正觉解脱及慧解脱、阿罗诃解脱，此三解脱无有差别，亦无胜如。”

梵志瞿默目揵连白曰：“阿难，可在此食。”

尊者阿难默然而受。

梵志瞿默目揵连知默然受已，即从座起，自行澡水，极美净妙，种种丰饶食啖含消，自手斟酌，极令饱满；食讫举器，行澡水竟，取一小床，别坐听法。

尊者阿难为彼说法，劝发渴仰，成就欢喜；无量方便为彼说法，劝发渴仰，成就欢喜已，尊者阿难所说如是，摩竭陀大臣雨势眷属，及梵志瞿默目揵连，闻尊者阿难所说，欢喜奉行。

--------------

** 第36卷 梵志品.象迹喻经第五

我闻如是：一时，佛游舍卫国，在胜林给孤独园。

尔时，卑卢异学平旦则从舍卫国出，往诣佛所，稽首作礼，却座一面，佛为彼说法，劝发渴仰，成就欢喜；无量方便为彼说法，劝发渴仰，成就欢喜已，默然而住。卑卢异学，佛为说法，劝发渴仰，成就欢喜已，即从坐起，稽首佛足，绕三匝而去。

尔时，生闻梵志乘极好白乘，与五百弟子俱，以平旦时从舍卫出，至无事处，欲教弟子讽读经书。生闻梵志遥见卑卢异学来，便问：“婆蹉，晨起从何处来？”

卑卢异学答曰：“梵志，我见世尊礼事、供养来。”

生闻梵志问曰：“婆蹉，颇知沙门瞿昙空安静处学智慧耶？”

卑卢异学答曰：“梵志，何等人可知世尊空安静处学智慧耶？梵志，若知世尊空安静处学智慧者，亦当如彼。但，梵志，我所读书有四句义，因四句义，我必信世尊、如来、无所著、等正觉，世尊所说法善，如来弟子圣众善趣。梵志，譬善象师游无事处，于树林间见大象迹，见已，必信彼象极大而有此迹。梵志，我亦如是，我所读书有四句义，因四句义，我必信世尊、如来、无所著、等正觉，世尊所说法善，如来弟子圣众善趣。

“云何四句义？梵志，智慧刹利论士多闻决定，能伏世人，无所不知，则以诸见造作文章，行于世间。彼作是念：‘我往沙门瞿昙所，问如是如是事。若能答者，当复重问；若不能答，便伏舍去。'彼闻世尊游某村邑，便往彼所，见世尊已，尚不敢问，况复能伏？梵志，我所读书，用得如此第一句义，我因此义，必信世尊、如来、无所著、等正觉，世尊所说法善，如来弟子圣众善趣。

“如是智慧梵志、智慧居士、智慧沙门论士多闻决定，能伏世人，无所不知，则以诸见造作文章，行于世间。彼作是念：‘我往沙门瞿昙所，问如是如是事。若能答者，当复重问；若不能答，便伏舍去。'彼闻世尊游某村邑，便往彼所，见世尊已，尚不敢问，况复能伏？梵志，我所读书，用得如此第四句义，我因此义，必信世尊、如来、无所著、等正觉，世尊所说法善，如来弟子圣众善趣。梵志，我所读书有此四句义，我因此四句义故，必信世尊、如来、无所著、等正觉，世尊所说法善，如来弟子圣众善趣。”

生闻梵志语曰：“婆蹉，汝大供养沙门瞿昙，所因所缘，欢喜奉行。”

卑卢异学答曰：“梵志，如是！如是！我极供养于彼世尊，亦极称誉，一切世间亦应供养。”

彼时，生闻梵志闻此义已，即从乘下，右膝著地，叉手向于胜林给孤独园，再三作礼：“南无如来、无所著、等正觉。”如是至三已，还乘极好白乘，往诣胜林给孤独园。到彼乘地，即便下乘，步进诣佛，共相问讯，却坐一面。

生闻梵志向与卑卢异学所共论事尽向佛说，世尊闻已，告曰：“梵志，卑卢异学说象迹喻，犹不善作，亦不具足。如象迹喻善作具足者，今为汝说，当善听之。

“梵志，譬善象师游无事处，于树林间见大象迹，见已，必信彼象极大而有此迹。梵志，彼善象师或不信者，于此林中复有母象，名加梨㝹，身极高大，彼有此迹，即寻此迹，复见大象迹，见已，必信彼象极大而有此迹。梵志，彼善象师或复不信，于此林中更有母象，名加罗梨，身极高大，彼有此迹，即寻此迹，复见大象迹，见已，必信彼象极大而有此迹。梵志，彼善象师或复不信，于此林中更有母象，名婆惒㝹，身极高大，彼有此迹，即寻此迹，复见大象迹，见已，必信彼象极大而有此迹。彼寻此迹已，见大象迹，大象迹方极长极广，周匝遍著，正深入地。及见彼象，或去或来，或住或走，或立或卧。见彼象已，便作是念：‘若有此迹，必是大象。'

“梵志，如是，若世中出如来、无所著、等正觉、明行成为、善逝、世间解、无上士、道法御、天人师，号佛、众佑，彼于此世，天及魔、梵、沙门、梵志，乃至天、人，自知、自觉、自作证成就游：生已尽，梵行已立，所作已办，不更受有，知如真。彼说法初妙、中妙、竟亦妙，有义有文，具足清净，显现梵行。彼所说法，或居士、居士子，闻已得信；于如来正法、律彼得信已，便作是念：‘在家至狭，尘劳之处；出家学道，发露旷大。我今在家，为锁所锁，不得尽形寿净修梵行。我宁可舍于少财物及多财物，舍少亲族及多亲族，剃除须发，著袈裟衣，至信、舍家、无家、学道。'

“彼于后时，舍少财物及多财物，舍少亲族及多亲族，剃除须发，著袈裟衣，至信、舍家、无家、学道。彼出家已，舍亲族相，受比丘要，修习禁戒，守护从解脱，又复善摄威仪礼节，见织芥罪，常怀畏怖，受持学戒。

“彼离杀、断杀，弃舍刀杖，有惭有愧，有慈悲心，饶益一切乃至昆虫，彼于杀生净除其心。彼离不与取、断不与取，与而后取，乐于与取，常好布施，欢喜无吝，不望其报，彼于不与取净除其心。彼离非梵行，断非梵行，勤修梵行，精勤妙行，清净无秽，离欲断淫，彼于非梵行净除其心。

“彼离妄言、断妄言、真谛言，乐真谛，住真谛，不移动，一切可信，不欺世间，彼于妄言净除其心。彼离两舌，断于两舌，行不两舌，不破坏他；不闻此语彼，欲破坏此；不闻彼语此，欲破坏彼；离者欲合，合者欢喜；不作群党，不乐群党，不称说群党事，彼于两舌净除其心。彼离粗言，断于粗言，若有所言，辞气粗犷，恶声逆耳，众所不喜，众所不爱，使他苦恼，令不得定，断如是言；若有所言，清和柔润，顺耳入心，可喜可爱，使他安隐，言声具了，不使人畏，令他得定，说如是言，彼于粗言净除其心。彼离绮语，断于绮言，时说、真说、法说、义说、止息说、乐止息说，事随时得宜，善教善诃，彼于绮语净除其心。

“彼离治生，断于治生，弃舍称量及斗斛，亦不受货，不缚束人，不望折斗量，不以小利侵欺于人，彼于治生净除其心。彼离受寡妇、童女，断受寡妇、童女，彼于受寡妇、童女净除其心。彼离受奴婢，断受奴婢，彼于受奴婢净除其心。彼离受象、马、牛、羊，断受象、马、牛、羊，彼于受象、马、牛、羊净除其心。彼离受鸡、猪，断受鸡、猪，彼于受鸡、猪净除其心。彼离受田业、店肆，断受田业、店肆，彼于受田业、店肆净除其心。彼离受生稻、麦、豆，断受生稻、麦、豆，彼于受生稻、麦、豆净除其心。

“彼离酒、断酒，彼于饮酒净除其心。彼离高广大床，断高广大床，彼于高广大床净除其心。彼离华鬘、璎珞、涂香、脂粉，断华鬘、璎珞、涂香、脂粉，彼于华鬘、璎珞、涂香、脂粉净除其心。彼离歌舞、倡妓及往观听，断歌舞、倡妓及往观听，彼于歌舞、倡妓及往观听净除其心。彼离受生色、像宝，断受生色、像宝，彼于受生色、像宝净除其心。彼离过中食，断过中食，一食、不夜食、学时食，彼于过中食净除其心。

“彼已成就此圣戒聚，复行极知足，衣取覆形，食取充躯，随所游至，与衣钵俱，行无顾恋，犹如鹰鸟，与两翅俱，飞翔空中。彼已成就此圣戒聚，及极知足，复守护诸根，常念闭塞，念欲明达，守护念心而得成就，恒起正知。若眼见色，然不受相，亦不味色，谓忿诤故，守护眼根；心中不生贪伺、忧戚、恶不善法，趣向彼故，守护眼根。如是耳、鼻、舌、身，若意知法，然不受相，亦不味法，谓忿诤故，守护意根；心中不生贪伺、忧戚、恶不善法，趣向彼故，守护意根。

“彼已成就此圣戒聚，及极知足，守护诸根，复正知出入，善观分别，屈伸低仰，仪容庠序，善著僧伽梨及诸衣钵，行住坐卧，眠寤语默，皆正知之。彼已成就此圣戒聚，及极知足，守护诸根，正知出入，复独住远离，在无事处，或至树下空安静处、山岩石室、露地穰积，或至林中，或在冢间。彼已在无事处，或至树下空安静处，敷尼师檀，结跏趺坐，正身正愿，反念不向，断除贪伺，心无有诤，见他财物诸生活具，不起贪伺，欲令我得，彼于贪伺净除其心。

“如是瞋恚、睡眠、掉悔、断疑、度惑，于诸善法，无有犹豫，彼于疑惑净除其心。彼断此五盖、心秽、慧羸，离欲、离恶不善之法，有觉有观，离生喜乐，逮初禅成就游。梵志，是谓如来所屈，如来所行，如来所服。然彼不以此为讫。世尊、如来、无所著、等正觉，世尊所说法善，如来弟子圣众善趣。

“彼觉观已息，内静一心，无觉无观，定生喜乐，逮第二禅成就游。梵志，是谓如来所屈，如来所行，如来所服。然彼不以此为讫。世尊、如来、无所著、等正觉，世尊所说法善，如来弟子圣众善趣。

“彼离喜欲，舍无求游，正念正智而身觉乐，谓圣所说、圣所舍、念、乐住、空，逮第三禅成就游。梵志，是谓如来所屈，如来所行，如来所服。然彼不以此为讫。世尊、如来、无所著、等正觉，世尊所说法善，如来弟子圣众善趣。

“彼乐灭、苦灭，喜、忧本已灭，不苦不乐、舍、念、清净，逮第四禅成就游。梵志，是谓如来所屈，如来所行，如来所服。然彼不以此为讫。世尊、如来、无所著、等正觉，世尊所说法善，如来弟子圣众善趣。

“彼已得如是定心，清净无秽，无烦柔软，善住得不动心，趣向漏尽智通作证。彼知此苦如真，知此苦集，知此苦灭，知此苦灭道如真；知此漏如真，知此漏集，知此漏灭，知此漏灭道如真。彼如是知、如是见，欲漏心解脱，有漏、无明漏心解脱；解脱已，便知解脱：生已尽，梵行已立，所作已办，不更受有，知如真。梵志，是谓如来所屈，如来所行，如来所服。彼以此为讫。世尊、如来、无所著、等正觉，世尊所说法善，如来弟子圣众善趣。梵志，于意云何？如是象迹喻善作具足耶？”

生闻梵志答曰：“唯然，瞿昙，如是象迹喻善作具足。”

生闻梵志白曰：“世尊，我已知。善逝，我已解。世尊，我今自归于佛、法及比丘众，惟愿世尊受我为优婆塞！从今日始，终身自归，乃至命尽。

佛说如是，生闻梵志及卑卢异学闻佛所说，欢喜奉行。

--------------

** 第36卷 梵志品.闻德经第六

我闻如是：一时，佛游舍卫国，在胜林给孤独园。

尔时，生闻梵志中后彷佯，往诣佛所，共相问讯，却坐一面，白曰：“瞿昙，我欲有所问，听乃敢陈。”

世尊告日：“梵志，恣汝所问。”

生闻梵志即便问曰：“沙门瞿昙弟子或有在家，或有出家学道，以何义故博闻诵习耶？”

世尊答曰：“梵志，我弟子或有在家，或出家学道，所以博闻诵习，欲自调御，欲自息止，自求灭讫。梵志，我弟子或有在家，或出家学道，以此义故博闻诵习。”

生闻梵志复问曰：“瞿昙，博闻诵习有差别耶？博闻诵习有功德耶？”

世尊答曰：“梵志，博闻诵习而有差别，博闻诵习则有功德。”

生闻梵志复问曰：“瞿昙，博闻诵习有何差别？有何功德耶？”

世尊答曰：“梵志，多闻圣弟子昼日作业，欲得其利，彼所作业败坏不成。彼所作业败坏不成已，然不忧戚、愁烦、啼哭，不椎身懊恼，亦不痴狂。梵志，若多闻圣弟子昼日作业，欲得其利，彼所作业败坏不成。彼所作业败坏不成已，然不忧戚、愁烦、啼哭，不椎身懊恼，亦不痴狂者。梵志，是谓博闻诵习而有差别，有此功德。

“复次，梵志，多闻圣弟子所有爱念，异无散解，不复相应，与别离已，然不忧戚、愁烦、啼哭，不椎身懊恼，亦不痴狂。梵志，若多闻圣弟子所有爱念，异无散解，不复相应，与别离已，然不忧戚、愁烦、啼哭，不椎身懊恼，亦不痴狂者。梵志，是谓博闻诵习而有差别，有此功德。

“复次，梵志，多闻圣弟子知所有财物皆悉无常，念出家学道。梵志，若多闻圣弟子知所有财物皆悉无常，念出家学道者。梵志，是谓博闻诵习而有差别，有此功德。

“复次，梵志，多闻圣弟子知所有财物皆悉无常已，剃除须发，著袈裟衣，至信、舍家、无家、学道。梵志，若多闻圣弟子知所有财物皆悉无常已，剃除须发，著袈裟衣，至信、舍家、无家、学道者。梵志，是谓博闻诵习而有差别，有此功德。

“复次，梵志，多闻圣弟子能忍饥渴、寒热、蚊虻、蝇蚤，风日所逼、恶声捶杖亦能忍之；身遇诸疾，极为苦痛，至命欲绝，诸不可乐皆能堪耐。梵志，若多闻圣弟子能忍饥渴、寒热、蚊虻、蝇蚤，风日所逼、恶声捶杖亦能忍之；身遇诸疾，极为苦痛，至命欲绝，诸不可乐皆能堪耐者。梵志，是谓博闻诵习而有差别，有此功德。

“复次，梵志，多闻圣弟子堪耐不乐，生不乐已，心终不著。梵志，若多闻圣弟子堪耐不乐，生不乐已，心终不著者。梵志，是谓博闻诵习而有差别，有此功德。

“复次，梵志，多闻圣弟子堪耐恐怖，生恐怖已，心终不著。梵志，若多闻圣弟子堪耐恐怖，生恐怖已，心终不著。梵志，是谓博闻诵习而有差别，有此功德。

“复次，梵志，多闻圣弟子若生三恶不善之念，欲念、恚念及害念，为此三恶不善念已，心终不著。梵志，若多闻圣弟子若生三恶不善之念，欲念、恚念及害念，为此三恶不善念已，心终不著者。梵志，是谓博闻诵习而有差别，有此功德。

“复次，梵志，多闻圣弟子离欲、离恶不善之法，至得第四禅成就游。梵志，若多闻圣弟子离欲、离恶不善之法，至得第四禅成就游者。梵志，是谓博闻诵习而有差别，有此功德。

“复次，梵志，多闻圣弟子三结已尽，得须陀洹，不堕恶法，定趣正觉，极受七有，天上人间七往来已，则得苦边。梵志，若多闻圣弟子三结已尽，得须陀洹，不堕恶法，定趣正觉，极受七有，天上人间七往来已，则得苦边者。梵志，是谓博闻诵习而有差别，有此功德。

“复次，梵志，多闻圣弟子三结已尽，淫、怒、痴薄，得一往来，天上人间一往来已，则得苦边。梵志，若多闻圣弟子三结已尽，淫、怒、痴薄，得一往来，天上人间一往来已，则得苦边者。梵志，是谓博闻诵习而有差别，有此功德。

“复次，梵志，多闻圣弟子五下分结尽，生彼间已，便般涅槃，得不退法，不还此世。梵志，若多闻圣弟子五下分结尽，生彼间已，便般涅槃，得不退法，不还此世者。梵志，是谓博闻诵习而有差别，有此功德。

“复次，梵志，多闻圣弟子有息解脱，离色得无色如其像定，身作证成就游，慧观断漏而知漏。梵志，若多闻圣弟子有息解脱，离色得无色如其像定，身作证成就游，慧观断漏而知漏者。梵志，是谓博闻诵习而有差别，有此功德。

“复次，梵志，多闻圣弟子如意足、天耳、他心智、宿命智、生死智，诸漏已尽，得无漏，心解脱，慧解脱，于现法中自知、自觉、自作证成就游：生已尽，梵行已立，所作已办，不更受有，知如真。梵志，若多闻圣弟子如意足、天耳、他心智、宿命智、生死智，诸漏已尽，得无漏，心解脱，慧解脱，于现法中自知、自觉、自作证成就游：生已尽，梵行已立，所作已办，不更受有，知如真者。梵志，是谓博闻诵习而有差别，有此功德。”

生闻梵志复问世尊：“此博闻诵习有此差别，有此功德，颇更有差别，更有功德，最上、最妙、最胜耶？”

世尊答曰：“梵志，此博闻诵习有此差别，有此功德，更无差别，更无功德，最上、最妙、最胜者。”

生闻梵志白曰：“世尊，我已知。善逝，我已解。世尊，我今自归于佛、法及比丘众，惟愿世尊受我为优婆塞！从今日始，终身自归，乃至命尽。”

佛说如是，生闻梵志闻佛所说，欢喜奉行。

--------------

** 第36卷 梵志品.何苦经第七

我闻如是：一时，佛游舍卫国，在胜林给孤独园。

尔时，生闻梵志中后彷徉，往诣佛所，共相问讯，却坐一面，白曰：“瞿昙，我欲有所问，听乃敢陈。”

世尊告曰：“梵志，恣汝所问。”

生闻梵志即便问曰：“瞿昙，在家者有何苦？出家学道者有何苦耶？”

世尊答曰：“梵志，在家者，以不自在为苦；出家学道者，以自在为苦。”

生闻梵志复问曰：“瞿昙，在家者云何以不自在为苦？出家学道者云何以自在为苦耶？”

世尊答曰：“梵志，若在家者，钱不增长，金、银、真珠、琉璃、水精悉不增长，畜牧、谷米及奴婢使亦不增长，尔时，在家忧苦愁戚，因此故在家者多有忧苦，多怀愁戚。梵志，若出家学道者行随其欲，行随恚痴，尔时，出家学道忧苦愁戚，因此故出家学道者多有忧苦，多怀愁戚。梵志，如是在家者以不自在为苦，出家学道者以自在为苦。”

生闻梵志复问曰：“瞿昙，在家者有何乐？出家学道者有何乐耶？”

世尊答曰：“梵志，在家者以自在为乐，出家学道者以不自在为乐。”

生闻梵志复问曰：“瞿昙，在家者云何以自在为乐？出家学道者云何以不自在为乐耶？”

世尊答曰：“梵志，若在家者钱得增长，金、银、真珠、琉璃、水精皆得增长，畜牧、谷米及奴婢使亦得增长，尔时，在家快乐欢喜，因此故在家者多快乐欢喜。梵志，出家学道者行不随欲，行不随恚痴，尔时，出家学道快乐欢喜，因此故出家学道者多快乐欢喜。梵志，如是在家者以自在为乐，出家学道者以不自在为乐。”

生闻梵志复问曰：“瞿昙，以何事故令天及人必无利义？以何事故令天及人必有利义？”

世尊答曰：“梵志，若天及人共诤者，必无利义；若天及人不诤者，必有利义。”

生闻梵志复问曰：“瞿昙，云何天及人共诤者必无利义？云何天及人不诤者必有利义耶？”

世尊答曰：“梵志，若时天及人斗诤怨憎者，尔时，天及人忧苦愁戚，因此故天及人多有忧苦，多怀愁戚。梵志，若时天及人不斗诤、不怨憎者，尔时，天及人快乐欢喜，因此故天及人多快乐、多欢喜。梵志，如是天及人共诤者，必无利义；天及人不诤者，必有利义。”

生闻梵志复问曰：“瞿昙，以何事故，令天及人必不得饶益，必得其苦？以何事故，令天及人必得饶益，必得其乐？”

世尊答曰：“梵志，若天及人行于非法及行恶者，必不得益，必得其苦。若天及人能行如法，不行恶者，必得饶益，必得其乐。”

生闻梵志复问曰：“瞿昙，天及人云何行于非法及行恶者，必不得益，必得其苦？天及人云何行如法，不行恶者，必得饶益，必得其乐？”

世尊答曰：“梵志，天及人身行非法及行恶，口、意行非法及行恶者，尔时，天及人必当减损，阿修罗必当兴盛。梵志，若天及人身行如法，守护其身，口、意行如法，守护口、意者，尔时，天及人必当兴盛，阿修罗必当减损。梵志，如是天及人行于非法及行恶者，必得不益，必得其苦。梵志，如是天及人能行如法，不行恶者，必得饶益，必得其乐。”

生闻梵志复问曰：“瞿昙，云何观恶知识？”

世尊答曰：“梵志，当观恶知识犹如月也。”

生闻梵志复问曰：“瞿昙，云何当观恶知识犹如月耶？”

世尊答曰：“梵志，如向尽月，日日稍减，宫殿亦减，光明亦减，形色亦减，日日尽去。梵志，有时月乃至于尽，都不复见。梵志，恶知识人于如来正法、律亦得其信，彼得信已，则于后时而不孝顺，亦不恭敬，所行不顺，不立正智，不趣向法次法，彼便失信，持戒、博闻、庶几、智慧亦复失之。梵志，有时此恶知识教灭善法，犹如月尽。梵志，如是当观恶知识犹如月也。”

生闻梵志复问曰：“瞿昙，云何观善知识？”

世尊答曰：“梵志，当观善知识犹如月也。”

生闻梵志复问曰：“瞿昙，云何当观善知识犹如月耶？”

世尊答曰：“梵志，犹如月初生，少壮明净，日日增长。梵志，或时月十五日，其殿丰满。梵志，如是善知识于如来正法、律得信，彼得信已，而于后时孝顺恭敬，所行随顺，立于正智，趣向法次法，彼增长信，持戒、博闻、庶几、智慧亦复增长。梵志，有时彼善知识善法具足，如十五日月。梵志，如是当观善知识犹如月也。”

于是，世尊说此颂曰：

<div class="poem">

譬如月无垢，游于虚空界，\\
一切世星宿，悉翳其光明。\\
如是信博闻，庶几无悭贪，\\
世间一切悭，悉翳施光明。\\
犹如有大龙，兴起云雷电，\\
雨下极滂沛，充满一切地。\\
如是信博闻，庶几无悭贪，\\
施饮食丰足，乐劝增广施。\\
如是极雷震，如天降时雨，\\
彼福雨广大，施主之所雨。\\
钱财多名誉，得生于善处，\\
彼当受于福，死已生天上。

</div>

佛说如是，生闻梵志闻佛所说，欢喜奉行。

--------------

** 第37卷 梵志品.何欲经第八

我闻如是：一时，佛游舍卫国，在胜林给孤独园。

尔时，生闻梵志中后彷徉，往诣佛所，共相问讯，却坐一面，白曰：“瞿昙，欲有所问，听乃敢陈。”

世尊告曰：“恣汝所问。”

梵志即便问曰：“瞿昙，刹利何欲、何行、何立、何依、何讫耶？”

世尊答曰：“刹利者，欲得财物，行于智慧，所立以刀，依于人民，以自在为讫。”

生闻梵志问曰：“瞿昙，居士何欲、何行、何立、何依、何讫耶？”

世尊答曰：“居士者，欲得财物，行于智慧，立以技术，依于作业，以作业竟为讫。”

生闻梵志问曰：“瞿昙，妇人何欲、何行、何立、何依、何讫耶？”

世尊答曰：“妇人者，欲得男子，行于严饰，立以儿子，依于无对，以自在为讫。”

生闻梵志问曰：“瞿昙，偷劫何欲、何行、何立、何依、何讫耶？”

世尊答曰：“偷劫者，欲不与取，行隐藏处，所立以刀，依于暗冥，以不见为讫。”

生闻梵志问曰：“瞿昙，梵志何欲、何行、何立、何依、何讫耶？”

世尊答曰：“梵志者，欲得财物，行于智慧，立以经书，依于斋戒，以梵天为讫。”

生闻梵志问曰：“瞿昙，沙门何欲、何行、何立、何依、何讫耶？”

世尊答曰：“沙门者，欲得真谛，行于智慧，所立以戒，依于无处，以涅槃为讫。”

生闻梵志白曰：“世尊，我已知。善逝，我已解。世尊，我今自归于佛、法及比丘众，惟愿世尊受我为优婆塞！从今日始，终身自归，乃至命尽。”

佛说如是，生闻梵志闻佛所说，欢喜奉行。

--------------

** 第37卷 梵志品.郁瘦歌逻经第九

我闻如是：一时，佛游王舍城，在竹林迦兰哆园。

尔时，郁瘦歌逻梵志中后彷徉，往诣佛所，共相问讯，却坐一面，白曰：“瞿昙，欲有所问，听乃敢陈。”

世尊告曰：“恣汝所问。”

郁瘦歌逻梵志即便问曰：“瞿昙，梵志为四种姓施设四种奉事，为梵志施设奉事，为刹利、居士、工师施设奉事。瞿昙，梵志为梵志施设奉事，梵志应奉事梵志，刹利、居士、工师亦应奉事梵志。瞿昙，此四种姓应奉事梵志。瞿昙，梵志为刹利施设奉事，刹利应奉事刹利，居士、工师、亦应奉事刹利。瞿昙，此三种姓应奉事刹利。瞿昙，梵志为居士施设奉事，居士应奉事居士，工师亦应奉事居士。瞿昙，此二种姓应奉事居士。瞿昙，梵志为工师施设奉事，工师应奉事工师，谁复下贱应施设奉事工师？唯工师奉事工师。”

世尊问曰：“梵志，诸梵志颇自知为四种姓施设四种奉事，为梵志施设奉事，为刹利、居士、工师施设奉事耶？”

郁瘦歌逻梵志答曰：“不知也。瞿昙，但诸梵志自作是说：‘我于此世，天及魔、梵、沙门、梵志，从人至天，梵志不自知为四种姓施设四种奉事，为梵志施设奉事，为刹利、居士、工师施设奉事。'”

世尊告曰：“梵志，犹如有人，强与他肉，而作是说：‘士夫可食，当与我值。'梵志，汝为诸梵志说亦复如是。所以者何？梵志不自知为四种姓施设四种奉事，为梵志施设奉事，为刹利、居士、工师施设奉事。”

世尊问曰：“梵志，云何奉事？若有奉事，因奉事故，有如无胜者，为是奉事耶？若有奉事，因奉事故，有胜无如者，为是奉事耶？梵志，若奉事梵志，因奉事故，有如无胜者，为是奉事耶？奉事刹利、居士、工师，因奉事故，有如无胜者，为是奉事耶？梵志，若奉事梵志，因奉事故，有胜无如者，为是奉事耶？奉事刹利、居士、工师，因奉事故，有胜无如者，为是奉事耶？”

郁瘦歌逻梵志答曰：“瞿昙，若我奉事，因奉事故，有如无胜者，我不应奉事彼。若我奉事，因奉事故，有胜无如者，我应奉事彼。瞿昙，若奉事梵志，因奉事故，有如无胜者，我不应奉事彼；奉事刹利、居士、工师，因奉事故，有如无胜者，我不应奉事彼。瞿昙，若奉事梵志，因奉事故，有胜无如者，我应奉事彼；奉事刹利、居士、工师，因奉事故，有胜无如者，我应奉事彼。”

世尊告曰：“梵志，若更有梵志来，非愚非痴，亦非颠倒，心无颠倒，自由自在，我问彼梵志：‘于意云何？若有奉事，因奉事故，有如无胜者，为是奉事耶？若有奉事，因奉事故，有胜无如者，为是奉事耶？梵志，若奉事梵志，因奉事故，有如无胜者，为是奉事耶？奉事刹利、居士、工师，因奉事故，有如无胜者，为是奉事耶？梵志，若奉事梵志，因奉事故，有胜无如者，为是奉事耶？奉事刹利、居士、工师，因奉事故，有胜无如者，为是奉事耶？'

“梵志，彼梵志非愚非痴，亦非颠倒，心无颠倒，自由自在，答我曰：‘瞿昙，若我奉事，因奉事故，有如无胜者，我不应奉事彼。若我奉事，因奉事故，有胜无如者，我应奉事彼。瞿昙，若奉事梵志，因奉事故，有如无胜者，我不应奉事彼；奉事刹利、居士、工师，因奉事故，有如无胜者，我不应奉事彼。瞿昙，若奉事梵志，因奉事故，有胜无如者，我应奉事彼；奉事刹利、居士、工师，因奉事故，有胜无如者，我应奉事彼。'”

世尊问曰：“梵志，于意云何？若有奉事，因奉事故，失信、戒、博闻、庶几、智慧者，为是奉事耶？若有奉事，因奉事故，增益信、戒、博闻、庶几、智慧者，为是奉事耶？梵志，若奉事梵志，因奉事故，失信、戒、博闻、庶几、智慧者，为是奉事耶？奉事刹利、居士、工师，因奉事故，失信、戒、博闻、庶几、智慧者，为是奉事耶？梵志，若奉事梵志，因奉事故，增益信、戒、博闻、庶几、智慧者，为是奉事耶？奉事刹利、居士、工师，因奉事故，增益信、戒、博闻、庶几、智慧者，为是奉事耶？”

郁瘦歌逻梵志答曰：“瞿昙，若我奉事，因奉事故，失信、戒、博闻、庶几、智慧者，我不应奉事彼。若我奉事，因奉事故，增益信、戒、博闻、庶几、智慧者，我应奉事彼。瞿昙，若奉事梵志，因奉事故，失信、戒、博闻、庶几、智慧者，我不应奉事彼；奉事刹利、居士、工师，因奉事故，失信、戒、博闻、庶几、智慧者，我不应奉事彼。瞿昙，若奉事梵志，因奉事故，增益信、戒、博闻、庶几、智慧者，我应奉事彼；奉事刹利、居士、工师，因奉事故，增益信、戒、博闻、庶几、智慧者，我应奉事彼。”

世尊告曰：“梵志，若更有梵志来，非愚非痴，亦非颠倒，心无颠倒，自由自在，我问彼梵志：‘于意云何？若有奉事，因奉事故，失信、戒、博闻、庶几、智慧者，为是奉事耶？若有奉事，因奉事故，增益信、戒、博闻、庶几、智慧者，为是奉事耶？梵志，若奉事梵志，因奉事故，失信、戒、博闻、庶几、智慧者，为是奉事耶？奉事刹利、居士、工师，因奉事故，失信、戒、博闻、庶几、智慧者，为是奉事耶？梵志，若奉事梵志，因奉事故，增益信、戒、博闻、庶几、智慧者，为是奉事耶？奉事刹利、居士、工师，因奉事故，增益信、戒、博闻、庶几、智慧者，为是奉事耶？'

“梵志，彼梵志非愚非痴，亦非颠倒，心无颠倒，自由自在，亦如是答我曰：‘瞿昙，若我奉事，因奉事故，失信、戒、博闻、庶几、智慧者，我不应奉事彼。若我奉事，因奉事故，增益信、戒、博闻、庶几、智慧者，我应奉事彼。瞿昙，若奉事梵志，因奉事故，失信、戒、博闻、庶几、智慧者，我不应奉事彼；奉事刹利、居士、工师，因奉事故，失信、戒、博闻、庶几、智慧者，我不应奉事彼。瞿昙，若奉事梵志，因奉事故，增益信、戒、博闻、庶几、智慧者，我应奉事彼；奉事刹利、居士、工师，因奉事故，增益信、戒、博闻、庶几、智慧者，我应奉事彼。'”

郁瘦歌逻梵志白曰：“瞿昙，梵志为四种姓施设四种自有财物，为梵志施设自有财物，为刹利、居士、工师施设自有财物。瞿昙，梵志为梵志施设自有财物者，瞿昙，梵志为梵志施设乞求自有财物。若梵志轻慢乞求者，则便轻慢自有财物；轻慢自有财物已，则便失利。犹如放牛人不能看牛者，则便失利。如是，瞿昙，梵志为梵志施设乞求自有财物。若梵志轻慢乞求者，则便轻慢自有财物；轻慢自有财物已，则便失利。

“瞿昙，梵志为刹利施设自有财物者，瞿昙，梵志为刹利施设弓箭自有财物。若刹利轻慢弓箭者，则便轻慢自有财物；轻慢自有财物已，则便失利。犹如放牛人不能看牛者，则便失利。如是，瞿昙，梵志为刹利施设弓箭自有财物。若刹利轻慢弓箭者，则便轻慢自有财物；轻慢自有财物已，则便失利。瞿昙，梵志为居士施设自有财物者，瞿昙，梵志为居士施设田作自有财物。若居士轻慢田作者，则便轻慢自有财物；轻慢自有财物已，则便失利。犹如放牛人不能看牛者，则便失利。如是，瞿昙，梵志为居士施设田作自有财物。若居士轻慢田作者，则便轻慢自有财物；轻慢自有财物已，则便失利。瞿昙，梵志为工师施设自有财物者，瞿昙，梵志为工师施设麻自有财物。若工师轻慢麻者，则便轻慢自有财物；轻慢自有财物已，则便失利。犹如放牛人不能看牛者，则便失利。如是，瞿昙，梵志为工师施设麻自有财物。若工师轻慢麻者，则便轻慢自有财物；轻慢自有财物已，则便失利。”

世尊问曰：“梵志，诸梵志颇自知为四种姓施设四种自有财物，为梵志施设自有财物，为刹利、居士、工师施设自有财物耶？”

郁瘦歌逻梵志答曰：“不知也。瞿昙，但诸梵志自说：‘我于此世，天及魔、梵、沙门、梵志，从人至天，不自知为四种姓施设四种自有财物，为梵志施设自有财物，为刹利、居士、工师施设自有财物。'”

世尊告曰：“梵志，犹如有人，强与他肉，而作是说：‘士夫可食，当与我值。'梵志，汝为诸梵志说亦复如是。所以者何？梵志不自知为四种姓施设四种自有财物，为梵志施设自有财物，为刹利、居士、工师施设自有财物。如是，梵志，我自善解、善知诸法，为人施设息止法、灭讫法、觉道法、善趣法、施设自有财物。”

世尊问曰：“梵志，于意云何？颇有梵志于此虚空不著、不缚、不触、不碍，刹利、居士、工师不然耶？”

郁瘦歌逻梵志答曰：“瞿昙，梵志于此虚空不著、不缚、不触、不碍，刹利、居士、工师亦然如是。”

“梵志，我自善解、善知诸法，为人施设息止法、灭讫法、觉道法、善趣法，施设自有财物。”世尊问曰：“梵志，于意云何？颇有梵志能行慈心，无结、无怨、无恚、无诤，刹利、居士、工师不然耶？”

郁瘦歌逻梵志答曰：“瞿昙，梵志能行慈心，无结、无怨、无恚、无诤，刹利、居士、工师亦然如是。”

“梵志，我自善解、善知诸法，为人施设息止法、灭讫法、觉道法、善趣法，施设自有财物。”世尊问曰：“梵志，于意云何？若百种人来，或有一人而语彼曰：‘汝等共来，若有生刹利族、梵志族者，唯彼能持澡豆至水洗浴，去垢极净。'梵志，于意云何？为刹利族、梵志族者，彼能持澡豆至水洗浴，去垢极净耶？为居士族、工师族者，彼不能持澡豆至水洗浴，去垢极净耶？为一切百种人皆能持澡豆至水洗浴，去垢极净耶？”

郁瘦歌逻梵志答日：“瞿昙，彼一切百种人皆能持澡豆至水洗浴，去垢极净。”

“如是，梵志，我自善解、善知诸法，为人施设息止法、灭讫法、觉道法、善趣法，施设自有财物。”世尊问曰：“梵志，于意云何？若百种人来，或有一人而语彼曰：‘汝等共来，若生刹利族、梵志族者，唯彼能以极燥娑罗及旃檀木用作火母，以钻钻之，生火长养。'梵志，于意云何？为刹利族、梵志族者，彼能以极燥娑罗及旃檀木用作火母，以钻钻之，生火长养耶？为居士族、工师族者，彼当以燥猪狗槽、伊兰檀木及余弊木用作火母，以钻钻之，生火长养耶？为一切百种人皆能以若干种木用作火母，以钻钻之，生火长养耶？”

郁瘦歌逻梵志答口：“瞿昙，彼一切百种人皆能以若干种木用作火母，以钻钻之，生火长养。”

“如是，梵志，我自善解、善知诸法，为人施设息止法、灭讫法、觉道法、善趣法，施设自有财物。”世尊问曰：“梵志，于意云何？若彼百种人皆以若干种木用作火母，以钻钻之，生火长养，彼一切火皆有焰、有色、有热、有光，皆能作火事。为彼火独有焰、有色、有热、有光，能作火事耶？为彼火独无焰、无色、无热、无光，不能作火事耶？为彼一切为皆有焰、有色、有热、有光，皆能作火事耶？”

郁瘦歌逻梵志答曰：“瞿昙，若百种人皆以若干种木用作火母，以钻钻之，生火长养者，彼一切火皆有焰、有色、有热、有光，皆能作火事。若彼火独有焰、有色、有热、有光，能为火事者，终无是处。若彼火独无焰、无色、无热、无光，不能为火事者，亦无是处。但，瞿昙，彼一切火皆有焰、有色、有热、有光，皆能作火事。”

“如是，梵志，我自善解、善知诸法，为人施设息止法、灭讫法、觉道法、善趣法，施设自有财物。”世尊问曰：“梵志，于意云何？若彼百种人皆以若干种木用作火母，以钻钻之，生火长养。彼或有人以燥草木著其火中，生焰、生色、生热、生烟，颇有焰、色、热、烟，焰、色、热、烟而差别耶？”

郁瘦歌逻梵志答曰：“瞿昙，若彼百种人皆以若干种木用作火母，以钻钻之，生火长养。彼若有人以燥草木著其火中，生焰、生色、生热、生烟，我于彼火焰、色、热、烟，焰、色、热、烟不能施设有差别也。”

世尊告曰：“梵志，如是我所得火，所得不放逸，能灭放逸及贡高慢，我于此火，火亦不能施设有差别也。”

郁瘦歌逻梵志白曰：“世尊，我已知。善逝，我已解。世尊，我今自归于佛、法及比丘众，惟愿世尊受我为优婆塞！从今日始，终身自归，乃至命尽。”

佛说如是，郁瘦歌逻梵志闻佛所说，欢喜奉行。

--------------

** 第37卷 梵志阿摄和经第十

我闻如是：一时，佛游舍卫国，在胜林给孤独园。

尔时，众多梵志于拘萨罗，集在学堂，共论此事：“梵志种胜，余者不如；梵志种白，余者皆黑；梵志得清净，非梵志不得清净；梵志梵天子，从彼口生，梵梵所化；而沙门瞿昙说四种姓皆悉清净，施设显示。”彼作是念：“诸贤，为谁有力能至沙门瞿昙所？则以此事如法难诘。”彼复作是念：“阿摄惒逻延多那摩纳为父母所举，受生清净，乃至七世父母不绝种族，生生无恶，博闻总持，诵过四典经，深达因、缘、正、文、戏五句说。阿摄惒逻延多那摩纳有力能至沙门瞿昙所，则以此事如法难诘。诸贤，可共诣阿摄惒逻延多那摩纳所，向说此事，随阿摄惒逻延多那摩纳所说，我等当受。”

于是，拘萨罗众多梵志即诣阿摄惒逻延多那摩纳所，共相问讯，却坐一面，语曰：“摩纳，我等众多梵志于拘萨罗，集在学堂，共论此事：‘梵志种胜，余者不如；梵志种白，余者皆黑；梵志得清净，非梵志不得清净；梵志梵天子，从彼口生，梵梵所化；而沙门瞿昙说四种姓皆悉清净，施设显示。'我等作是念：‘诸贤，为谁有力能至沙门瞿昙所？则以此事如法难诘。'我等复作是念：‘阿摄惒逻延多那摩纳为父母所举，受生清净，乃至七世父母不绝种族，生生无恶，博闻总持，诵过四典经，深达因、缘、正、文、戏五句说。阿摄惒逻延多那摩纳有力能至沙门瞿昙所，则以此事如法难诘。'愿阿摄惒逻延多那摩纳往诣沙门瞿昙所，则以此事如法难诘。”

阿摄惒逻延多那摩纳语诸梵志曰：“诸贤，沙门瞿昙如法说法，若如法说法者，不可难诘也。”

拘萨罗众多梵志语曰：“摩纳，汝未有屈事，未可豫自伏。所以者何？阿摄惒逻延多那摩纳为父母所举，受生清净，乃至七世父母不绝种族，生生无恶，博闻总持，诵过四典经，深达因、缘、正、文、戏五句说。阿摄惒逻延多那摩纳有力能至沙门瞿昙所，则以此事如法难诘。愿阿摄惒逻延多那摩纳往诣沙门瞿昙所，则以此事如法难诘。”

阿摄惒逻延多那摩纳为拘萨罗众多梵志默然而受。于是，阿摄惒逻延多那摩纳与彼拘萨罗众多梵志往诣佛所，共相问讯，却坐一面，白曰：“瞿昙，欲有所问，听我问耶？”

世尊告曰：“摩纳，恣汝所问。”

阿摄惒逻延多那便问曰：“瞿昙，诸梵志等作如是说：‘梵志种胜，余者不如；梵志种白，余者皆黑；梵志得清净，非梵志不得清净；梵志梵天子，从彼口生，梵梵所化。'未知沙门瞿昙当云何说？”

世尊告曰：“我今问汝，随所解答。摩纳，颇闻余尼及剑浮国有二种姓，大家及奴，大家作奴，奴作大家耶？”

阿摄惒逻延多那摩纳答曰：“瞿昙，我闻余尼及剑浮国有二种姓，大家及奴，大家作奴，奴作大家也。”

“如是，摩纳，梵志若正趣者，彼得善解，自知如法；刹利、居士、工师若正趣者，亦得善解，自知如法。”

阿摄惒逻延多那摩纳白曰：“瞿昙，甚奇！甚特！快说此喻，但诸梵志作如是说：‘梵志种胜，余者不如；梵志种白，余者皆黑；梵志得清净，非梵志不得清净；梵志梵天子，从彼口生，梵梵所化。'”

世尊问曰：“摩纳，于意云何？颇独有梵志于此虚空不著不缚，不触不碍，刹利、居士、工师为不然耶？”

阿摄惒逻延多那摩纳答曰：“瞿昙，梵志于此虚空不著不缚，不触不碍，刹利、居士、工师亦然。”

“如是，摩纳，梵志若正趣者，彼得善解，自知如法；刹利、居士、工师若正趣者，亦得善解，自知如法。”

阿摄惒逻延多那摩纳白曰：“瞿昙，甚奇！甚特！快说此喻，但诸梵志作如是说：‘梵志种胜，余者不如；梵志种白，余者皆黑；梵志得清净，非梵志不得清净；梵志梵天子，从彼口生，梵梵所化。'”

世尊问曰：“摩纳，于意云何？颇独有梵志能行慈心，无结无怨，无恚无诤，刹利、居士、工师不然耶？”

阿摄惒逻延多那摩纳答曰：“瞿昙，梵志能行慈心，无结无怨，无恚无诤，刹利、居士、工师亦然。”

“如是，摩纳，梵志若正趣者，彼得善解，自知如法；刹利、居士、工师若正趣者，亦得善解，自知如法。”

阿摄惒逻延多那摩纳白曰：“瞿昙，甚奇！甚特！快说此喻，但诸梵志作如是说：‘梵志种胜，余者不如；梵志种白，余者皆黑；梵志得清净，非梵志不得清净；梵志梵天子，从彼口生，梵梵所化。'”

世尊问曰：“摩纳，于意云何？若百种人来，或有一人而语彼曰：‘汝等共来，若生刹利族、梵志族者，唯彼能持澡豆至水洗浴，去垢极净。'摩纳，于意云何？为刹利族、梵志族者，彼能持澡豆至水洗浴，去垢极净耶？为居士族、工师族者，彼不能持澡豆至水洗浴，去垢极净耶？为一切百种人皆能持澡豆至水洗浴，去垢极净耶？”

阿摄惒逻延多那摩纳答曰：“瞿昙，彼一切百种人皆能持澡豆至水洗浴，去垢极净。”

“如是，摩纳，梵志若正趣者，彼得善解，自知如法；刹利、居士、工师若正趣者，亦得善解，自知如法。”

阿摄惒逻延多那摩纳白曰：“瞿昙，甚奇！甚特！快说此喻，但诸梵志作如是说：‘梵志种胜，余者不如；梵志种白，余者皆黑；梵志得清净，非梵志不得清净；梵志梵天子，从彼口生，梵梵所化。'”

世尊问曰：“摩纳，于意云何？若百种人来，或有一人而语彼曰：‘汝等共来，若生刹利族、梵志族者，唯彼能以极燥娑罗及旃檀木用作火母，以钻钻之，生火长养。'摩纳，于意云何？为刹利族、梵志族者，彼能以极燥娑罗及旃檀木用作火母，以钻钻之，生火长养耶？为居士族、工师族者，彼当以燥猪狗槽及伊兰檀木及余弊木用作火母，以钻钻之，生火长养耶？为一切百种人皆能以若干种木用作火母，以钻钻之，生火长养耶？”

阿摄惒逻延多那摩纳答曰：“瞿昙，彼一切百种人皆能以若干种木用作火母，以钻钻之，生火长养。”

“如是，摩纳，梵志若正趣者，彼得善解，自知如法；刹利、居士、工师若正趣者，亦得善解，自知如法。”

阿摄惒逻延多那摩纳白曰：“瞿昙，甚奇！甚特！快说此喻，但诸梵志作如是说：‘梵志种胜，余者不如；梵志种白，余者皆黑；梵志得清净，非梵志不得清净；梵志梵天子，从彼口生，梵梵所化。'”

世尊问曰：“摩纳，于意云何？若彼百种人皆以若干种木用作火母，以钻钻之，生火长养，彼一切火皆有焰、有色、有热、有光，皆能作火事。为彼火独有焰、有色、有热、有光，能作火事耶？为彼火独无焰、无色、无热、无光，不能作火事耶？为彼一切火皆有焰、有色、有热、有光，皆能作火事耶？”

阿摄惒逻延多那摩纳白曰：“瞿昙，若彼百种人皆以若干种木用作火母，以钻钻之，生火长养者，彼一切火皆有焰、有色、有热、有光，皆能作火事。若彼火独有焰、有色、有热、有光，能为火事者，终无是处。若彼火独无焰、无色、无热、无光，不能为火事者，亦无是处。瞿昙，但彼一切火皆有焰、有色、有热、有光，皆能作火事。”

“如是，摩纳，梵志若正趣者，彼得善解，自知如法；刹利、居士、工师若正趣者，亦得善解，自知如法。”

阿摄惒逻延多那摩纳白曰：“瞿昙，甚奇！甚特！快说此喻，但诸梵志作如是说：‘梵志种胜，余者不如；梵志种白，余者皆黑；梵志得清净，非梵志不得清净；梵志梵天子，从彼口生，梵梵所化。'”

世尊告曰：“摩纳，若此身随所生者，即彼之数。若生梵志族者，即梵志族数。若生刹利、居士、工师族者，即工师族数。摩纳，犹若如火，随所生者，即彼之数。若因木生者，即木火数。若因草粪薪生者，即薪火数。如是，摩纳，此身随所生者，即彼之数。若生梵志族者，即梵志族数。若生刹利、居士、工师族者，即工师族数。”

世尊问曰：“摩纳，于意云何？若刹利女与梵志男共合会者，彼因合会，后便生子，或似父，或似母，或不似父母。汝云何说？彼为刹利？为梵志耶？”

阿摄惒逻延多那摩纳答曰：“瞿昙，刹利女与梵志男共合会者，彼因合会，后便生子，或似父，或似母，或不似父母，我不说彼刹利，亦不说梵志。瞿昙，我但说彼他身。”

“如是，摩纳，此身随所在者，即彼之数。若生梵志族者，即梵志族数。若生刹利、居士、工师族者，即工师族数。”

世尊问曰：“摩纳，若梵志女与刹利男共合会者，彼因合会，后便生子，或似父，或似母，或不似父母。汝云何说？彼为梵志？为刹利耶？”

阿摄惒逻延多那摩纳答曰：“瞿昙，梵志女与刹利男共合会者，彼因合会，后便生子，或似父，或似母，或不似父母，我不说彼梵志，亦不说刹利。瞿昙，我但说彼他身。”

“如是，摩纳，此身随所生者，既彼之数。若生梵志族者，即梵志族数。若生刹利、居士、工师族者，即工师族数。”

世尊问曰：“摩纳，于意云何？若人有众多草马，放一父驴，于中一草马与父驴共合会，彼因合会，后便生驹。汝云何说？彼为驴？为马耶？”

阿摄惒暹延多那摩纳答曰：“瞿昙，若有马与驴共合会，彼因合会，后便生驹，我不说彼驴，亦不说马。瞿昙，我但说彼骡也。”

“如是，摩纳，若此身随所生者，即彼之数。若生梵志族者，即梵志族数。若生刹利、居士、工师族者，即工师族数。”

世尊告曰：“摩纳，乃往昔时有众多仙人共住无事高处，生如是恶见：‘梵志种胜，余者不如；梵志种白，余者皆黑；梵志得清净，非梵志不得清净；梵志梵天子，从彼口生，梵梵所化。'

“于是，阿私罗仙人提鞞逻闻众多仙人共住无事高处，生如是恶见已，著袈裟衣，以袈裟巾裹头，拄杖持伞，著白衣，不从门入，至仙人住处静室经行。于是，共住无事高处有一仙人见阿私罗仙人提鞞逻著袈裟衣，以袈裟巾裹头，拄杖持伞，著白衣履，不从门入，至仙人住处静室经行；见已，往诣共住无事高处众多仙人所，便作是语：‘诸贤，今有一人著袈裟衣，以袈裟巾裹头，拄杖持伞，著白衣履，不从门入，至仙人住处静室经行，我等宁可共往咒之：“汝作灰！汝作灰耶！”'

“于是，共住无事高处众多仙人即往诣彼阿私罗仙人提鞞逻所，到已共咒：‘汝作灰！汝作灰！'如其咒法咒之汝作灰汝作灰者，如是如是，光颜益好，身体悦泽。彼众多仙人便作是念：‘我等本咒汝作灰！汝作灰者，彼即作灰。我今咒此人汝作灰！汝作灰！我等如其咒法咒此人，此人光颜益好，身体悦泽，我宁可问。'即便问之：‘汝为是谁？'阿私罗仙人提鞞逻答曰：‘诸贤，汝等颇闻有阿私罗仙人提鞞逻耶？'答曰：‘闻有阿私罗仙人提鞞逻。'复语曰：‘我即是也。'彼众多仙人即共辞谢阿私罗仙人提鞞逻曰：‘愿为忍恕！愿为忍恕！我等不知尊是阿私罗仙人提鞞逻耳！'于是，阿私罗仙人提鞞逻语诸仙人曰：‘我已相恕，汝等实生恶见：梵志种胜，余者不如；梵志种白，余者皆黑；梵志得清净，非梵志不得清净；梵志梵天子，从彼口生，梵梵所化。'彼诸仙人答曰：‘如是，阿私罗。'

“复问诸仙人曰：‘汝等为自知己父耶？'彼诸仙人答曰：‘知也，彼梵志取梵志妇，非非梵志，彼父复父，乃至七世父。彼梵志取梵志妇，非非梵志。'阿私罗复问诸仙人曰：‘汝等为自知己母耶？'彼诸仙人答曰：‘知也，彼梵志取梵志夫，非非梵志，彼母复母，乃至七世母。彼梵志取梵志夫，非非梵志。'阿私罗复问诸仙人曰：‘汝等颇自知受胎耶？'彼诸仙人答曰：‘知也，以三事等合会受胎，父母合会，无满堪耐，香阴已至。阿私罗，此事等会，入于母胎。'

“阿私罗复问诸仙人曰：‘颇知受生为男？为女？知所从来？为从刹利族来？梵志、居士、工师族来耶？为从东方、南方、西方、北方来耶？'彼诸仙人答曰：‘不知。'阿私罗复语彼仙人曰：‘诸贤，不见不知此者，汝等不知受胎，谁从何处来，为男为女，为从刹利来，梵志、居士、工师来，为从东方、南方、西方、北方来；然作是说：梵志种胜，余者不如；梵志种白，余者皆黑；梵志得清净，非梵志不得清净；梵志梵天子，从彼口生，梵梵所化。'摩纳，彼住无事高处众多仙人为阿私罗仙人提鞞逻如是善教善诃，不能施设清净梵志，况汝师徒著皮草衣？”

于是，阿摄惒逻延多那摩纳为世尊面诃诘责，内怀愁戚，低头默然，失辩无言。

于是，世尊面诃诘责阿摄惒逻延多那摩纳已，复令欢悦，即便告曰：“摩纳，有一梵志作斋行施，彼有四儿，二好学问，二不学问。于摩纳意云何？彼梵志为先施谁第一座、第一澡水、第一食耶？”

阿摄惒逻延多那摩纳答曰：“瞿昙，若彼梵志其有二儿，好学问者，必先施彼第一座、第一澡水、第一食也！”

世尊复问曰：“摩纳，复有一梵志作斋行施，彼有四儿，二好学问，然不精进，喜行恶法。二不学问，然好精进，喜行妙法。于摩纳意云何？彼梵志为先施谁第一座、第一澡水、第一食耶？”

阿摄惒逻延多那摩纳答曰：“瞿昙，若彼梵志其有二儿，虽不学问，而好精进，喜行妙法者，必先施彼第一座、第一澡水、第一食也！”

世尊告曰：“摩纳，汝先称叹学问，后称叹持戒。摩纳，我说种姓皆悉清净施设显示，汝亦说种姓皆悉清净施设显示。”

于是，阿摄惒逻延多那摩纳即从座起，欲稽首佛足，尔时，彼大众唱高大音声：“沙门瞿昙甚奇！甚特！有大如意足，有大威德，有大福佑，有大威神。所以者何？如沙门瞿昙说，四种姓皆悉清净施设显示，令阿摄惒逻延多那摩纳亦说四种姓皆悉清净。”

尔时，世尊知彼大众心之所念，告曰：“止！止！阿摄惒逻延多那，但心喜足，可还复坐，我当为汝说法。”

阿摄惒逻延多那摩纳稽首佛足，却坐一面。世尊为彼说法，劝发渴仰，成就欢喜；无量方便为彼说法，劝发渴仰，成就欢喜已，默念而住。

于是，阿摄惒逻延多那摩纳，佛为说法，劝发渴仰，成就欢喜已，即从座起，稽首佛足，绕三匝而去。是时，拘萨罗众多梵志还去不远，种种言语责数阿摄惒逻延多那：“欲何等作？欲伏沙门瞿昙，而反为沙门瞿昙所降伏还。犹如有人，为眼入林中，而反失眼还；阿摄惒逻延多那，汝亦如是，欲伏沙门瞿昙，而反为沙门瞿昙所降伏还。犹如有人，为饮入池，而反渴还；阿摄惒逻延多那，汝亦如是，欲伏沙门瞿昙，而反为沙门瞿昙所降伏还。阿摄惒逻延多那，欲何等作？”

于是，阿摄惒逻延多那摩纳语拘萨罗众多梵志曰：“诸贤，我前已说，沙门瞿昙如法说法，若如法说法者，不可难诘也！”

佛说如是，阿摄惒逻延多那摩纳闻佛所说，欢喜奉行。

（第三念诵讫）

--------------

*  梵志品.鹦鹉经第十一（第四分别诵）

　鹦鹉、须闲提，娑罗婆游堂，

须达、梵波罗，黄芦园、头那，

阿伽罗诃那，阿兰那、梵摩。


**  第38卷 梵志品.鹦鹉经第十一（第四分别诵）
我闻如是：一时，佛游王舍城，在竹林迦兰哆园。

尔时，鹦鹉摩纳都题子少有所为，往至王舍城，寄宿居士家。于是，鹦鹉摩纳都题子问所寄宿居士曰：“颇有沙门、梵志宗主众师，统领大众，为人所尊，令我随时往见奉敬，倘能因此敬奉之时，得欢喜耶？”

居士答曰：“有也！天爱，沙门瞿昙释种子舍释宗族，剃除须发，著袈裟衣，至信、舍家、无家、学道，觉无上正尽觉。天爱，自可随时往见，诣彼奉敬，或能因此奉敬之时，心得欢喜。”

鹦鹉摩纳即复问曰：“沙门瞿昙今在何处？我欲见之。”

居士答曰：“沙门瞿昙在此王舍城竹林迦兰哆园，便可往见。”

于是，鹦鹉摩纳从所寄宿居士家出，往诣竹林迦兰哆园。鹦鹉摩纳遥见世尊在树林间，端正姝好，犹星中月，光耀暐晔，晃若金山，相好具足，威神巍巍，诸根寂定，无有蔽碍，成就调御，息心静默；见已，便前往诣佛所，共相问讯，却坐一面，白曰：“瞿昙，欲有所问，听乃敢陈。”

世尊告曰：“恣汝所问。”

鹦鹉摩纳问曰：“瞿昙，如我所闻：若在家者，便得善解，则知如法；出家学道者，则不然也。我问瞿昙，此事云何？”

世尊告曰：“此事不定。”

鹦鹉摩纳白曰：“瞿昙，愿今为我分别此事。”

世尊告曰：“摩纳，谛听！善思念之，我当为汝具分别说。”鹦鹉摩纳受教而听。

佛言：“摩纳，若有在家及出家学道行邪行者，我不称彼。所以者何？若有在家及出家学道行邪行者，不得善解，不知如法。是故，摩纳，若有在家及出家学道行邪行者，我不称彼。摩纳，若有在家及出家学道行正行者，我称说彼。所以者何？若有在家及出家学道行正行者，必得善解，则知如法。是故，摩纳，若有在家及出家学道行正行者，我称说彼。摩纳，我如是说，说此二法，如是分别，如是显示。若有沙门、梵志有力坚固深入，一向专著，而说此为真谛，余者虚妄。”

鹦鹉摩纳白曰：“瞿昙，如我所闻：若在家者，便有大利，有大功德；出家学道者，则不然也。我问瞿昙，此事云何？”

世尊告曰：“此事不定。”

鹦鹉摩纳白曰：“瞿昙，愿复为我分别此事。”

世尊告曰：“摩纳，谛听！善思念之，我当为汝具分别说。”鹦鹉摩纳受教而听。

佛言：“摩纳，若在家者，有大灾患，有大斗诤，有大怨憎，行邪行者，不得大果，无大功德。犹如田作，有大灾患，有大斗诤，有大怨僧，行邪行者，不得大果，无大功德；如是，摩纳，若在家者亦复如是。摩纳，出家学道少有灾患，少有斗诤，少有怨憎，行邪行者，不得大果，无大功德。犹如治生，少有灾患，少有斗诤，少有怨憎，行邪行者，不得大果，无大功德；如是，摩纳，出家学道亦复如是。

“摩纳，若在家者，有大灾患，有大斗诤，有大怨憎，行正行者，得大果报，有大功德。犹如田作，有大灾患，有大斗诤，有大怨憎，行正行者，得大果报，有大功德；如是，摩纳，若在家者亦复如是。摩纳，出家学道少有灾患，少有斗诤，少有怨僧，行正行者，得大果报，有大功德。犹如治生，少有灾患，少有斗诤，少有怨憎，行正行者，得大果报，有大功德；如是，摩纳，出家学道亦复如是。摩纳，我如是说，说此二法，如是分别，如是显示。若有沙门、梵志有力坚固深入，一向专著，而说此为真谛，余者虚妄。”

鹦鹉摩纳白曰：“瞿昙，彼诸梵志施设五法，有大果报，有大功德，作福得善。”

世尊告曰：“若诸梵志施设五法，有大果报，有大功德，作福得善。汝在此众，今可说耶？”

鹦鹉摩纳白曰：“瞿昙，我无不可。所以者何？瞿昙，于今现坐此众。”

世尊告曰：“汝便可说。”

鹦鹉摩纳白曰：“瞿昙，善听！瞿昙，梵志施设第一真谛法，有大果报，有大功德，作福得善，第二诵习，第三热行，第四苦行。瞿昙，梵志施设第五梵行，有大果报，有大功德，作福得善。”

世尊告曰：“若有梵志施设五法，有大果报，有大功德，作福得善，彼梵志中颇有一梵志作如是说：‘我此五法，于现法中自知、自觉、自作证已，施设果'耶？”

鹦鹉摩纳白世尊曰：“无也，瞿昙。”

世尊告曰：“颇有师及祖师，至七世父母，作如是说：‘我此五法，于现法中自知、自觉、自作证已，施设果'耶？”

鹦鹉摩纳白世尊曰：“无也，瞿昙。”

尔时，世尊问曰：“摩纳，若昔有梵志寿终命过，诵持经书，流布经书，诵习典经：一曰、夜吒，二曰、婆摩，三曰、婆摩提婆，四曰、毗奢蜜哆罗，五曰、夜婆陀揵尼，六曰、应疑罗婆，七曰、婆私吒，八曰、迦葉，九曰、娑罗婆，十曰、婆惒。谓今诸梵志即彼具经诵习持学，彼颇作是说：‘我此五法，于现法中自知、自觉、自作证已，施设果'耶？”

鹦鹉摩纳白世尊曰：“无也，瞿昙，但诸梵志因信受持。”

世尊告曰：“若于诸梵志，无一梵志而作是说：‘我此五法，于现法中自知、自觉、自作证已，施设果报。'亦无师及祖师，乃至七世父母，而作是说：‘我此五法，于现法中自知、自觉、自作证已，施设果报。'若昔有梵志寿终命过，诵持经书，流布经书，诵习典经：一曰、夜吒，二曰、婆摩，三曰、婆摩提婆，四曰、毗奢蜜哆逻，五曰、夜婆陀揵尼，六曰、应疑罗婆，七曰、婆私吒，八曰、迦葉，九曰、婆罗婆，十曰、婆惒。谓今诸梵志即彼具经诵习持学，彼无作是说：‘我此五法，于现法中自知、自觉、自作证已，施设果报。'摩纳，彼诸梵志不以此故，于信向中无根本耶？”

鹦鹉摩纳白曰：“瞿昙，实无根本，但诸梵志闻已受持。”

世尊告曰：“犹众盲儿各相扶持，彼在前者，不见于后，亦不见中；彼在中者，不见于前，亦不见后；彼在后者，不见于中，亦不见前。摩纳，所说诸梵志辈亦复如是。摩纳，前说信而后复说闻。”

鹦鹉摩纳瞋恚世尊，憎嫉不悦，诽谤世尊，指摘世尊，骂詈世尊，应诽谤瞿昙，应指瞿昙，应堕瞿昙，语世尊曰：“有一梵志，名弗袈裟罗，姓直清净化，彼作是说：‘若有沙门、梵志，于人上法有知有见，现我得者，我闻是已，便大笑之，意不相可，虚妄不真，亦不如法。云何人生人中，自说得人上法？若于人上法言我知我见者，此事不然。'”

于是，世尊便作是念：“鹦鹉摩纳都题子瞋恚于我，憎嫉不悦，诽谤于我，指摘于我，骂詈于我，应诽谤瞿昙，应指瞿昙，应堕瞿昙，而语我曰：‘瞿昙，有梵志名弗袈娑罗，姓直清净化，彼作是说：“若有沙门、梵志，于人上法有知有见，现我得者，我闻是已，便大笑之，意不相可，虚妄不真，亦不如法。云何人生人中，自说得人上法？若于人上法言我知我见者，此事不然。”'”

世尊知已，告曰：“摩纳，梵志弗袈裟裟罗姓直清净化，彼知一切沙门、梵志心之所念，然后作是说：‘若有沙门、梵志，于人上法有知有见，现我得者，我闻是已，便大笑之，意不相可，虚妄不真，亦不如法。云何人生人中，自说得人上法？若于人上法言我知我见者，此事不然'耶？”

鹦鹉摩纳答曰：“瞿昙，梵志弗袈裟娑罗姓直清净化，自有一婢，名曰不尼，尚不能知心之所念，况复欲知一切沙门、梵志心之所念耶？若使知者，终无是处。”

世尊告曰：“犹人生盲，彼作是说：‘无黑白色，亦无见黑白色者；无好恶色，亦无见好恶色；无长短色，亦无见长短色；无近远色，亦无见近远色；无粗细色，亦无见粗细色。我初不见不知，是故无色。'彼生盲人作如是说，为真实耶？”

鹦鹉摩纳答世尊曰：“不也，瞿昙。所以者何？有黑白色，亦有见黑白色者；有好恶色，亦有见好恶色；有长短色，亦有见长短色；有近远色，亦有见近远色；有粗细色，亦有见粗细色。若言：‘我初不见不知，是故无色。'彼生盲人作是说者，为不真实。”

“摩纳，梵志弗袈裟裟罗姓直清净化，彼所说者，非如生盲无目人耶？”

鹦鹉摩纳答世尊曰：“如盲，瞿昙。”

世尊告曰：“摩纳，于意云何？若昔有梵志寿终命过，诵持经书，流布经书，诵习典经，谓商伽梵志、生闻梵志、弗袈裟裟罗梵志及汝父都题，若彼所说，可不可、有真无真、有高有下耶？”

鹦鹉摩纳答世尊曰：“若昔有梵志寿终命过，诵持经书，流布经书，诵习典经，谓商伽梵志、生闻梵志、弗袈裟裟罗梵志及我父都题，彼所说者，于我意者，欲令可，莫令不可；欲令真，莫令不真；欲令高，莫令下。”

彼时，世尊问曰：“摩纳，梵志弗袈裟裟罗姓直清净化，彼所说者，非为不可、无有可耶？非为不真、无有真耶？非为至下、无有高耶？”

鹦鹉摩纳答世尊曰：“实尔，瞿昙。”

“复次，摩纳，有五法作障碍，作覆盖，作盲无目，能灭智慧，唐自疲劳，不得涅槃。云何为五？摩纳，欲第一法作障碍，作覆盖，作盲无目，能灭智慧，唐自疲劳，不得涅槃。摩纳，恚、身见、戒取，疑第五法作障碍，作覆盖，作盲无目，能灭智慧，唐自疲劳，不得涅槃。摩纳，于意云何？为此五法之所障碍，覆盖阴缠，彼若欲观自义，观他义，观俱义，及知一切沙门、梵志心之所念者，终无是处。摩纳，梵志弗袈裟裟罗姓直清净化，为欲所染，欲所秽染，欲触欲猗，著于欲，入于欲中，不见灾患，不知出要而行于欲，彼为此五法之所障碍，覆盖阴缠，彼若欲观自义，观他义，观俱义，及知一切沙门、梵志心之所念者，终无是处。

“复次，摩纳，有五欲功德，爱念意乐，彼有爱色欲相应，甚可于乐。云何为五？目知色，耳知声，鼻知香，舌知味，身知触。摩纳，于意云何？众生因此五欲功德故，生乐生喜，不复是过耶？”

鹦鹉摩纳白世尊曰：“如是，瞿昙。”

世尊问曰：“摩纳，于意云何？若因草木而燃火，及离草木而燃火？何者光焰最上、最妙、最胜耶？”

鹦鹉摩纳白曰：“瞿昙，若离草木而燃火者，终无是处，唯有如意足力。瞿昙，若离草木而燃火者，彼光焰最上、最妙、最胜。”

世尊告曰：“如是！如是！摩纳，若离草木而燃火者，终无是处，唯有如意足力。若离草木而无火者，彼光焰最上、最妙、最胜。我今假说，摩纳，如因草木而燃火者，如是众生所生喜乐，谓因欲、恶不善之法，不得舍乐及于止息。摩纳，如离草木而燃火者，如是众生所生舍乐，谓因离欲，从诸善法而得舍乐及于止息。”

世尊告曰：“摩纳，于意云何？有一梵志作斋行施，或从东方有刹利童子来，彼作是说：‘我于其中得第一座、第一澡水、第一饮食。'彼于其中不得第一座、第一澡水、第一饮食，便生怨恨而怀憎嫉。或从南方有梵志童子来，彼作是说：‘我于其中得净妙食。'彼于其中不得净妙食，便生怨恨而怀憎嫉。或从西方有居士童子来，彼作是说：‘我于其中得丰饶食。'彼于其中不得丰饶食，便生怨恨面怀憎嫉。或从北方有工师童子来，彼作是说：‘我于其中得丰足食。'彼于其中不得丰足食，便生怨恨而怀憎嫉。摩纳，彼诸梵志行如是施，施设何等报耶？”

鹦鹉摩纳白曰：“瞿昙，梵志不如是心行于布施，使他生怨恨而怀憎嫉。瞿昙，当知梵志以悯伤心而行于施，以悯伤心而行施已，便得大福。”

世尊告曰：“摩纳，梵志非为施设第六法，有大果报，有大功德，作福得善耶？”

鹦鹉摩纳答世尊曰：“如是，瞿昙。”

世尊问曰：“摩纳，若有梵志施设五法，有大果报，有大功德，作福得善，汝见此法多在何处？为在家耶？为出家学道耶？”

鹦鹉摩纳答曰：“瞿昙，若有梵志施设五法，有大果报，有大功德，作福得善，我见此法多在出家学道，非在家也。所以者何？在家者多事，多有所作，多有结恨，多有憎诤，彼不能得守护诚谛。瞿昙，出家学道者少事，少有所作，少有结恨，少有憎诤，彼必能得守护诚谛。瞿昙，彼诚谛者，我见多在出家学道，非在家也。所以者何？在家者多事，多有所作，多有结恨，多有憎诤，彼不得行施，不得诵习，不得行苦行，不得行梵行。瞿昙，出家学道者少事，少有所作，少有结恨，少有憎诤，彼得行施，彼得诵习，得行苦行，得行梵行。瞿昙，行梵行者，我见此法多在出家学道，非在家也。”

世尊告曰：“摩纳，若有梵志施设五法，有大果报，有大功德，作福得善者，我说是从心起。云何为心？若心无结、无怨、无恚、无诤，为修彼故。摩纳，于意云何？若有比丘守护诚谛者，彼因守护诚谛故，得喜得悦。摩纳，若有喜及悦，善善相应，我说是从心起。云何为心？若心无结、无怨、无恚、无诤，为修彼故，如是彼得行施，彼得诵习，得行苦行，得行梵行。彼因行梵行故，得喜得悦。摩纳，若有喜及悦，善善相应，我说是从心起。云何为心？若心无结、无怨、无恚、无诤，彼心与慈俱，遍满一方成就游。如是二三四方，四维上下，普周一切，心与慈俱，无结、无怨、无恚、无诤，极广甚大，无量善修，遍满一切世间成就游。如是悲、喜心与舍俱，无结、无怨、无恚、无诤，极广甚大，无量善修，遍满一切世间就游。

“摩纳，犹如有人善吹于螺，彼若有方未曾闻者，彼于夜半而登高山，极力吹螺，出微妙声，遍满四方。如是比丘心与慈俱，遍满一方成就游。如是二三四方，四维上下，普周一切，心与慈俱，无结、无怨、无恚、无诤，极广甚大，无量善修，遍满一切世间成就游。如是悲、喜心与舍俱，无结、无怨、无恚、无诤，极广甚大，无量善修，遍满一切世间成就游。摩纳，于意云何？若有求天，要求天上故，便行贪伺相应心，令我作天及余天。若有求天，要求天上故，便无结、无怨、无恚、无诤，无量极广善修，心定意解，遍满成就游，令我作天及余天。汝观于彼，谁得作天及余天耶？”

鹦鹉摩纳答曰：“瞿昙，若此求天，要求天上故，便无结、无怨、无恚、无诤，无量极广善修，心定意解，遍满成就游者，我观于彼必得作天或余天也。”

世尊问曰：“摩纳，于意云何？若有求梵天，要求梵天上故，便行贪伺相应心，令我作梵天及余梵天。若有求梵天，要求梵天上故，便无结、无怨、无恚、无诤，无量极广善修，心定意解，遍满成就游，令我作梵天及余梵天。汝观于彼，谁得作梵天及余梵天耶？”

鹦鹉摩纳答曰：“瞿昙，若此求梵天，要求梵天上故，便无结、无怨、无恚、无诤，无量极广善修，心定意解，遍满成就游者，我观于彼得作梵天或余梵天。”

鹦鹉摩纳问曰：“瞿昙，知梵道迹耶？”

世尊告曰：“摩纳，我今问汝，随所解答。摩纳，于意云何？那罗歌逻村去此众不远耶？”

鹦鹉摩纳答曰：“不远。”

世尊告曰：“摩纳，于意云何？汝于此众告一人曰：‘汝往至彼那罗歌逻村，到便即还。'彼受汝教，速疾往至那罗歌逻村，到便即还。彼往返已，汝问道路，谓于那罗歌逻村往返出入事，彼人宁住不能答耶？”

鹦鹉摩纳答世尊曰：“不也，瞿昙。”

世尊告曰：“摩纳，彼人往返于那罗歌逻村，问道路事，乃可得住而不能答；若问如来、无所著、等正觉梵道迹者，终不暂住而不能答。”

鹦鹉摩纳白世尊曰：“沙门瞿昙，无著天祠，此事具足，谓问梵道迹能速答故。世尊，我已知。善逝，我已解。世尊，我今自归于佛、法及比丘众，惟愿世尊受我为优婆塞！从今日始，终身自归，乃至命尽。”

佛说如是，鹦鹉摩纳闻佛所说，欢喜奉行。

--------------

** 第38卷 梵志品.须闲提经第十二

我闻如是：一时，佛游拘楼瘦，在婆罗婆第一静室，坐于草座。

尔时，世尊过夜平旦，著衣持钵，入剑摩瑟昙次第乞食；食讫，中后还举衣钵，澡洗手足，以尼师檀著于肩上，往诣一林，至昼行处。尔时，世尊入于彼林，至一树下，敷尼师檀，结跏趺坐。

于是，须闲提异学中后彷徉，往诣婆罗婆第一静室。须闲提异学遥见婆罗婆第一静室有布草座一胁卧处，似师子卧，似沙门卧，似梵行卧。须闲提异学见已，问曰：“婆罗婆第一静室，谁有此草座一胁卧处，似师子卧，似沙门卧，似梵行卧？”

婆罗婆梵志答曰：“须闲提，有沙门瞿昙释种子，舍释宗族，剃除须发，著袈裟衣，至信、舍家、无家、学道，觉无上正尽觉。彼第一静室有此草座一胁卧处，似师子卧，似沙门卧，似梵行卧。”

须闲提异学语曰：“婆罗婆，我今不可见见，不可闻闻，谓我见沙门瞿昙卧处。所以者何？彼沙门瞿昙败坏地，败坏地者，无可用也。”

婆罗婆语曰：“须闲提，汝不应以此事骂彼沙门瞿昙。所以者何？彼沙门瞿昙多有慧，刹利慧、梵志慧、居土慧、沙门慧，若说慧者皆得圣智。须闲提，我欲以此义向彼沙门瞿昙说，为可尔不？”

须闲提语曰：“婆罗婆，若欲说者，则随汝意，我无所违。婆罗婆，若见沙门瞿昙者，我亦说此义。所以者何？彼沙门瞿昙败坏地，败坏地者，无可用也。”

尔时，世尊在昼行处，以净天耳出过于人，闻娑罗婆梵志与须闲提异学共论此事。世尊闻已，则于晡时从宴坐起，往诣婆罗婆梵志第一静室，于草座上敷尼师檀，结跏趺坐。婆罗婆梵志遥见世尊在树林间，端正姝好，犹星中月，光耀暐晔，晃若金山，相好具足，威神巍巍，诸根寂定，无有蔽碍，成就调御，息心静默；见已，进前往诣佛所，共相问讯，却坐一面。

世尊问曰：“婆罗婆，与须闲提异学共论此草座处耶？”

婆罗婆梵志答世尊曰：“如是，瞿昙，我亦欲以此事向沙门瞿昙说，然沙门瞿昙未说已自知。所以者何？以如来、无所著、等正觉故。”

世尊与婆罗婆梵志共论此事，须闲提异学于后彷徉，往诣婆罗婆第一静室。世尊遥见须闲提异学来已，而作是说：“须闲提，不调御眼根，不密守护而不修者，必受苦报。彼于沙门瞿昙善自调御，善密守护而善修者，必得乐报。须闲提，汝因此故，说沙门瞿昙败坏地，败坏地者，无可用耶？”

须闲提异学答世尊曰：“如是，瞿昙。”

“须闲提，如是耳、鼻、舌、身根，不调御意根，不密守护而不修者，必受苦报。彼于沙门瞿昙善自调御，善密守护而善修者，必得乐报。须闲提，汝因此故，说沙门瞿昙败坏地，败坏地者，无可用耶？”

须闲提异学答世尊曰：“如是，瞿昙。”

世尊问曰：“须闲提，于意云何？若人本未出家学道，彼眼知色，爱念意乐，可欲相应。彼于后时舍眼知色，剃除须发，著袈裟衣，至信、舍家、无家、学道。彼眼知色，集、灭、味、患、出要见如真，内息心游行。彼若见人未离色欲，为色爱所食，为色热所热。彼眼知色，爱念意乐，可欲相应，行时见已，不称彼、不乐彼。须闲提，于意云何？若有此乐，因爱因色，乐此乐时，薄贱故不称彼，薄贱故不乐彼。须闲提，宁可于彼有所说耶？”

答世尊曰：“不也，瞿昙。”

“须闲提，于意云何？若人本未出家学道，如是耳知声，鼻知香，舌知味，身知触，爱念意乐，可欲相应。彼于后时，舍身知触，剃除须发，著袈裟衣，至信、舍家、无家、学道。彼身知触，集、灭、味、患、出要见如真，内息心游行。彼若见人未离触欲，为触爱所食，为触热所热。彼身知触，爱念意乐，可欲相应，行时见已，不称彼，不乐彼。须闲提，于意云何？若有见此乐，因爱因触，乐此乐时，薄贱故不称彼，薄贱故不乐彼。须闲提，宁可于彼有所说耶？”

答世尊曰：“不也，瞿昙。”

世尊问曰：“须闲提，于意云何？若人本未出家学道，五欲功德爱念意乐，可欲相应。彼于后时，舍五欲功德，剃除须发，著袈裟衣，至信、舍家、无家、学道。彼五欲功德，集、灭、味、患、出要见如真，内息心游行。彼若见人未离欲，为欲爱所食，为欲热所热，五欲功德爱念意乐，可欲相应，行时见已，不称彼，不乐彼。须闲提，于意云何？若有此乐，因欲因欲爱，乐此乐时，簿贱故不称彼，簿贱故不乐彼。须闲提，宁可于彼有所说耶？”

答世尊曰：“不也，瞿昙。”

“须闲提，我本未出家学道时，得五欲功德，易不难得，爱念意乐，可欲相应。我于后时，舍五欲功德，剃除须发，著袈裟衣，至信、舍家、无家、学道。彼五欲功德，集、灭、味、患、出要见如真，内息心游行。我见人未离欲，为欲爱所食，为欲热所热，五欲功德，爱念意乐，可欲相应，行时见已，我不称彼，我不乐彼。须闲提，于意云何？若有此乐，因欲因欲爱，乐此乐时，薄贱故我不称彼，薄贱故我不乐彼。须闲提，宁可于我有所说耶？”

答世尊曰：“不也，瞿昙。”

世尊告曰：“须闲提，犹如居士、居士子，极大富乐，资财无量，多诸畜牧、封户、食邑，诸生活具种种丰饶。彼得五欲，易不难得，彼成就身妙行，口、意妙行；临死之时，不乐舍五欲功德，身坏命终，后升善处，得生天上，具足行五欲功德。须闲提，此天及天子宁当舍天五欲功德，乐人间欲，欢喜念耶？”

答世尊曰：“不也，瞿昙。所以者何？人间欲者，臭处不净，意甚秽恶而不可向，憎诤极苦。瞿昙，于人间欲，天欲最上、最妙、最胜。若彼天及天子舍于天上五欲功德，乐人间欲，欢喜念者，终无是处。”

“如是，须闲提，我断人间欲，度于天欲，剃除须发，著袈裟衣，至信、舍家、无家、学道。彼五欲功德，集、灭、味、患、出要见如真，内息心游行。我见人未离欲，为欲爱所食，为欲热所热，五欲功德爱念意乐，可欲相应，行时见已，我不称彼，我不乐彼。须闲提，于意云何？若有此乐，因欲因欲爱，乐此乐时，薄贱故我不称彼，薄贱故我不乐彼。须闲提，宁可于我有所说耶？”

答世尊曰：“不也，瞿昙。”

世尊告曰：“须闲提，犹人病癞，身体烂熟，为虫所食，爪摘疮开，临火坑炙。须闲提，于意云何？若病癞人身体烂熟，为虫所食，爪摘疮开，临火坑炙；如是宁得除病有力，不坏诸根，为脱癞病，身体完健，平复如故，还本所耶？”

答世尊曰：“不也，瞿昙。所以者何？若病癞人身体烂熟，为虫所食，爪摘疮开，临火坑炙，如是更生疮转增多，本疮转大，然彼反以癞疮为乐。”

“须闲提，如病癞人身体烂熟，为虫所食，爪摘疮开，临火坑炙；如是更生疮转增多，本疮转大，然彼反以癞疮为乐。须闲提，如是众生未离欲，为欲爱所食，为欲热所热而行于欲。须闲提，如是众生未离欲，为欲爱所食，为欲热所热而行于欲；如是欲转增多，欲爱转广，然彼反以欲爱为乐。彼若不断欲，不离欲爱，内息心，已行、当行、今行者，终无是处。所以者何？此非道理，断欲、离欲爱，谓行于欲。”

世尊告曰：“须闲提，犹王及大臣，得五所欲，易不难得。彼若不断欲，不离欲爱，内息心，已行、当行、今行者，终无是处。所以者何？此非道理，断欲、离欲爱，谓行于欲。如是，须闲提，众生未离欲，为欲爱所食，为欲热所热而行于欲。须闲提，若众生未离欲，为欲爱所食，为欲热所热而行欲者；如是欲转增多，欲爱转广，然彼反以欲爱为乐。彼若不断欲，不离欲爱，内息心，已行、当行、今行者，终无是处。所以者何？此非道理，断欲、离欲爱，谓行于欲。

“须闲提，犹病癞人身体烂熟，为虫所食，爪摘疮开，临火坑炙。有人为彼怜念悯伤，求利及饶益，求安隐快乐，与如其像好药；与如其像好药已，除病得力，不坏诸根，已脱癞病，身体完健，平复如故，更还本所。彼若见人有癞病者，身体烂熟，为虫所食，以爪摘疮开，临火坑炙。须闲提，彼人见已，宁复意乐称誉喜耶？”

答世尊曰：“不也，瞿昙。所以者何？有病须药，无病不须。”

“须闲提，于意云何？若彼癞人除病得力，不坏诸根，已脱癞病，身体完健，平复如故，更还本所。有二力士，强捉彼人临火坑炙，彼于其中慞惶回避，身生重热。须闲提，于意云何？此火坑者，于今更热，大苦可患，甚于本耶？”

答世尊曰：“不也，瞿昙。其本病癞，身体烂熟，为虫所食，爪摘疮开，临火坑炙；彼于苦大乐更乐想，其心迷乱，有颠倒想。瞿昙，彼人于今除病得力，不坏诸根，已脱癞病，身体完健，平复如故，更还本所；彼于苦大苦更乐想，其心泰然，无颠倒想。”

“须闲提，如病癞人身体烂熟，为虫所食，爪摘疮开，临火坑炙；彼于苦大乐更乐想，其心迷乱，有颠倒想。如是，须闲提，众生不离欲，为欲爱所食，为欲热所热而行于欲；彼于苦欲有乐欲想，其心迷乱，有颠倒想。须闲提，犹如彼人除病得力，不坏诸根，已脱癞病，身体完健，平复如故，更还本所；彼于苦大苦更乐想，其心泰然，无颠倒想。如是，须闲提，我于苦欲有苦欲想，得如真实，无颠倒想。所以者何？须闲提，过去时欲不净臭处，意甚秽恶而不可向，憎诤苦更触；未来、现在欲亦不净臭处，意甚秽恶而不可向，憎诤苦更触。须闲提，如来、无所著、等正觉说无病第一利，涅槃第一乐。”

须闲提异学白世尊曰：“瞿昙，我亦曾从耆旧尊德长老久学梵行所，闻无病第一利，涅槃第一乐。”

世尊问曰：“须闲提，若汝曾从耆旧尊德长老久学梵行所，闻无病第一利，涅槃第一乐。须闲提，何者无病？何者涅槃耶？”

于是，须闲提异学身即是病、是痈、是箭、是蛇、是无常、是苦、是空、是非神，以两手抆摸而作是说：“瞿昙，此是无病，此是涅槃。”

世尊语曰：“须闲提，犹如生盲，从有目人闻其所说：‘白净无垢！白净无垢！'彼闻此已，便求白净。有谄诳人而不为彼求利及饶益，求安隐快乐，则以垢腻不净之衣，持往语曰：‘汝当知之！此是白净无垢之衣，汝以两手敬受被身。'彼盲子喜，即以两手敬受被身而作是说：‘白净无垢！白净无垢！'须闲提，彼人为自知说？为不知说？为自见说？为不见说？”

须闲提异学答曰：“瞿昙，如是说者，实不知见。”

世尊语曰：“如是，须闲提，如盲无目，身即是病、是痈、是箭、是蛇、是无常、是苦、是空、是非神，以两手抆摸而作是说：‘瞿昙，此是无病，此是涅槃。'须闲提，汝尚不识于无病，何况知见于涅槃耶？言知见者，终无是处。须闲提，如来、无所著、等正觉说：

<div class="poem">

‘无病第一利，涅槃第一乐，\\
诸道八正道，往安隐甘露。'

</div>

“彼众多人并共闻之，众多异学闻此偈已，展转相传，不能知义。彼既闻已，而欲求教，彼并愚痴，还相欺诳。彼自现身四大之种，从父母生，饮食所长，常覆按摩澡浴，强忍、破坏、磨灭、离散之法，然见神受神，缘受则有，缘有则生，缘生则老死，缘老死则愁戚啼哭、忧苦懊恼，如是此生纯大苦阴。”

于是，须闲提异学即从座起，偏袒著衣，叉手向佛，白曰：“瞿昙，我今极信沙门瞿昙，惟愿瞿昙善为说法，令我得知此是无病，此是涅槃。”

世尊告曰：“须闲提，若汝圣慧眼未净者，我为汝说无病、涅槃，终不能知，唐烦劳我。须闲提，犹生盲人，因他往语：‘汝当知之！此是青色，黄、赤、白色。'须闲提，彼生盲人颇因他说，知是青色、黄、赤、白色耶？”

答世尊曰：“不也，瞿昙。”

“如是，须闲提，若汝圣慧眼未净者，我为汝说无病、涅槃，终不能知，唐烦劳我。须闲提，我为汝说如其像妙药，令未净圣慧眼而得清净。须闲提，若汝圣慧眼得清净者，汝便自知此是无病，此是涅槃。须闲提，犹生盲人，有诸亲亲为彼慈悯，求利及饶益，求安隐快乐故，为求眼医。彼眼医者与种种治，或吐或下，或灌于鼻，或复灌下，或刺其脉，或令泪出。须闲提，倘有此处，得净两眼。须闲提，若彼两眼得清净者，则便自见此是青色，黄、赤、白色。见彼垢腻不净之衣，便作是念：‘彼即怨家，长夜则以垢腻之衣欺诳于我。'便有憎心。须闲提，此人倘能杀害于彼。如是，须闲提，我为汝说如其像妙药，令未净圣慧眼而得清净。须闲提，若汝圣慧眼得净者，汝便自知此是无病，此是涅槃。

“须闲提，有四种法，未净圣慧眼而得清净。云何为四？亲近善知识，恭敬、承事，闻善法，善思惟，趣向法次法。须闲提，汝当如是学，亲近善知识，恭敬、承事，闻善法，善思惟，趣向法次法。须闲提，当学如是。须闲提，汝亲近善知识，恭敬承事已，便闻善法；闻善法已，便善思惟；善思惟已，便趣向法次法；趣向法次法已，便知此苦如真，知此苦集、知此苦灭、知此苦灭道如真。

“云何知苦如真？谓生苦、老苦、病苦、死苦、怨憎会苦、爱别离苦、所求不得苦、略五盛阴苦，如是知苦如真。云何知苦集如真？谓此爱当受未来有，与喜欲俱，愿彼彼有，如是知苦集如真。云何知苦灭如真？谓此爱当受未来有，与喜欲俱，愿彼彼有灭、无余、断、舍、吐、尽、无欲、没、息止，如是知苦灭如真。云何知苦灭道如真？谓八支圣道，正见乃至正定，是谓为八，如是知苦灭道如真。”

说此法已，须闲提异学远尘离垢，诸法法眼生。于是，须闲提异学见法得法，觉白净法，断疑度惑，更无余尊，不复从他，无有犹豫，已住果证，于世尊法得无所畏；即从座起，稽首佛足，白曰：“世尊，愿令我得出家学道，受具足，得比丘。”

世尊告曰：“善来比丘，修行梵行。”

须闲提异学即是出家学道，受具足，得比丘。须闲提出家学道，受具足，知法已，至得阿罗诃。

佛说如是，尊者须闲提闻佛所说，欢喜奉行。

--------------

** 第39卷 梵志品.婆罗婆堂经第十三

我闻如是：一时，佛游舍卫国，在东园鹿子母堂。

尔时，有二人婆私吒及婆罗婆梵志族，剃除须发，著袈裟衣，至信、舍家、无家、学道。诸梵志见已，极诃责数，甚急至苦，而语之曰：“梵志种胜，余者不如；梵志种白，余者皆黑；梵志得清净，非梵志不得清净；梵志梵天子，从彼口生，梵梵所化。汝等舍胜从不如，舍白从黑，彼秃沙门为黑所缚，断种无子，是故汝等所作大恶，极犯大过。”

尔时，世尊则于晡时从宴坐起，堂上来下，于堂影中露地经行，为诸比丘说甚深微妙法。尊者婆私吒遥见世尊则于晡时从宴坐起，堂上来下，于堂影中露地经行，为诸比丘说甚深微妙法。尊者婆私吒见已，语曰：“贤者婆罗婆，当知世尊则于晡时从宴坐起，堂上来下，于堂影中露地经行，为诸比丘说甚深微妙法。贤者婆罗婆，可共诣佛，或能因此从佛闻法。”

于是，婆私吒及婆罗婆即诣佛所，稽首作礼，从后经行。世尊回顾，告彼二人：“婆私吒，汝等二梵志舍梵志族，剃除须发，著袈裟衣，至信、舍家、无家、觉道。诸梵志见已，不大责数耶？”

彼即答曰：“唯然，世尊，诸梵志见已，极诃责数，甚急至苦。”

世尊问曰：“婆私吒，诸梵志见已，云何极诃责数，甚急至苦耶？”

答曰：“世尊，诸梵志见我等已，而作是说：‘梵志种胜，余者不如；梵志种白，余者皆黑；梵志得清净，非梵志不得清净；梵志梵天子，从彼口生，梵梵所化。汝等舍胜从不如，舍白从黑，彼秃沙门为黑所缚，断种无子，是故汝等所作大恶，极犯大过。'世尊，诸梵志见我等已，如是极诃责数，甚急至苦。”

世尊告曰：“婆私吒，彼诸梵志所说至恶，极自无赖。所以者何？谓彼愚痴，不善晓解，不识良田，不能自知，作如是说：‘我等梵志是梵天子，从彼口生，梵梵所化。'所以者何？婆私吒，我此无上明、行、作证，不说生胜，不说种姓，不说骄慢，彼可我意，不可我意，因坐因水，所学经书。婆私吒，若有婚姻者，彼应说生，应说种姓，应说骄慢，彼可我意，不可我意，因坐因水，所学经书。婆私吒，若有计生、计姓、计慢者，彼极远离于我无上明、行、作证。婆私吒，说生、说姓、说慢，彼可我意，不可我意，因坐因水，所学经书者，于我无上明、行、作证别。复次，婆私吒，谓有三种，令非一切人人共诤，杂善不善法，彼则为圣所称不称。云何为三？刹利种、梵志种、居士种。婆私吒，于意云何？刹利杀生、不与取、行邪淫、妄言，乃至邪见，居士亦然，非梵志耶？”

答曰：“世尊，刹利亦可杀生、不与取、行邪淫、妄言，乃至邪见，梵志、居士亦复如是。”

世尊问曰：“婆私吒，于意云何？梵志离杀、断杀、不与取、行邪淫、妄言，乃至离邪见，得正见，刹利、居士为不然耶？”

答曰：“世尊，梵志亦可离杀、断杀、不与取、行邪淫、妄言，乃至离邪见得正见，刹利、居士亦复如是。”

世尊问曰：“婆私吒，于意云何？若有无量恶不善法，是刹利、居士所行，非梵志耶？若有无量善法，是梵志所行，非刹利、居士耶？”

答曰：“世尊，若有无量恶不善法，彼刹利、居士亦可行，梵志亦复如是。若有无量善法，彼梵志亦可行，刹利、居士亦复如是。”

“婆私吒，若有无量恶不善法，一向刹利、居士行，非梵志者；若有无量善法，一向梵志行，非刹利、居士者。彼诸梵志可作是说：‘我等梵志是梵天子，从彼口生，梵梵所化。'所以者何？婆私吒，见梵志女始婚姻时，婚姻已后，见怀妊身时，怀妊身已后，见产生时，或童男，或童女。婆私吒，如是诸梵志亦如世法，随产道生，然彼妄言，谤梵天而作是说：‘我等梵志是梵天子，从彼口生，梵梵所化。'

“婆私吒，若族姓子、若干种姓、若干种名，舍苦干族，剃除须发，著袈裟衣，至信、舍家、无家，从我学道，应作是说：‘我等梵志是梵天子，从彼口生，梵梵所化。'所以者何？婆私吒，彼族姓子人我正法、律中，受我正法、律，得至彼岸，断疑度惑，无有犹豫，于世尊法得无所畏，是故彼应作是说：‘我等梵志是梵天子，从彼口生，梵梵所化。'婆私吒，彼梵天者，是说如来、无所著、等正觉。梵是如来，冷是如来。无烦无热，不离如者，是如来也。婆私吒，于意云何？诸释下意爱敬至重，供养奉事于波斯匿拘娑罗王耶？”

彼则答曰：“如是，世尊。”

世尊问曰：“婆私吒，于意云何？若诸释下意爱敬至重，供养奉事于波斯匿拘娑罗王，如是波斯匿拘娑罗王则于我身下意爱敬至重，供养奉事我耶？”

答世尊曰：“诸释下意爱敬至重，供养奉事于波斯匿拘娑罗王者，此无奇特。若波斯匿拘娑罗王下意爱敬至重，供养奉事于世尊者，此甚奇特！”

世尊告曰：“婆私吒，波斯匿拘娑罗王不如是意，而于我身下意爱敬至重，供养奉事于我：‘沙门瞿昙种族极高，我种族下；沙门瞿昙财宝甚多，我财宝少；沙门瞿昙形色至妙，我色不妙；沙门瞿昙有大威神，我威神小；沙门瞿昙有善智慧，我有恶智。'婆私吒，但波斯匿拘娑罗王爱敬于法，至重供养，为奉事故，而于我身下意爱敬至重，供养奉事于我。”

尔时，世尊告比丘曰：“婆私吒，有时此世皆悉败坏。此世坏时，若有众生生晃昱天，彼于其中妙色意生，一切支节诸根具足，以喜为食，自身光明，升于虚空，净色久住。

“婆私吒，有时此大地满其中水，彼大水上以风吹搅，结构为精，合聚和合，犹如熟酪，以抨抨乳，结构为精，合聚和合。如是，婆私吒，有时此大地满其中水，彼大水上以风吹搅，结构为精，合聚和合，从是生地味，有色香味。云何为色？犹如生酥及熟酥色。云何为味？如蜜丸味。

“婆私吒，有时此世还复成时，若有众生生晃昱天，寿尽、业尽、福尽命终，生此为人。生此间已，妙色意生，一切支节诸根具足，以喜为食，自身光明，升于虚空，净色久住。婆私吒，尔时，世中无有日月，亦无星宿，无有昼夜。无月、半月，无时无岁。

“婆私吒，当尔之时，无父无母，无男无女，又无大家，复无奴婢，唯等众生。于是，有一众生贪餮不廉，便作是念：‘云何地味？我宁可以指抄此地味尝。'彼时，众生便以指抄此地味尝。如是，众生既知地味，复欲得食。彼时，众生复作是念：‘何故以指食此地味，用自疲劳？我今宁可以手撮此地味食之。'彼时，众生便以手撮此地味食。于彼众生中复有众生，见彼众生各以手撮此地味食，便作是念：‘此实为善！此实为快！我等宁可亦以手撮此地味食。'时，彼众生即以手撮此地味食。若彼众生以手撮此地味食已，如是如是，身生转厚、转重、转坚，若彼本时有清净色，于是便灭，自然生暗。婆私吒，世间之法，自然有是。若生暗者，必生日月；生日月已，便生星宿；生星宿已，便成昼夜；成昼夜已，便有月、半月，有时、有岁。彼食地味，住世久远。

“婆私吒，若有众生食地味多者，便生恶色；食地味少者，便有妙色。从是知色有胜有如，因色胜如故，众生众生共相轻慢言：‘我色胜，汝色不如。'因色胜如而生轻慢及恶法故，地味便灭。地味灭已，彼众生等便共聚集，极悲啼泣而作是语：‘奈何地味！奈何地味！'犹如今人含消美物，不说本字，虽受持而不知义，此说观义亦复如是。婆私吒，地味灭后，彼众生生地肥，有色香味。云何为色？犹如生酥及熟酥色。云何为味？如蜜丸味。彼食此地肥，住世久远。

“婆私吒，若有众生食地肥多者，便生恶色；食地肥少者，便有妙色。从是知色有胜有如，因色胜如故，众生众生共相轻慢言：‘我色胜，汝色不如。'因色胜如而生轻慢及恶法故，地肥便灭。地肥灭已，彼众生等便共聚集，极悲啼泣而作是语：‘奈何地肥！奈何地肥！'犹如今人为他所责，不说本字，虽受持而不知义，此说观义亦复如是。婆私吒，地肥灭后，彼众生生婆罗，有色香味。云何为色？犹如昙华色。云何为味？如淖蜜丸味。彼食此婆罗，住世久远。

“婆私吒，若有众生食婆罗多者，便生恶色；食婆罗少者，便有妙色。从是知色有胜有如，因色胜如故，众生众生共相轻慢言：‘我色胜，汝色不如。'因色胜如而生轻慢及恶法故，婆罗便灭。婆罗灭已，彼众生等便共聚集，极悲啼泣而作是语：‘奈何婆罗！奈何婆罗！'犹如今人苦法所触，不说本字，虽受持而不知义，此说观义亦复如是。

“婆私吒，婆罗灭后，彼众生生自然粳米，白净无皮，亦无有䵃[kuàng]蒿，长四寸，朝刈暮生，暮刈朝生，熟有盐味，无有生气，众生食此自然粳米。如彼众生食此自然粳米已，彼众生等便生若干形，或有众生而生男形，或有众生而生女形。若彼众生生男女形者，彼相见已，便作是语：‘恶众生生！恶众生生！'

“婆私吒，恶众生生者，谓说妇人也。若彼众生生于男形及女形者，彼众生等则更相伺；更相伺已，眼更相视；更相视已，则更相染；更相染已，便有烦热；有烦热已，便相爱著；相爱著已，便行于欲。若见行欲，便以木石，或以杖块而打掷之，便作是语：‘咄！弊恶众生作非法事，云何众生共作是耶？'犹如今人迎新妇时，则以朴华散，或以华鬘垂，作如是言：‘新妇安隐！新妇安隐！'本所可憎，今所可爱。婆私吒，若有众生恶不净法，憎恶羞耻，怀惭愧者，彼便离众一日、二日至六、七日，半月、一月乃至一岁。婆私吒，若有众生欲得行此不净行者，彼便作家而作是说：‘此中作恶！此中作恶！'婆私吒，是谓初因初缘世中起家法，旧第一智，如法非不如法，如法人尊。

“于中有一懒惰众生，便作是念：‘我今何为日日常取自然粳米？我宁可并取一日食直耶？'彼便并取一日食米。于是，有一众生语彼众生曰：‘众生，汝来共行取米耶？'彼则答曰：‘我已并取，汝自取去。'彼众生闻已，便作是念：‘此实为善！此实为快！我亦宁可并取明日所食米耶？'彼便并取明日米来。复有一众生语彼众生曰：‘众生，汝来共行取米耶？'彼则答曰：‘我已并取明日米来，汝自取去。'彼众生闻已，便作是念：‘此实为善！此实为快！我今宁可并取宿日食米来耶？'时，彼众生即便并取七日米来。如彼众生自然粳米极取积聚，彼七粳米便生皮䵃[kuàng]，刈至七日亦生皮䵃[kuàng]，随所刈处，即不复生。

“于是，彼众生便共聚集，极悲啼泣，作如是语：‘我等生恶不善之法，谓我曹等储畜宿米。所以者何？我等本有妙色意生，一切支节诸根具足，以喜为食，自身光明，升于虚空，净色久住。我等生地味，有色香味。云何为色？犹如生酥及熟酥色。云何为味？如蜜丸味。我等食地味，住世久远。我等若食地味多者，便生恶色；食地味少者，便有妙色。从是知色有胜有如，因色胜如故，我等各各共相轻慢言：我色胜，汝色不如。因色胜如而生轻慢及恶法故，地味便灭。地味灭后，我等生地肥，有色香味。云何为色？犹如生酥及熟酥色。云何为味？如蜜丸味。我等食地肥，住世久远。我等若食地肥多者，便生恶色；食地肥少者，便有妙色。从是知色有胜有如，因色胜如故，我等各各共相轻慢言：我色胜，汝色不如。因色胜如而生轻慢及恶法故，地肥便灭。地肥灭后，我等生婆罗，有色香味。云何为色？犹如昙华色。云何为味？如淖蜜丸味。我等食婆罗，住世久远。我等若食婆罗多者，便生恶色；食婆罗少者，便有妙色。从是知色有胜有如，因色胜如故，我等各各共相轻慢言：我色胜，汝色不如。因色胜如而生轻慢及恶法故，婆罗便灭。婆罗灭后，我等生自然粳米，白净无皮，亦无有䵃[kuàng]蒿，长四寸，朝刈暮生，暮刈朝生，熟有盐味，无有生气，我等食彼自然粳米。如我等自然粳米，极取积聚，彼宿粳米便生皮䵃[kuàng]，刈至七日，亦生皮䵃[kuàng]，随所刈处，即不复生。我等宁可造作田种，立标榜耶？'

“于是，众生等造作田种，竖立标榜。于中有一众生自有稻谷，而入他田窃取他稻。其主见已，便作是语：‘咄！咄！弊恶众生，云何作是？汝自有稻，而入他田窃取他稻。汝今可去，后莫复作！'然彼众生复至再三窃取他稻，其主亦至再三见已，便以拳叉牵诣众所，语彼众曰：‘此一众生自有稻谷，而入我田窃取我稻。'然彼一众生亦语众曰：‘此一众生以拳叉我牵来诣众。'

“于是，彼诸众生共聚集会，极悲啼泣而作是语：‘我等生恶不善之法，谓守田也。所以者何？因守田故，便共诤讼，有失有尽，有相道说，有拳相叉。我等宁可于其众中举一端正形色，极妙最第一者，立为田主。若可诃者，当令彼诃；若可摈者，当令彼摈。若我曹等所得稻谷，当以如法输送与彼。'于是，彼众生中，若有端正形色，极妙最第一者，众便共举，立为田主。若可诃者，彼便诃责；若可摈者，彼便摈弃。若有稻者，便以如法输送与彼是田主，是田主谓之刹利也，令如法乐众生，守护行戒是王，是王谓之王也。婆私吒，是谓初因初缘世中刹利种，旧第一智，如法非不如法，如法人尊。

“于是，彼异众生以守为病，以守为痈，以守为箭刺，便弃舍守，依于无事，作草叶屋而学禅也。彼从无事，朝朝平旦入村邑王城而行乞食。彼多众生见便施与，恭敬尊重，而作是语：‘此异众生以守为病，以守为痈，以守为箭刺，便弃舍守，依于无事，作草叶屋而学禅也。'此诸尊舍害、恶不善法是梵志，是梵志谓之梵志也。

“彼众生学禅不得禅，学苦行不得苦行，学远离不得远离，学一心不得一心，学精进不得精进，便舍无事，还村邑王城，作四柱屋，造立经书。彼多众生见如是已，便不复施与、恭敬、尊重，而作是语：‘此异众生本以守为病，以守为痈，以守为箭剌，便弃舍守，依于无事，作草叶屋，而学于禅不能得禅，学苦行不得苦行，学远离不得远离，学一心不得一心，学精进不得精进；便舍无事，还村邑王城，作四柱屋，造立经书。'此诸尊等更学博闻，不复学禅是博闻，是博闻谓之博闻。婆私吒，是谓初因初缘世中有梵志种，旧第一智，如法非不如法，如法人尊。

“于是，彼异众生各各诣诸方而作田业，是各各诸方而作田业，是各各诸方而作田业，谓之鞞舍。婆私吒，是谓初因初缘世中有鞞舍种，旧第一智，如法非不如法，如法人尊。

“婆私吒，世中起此三种姓已，便知有第四沙门种也。云何世中有此三种姓已，便知有第四沙门种耶？于刹利族姓之子，能自诃责恶不善法，自厌憎恶恶不善法，剃除须发，著袈裟衣，至信、舍家、无家、学道，而作是念：‘我当作沙门行于梵行。'便作沙门行于梵行。如是梵志种族、鞞舍种族族姓之子，亦自诃责恶不善法，自厌憎恶恶不善法，剃除须发，著袈裟衣，至信、舍家、无家、学道，亦作是念：‘我当作沙门行于梵行。'便作沙门行于梵行。婆私吒，如是世中起此三种姓已，便知有第四沙门种也。

“婆私吒，我今广说此三种姓。云何广有此三种耶？刹利种族族姓之子身行不善法，口、意行不善法，彼身坏命终，一向受苦。如是梵志种族、鞞舍种族族姓之子身行不善法，口、意行不善法，彼身坏命终，一向受苦。婆私吒，刹利种族族姓之子身行善法，口、意行善法，彼身坏命终，一向受乐。如是梵志种族、鞞舍种族族姓之子身行善法，口、意行善法，彼身坏命终，一向受乐。婆私吒，刹利种族族姓之子身行二行及与护行，口、意行二行及与护行，彼身坏命终，受于苦乐。如是梵志种族、鞞舍种族族姓之子身行二行及与护行，口、意行二行及与护行，彼身坏命终，受于苦乐。

“婆私吒，刹利种族族姓之子修七觉法，善思善观，彼如是知、如是见，欲漏心解脱，有漏、无明漏心解脱；解脱已，便知解脱：生已尽，梵行已立，所作已办，不更受有，知如真。如是，梵志种族、鞞舍种族族姓之子修七觉法，善思善观，彼如是知、如是见，欲漏心解脱，有漏、无明漏心解脱；解脱已，便知解脱：生已尽，梵行已立，所作已办，不更受有，知如真。婆私吒，如是此三种广分别也。梵天帝主说此偈曰：

<div class="poem">

‘刹利二足尊，谓有种族姓，\\
求学明及行，彼为天人称。'

</div>

“婆私吒，梵天帝主善说此偈，非不善也；善歌讽诵，非不善也，善咏语言，非不善也。谓如是说：

<div class="poem">

‘刹利二足尊，谓有种族姓，\\
求学明及行，彼为天人称。'

</div>

“所以者何？我亦如是说：刹利二足尊，谓有种族姓，求学明及行，彼为天人称。”

佛说如是，尊者婆私吒、婆罗婆等，及诸比丘闻佛所说，欢喜奉行。

--------------

** 第39卷 梵志品.须达哆经第十四

我闻如是：一时，佛游舍卫国，在胜林给孤独园。

尔时，须达哆居士往诣佛所，稽首作礼，却坐一面。

世尊问曰：“居士家颇行施耶？”

须达哆居士答曰：“唯然，世尊，家行布施，但为至粗，不能好也，糠饭麻羹，姜菜一片。”

世尊告曰：“居士，若施粗食及施妙食，俱得报耳！居士，若行粗施，不信施、不故施、不自手施、不自往施、不思惟施、不由信施、不观业果报施者，当观如是受报：心不欲得好家，不欲得好乘，不欲得好衣被，不欲得好饮食，不欲得好五欲功德。所以者何？以不至心故行施也。居士，当知受报如是。居士，若行粗施，信施、故施、自手施、自往施、思惟施、由信施、观业果报施者，当观如是受报：心欲得好家，欲得好乘，欲得好衣被，欲得好饮食，欲得好五欲功德。所以者何？以其至心故行施也。居士，当知受报如是。

“居士，若行妙施，不信施、不故施、不自手施、不自往施、不思惟施、不由信施、不观业果报施者，当观如是受报：心不欲得好家，不欲得好乘，不欲得好衣被，不欲得好饮食，不欲得好五欲功德。所以者何？以不至心故行施也。居士，当知受报如是。居士，若行妙施，信施、故施、自手施、自往施、思惟施、由信施、观业果报施者，当观如是受报：心欲得好家，欲得好乘，欲得好衣被，欲得好饮食，欲得好五欲功德。所以者何？以其至心故行施也。居士，当知受报如是。

“居士，昔过去时有梵志大长者，名曰随蓝，极大富乐，资财无量，封户食邑多诸珍宝，畜牧产业不可称计，彼行布施其像如是：八万四千金钵盛满碎银，行如是大施；八万四千银钵盛满碎金，行如是大施；八万四千金钵盛满碎金，行如是大施；八万四千银钵盛满碎银，行如是大施；八万四千象，庄校严饰，白络覆上，行如是大施；八万四千马，庄校严饰，白络金合霏那，行如是大施；八万四千牛，衣绳衣覆，构之皆得一斛乳汁，行如是大施；八万四千女，姿容端正，睹者欢悦，众宝璎珞，严饰具足，行如是大施，况复其余食啖含消！

“居士，若梵志随蓝行如是大施，若复有施满阎浮场凡夫食者，此于彼施为最胜也。

“居士，若梵志随蓝行如是大施，及施满阎浮场凡夫人食，若复有施一须陀洹食者，此于彼施最为胜也。

“居士，若梵志随蓝行如是大施，及施满阎浮场凡夫人食，施百须陀洹食，若复有施一斯陀含食者，此于彼施为最胜也。

“居士，若梵志随蓝行如是大施，及施满阎浮场凡夫人食，施百须陀洹、百斯陀含食，若复有施一阿那含食者，此于彼施为最胜也。

“居士，若梵志随蓝行如是大施，及施满阎浮场凡夫人食，施百须陀洹、百斯陀含、百阿那含食，若复有施一阿罗诃食者，此于彼施为最胜也。

“居士，若梵志随蓝行如是大施，及施满阎浮场凡夫人食，施百须陀洹、百斯陀含、百阿那含、百阿罗诃食，若复有施一辟支佛食者，此于彼施为最胜也。

“居士，若梵志随蓝行如是大施，及施满阎浮场凡夫人食，施百须陀洹、百斯陀含、百阿那含、百阿罗诃、百辟支佛食，若复有施一如来、无所著、等正觉食者，此于彼施为最胜也。

“居士，若梵志随蓝行如是大施，及施满阎浮场凡夫人食，施百须陀洹、百斯陀含、百阿那含、百阿罗诃、百辟支佛食，若有作房舍，施四方比丘众者，此于彼施为最胜也。

“居士，若梵志随蓝行如是大施，及施满阎浮场凡夫人食，施百须陀洹、百斯陀含、百阿那含、百阿罗诃、百辟支佛食，作房舍施四方比丘众，若有欢喜心归命三尊佛、法、比丘众及受戒者，此于彼施为最胜也。

“居士，若梵志随蓝行如是大施，及施满阎浮场凡夫人食，施百须陀洹、百斯陀含、百阿那含、百阿罗诃、百辟支佛食，作房舍施四方比丘众，欢喜心归命三尊佛、法、比丘众及受戒，若有为彼一切众生行于慈心，乃至𤛓牛顷者，此于彼施为最胜也。

“居士，若梵志随蓝行如是大施，及施满阎浮场凡夫人食，施百须陀洹、百斯陀含、百阿那含、百阿罗诃、百辟支佛食，作房舍施四方比丘众，欢喜心归命三尊佛、法、比丘众及受戒，为一切众生行于慈心，乃至𤛓牛顷，若有能观一切诸法无常、苦、空及非神者，此于彼施为最胜也。

“于居士意云何？昔时梵志大长者名随蓝者，谓异人耶？莫作斯念！所以者何？当知即是我也。我昔为梵志大长者，名曰随蓝。居士，我于尔时为自饶益，亦饶益他，饶益多人，悯伤世间，为天、为人求义及饶益，求安隐快乐，尔时说法不至究竟，不究竟白净、不究竟梵行、不究竟梵行讫。尔时，不离生老病死、啼哭忧戚，亦未能得脱一切苦。

“居士，我今出世如来、无所著、等正觉、明行成为、善逝、世间解、无上士、道法御、天人师，号佛、众佑，我今自饶益，亦饶益他，饶益多人，悯伤世间，为天、为人求义及饶益，求安隐快乐，我今说法得至究竟，究竟白净、究竟梵行、究竟梵行讫。我今已离生老病死、啼哭忧戚，我今已得脱一切苦。”

佛说如是，须达哆居士及诸比丘闻佛所说，欢喜奉行。

--------------

** 第39卷 梵志品.梵波罗延经第十五

我闻如是：一时，佛游舍卫国，在胜林给孤独园。

尔时，拘娑罗国众多梵志中后彷徉，往诣佛所，共相问讯，却坐一面，白曰：“瞿昙，欲有所问，听我问耶？”

世尊告曰：“恣汝所问。”

时，诸梵志问曰：“瞿昙，颇今有梵志学故梵志法，为越故梵志法耶？”

世尊答曰：“今无梵志学故梵志法，梵志久已越故梵志法。”

时，诸梵志问曰：“瞿昙，云何今无梵志学故梵志法，诸梵志等越故梵志法来为几时耶？”

彼时，世尊以偈答曰：

<div class="poem">

所谓昔时有，自调御热行，\\
舍五欲功德，行清净梵行。\\
梵行及戒行，率至柔软性，\\
恕亮无害心，忍辱护其意。\\
昔时有此法，梵志不护此，\\
梵志不守护；所有钱财谷，\\
诵习钱财谷，梵志守此藏。\\
衣色若干种，屋舍及床榻，\\
丰城及诸国，梵志学如是，\\
此梵志莫害，率守护诸法。\\
往到于他门，无有拘制彼，\\
发家乞求法，随其食时到。\\
梵志住在家，见者欲为施，\\
满四十八年，行清净梵行。\\
求索明行成，昔时梵志行，\\
彼不偷财物，亦无有恐怖。\\
爱受摄相应，当以共和合，\\
不为烦恼故，怨淫相应法。\\
诸有梵志者，无能行如是，\\
若有第一行，梵志极坚求。\\
彼诸淫欲法，不行乃至梦，\\
彼因此梵行，自称梵我梵。\\
知彼有此行，慧者当知彼，\\
床薄衣极单，食酥乳命存。\\
乞求皆如法，立斋行布施，\\
斋时无异乞，自于己乞求。\\
立斋行施时，彼不有杀牛，\\
如父母兄弟，及余有亲亲。\\
人牛亦如是，彼因是生乐，\\
饮食体有力，乘者安隐乐。\\
知有此义理，莫乐杀于牛，\\
柔软身极大，精色名称誉。\\
殷勤自求利，昔时梵志行，\\
梵志为自利，专事及非事。\\
彼当来此世，必度脱此世，\\
彼月过于月，见意趣向彼。\\
游戏于夜中，严饰诸妇人，\\
吉牛围绕前，妇女极端正。\\
人间微妙欲，梵志之常愿，\\
具足车乘具，善作缝治好。\\
家居及婚姻，梵志之常愿，\\
彼造作此缚，我等从彼来。\\
大王斋行施，莫失其财利，\\
饶财物米谷，若有余钱财。\\
大王相应此，梵志及车乘，\\
象斋及马斋，马斋不障门。\\
聚集作斋施，财物施梵志，\\
彼从此得利，爱乐惜财物。\\
彼以起为欲，数数增长爱，\\
犹如广池水，及无量财物。\\
如是人有牛，于生生活具，\\
彼造作此缚，我等从彼来。\\
大王斋行施，莫失其财利，\\
饶财物米谷，若汝多有牛。\\
大王相应此，梵志及车乘，\\
无量百千牛，因为斋故杀。\\
头角无所娆，牛猪昔时等，\\
往至提牛角，持利刀杀牛。\\
唤牛及于父，罗刹名曰香，\\
彼唤呼非法，以刀刺牛时。\\
此法行于斋，越过最在前，\\
无有事而杀，远离衰退法。\\
昔时有三病，欲不用食老，\\
以憎嫉于牛，起病九十八。\\
如是此憎诤，故为智所恶，\\
若人见如是，谁不有憎者？\\
如是此世行，无智最下贱，\\
各各为欲憎，若妇诽谤夫。\\
刹利梵志女，及守护于姓，\\
若犯于生法，自在由于欲。

</div>

“如是，梵志，今无梵志学故梵志法，梵志越故梵志法来尔许时也。”

于是，拘娑罗国众多梵志白曰：“世尊，我已知。善逝，我已解。世尊，我今自归于佛、法及比丘众，惟愿世尊受我为优婆塞！从今日始，终身自归，乃至命尽。”

佛说如是，彼拘娑罗国众多梵志及诸比丘闻佛所说，欢喜奉行。

--------------

** 第40卷 梵志品.黄芦园经第十六

我闻如是：一时，佛游鞞兰若，在黄芦园中。

尔时，鞞兰若梵志年耆宿老，寿将欲过，命垂至尽，年百二十，拄杖而行，中后彷徉，往诣佛所，共相问讯，当在佛前倚杖而立，白曰：“瞿昙，我闻沙门瞿昙年幼极少，新出家学，若有名德沙门梵志亲自来诣，而不礼敬，亦不尊重，不从座起，不请令坐。瞿昙，此事大为不可。”

世尊告曰：“梵志，我初不见天及魔、梵、沙门、梵志，从人至天，谓自来诣，能令如来礼敬尊重，而从座起，请令坐者。梵志，若有来诣，欲令如来礼敬尊重，而从座起，请令坐者，彼人必当头破七分。”

梵志复白：“瞿昙无味。”

世尊告曰：“梵志，有事令我无味，然不如汝言。若有色味、声味、香味、触味者，彼如来断智绝灭拔根终不复生，是谓有事令我无味，然不如汝言。”

梵志复白：“瞿昙无恐怖。”

世尊告曰：“梵志，有事令我无恐怖，然不如汝言。若有色恐怖，声、香、味、触恐怖者，彼如来断智绝灭拔根终不复生，是谓有事令我无恐怖，然不如汝言。”

梵志复白：“瞿昙不入胎。”

世尊告曰：“梵志，有事令我不入胎，然不如汝言。若有沙门、梵志当来胎床，断智绝灭拔根终不复生者，我说彼不入胎，如来当来胎床，断智绝灭拔根终不复生，是故令我不入胎，是谓有事令我不入胎，然不如汝言。

“梵志，我于此众生无明来，无明乐、无明覆、无明卵之所裹，我先观法，我于众生为最第一。犹鸡生卵，或十或十二，随时念，随时覆，随时暖，随时拥护，彼于其后，鸡设放逸，于中有鸡子，或以口嘴，或以足爪，啄破其卵，安隐自出，彼于鸡子为最第一。我亦如是，于此众生无明来，无明乐、无明覆、无明卵之所裹，我先观法，我于众生为最第一。

“梵志，我持蒿草住诣觉树，布草树下，敷尼师坛，结跏趺坐，不破正坐，要至漏尽。我不破正坐，要至漏尽，我正坐已，离欲、离恶不善之法，有觉有观，离生喜乐，逮初禅成就游，是谓我尔时获第一增上心，即于现法得安乐居，易不难得，乐住无怖，安隐快乐，令升涅槃。

“复次，梵志，我觉观已息，内静、一心，无觉无观，定生喜乐，逮第二禅成就游，是谓我尔时获第二增上心，即于现法得安乐居，易不难得，乐住无怖，安隐快乐，令升涅槃。

“复次，梵志，我离于喜欲舍无求游，正念正智而身觉乐，谓圣所说、圣所舍、念、乐住、空，逮第三禅成就游，是谓我尔时获第三增上心，即于现法得安乐居，易不难得，乐住无布，安隐快乐，令升涅槃。

“复次，梵志，我乐灭、苦灭，喜、忧本已灭，不苦不乐、舍、念、清净，逮第四禅成就游，是谓我尔时获第四增上心，即于现法得安乐居，易不难得，乐住无怖，安隐快乐，令升涅槃。

“复次，梵志，我已得如是定心清净，无秽无烦，柔软善住，得不动心，觉忆宿命智通作证，我有行有相貌，忆本无量昔所经历，谓一生、二生、百生、千生、成劫、败劫、无量成败劫，彼众生名某，彼昔更历，我曾生彼，如是姓，如是字，如是生，如是饮食，如是受苦乐，如是长寿，如是久住，如是寿讫。此死生彼，彼死生此，我生在此，如是姓，如是字，如是生，如是饮食，如是受苦乐，如是长寿，如是久住，如是寿讫。是谓我尔时初夜得此第一明达，以本无放逸，乐住远离，修行精勤，谓无智灭而智生，暗坏而明成，无明灭而明生，谓忆宿命智作证明达。

“复次，梵志，我已得如是定心清净，无秽无烦，柔软善住，得不动心，学于生死智通作证。我以清净天眼出过于人，见此众生死时生时，好色恶色，妙与不妙，往来善处及不善处，随此众生之所作业，见其如真。若此众生成就身恶行，口、意恶行，诽谤圣人，邪见，成就邪见业；彼因缘此，身坏命终，必至恶处，生地狱中。若此众生成就身妙行，口、意妙行，不诽谤圣人，正见，成就正见业；彼因缘此，身坏命终，必升善处，上生天中。是谓我尔时中夜得此第二明达，以本无放逸，乐住远离，修行精勤，谓无智灭而智生，暗坏而明成，无明灭而明生，谓生死智作证明达。

“复次，梵志，我已得如是定心清净，无秽无烦，柔软善住，得不动心，学于漏尽智通作证。我知此苦如真，知此苦集，知此苦灭，知此苦灭道如真；知此漏如真，知此漏集，知此漏灭，知此漏灭道如真。我如是知，如是见，欲漏心解脱，有漏、无明漏心解脱；解脱已，便知解脱：生已尽，梵行已立，所作已办，不更受有，知如真。是谓我尔时后夜得此第三明达，以本无放逸，乐住远离，修行精勤，谓无智灭而智生，暗坏而明成，无明灭而明生，谓漏尽智作证明达。

“复次，梵志，若有正说而说不痴法，众生生世，一切众生最胜，不为苦乐所覆，当知正说者即是我也。所以者何？我说不痴法，众生生世，一切众生最胜，不为苦乐所覆。”

于是，鞞兰若梵志即便舍杖，稽首佛足，白世尊曰：“世尊为第一，世尊为大，世尊为最，世尊为胜，世尊为等，世尊为不等，世尊无与等等，世尊无障，世尊无障人。世尊，我今自归于佛、法及比丘众，惟愿世尊受我为优婆塞！从今日始，终身自归，乃至命尽。”

佛说如是，鞞兰若梵志及诸比丘闻佛所说，欢喜奉行。

--------------

** 第40卷 梵志品.头那经第十七

我闻如是：一时，佛游舍卫国，在胜林给孤独园。

尔时，头那梵志中后彷徉，往诣佛所，共相问讯，却坐一面。世尊问曰：“头那，若有问汝是梵志耶？汝梵志汝自称说。”

梵志头那答曰：“瞿昙，若有正称说梵志者，为父母所举，受生清净，乃至七世父母不绝种族，生生无恶，博闻总持，诵过四典经，深达因、缘、正、文、戏五句说。瞿昙，正称说梵志者，即是我也。所以者何？我为父母所举，受生清净，乃至七世父母不绝种族，生生无恶，博闻总持，诵过四典经，深达因、缘、正、文、戏五句说。”

世尊告曰：“头那，我今问汝，随所解答。头那，于意云何？若昔有梵志寿终命过，诵持经书，流布经书，诵习典经，所谓夜吒、婆摩、婆摩提婆、毗奢蜜哆逻、夜陀揵尼、应疑罗娑、婆私吒、迦葉、娑罗婆、婆和，谓此施设五种梵志，有梵志犹如梵，有梵志似如天，有梵志不越界，有梵志越界，有梵志旃荼罗第五。头那，此五种梵志，汝为似谁？”

头那白曰：“瞿昙略说此义，不广分别，我不能知。惟愿沙门瞿昙善说，令我知义！”

世尊告曰：“头那，谛听！善思念之，我当为汝广分别说。”

头那白曰：“唯然，瞿昙。”头那梵志受教而听。

佛言：“头那，云何梵志犹如梵耶？若有梵志为父母所举，受生清净，乃至七世父母不绝种族，生生无恶。彼四十八年行童子梵行，欲得经书，诵习典经。彼得经书，诵习典经已，为供养师求乞财物，如法，非不如法。云何不如法？非田作，非治生，非书，非算，非数，非印，非手笔，非文章，非经，非诗，非以刀杖，非王从事。如法求乞，求乞财物供养于师。布施财物已，心与慈俱，遍满一方成就游。如是二三四方、四维上下，普周一切，心与慈俱，无结无怨，无恚无诤，极广甚大，无量善修，遍满一切世间成就游。如是悲、喜心与舍俱，无结无怨，无恚无诤，极广甚大，无量善修，遍满一切世间成就游。头那，如是梵志犹如梵也。

“头那，云何梵志似如天耶？若有梵志为父母所举，受生清净，乃至七世父母不绝种族，生生无恶。彼四十八年行童子梵行，欲得经书，诵习典经。彼得经书，诵习典经已，为供养师求乞财物，如法，非不如法。云何不如法？非田作，非治生，非书，非算，非数，非印，非手笔，非文章，非经，非诗，非以刀杖，非王从事。如法求乞，求乞财物供养于师。布施财物已，行身妙行，口、意妙行。行身妙行，口、意妙行已，彼因缘此，身坏命终，必升善处，上生天中。头那，如是梵志似如天也。

“头那，云何梵志不越界耶？若有梵志为父母所举，受生清净，乃至七世父母不绝种族，生生无恶。彼四十八年行童子梵行，欲得经书，诵习典经。彼得经书，诵习典经已，为供养师求乞财物，如法，非不如法。云何不如法？非田作，非治生，非书，非算，非数，非印，非手笔，非文章，非经，非诗，非以刀杖，非王从事。如法求乞，求乞财物供养于师。布施财物已，为自求妻，如法，非不如法。云何不如法？梵志不如是，意向梵志女，令更相爱，相摄合会。彼趣梵志女，非不梵志女，亦非刹利女。不怀妊，不产生。头那，以何等故梵志非趣怀妊？莫令彼男及以女人名不净淫，是故梵志非趣怀妊。头那，以何等故梵志不趣产生？莫令彼男及以女人名不净恚，是故梵志不趣产生。头那，彼所趣向，不为财物，不为骄傲，不为庄严，不为校饰，但为子故。彼生子已，若有故梵志要誓处所界障，住彼持彼，不越于彼。头那，如是梵志不越界也。

“头那，云何梵志为越界耶？若有梵志为父母所举，受生清净，乃至七世父母不绝种族，生生无恶。彼四十八年行童子梵行，欲得经书，诵习典经。彼得经书，诵习经典已，为供养师求乞财物，如法，非不如法。云何不如法？非田作，非治生，非书，非算，非数，非印，非手笔，非文章，非经，非诗，非以刀杖，非王从事。如法求乞，求乞财物供养于师。布施财物已，为自求妻，如法，非不如法。云何不如法？梵志不如是，意向梵志女，令更相爱，相摄合会。彼趣梵志女，非不梵志女，亦非刹利女。不怀妊，不产生。头那，以何等故梵志不趣怀妊？莫令彼男及以女人名不净淫，是故梵志不趣怀妊。头那，以何等故梵志不趣产生？莫令彼男及以女人名不净恚，是故梵志不趣产生。头那，彼所趣向，不为财物，不为骄傲，不为壮严，不为校饰，但为子故。彼生子已，若有故梵志要誓处所界障，不住止彼，不受持彼，便越于彼。头那，如是梵志名越界也。

“头那，云何梵志梵志旃荼罗？若有梵志为父母所举，受生清净，乃至七世父母不绝种族，生生无恶。彼四十八年行童子梵行，欲得经书，诵习典经。彼得经书，诵习典经已，为供养师求乞财物，如法，非不如法。云何不如法？非田作，非治生，非书，非算，非数，非印，非手笔，非文章，非经，非诗，非以刀杖，非王从事。如法求乞，求乞财物供养于师。布施财物已，为自求妻，如法，非不如法。云何不如法？梵志不如是，意向梵志女，令更相爱，相摄合会。趣彼梵志女，非不梵志女，亦不刹利女。不怀妊，不产生。头那，以何等故梵志不趣怀妊？莫令彼男及以女人名不净淫，是故梵志不趣怀妊。头那，以何等故梵志不趣产生？莫令彼男及以女人名不净恚，是故梵志不趣产生。头那，彼所趣向，不为财物，不为骄傲，不为庄严，不为校饰，但为子故。彼生子已，作王相应事、贼相应事、邪道相应事，作如是说：‘梵志应作一切事，梵志不以此染著，亦不秽污，犹若如火，净亦烧，不净亦烧。梵志不应作一切事，梵志不以此染著，亦不秽污。'头那，如是梵志梵志旃荼罗。头那，此五种梵志，汝为似谁？”

头那白曰：“瞿昙，说此最后梵志旃荼罗者，我尚不及，况复余耶？世尊，我已知。善逝，我已解。世尊，我今自归于佛、法及比丘众，惟愿世尊受我为优婆塞！从今日始，终身自归，乃至命尽。”

佛说如是，头那梵志闻佛所说，欢喜奉行。

--------------

** 第40卷 梵志品.阿伽罗诃那经第十八

我闻如是：一时，佛游舍卫国，在胜林给孤独园。尔时，阿伽罗诃那梵志中后彷徉，往诣佛所，共相问讯，却坐一面，白曰：“瞿昙，欲有所问，听乃敢陈。”

世尊告曰：“恣汝所问。”

梵志即便问曰：“瞿昙，梵志经典何所依住？”

世尊答曰：“梵志经典依于人住。”

梵志即复问曰：“瞿昙，人何所依住？”

世尊答曰：“人依稻麦住。”

梵志即复问曰：“瞿昙，稻麦何所依住？”

世尊答曰：“稻麦依地住。”

梵志即复问曰：“瞿昙，地何所依住？”

世尊答曰：“地依水住。”

梵志即复问曰：“瞿昙，水何所依住？”

世尊答曰：“水依风住。”

梵志即复问曰：“瞿昙，风何所依住？”

世尊答曰：“风依空住。”

梵志即复问曰：“瞿昙，空何所依住？”

世尊答曰：“空无所依，但因日月，故有虚空。”

梵志即复间曰：“瞿昙，日月何所依住？”

世尊答曰：“日月依于四王天住。”

梵志即复问曰：“瞿昙，四王天何所依住？”

世尊答曰：“四王天依三十三天住。”

梵志即复问曰：“瞿昙，三十三天何所依住？”

世尊答曰：“三十三天依焰摩天住。”

梵志即复问曰：“瞿昙，焰摩天何所依住？”

世尊答曰：“焰摩天依兜瑟哆天住。”

梵志即复问曰：“瞿昙，兜瑟哆天何所依住？”

世尊答曰：“兜瑟哆天依化乐天住。”

梵志即复问曰：“瞿昙，化乐天何所依住？”

世尊答曰：“化乐天依他化乐天住。”

梵志即复问曰：“瞿昙，他化乐天何所依住？”

世尊答曰：“他化乐天依梵世住。”

梵志即复问曰：“瞿昙，梵世何所依住？”

世尊答曰：“梵世依于大梵住。”

梵志即复问曰：“瞿昙，大梵何所依住？”

世尊答曰：“大梵依于忍辱温良住。”

梵志即复问曰：“瞿昙，忍辱温良何所依住？”

世尊答曰：“忍辱温良依涅槃住。”

梵志即复问曰：“瞿昙，涅槃何所依住？”

世尊告曰：“梵志意欲依无穷事，汝今从我受问无边，然涅槃者无所依住，但涅槃灭讫，涅槃为最。梵志，以此义故，从我行梵行。”

梵志白曰：“世尊，我已知。善逝，我已解。世尊，我今自归于佛、法及比丘众，惟愿世尊受我为优婆塞！从今日始，终身自归，乃至命尽。”

佛说如是，阿伽罗诃那梵志闻佛所说，欢喜奉行。

--------------

** 第40卷 梵志品.阿兰那经第十九

我闻如是：一时，佛游舍卫国，在胜林给孤独园。尔时，诸比丘于中食后集坐讲堂，论如是事：“诸贤，甚奇！甚奇！人命极少，要至后世，应作善事，应行梵行，生无不死，然今世人于法行、于义行、于善行、于妙行，无为无求。”

彼时，世尊在昼行处，以净天耳出过于人，闻诸比丘于中食后集坐讲堂，论如是事：“诸贤，甚奇！甚奇！人命极少，要至后世，应作善事，应行梵行，生无不死，然今世人于法行、于义行、于善行、于妙行，无为无求。”

世尊闻已，则于晡时从宴坐起，住诣讲堂，在比丘众前敷座而坐，问诸比丘：“汝论何事？以何等故集坐讲堂？”

时，诸比丘白曰：“世尊，我等众比丘于中食后集坐讲堂，论如是事：‘诸贤，甚奇！甚奇！人命极少，要至后世，应作善事，应行梵行，生无不死，然今世人于法行、于义行、于善行、于妙行，无为无求。'世尊，我等共论此事，以此事故集坐讲堂。”

世尊叹曰：“善哉！善哉！比丘，谓汝作是说：‘诸贤，甚奇！甚奇！人命极少，要至后世，应作善事，应行梵行，生无不死，然今世人于法行、于义行、于善行、于妙行，无为无求。'所以者何？我亦如是说：‘甚奇！甚奇！人命极少，要至后世，应作善事，应行梵行，生无不死，然今世人于法行、于义行、于善行、于妙行，无为无求。'所以者何？乃过去世时，有众生寿八万岁。比丘，人寿八万岁时，此阎浮洲极大丰乐，饶财珍宝，村邑相近，如鸡一飞。比丘，人寿八万岁时，女年五百乃当出嫁。比丘，人寿八万岁时，唯有如是病，谓寒、热、大小便、欲、不食、老，更无余患。

“比丘，人寿八万岁时，有王名拘牢婆，为转轮王，聪明智慧，有四种军，整御天下，由己自在，如法法王成就七宝。彼七宝者，轮宝、象宝、马宝、珠宝、女宝、居士宝、主兵臣宝，是谓为七。千子具足，颜貌端正，勇猛无畏，能伏他众，必当统领此一切地，乃至大海，不以刀杖，以法致令，令得安隐。

“比丘，拘牢婆王有梵志，名阿兰那大长者，为父母所举，受生清净，乃至七世父母不绝种族，生生无恶，博闻总持，诵过四典经，深达因、缘、正、文、戏五句说。比丘，梵志阿兰那有无量百千摩纳磨，梵志阿兰那为无量百千摩纳磨住一无事处，教学经书。

“尔时，梵志阿兰那独住静处，宴坐思惟，心作是念：‘甚奇！甚奇！人命极少，要至后世，应作善事，应行梵行，生无不死，然今世人于法行、于义行、于善行、于妙行，无为无求。我宁可剃除须发，著袈裟衣，至信、舍家、无家、学道。'于是，梵志阿兰那往至若干国众多摩纳磨所，而语彼曰：‘诸摩纳磨，我独住静处，宴坐思惟，心作是念：“甚奇！甚奇！人命极少，要至后世，应作善事，应行梵行，生无不死，然今世人于法行、于义行、于善行、于妙行，无为无求。我今宁可剃除须发，著袈裟衣，至信、舍家、无家、学道。”诸摩纳磨，我今欲剃除须发，著袈裟衣，至信、舍家、无家、学道，汝等当作何等？'

“彼若干国众多摩纳磨白曰：‘尊师，我等所知，皆蒙师恩。若尊师剃除须发，著袈裟衣，至信、舍家、无家、学道者，我等亦当剃除须发，著袈裟衣，至信、舍家、无家，从彼尊师出家学道。'于是，梵志阿兰那则于后时剃除须发，著袈裟衣，至信、舍家、无家、学道；彼若干国众多摩纳磨亦剃除须发，著袈裟衣，至信、舍家、无家，从彼尊师梵志阿兰那出家学道，是为尊师阿兰那，是为尊师阿兰那弟子名号生也。

“尔时，尊师阿兰那为弟子说法：‘诸摩纳磨，甚寄！甚奇！人命极少，要至后世，应作善事，应行梵行，生无不死，然今世人于法行、于义行、于善行、于妙行，无为无求。'尔时，尊师阿兰那为弟子说法：‘诸摩纳磨，甚奇！甚奇！人命极少，要至后世，应作善事，应行梵行，生无不死，然今世人于法行、于义行、于善行、于妙行，无为无求。'如是尊师阿兰那为弟子说法。

“复次，尊师阿兰那为弟子说法：‘摩纳磨，犹如朝露滴在草上，日出则消，暂有不久。如是，摩纳磨，人命如朝露，甚为难得，至少少味，大苦灾患，灾患甚多。'如是尊师阿兰那为弟子说法。

“复次，尊师阿兰那为弟子说法：‘摩纳磨，犹大雨时，滴水成泡，或生或灭。如是，摩纳磨，人命如泡，甚为难得，至少少味，大苦灾患，灾患甚多。'如是尊师阿兰那为弟子说法。

“复次，尊师阿兰那为弟子说法：‘摩纳磨，犹如以杖投著水中，还出至速。如是，摩纳磨，人命如杖，投水出速，甚为难得，至少少味，大苦灾患，灾患甚多。'如是尊师阿兰那为弟子说法。

“复次，尊师阿兰那为弟子说法：‘摩纳磨，犹新瓦盂，投水出速，著风热中，干燥至速。如是，摩纳磨，人命如新瓦盂，水渍速燥，甚为难得，至少少味，大苦灾患，灾患甚多。'如是尊师阿兰那为弟子说法。

“复次，尊师阿兰那为弟子说法：‘摩纳磨，犹如小段肉著大釜水中，下炽燃火，速得消尽。如是，摩纳磨，人命如肉消，甚为难得，至少少味，大苦灾患，灾患甚多。'如是尊师阿兰那为弟子说法。

“复次，尊师阿兰那为弟子说法：‘摩纳磨，犹缚贼送至标下杀，随其举足，步步趣死，步步趣命尽。如是，摩纳磨，人命如贼，缚送标下杀，甚为难得，至少少味，大苦灾患，灾患甚多。'如是尊师阿兰那为弟子说法。

“复次，尊师阿兰那为弟子说法：‘摩纳磨，犹如屠儿牵牛杀之，随其举足，步步趣死，步步趣命尽。如是，摩纳磨，人命如牵牛杀，甚为难得，至少少味，大苦灾患，灾患甚多。'如是尊师阿兰那为弟子说法。

“复次，尊师阿兰那为弟子说法：‘摩纳摩，犹如机织，随其行纬，近成近讫。如是，摩纳磨，人命如机织讫，甚为难得，至少少味，大苦灾患，灾患甚多。'如是尊师阿兰那为弟子说法。

“复次，尊师阿兰那为弟子说法：‘摩纳磨，犹如山水，瀑涨流疾，多有所漂，水流速驶，无须臾停。如是，摩纳磨，人寿行速，去无一时住。如是，摩纳磨，人命如驶水流，甚为难得，至少少味，大苦灾患，灾患甚多。'如是尊师阿兰那为弟子说法。

“复次，尊师阿兰那为弟子说法：‘摩纳磨，犹如夜暗以杖投地，或下头堕地，或上头堕地，或复卧堕，或堕净处，或堕不净处。如是，摩纳磨，众生为无明所覆，为爱所系，或生泥犁，或生畜生，或生饿鬼，或生天上，或生人间。如是，摩纳磨，人命如暗杖投地，甚为难得，至少少味，大苦灾患，灾患甚多。'如是尊师阿兰那为弟子说法。

“复次，尊师阿兰那为弟子说法：‘摩纳磨，我于世断除贪伺，心无有诤，见他财物诸生活具，不起贪伺，欲令我得，我于贪伺净除其心。如是瞋恚、睡眠、掉悔，我于世断疑度惑，于诸善法无有犹豫，我于疑惑净除其心。摩纳磨，汝等于世亦当断除贪伺，心无有诤，见他财物诸生活具，不起贪伺，欲令我得，汝于贪伺净除其心。如是瞋恚、睡眠、掉悔，汝于世断疑度惑，于诸善法无有犹豫。'如是尊师阿兰那为弟子说法。

“复次，尊师阿兰那为弟子说法：‘摩纳磨，我心与慈俱，遍满一方成就游。如是二三四方，四维上下，普周一切，心与慈俱，无结无怨，无恚无诤，极广甚大，无量善修，遍满一切世间成就游。如是悲、喜心与舍俱，无结无怨，无恚无诤，极广甚大，无量善修，遍满一切世间成就游。摩纳磨，汝等亦当心与慈俱，遍满一方成就游。如是二三四方，四维上下，普周一切，心与慈俱，无结无怨，无恚无诤，极广甚大，无量善修，遍满一切世间成就游。如是悲、喜心与舍俱，无结无怨，无恚无诤，极广甚大，无量善修，遍满一切世间就游。'如是尊师阿兰那为弟子说法。

“复次，尊师阿兰那为弟子说梵世法。若尊师阿兰那为说梵世法时，诸弟子等有不具足奉行法者，彼命终已，或生四王天，或生三十三天，或生焰摩天，或生兜瑟哆天，或生化乐天，或生他化乐天。若尊师阿兰那为说梵世法时，诸弟子等设有具足奉行法者，修四梵室，舍离于欲，彼命终已，得生梵天。尔时，尊师阿兰那而作是念：‘我不应与弟子等同，俱至后世共生一处。我今宁可更修增上慈，修增上慈已，命终得生晃昱天中。'尊师阿兰那则于后时更修增上慈，修增上慈已，命终得生晃昱天中。尊师阿兰那及诸弟子学道不虚，得大果报。比丘，于意云何？昔时尊师阿兰那者谓异人耶？莫作斯念！所以者何？比丘，当知即是我也。我于尔时名尊师阿兰那，我于尔时有无量百千弟子，我于尔时为诸弟子说梵世法。

“我说梵世法时，诸弟子等有不具足奉行法者，彼命终已，或生四王天，或生三十三天，或生焰摩天，或生兜瑟哆天，或生化乐天，或生他化乐天。我说梵世法时，诸弟子等设有具足奉行法者，修四梵室，舍离于欲，彼命终已，得生梵天。我于尔时而作是念：‘我不应与弟子等同，俱至后世共生一处。我今宁可更修增上慈，修增上慈已，命终得生晃昱天中。'我于后时更修增上慈，修增上慈已，命终得生晃昱天中。我于尔时及诸弟子学道不虚，得大果报。

“我于尔时自饶益，亦饶益他，饶益多人，悯伤世间，为天为人求义及饶益，求安隐快乐。我于尔时说法不至究竟，不究竟白净、不究竟梵行、不究竟梵行讫。我于尔时不离生老病死、啼哭忧戚，亦未能得脱一切苦。比丘，我今出世，如来、无所著、等正觉、明行成为、善逝、世间解、无上士、道法御、天人师，号佛、众佑，我今自饶益，亦饶益他，饶益多人，愍伤世间，为天为人求义及饶益，求安隐快乐。我今说法得至究竟，究竟白净、究竟梵行、究竟梵行讫，我今已离生老病死、啼哭忧戚，我今已得脱一切苦。

“比丘，若有正说者，人命极少，要至后世，应行善事，应行梵行，生无不死。比丘，今是正说。所以者何？今若有长寿，远至百岁，或复小过者。若有长寿者，命存三百时，春时百、夏时百、冬时百。是命存千二百月，春四百、夏四百、冬四百。命存千二百月者，命存二千四百半月，春八百、夏八百、冬八百。命存二千四百半月者，三万六千昼夜，春万二千、夏万二千、冬万二千。命存三万六千昼夜者，七万二千食，及障碍及母乳。于有障碍，苦不食，瞋不食，病不食，有事不食，行来不食，至王间不食，斋日不食，不得者不食，是谓比丘一百岁命存百岁数、时数、岁时数、月数、半月数、月半月数、昼数、夜数、昼夜数、食数、障碍数、食障碍数。

“比丘，若有尊师所为弟子起大慈哀，怜念愍伤，求义及饶益，求安隐快乐者，我今已作，汝亦当复作，至无事处、山林树下、空安静处，宴坐思惟，勿得放逸！勤加精进，莫令后悔！此是我之教敕，是我训诲。”

佛说如是，彼诸比丘闻佛所说，欢喜奉行。

--------------

** 第41卷 梵志品.梵摩经第二十

我闻如是：一时，佛游鞞陀提国，与大比丘众俱。

尔时，弥萨罗有梵志，名曰梵摩，极大富乐，资财无量，畜牧产业不可称计，封户食邑种种具足丰饶，弥萨罗乃至水草木，谓摩竭陀王未生怨鞞陀提子特与梵封。梵志梵摩有一摩纳，名优多罗，为父母所举，受生清净，乃至七世父母不绝种族，生生无恶，博闻总持，诵过四典经，深达因、缘、正、文、戏五句说。

梵志梵摩闻：有沙门瞿昙释种子舍释宗族，剃除须发，著袈裟衣，至信、舍家、无家、学道，游鞞陀提国，与大比丘众俱。彼沙门瞿昙有大名称，周闻十方，彼沙门瞿昙如来、无所著、等正觉、明行成为、善逝、世间解、无上士、道法御、天人师，号佛、众佑。彼于此世，天及魔、梵、沙门、梵志，从人至天，自知、自觉、自作证成就游。彼说法，初妙、中妙、竟亦妙，有义有文，具足清净，显现梵行。复次闻：彼沙门瞿昙成就三十二大人之相，若成就大人相者，必有二处真谛不虚。若在家者，必为转轮王，聪明智慧，有四种军，整御天下，由己自在，如法法王成就七宝。彼七宝者，轮宝、象宝、马宝、珠宝、女宝、居士宝、主兵臣宝，是谓为七。千子具足，颜貌端正，勇猛无畏，能伏他众。彼必统领此一切地乃至大海，不以刀杖，以法教令，令得安隐。若剃除须发，著袈裟衣，至信、舍家、无家、学道者，必得如来、无所著、等正觉，名称流布，周闻十方。

梵志梵摩闻已，告曰：“优多罗，我闻如是：彼沙门瞿昙释种子舍释宗族，剃除须发，著袈裟衣，至信、舍家、无家、学道，游鞞陀提国，与大比丘众俱。优多罗，彼沙门瞿昙有大名称，周闻十方，彼沙门瞿昙如来、无所著、等正觉、明行成为、善逝、世间解、无上士、道法御、天人师，号佛、众佑。彼于此世，天及魔、梵、沙门、梵志，从人至天，自知、自觉、自作证成就游。彼说法，初妙、中妙、竟亦妙，有义有文，具足清净，显现梵行。

“复次，优多罗，彼沙门瞿昙成就三十二大人之相，若成就大人相者，必有二处真谛不虚。若在家者，必为转轮王，聪明智慧，有四种军，整御天下，由己自在，如法法王成就七宝。彼七宝者，轮宝、象宝、马宝、珠宝、女宝、居士宝、主兵臣宝，是谓为七。千子具足，颜貌端正，勇猛无畏，能伏他众。彼必统领此一切地乃至大海，不以刀杖，以法教令，令得安隐。若剃除须发，著袈裟衣，至信、舍家、无家、学道者，必得如来、无所著、等正觉，名称流布，周闻十方。

“优多罗，汝受持诸经，有三十二大人之相。若成就大人相者，必有二处真谛不虚。若在家者，必为转轮王，聪明智慧，有四种军，整御天下，由己自在，如法法王成就七宝。彼七宝者，轮宝、象宝、马宝、珠宝、女宝、居士宝、主兵臣宝，是谓为七。千子具足，颜貌端正，勇猛无畏，能伏他众。彼必统领此一切地乃至大海，不以刀杖，以法教令，令得安隐。若剃除须发，著袈裟衣，至信、舍家、无家、学道者，必得如来、无所著、等正觉，名称流布，周闻十方。”

优多罗答曰：“唯然，世尊，我受持诸经，有三十二大人之相。若成就大人相者，必有二处真谛不虚。若在家者，必为转轮王，聪明智慧，有四种军，整御天下，由己自在，如法法王成就七宝。彼七宝者，轮宝、象宝、马宝、珠宝、女宝、居士宝、主兵臣宝，是谓为七。千子具足，颜貌端正，勇猛无畏，能伏他众。彼必统领此一切地乃至大海，不以刀杖，以法教令，令得安隐。若剃除须发，著袈娑衣，至信、舍家、无家、学道者，必得如来、无所著、等正觉，名称流布，周闻十方。”

梵志梵摩告曰：“优多罗，汝往诣彼沙门瞿昙所，观彼沙门瞿昙为如是？为不如是？实有三十二大人相耶？”

优多罗摩纳闻已，稽首梵志梵摩足，绕三匝而去；往诣佛所，共相问讯，却坐一面，观世尊身三十二相。彼见世尊身有三十相，于二相疑惑：阴马藏及广长舌。世尊念曰：“此优多罗于我身观三十二相。彼见有三十相，于二相疑惑：阴马藏及广长舌。我今宁可断其疑惑。”世尊知已，即如其像作如意足，如其像作如意足已，令优多罗摩纳见我身阴马藏及广长舌。

于是，世尊即如其像作如意足，如其像作如意足已，优多罗摩纳见世尊身阴马藏及广长舌。广长舌者，从口出舌，尽覆其面。优多罗摩纳见已，而作是念：“沙门瞿昙成就三十二大人之相。若成就大人相者，必有二处真谛不虚。若在家者，必为转轮王，聪明智慧，有四种军，整御天下，由己自在，如法法王成就七宝。彼七宝者，轮宝、象宝、马宝、珠宝、女宝、居士宝、主兵臣宝，是谓为七。千子具足，颜貌端正，勇猛无畏，能伏他众。彼必统领此一切地乃至大海，不以刀杖，以法教令，令得安隐。若剃除须发，著袈裟衣，至信、舍家、无家、学道者，必得如来、无所著、等正觉，名称流布，周闻十方。”

优多罗摩纳复作是念：“我宁可极观威仪礼节，及观游行所趣。”于是，优多罗摩纳寻随佛行，于夏四月观威仪礼节，及观游行所趣。优多罗摩纳过夏四月，悦可世尊威仪礼节，及观游行所趣，白曰：“瞿昙，我今有事，欲还请辞。”

世尊告曰：“优多罗，汝去随意。”

优多罗摩纳闻世尊所说，善受善持，即从坐起，绕三匝而去；往诣梵志梵摩所，稽首梵志梵摩足，却坐一面。

梵志梵摩问曰：“优多罗，实如所闻，沙门瞿昙有大名称，周闻十方，为如是？为不如是？实有三十二大人相耶？”

优多罗摩纳答曰：“唯然，尊，实如所闻，沙门瞿昙有大名称，周闻十方，沙门瞿昙如是，非不如是，实有三十二相。

“尊，沙门瞿昙足安平立。是谓，尊，沙门瞿昙大人大人之相。

“复次，尊，沙门瞿昙足下生轮，轮有千辐，一切具足。是谓，尊，沙门瞿昙大人大人之相。

“复次，尊，沙门瞿昙足指纤长。是谓，尊沙门瞿昙大人大人之相。

“复次，尊，沙门瞿昙足周正直。是谓，尊，沙门瞿昙大人大人之相。

“复次，尊，沙门瞿昙足跟踝后两边平满。是谓，尊，沙门瞿昙大人大人之相。

“复次，尊，沙门瞿昙足两踝傭。是谓，尊，沙门瞿昙大人大人之相。

“复次，尊，沙门瞿昙身毛上向。是谓，尊，沙门瞿昙大人大人之相。

“复次，尊，沙门瞿昙手足网缦，犹如鹅王。是谓，尊，沙门瞿昙大人大人之相。

“复次，尊，沙门瞿昙手足极妙，柔弱软软，犹兜罗华。是谓，尊，沙门瞿昙大人大人之相。

“复次，尊，沙门瞿昙肌皮软细，尘水不著。是谓，尊，沙门瞿昙大人大人之相。

“复次，尊，沙门瞿昙一一毛，一一毛者，身一一孔一毛生，色若绀青，如螺右旋。是谓，尊，沙门瞿昙天人大人之相。

“复次，尊，沙门瞿昙鹿腨肠，犹如鹿王。是谓，尊，沙门瞿昙大人大人之相。

“复次，尊，沙门瞿昙阴马藏，犹良马王。是谓，尊，沙门瞿昙大人大人之相。

“复次，尊，沙门瞿昙身形圆好，犹尼拘类树，上下圆相称。是谓，尊，沙门瞿昙大人大人之相。

“复次，尊，沙门瞿昙身不阿曲，身不曲者，平立伸手以摩其膝。是谓，尊，沙门瞿昙大人大人之相。

“复次，尊，沙门瞿昙身黄金色，如紫磨金。是谓，尊，沙门瞿昙大人大人之相。

“复次，尊，沙门瞿昙身七处满，七处满者，两手、两足、两肩及项。是谓，尊，沙门瞿昙大人大人之相。

“复次，尊，沙门瞿昙其上身大，犹如师子。是谓，尊，沙门瞿昙大人大人之相。

“复次，尊，沙门瞿昙师子颊车。是谓，尊，沙门瞿昙大人大人之相。

“复次，尊，沙门瞿昙脊背平直。是谓，尊，沙门瞿昙大人大人之相。

“复次，尊，沙门瞿昙两肩上连，通颈平满。是谓，尊，沙门瞿昙大人大人之相。

“复次，尊，沙门瞿昙四十齿，平齿、不疏齿、白齿、通味第一味。是谓，尊，沙门瞿昙大人大人之相。

“复次，尊，沙门瞿昙梵音可爱，其声犹如迦罗毗伽。是谓，尊，沙门瞿昙大人大人之相。

“复次，尊，沙门瞿昙广长舌，广长舌者，舌从口出，遍覆其面。是谓，尊，沙门瞿昙大人大人之相。

“复次，尊，沙门瞿昙承泪处满，犹如牛王。是谓，尊，沙门瞿昙大人大人之相。

“复次，尊，沙门瞿昙眼色绀青。是谓，尊，沙门瞿昙大人大人之相。

“复次，尊，沙门瞿昙顶有肉髻，团圆相称，发螺右旋。是谓，尊，沙门瞿昙大人大人之相。

“复次，尊，沙门瞿昙眉间生毛，洁白右萦。是谓，尊，沙门瞿昙大人大人之相。

“是谓，尊，沙门瞿昙成就三十二大人之相。若成就大人相者，必有二处真谛不虚。若在家者，必为转轮王，聪明智慧，有四种军，整御天下，由己自在，如法法王成就七宝。彼七宝者，轮宝、象宝、马宝、珠宝、女宝、居士宝、主兵臣宝，是谓为七。千子具足，颜貌端正，勇猛无畏，能伏他众。彼必统领此一切地乃至大海，不以刀杖，以法教令，令得安隐。若剃除须发，著袈娑衣，至信、舍家、无家、学道者，必得如来、无所著、等正觉，名称流布，周闻十方。

“复次，尊，我见沙门瞿昙著衣、已著衣，被衣、已被衣，出房、已出房，出园、已出园，行道至村间，入村、已入村，在巷，入家、已入家，正床、已正床，坐、已坐，澡手、已澡手，受饮食、已受饮食，食、已食，澡手咒愿，从坐起，出家、已出家，在巷，出村、已出村，入园、已入园，入房、已入房，尊，沙门瞿昙著衣齐整，不高不下，衣不近体，风不能令衣远离身。尊，沙门瞿昙被衣齐整，不高不下，衣不近体，风不能令衣远离身。尊，沙门瞿昙常著新衣，随顺于圣，以刀割截，染作恶色，如是彼圣染作恶色。彼持衣者，不为财物，不为贡高，不为自饰，不为庄严，但为障蔽蚊虻、风日之所触故，及为惭愧，覆其身故。

“彼出房时，身不低仰。尊，沙门瞿昙出房时，终不低身。尊，沙门瞿昙若欲行时，先举右足，正举正下，行不扰乱，亦无恶乱，行时两踝终不相掁。尊，沙门瞿昙行时不为尘土所坌。所以者何？以本善行故。彼出园时，身不低仰。尊，沙门瞿昙出园时，终不低身，往到村间，身极右旋，观察如龙，遍观而观，不恐不怖，亦不惊惧，观于诸方。所以者何？以如来、无所著、等正觉故。彼入村时，身不低仰。尊，沙门瞿昙入村时，终不低身。彼在街巷不低视，亦不仰视，唯直正视，于中不碍所知所见。

“尊，沙门瞿昙诸根常定。所以者何？以本善行故。彼入家时，身不低仰。尊，沙门瞿昙入家时，终不低身。尊，沙门瞿昙回身右旋，正床而坐。彼于床上不极身力坐，亦不以手案髀坐床。彼坐床已，不悒悒，不烦恼，亦复不乐。受澡水时，不高不下，不多不少。彼受饮食，不高不下，不多不少。尊，沙门瞿昙受食平钵，等羹饮食。尊，沙门瞿昙抟食，齐整徐著口中，抟食未至，不豫张口，及在口中三嚼而咽，无饭及羹亦不断碎，有余在口，复内后抟。

“尊，沙门瞿昙以三事清净，食欲得味，不欲染味彼食，不为财物，不为贡高，不为自饰，不为庄严，但欲存身，久住无患，用止故疹，不起新病，存命无患，有力快乐。饭食已讫，受澡手水，不高不下，不多不少。受澡钵水，不高不下，不多不少。彼洗手净已，其钵亦净。洗钵净已，其手亦净。拭手已，便拭钵。拭钵已，便拭手。彼洗拭钵已，安著一面，不近不远，不数观钵，亦不为钵。彼不毁訾此食，亦不称誉彼食，但暂默然已，为诸居士说法，劝发渴仰，成就欢喜；无量方便为彼说法，劝发渴仰，成就欢喜已，即从座起，便退而还。彼出家时，身不低仰。

“尊，沙门瞿昙出家时，终不低身。彼在街巷不低视，亦不仰视，唯直正视，于中不碍所知所见。尊，沙门瞿昙诸根常定。所以者何？以本善行故。彼出村时，身不低仰。尊，沙门瞿昙出村时，终不低身。彼入园时，身不低仰。尊，沙门瞿昙入园时，终不低身。彼中食后，收举衣钵，澡洗手足，以尼师坛著于肩上，入房宴坐。尊，沙门瞿昙饶益世间故，入房宴坐。尊，沙门瞿昙则于晡时从宴坐起，面色光泽。所以者何？以如来、无所著、等正觉故。

“尊，沙门瞿昙口出八种音声：一曰、甚深，二曰、毗摩楼簸，三曰、入心，四曰、可爱，五曰、极满，六曰、活瞿，七曰、分了，八曰、智也。多人所爱，多人所乐，多人所念，令得心定。尊，沙门瞿昙随众说法，声不出众外，唯在于众，为彼说法，劝发渴仰，成就欢喜；无量方便为彼说法，劝发渴仰，成就欢喜已，即从座起，还归本所。尊，沙门瞿昙其像如是，但有殊胜复过于是。尊，我欲诣彼沙门瞿昙，从学梵行。”

梵志梵摩告曰：“随意。”

于是，优多罗摩纳稽首梵志梵摩足，绕三匝而去；往诣佛所，稽首佛足，却坐一面，白曰：“世尊，愿从世尊学道受具足，成就比丘，得从世尊修行梵行。”

于是，世尊度优多罗摩纳，令学道受具足。度优多罗摩纳，令学道受具足已，游行鞞陀提国，与大比丘众俱，展转进前，到弥萨罗，住弥萨罗大天奈林。彼弥萨罗梵志、居士闻沙门瞿昙释种子舍释宗族，出家学道，游行鞞陀提国，与大比丘众俱，展转来至此弥萨罗，住大天奈林：“沙门瞿昙有大名称，周闻十方，沙门瞿昙如来、无所著、等正觉、明行成为、善逝、世间解、无上士、道法御、天人师，号佛、众佑，彼于此世，天及魔、梵、沙门、梵志，从人至天，自知、自觉、自作证成就游。彼说法，初妙、中妙、竟亦妙，有义有文，具足清净，显现梵行。若有见如来、无所著、等正觉，敬重礼拜，供养承事者，快得善利！我等宁可共往见彼沙门瞿昙，礼拜供养。”

彼弥萨罗梵志、居士各与等类眷属相随，从弥萨罗出，北行至大天奈林，欲见世尊礼拜供养。往诣佛已，或有弥萨罗梵志、居士稽首佛足，却坐一面。或有与佛共相问讯，却坐一面。或有叉手向佛，却坐一面。或有遥见佛已，默然而坐。彼弥萨罗梵志、居士各各坐已，佛为说法，劝发渴仰，成就欢喜；无量方便为彼说法，劝发渴仰，成就欢喜已，默然而住。

梵志梵摩闻沙门瞿昙释种子舍释宗族，出家学道，游行鞞陀提国，与大比丘众俱，展转来至此弥萨罗国，住大天奈林：“彼沙门瞿昙有大名称，周闻十方，彼沙门瞿昙如来、无所著、等正觉、明行成为、善逝、世间解、无上士、道法御、天人师，号佛、众佑，彼于此世，天及魔、梵、沙门、梵志，从人至天，自知、自觉、自作证成就游。彼说法，初妙、中妙、竟亦妙，有义有文，具足清净，显现梵行。若有见如来、无所著、等正觉，敬重礼拜，供养承事者，快得善利！我宁可往见沙门瞿昙，礼拜供养。”

梵志梵摩告御者曰：“汝速严驾，我今欲往诣沙门瞿昙。”

御者受教，即速严驾讫，还白曰：“严驾已毕，尊自知时。”

于是，梵摩乘极贤妙车，从弥萨罗出，北行至大天奈林，欲见世尊礼拜供养。

尔时，世尊在无量众前后围绕而为说法。梵志梵摩遥见世尊在无量众前后围绕而为说法，见已恐怖。于是，梵摩即避在道侧，至树下住，告一摩纳：“汝往诣彼沙门瞿昙，为我间讯圣体康强，安快无病，起居轻便，气力如常耶？作如是语：‘瞿昙，我师梵摩问讯圣体康强，安快无病，起居轻便，气力如常耶？瞿昙，我师梵摩欲来见沙门瞿昙。'”

于是，摩纳即受教行，往诣佛所，共相问讯，却坐一面，白曰：“瞿昙，我师梵摩问讯圣体康强，安快无病，起居轻便，气力如常耶？瞿昙，我师梵摩欲来见沙门瞿昙。”

世尊告曰：“摩纳，令梵志梵摩安隐快乐，令天及人、阿修罗、揵沓惒、罗刹及余种种身安隐快乐。摩纳，梵志梵摩欲来随意。”

于是，摩纳闻佛所说，善受善持，即从座起，绕佛三匝而去，还诣梵志梵摩所，白曰：“尊，我已通沙门瞿昙，彼沙门瞿昙今住待尊，唯尊知时。”

梵志梵摩即从车下，步诣佛所。彼众遥见梵志梵摩来，即从座起，开道避之。所以者何？以有名德及多识故。

梵志梵摩告彼众曰：“诸贤，各各复坐！我欲直往见沙门瞿昙。”

于是，梵摩往诣佛所，共相问讯，却坐一面。

尔时，梵摩不坏二根，眼根及耳根。梵志梵摩坐已，谛观佛身三十二相，彼见三十相，于二相有疑：阴马藏及广长舌。梵志梵摩即时以偈问世尊曰：

<div class="poem">

如我昔曾所闻，三十二大人相，\\
于中求不见二，尊沙门瞿昙身，\\
为有阴马藏不？一切人尊深密，\\
云何为人最尊？不现视微妙舌，\\
若尊有广长舌，惟愿令我得见，\\
今实有疑惑心，愿调御决我疑。

</div>

世尊作是念：“此梵志梵摩求我身三十二相，彼见三十，于二有疑：阴马藏及广长舌。我今宁可除彼疑惑。”世尊知已，作如其像如意足，作如其像如意足已，梵志梵摩见世尊身阴马藏及广长舌。于中广长舌者，舌从口出，尽覆其面。世尊止如意足已，为梵志梵摩说此颂曰：

<div class="poem">

谓汝昔曾所闻，三十二大人相，\\
彼一切在我身，满具足最上正。\\
调御断于我疑，梵志发微妙信，\\
至难得见闻，最上正尽觉。\\
出世为极难，最上正尽觉，\\
梵志我正觉，无上正法王。

</div>

梵志梵摩闻已，而作是念：“此沙门瞿昙成就三十二大人之相，成就大人相者，必有二处真谛不虚。若在家者，必为转轮王，聪明智慧，有四种军，整御天下，如法法王成就七宝。彼七宝者，轮宝、象宝、马宝、珠宝、女宝、居士宝、主兵臣宝，是谓为七。千子具足，颜貌端正，勇猛无畏，能伏他众。彼必统领此一切地乃至大海，不以刀杖，以法教令，令得安隐。若剃除须发，著袈娑衣，至信、舍家、无家、学道者，必得如来、无所著、等正觉，名称流布，周闻十方。”

于是，世尊而作是念：“此梵志梵摩长夜无谀谄、无欺诳，所欲所问者，一切欲知非为触娆，彼亦如是，我宁可说彼甚深阿毗昙。”世尊知已，为梵志梵摩即说颂曰：

<div class="poem">

现世乐法故，饶益为后世，\\
梵志汝问事，随本意所思，\\
彼彼诸问事，我为汝断疑。

</div>

世尊已许问，梵志梵摩故，便问世尊事，随本意所思：

<div class="poem">

云何为梵志？三达有何义？\\
以何说无著？何等正尽觉？

</div>

尔时，世尊以颂答曰：

<div class="poem">

灭恶不善法，立住择梵行，\\
修习梵志行，以此为梵志。\\
明达于过去，见乐及恶道，\\
得无明尽说，知是立牟尼。\\
善知清净心，尽脱淫怒痴，\\
成就于三明，以此为三达。\\
远离不善法，正住第一义，\\
第一世所敬，以此为无著。\\
饶益天及人，与眼灭坏诤，\\
普知现视尽，以此正尽觉。

</div>

于是，梵摩即从座起，欲稽首佛足。彼时大众同时俱发高大音声：“沙门瞿昙甚奇！甚特！有大如意足，有大威德，有大福佑，有大威神。所以者何？此弥萨罗国所有梵志、居士者，梵志梵摩于彼最第一，谓出生故，梵志梵摩为父母所举，受生清净，乃至七世父母不绝种族，生生无恶。彼为沙门瞿昙极下意尊敬作礼，供养奉事。沙门瞿昙甚奇！甚特！有大如意足，有大威德，有大福佑，有大威神。所以者何？此弥萨罗国所有梵志、居士者，梵志梵摩于彼最第一，谓学书故，梵志梵摩博闻总持，诵过四典经，深达因、缘、正、文、戏五句说。彼为沙门瞿昙极下意尊敬作礼，供养奉事。

“沙门瞿昙甚奇！甚特！有大如意足，有大威德，有大福佑，有大威神。所以者何？此弥萨罗国所有梵志、居士者，梵志梵摩于彼最第一，谓财物故，梵志梵摩极大富乐，资财无量，畜牧产业不可称计，封户食邑种种具足丰饶，弥萨罗乃至水草木，谓王摩竭陀未生怨鞞陀提子特与梵封。彼为沙门瞿昙极下意尊敬作礼，供养奉事。沙门瞿昙甚奇！甚特！有大如意足，有大威德，有大福佑，有大威神。所以者何？此弥萨罗国所有梵志、居士者，梵志梵摩于彼最第一，谓寿命故，梵志梵摩极大长老，寿命具足，年百二十六。彼为沙门瞿昙极下意尊敬作礼，供养奉事。”

是时，世尊以他心智知彼大众心之所念，世尊知已，告梵志梵摩：“止！止！梵志，但心喜足，可还复坐，为汝说法。”

梵志梵摩稽首佛足，却坐一面。世尊为彼说法，劝发渴仰，成就欢喜；无量方便为彼说法，劝发渴仰，成就欢喜已，如诸佛法，先说端正法，闻者欢悦，谓说施、说戒、说生天法，毁訾欲为灾患，生死为秽，称叹无欲为妙，道品白净。为说是已，佛知彼有欢喜心、具足心、柔软心、堪耐心、升上心、一向心、无疑心、无盖心，有能有力受佛正法，谓如诸佛所说正要，世尊具为彼说苦、集、灭、道。梵志梵摩即于座上见四圣谛苦、集、灭、道，犹如白素易染为色，如是梵摩即于座上见四圣谛苦、集、灭、道。

于是，梵摩见法得法，觉白净法，断疑度惑，更无余尊，不复由他，无有犹豫，已住果证，于世尊法得无所畏；即从座起，稽首佛足：“世尊，我今自归于佛、法及比丘众，惟愿世尊受我为优婆塞！从今日始，终身自归，乃至命尽。”

时，梵志梵摩又手向佛，白曰：“世尊，惟愿明日垂顾受请，及比丘众！”

世尊为梵志梵摩故，默然而受。梵志梵摩知世尊默然受已，稽首佛足，绕三匝而去，还归其家，即于其夜施设肴馔极妙上味、种种丰饶食啖含消。施设已讫，平旦敷床，至时唱曰：“世尊，饭食已办，唯圣知时。”

于是，世尊过夜平旦，著衣持钵，比丘翼从，世尊在前，往诣梵志梵摩家，于比丘众前敷座而坐。梵志梵摩知世尊及比丘众众坐已定，自行澡水，以上味肴馔、种种丰饶食啖含消，自手斟酌，令极饱满；食讫收器，行澡水竟，取一小床，坐受咒愿。

梵志梵摩坐已，世尊为彼说咒愿曰：

<div class="poem">

咒火第一斋，通音诸音本，\\
王为人中尊，海为江河长，\\
月为星中明，明照无过日。\\
上下维诸方，及一切世间，\\
从人乃至天，唯佛最第一。

</div>

于是，世尊为梵志梵摩说咒愿已，从座起去。弥萨罗国住经数日，摄衣持钵，则便游行至舍卫国，展转前进，到舍卫国，住胜林给孤独园。于是，众多比丘舍卫乞食时，闻彼弥萨罗梵志梵摩以偈问佛事，彼便命终。诸比丘闻已，食讫，中后收举衣钵，澡洗手足，以尼师坛著于肩上，往诣佛所，稽首作礼，却住一面，白曰：“世尊，我等众多比丘平旦著衣，持钵入舍卫乞食时，闻彼弥萨罗梵志梵摩以偈问佛事，彼便命终。世尊，彼至何处？为生何许？后世云何？”

世尊答曰：“比丘，梵志梵摩极有大利，最后知法，为法故不烦劳我。比丘，梵志梵摩五下分结尽，生彼得般涅槃，得不退法，不还此世。”

尔时，世尊记说梵摩得阿那含。佛说如是，梵志梵摩及诸比丘闻佛所说，欢喜奉行。

梵志品第十二竟。

--------------

