#+OPTIONS: toc:nil num:nil
*  晡利多品.第十七（有十经）（第五后诵）

持斋、晡利多，罗摩、五下分，

心秽、箭毛二，鞞摩那修学，

法乐比丘尼，拘絺罗在后。

#+TOC: headlines 2

**  第55卷 晡利多品.持斋经第一
我闻如是：一时，佛游舍卫国，在于东园鹿子母堂。

尔时，鹿子母毗舍佉平旦沐浴，著白净衣，将子妇等眷属围绕，往诣佛所，稽首作礼，却住一面。世尊问曰：“居士妇，今沐浴耶？”

答曰：“世尊，我今持斋。善逝，我今持斋。”

世尊问曰：“居士妇，今持何等斋耶？斋有三种，云何为三？一者、放牛儿斋，二者、尼揵斋，三者、圣八支斋。居士妇，云何名为放牛儿斋？若放牛儿朝放泽中，晡收还村，彼还村时，作如是念：‘我今日在此处放牛，明日当在彼处放牛；我今日在此处饮牛，明日当在彼处饮牛；我牛今在此处宿止，明日当在彼处宿止。'居士妇，如是有人若持斋时，作是思惟：‘我今日食如此之食，明日当食如彼食也；我今日饮如此之饮，明日当饮如彼饮也；我今含消如此含消，明当含消如彼含消。'其人于此昼夜乐著欲过，是谓名曰放牛儿斋。若如是持放牛儿斋者，不获大利，不得大果，无大功德，不得广布。

“居士妇，云何名为尼揵斋耶？若有出家学尼揵者，彼劝人曰：‘汝于东方过百由延外有众生者，拥护彼故，弃舍刀杖；如是南方、西方、北方过百由延外有众生者，拥护彼故，弃舍刀杖。'是为彼劝进人。‘或有想护众生，或无想不护众生，汝当十五日说从解脱时，脱衣裸形，东向住立，作如是说：我无父母，非父母有；我无妻子，非妻子有；我无奴婢，非奴婢主。'居士妇，彼劝进于真谛语，而反劝进虚妄之言。彼人日日见其父母，便作此念：‘是我父母。'父母日日见其儿子，亦作此念：‘是我儿子。'彼见妻子，而作此念：‘是我妻子。'妻子见彼，亦作此念：‘是我尊长。'彼见奴婢，复作此念：‘是我奴婢。'奴婢见彼，亦作此念：‘是我大家。'彼用此欲，不与而用，非是与用，是谓名曰尼揵斋也。若如是持尼揵斋者，不获大利，不得大果，无大功德，不得广布。

“居士妇，云何名为圣八支斋？多闻圣弟子若持斋时，作是思惟：‘阿罗诃真人尽形寿离杀、断杀，弃舍刀杖，有惭有愧，有慈悲心，饶益一切乃至昆虫，彼于杀生净除其心。我亦尽形寿离杀、断杀，弃舍刀杖，有惭有愧，有慈悲心，饶益一切乃至昆虫，我今于杀生净除其心，我以此支于阿罗诃等同无异。'是故说斋。

“复次，居士妇，多闻圣弟子若持斋时，作是思惟：‘阿罗诃真人尽形寿离不与取、断不与取，与而后取，乐于与取，常好布施，心乐放舍，欢喜无吝，不望其报，不以盗覆心，能自制已，彼于不与取净除其心。我亦尽形寿离不与取、断不与取，与而后取，乐于与取，常好布施，心乐放舍，欢喜无吝，不望其报，不以盗覆心，能自制已，我于不与取净除其心，我以此支于阿罗诃等同无异。'是故说斋。

“复次，居士妇，多闻圣弟子若持斋时，作是思惟：‘阿罗诃真人尽形寿离非梵行、断非梵行，修行梵行，至诚心净，行无臭秽，离欲断淫，彼于非梵行净除其心。我于此日此夜离非梵行、断非梵行，修行梵行，至诚心净，行无臭秽，离欲断淫，我于非梵行净除其心，我以此支于阿罗诃等同无异。'是故说斋。

“复次，居士妇，多闻圣弟子若持斋时，作是思惟：‘阿罗诃真人尽形寿离妄言、断妄言，真谛言，乐真谛，住真谛，为人所信，不欺世间，彼于妄言净除其心。我亦尽形寿离妄言、断妄言，真谛言，乐真谛，住真谛，为人所信，不欺世间，我于妄言净除其心，我以此支于阿罗诃等同无异。'是故说斋。

“复次，居士妇，多闻圣弟子若持斋时，作是思惟：‘阿罗诃真人尽形寿离酒放逸、断酒放逸，彼于酒放逸净除其心。我亦尽形寿离酒放逸、断酒放逸，我于酒放逸净除其心，我以此支于阿罗诃等同无异。'是故说斋。

“复次，居士妇，多闻圣弟子若持斋时，作是思惟：‘阿罗诃真人尽形寿离高广大床、断高广大床，乐下坐卧，或床或敷草，彼于高广大床净除其心。我于此日此夜离高广大床、断高广大床，乐下坐卧，或床或敷草，我于高广大床净除其心，我以此支于阿罗诃等同无异。'是故说斋。

“复次，居士妇，多闻圣弟子若持斋时，作是思惟：‘阿罗诃真人尽形寿离华鬘、璎珞、涂香、脂粉、歌舞、倡伎及往观听，断华发、璎珞、涂香、脂粉、歌舞、倡伎及往观听，彼于华鬘、璎珞、涂香、脂粉、歌舞、倡伎及往观听净除其心。我于此日此夜离华鬘、璎珞、涂香、脂粉、歌舞、倡伎及往观听，断华鬘、璎珞、涂香、脂粉、歌舞、倡伎及往观听，我于华鬘、璎珞、涂香、脂粉、歌舞、倡伎及往观听净除其心，我以此支于阿罗诃等同无异。'是故说斋。

“复次，居士妇，多闻圣弟子若持斋时，作是思惟：‘阿罗诃真人尽形寿离非时食、断非时食，一食，不夜食，乐于时食，彼于非时食净除其心。我于此日此夜离非时食、断非时食，一食，不夜食，乐于时食，我于非时食净除其心，我以此支于阿罗诃等同无异。'是故说斋。

“彼住此圣八支斋已，于上当复修习五法。云何为五？居士妇，多闻圣弟子若持斋时，忆念如来，彼世尊、如来、无所著、等正觉、明行成为、善逝、世间解、无上士、道法御、天人师，号佛、众佑。彼作如是忆念如来已，若有恶伺，彼便得灭，所有秽污恶不善法，彼亦得灭。居士妇，多闻圣弟子缘如来故，心静得喜，若有恶伺，彼便得灭，所有秽污恶不善法，彼亦得灭。

“譬若如人，头有垢腻，因膏泽、暖汤、人力、洗沐故，彼便得净。如是多闻圣弟子若持斋时，忆念如来，彼世尊、如来、无所著、等正觉、明行成为、善逝、世闻解、无上士、道法御、天人师，号佛，众佑。彼作如是忆念如来已，若有恶伺，彼便得灭，所有秽污恶不善法，彼亦得灭。居士妇，多闻圣弟子缘如来故，心静得喜，若有恶伺，彼便得灭，所有秽污恶不善法，彼亦得灭。是谓多闻圣弟子持梵斋，梵共会，因梵故，心静得喜，若有恶伺，彼便得灭，所有秽污恶不善法，彼亦得灭。

“复次，居士妇，多闻圣弟子若持斋时，忆念于法，此法世尊善说，究竟，恒不变易，正智所知，正智所见，正智所觉。彼作如是忆念法已，若有恶伺，彼便得灭，所有秽污恶不善法，彼亦得灭。居士妇，多闻圣弟子缘于法故，心静得喜，若有恶伺，彼便得灭，所有秽污恶不善法，彼亦得灭。

“犹人身有垢腻不净，因麸、澡豆、暖汤、人力、极洗浴故，身便得净。如是多闻圣弟子若持斋时，忆念于法，此法世尊善说，究竟，恒不变易，正智所知，正智所见，正智所觉。彼作如是忆念法已，若有恶伺，彼便得灭，所有秽污恶不善法，彼亦得灭。居士妇，多闻圣弟子缘于法故，心静得喜，若有恶伺，彼便得灭，所有秽污恶不善法，彼亦得灭。居士妇，是谓多闻圣弟子持法斋，法共会，因法故，心静得喜，若有恶伺，彼便得灭，所有秽污恶不善法，彼亦得灭。

“复次，居士妇，多闻圣弟子若持斋时，忆念于众，世尊弟子众善趣向质直，行要行趣，如来众中实有阿罗诃真人趣、阿罗诃果证、阿那含趣、阿那含果证、斯陀含趣、斯陀含果证、须陀洹趣、须陀洹果证，是为四双人八辈圣士，是谓世尊弟子众，成就戒、定、慧、解脱、解脱智见，可呼、可请、可供养、可奉事、可敬重，则为天人良福之田。彼作如是忆念众已，若有恶伺，彼便得灭，所有秽污恶不善法，彼亦得灭。居士妇，多闻圣弟子缘于众故，心静得喜，若有恶伺，彼便得灭，所有秽污恶不善法，彼亦得灭。

“犹如人衣有垢腻不净，因灰、皂荚、澡豆、汤水、人力浣故，彼便得净。如是多闻圣弟子若持斋时，忆念于众，世尊弟子众善趣向质直，行要行趣，如来众中实有阿罗诃真人趣、阿罗诃果证、阿那含趣、阿那含果证、斯陀含趣、欺陀含果证、须陀洹趣、须陀洹果证，是为四双人八辈圣士，是谓世尊弟子众，成就戒、定、慧、解脱、解脱智见，可呼、可请、可供养、可奉事、可敬重，则为天人良福之田。彼作如是忆念众已，若有恶伺，彼便得灭，所有秽污恶不善法，彼亦得灭。居士妇，多闻圣弟子缘于众故，心静得喜，若有恶伺，彼便得灭，所有秽污恶不善法，彼亦得灭。是谓多闻圣弟子持众斋，众共会，因众故，心静得喜，若有恶伺，彼便得灭，所有秽污恶不善法，彼亦得灭。

“复次，居士妇，多闻圣弟子若持斋时，忆念自戒，不缺不穿，无秽无污，极广极大，不望其报，智者称誉，善具善趣，善受善持。彼作如是忆念自戒已，若有恶伺，彼便得灭，所有秽污恶不善法，彼亦得灭。居士妇，多闻圣弟子缘于戒故，心静得喜，若有恶伺，彼便得灭，所有秽污恶不善法，彼亦得灭。

“犹若如镜，生垢不明，因石磨锃莹，由人力治，便得明净。如是多闻圣弟子若持斋时，忆念自戒，不缺不穿，无秽无污，极广极大，不望其报，智者称誉，善具善趣，善受善持。彼作如是忆念自戒已，若有恶伺，彼便得灭，所有秽污恶不善法，彼亦得灭。居士妇，多闻圣弟子缘于戒故，心静得喜，若有恶伺，彼秽得灭，所有秽污恶不善法，彼亦得灭。是谓多闻圣弟子持戒斋，戒共会，因戒故，心静得喜，若有恶伺，彼便得灭，所有秽污恶不善法，彼亦得灭。

“复次，居士妇，多闻圣弟子若持斋时，忆念诸天，实有四王天。彼天若成就信，于此命终，得生彼间，我亦有彼信。彼天若成就戒、闻、施、慧，于此命终，得生彼间，我亦有彼慧。实有三十三天、焰摩天、兜率陀天、化乐天、他化乐天。彼天若成就信，于此命终，得生彼间，我亦有彼信。彼天若就戒、闻、施、慧，于此命终，得生彼间，我亦有彼慧。彼作如是忆念已，及诸天信、戒、闻、施，慧，若有恶伺，彼便得灭，所有秽污恶不善法，彼亦得灭。居士妇，多闻圣弟子缘诸天故，心静得喜，若有恶伺，彼便得灭，所有秽污恶不善法，彼亦得灭。

“犹如上色金，生垢不净，因火排钻椎赤土、人力，磨拭莹治，便得明净。如是多闻圣弟子若持斋时，忆念诸天，实有四王天。彼天若成就信，于此命终，得生彼间，我亦有彼信。彼天若成就戒、闻、施、慧，于此命终，得生彼间，我亦有彼慧。实有三十三天、焰摩天、兜率陀天、化乐天，他化乐天。彼天若成就信，于此命终，得生彼间，我亦有彼信。彼天若成就戒、闻、施、慧，于此命终，得生彼间，我亦有彼慧。彼作如是忆念已，及诸天信、戒、闻、施、慧，若有恶伺，彼便得灭，所有秽污恶不善法，彼亦得灭。

“居士妇，若行如是圣八支斋，若有十六大国，谓：一者、鸯迦，二者、摩竭陀，三者、迦尸，四者、拘萨罗，五者、拘楼，六者、般阇罗，七者、阿摄贝，八者、阿和檀提，九者、枝提，十者、拔耆，十一者、跋蹉，十二、跋罗，十三、苏摩，十四、苏罗吒，十五、喻尼，十六、剑浮。此诸国中所有钱宝、金、银、摩尼、真珠、琉璃、壤伽、碧玉、珊瑚、留邵、鞞留、鞞勒、玛瑙、蝳蝐、赤石、琁珠，设使有人于中作王，随用自在者，彼一切皆持圣八支斋，不直十六分。

“居士妇，我因此故说，人王者不如天乐。若人五十岁是四王天一昼一夜，如是三十昼夜为一月，十二月为一岁，如此五百岁是四王天寿。居士妇，必有是处，若族姓男、族姓女持圣八支斋，身坏命终，生四天王中。

“居士妇，我因此故说，人王者不如天乐。若人百岁是三十三天一昼一夜，如是三十昼夜为一月，十二月为一岁，如此千岁是三十三天寿。居士妇，必有是处。若族姓男、族姓女持圣八支斋，身坏命终，生三十三天中。

“居士妇，我因此故说，人王者不如天乐。若人二百岁是焰摩天一昼一夜，如是三十昼夜为一月，十二月为一岁，如此二千岁是焰摩天寿。居士妇，必有是处。若族姓男、族姓女持圣八支斋，身坏命终，生焰摩天中。

“居士妇，我因此故说，人王者不如天乐。若人四百岁是兜率陀天一昼一夜，如是三十昼夜为一月，十二月为一岁，如此四千岁是兜率陀天寿。居士妇，必有是处，若族姓男、族姓女持圣八支斋，身坏命终，生兜率陀天中。

“居士妇，我因此故说，人王者不如天乐。若人八百岁是化乐天一昼一夜，如是三十昼夜为一月，十二月为一岁，如此八千岁是化乐天寿。居士妇，必有是处，若族姓男、族姓女持圣八支斋，身坏命终，生化乐天中。

“居士妇，我因此故说，人王者不如天乐。若人千六百岁是他化乐天一昼一夜，如是三十昼夜为一月，十二月为一岁，如此万六千岁是他化乐天寿。居士妇，必有是处，若族姓男、族姓女持圣八支斋，身坏命终，生他化乐天中。

于是，鹿子母毗舍佉叉手向佛，白曰：“世尊，圣八支斋甚奇！甚特！大利大果，有大功德，有大广布。世尊，我从今始，自尽形寿持圣八支斋，随其事力，布施修福。”

于是，鹿子母闻佛所说，善受善持，稽首佛足，绕三匝而去。

佛说如是，鹿子毋毗舍佉及诸比丘闯佛所说，欢喜奉行。

--------------

** 第55卷 晡利多品.晡利多经第二

我闻如是：一时，佛游那难大，在波和利柰园之中。

尔时，晡利多居士著白净衣，白巾裹头，拄杖执盖，著世俗屣，从园至园，从观至观，从林至林，遍游行彷徉。若见诸沙门、梵志者，便作是说：“诸贤，当知我离俗断俗，舍诸俗事。”

彼诸沙门、梵志以濡软柔和语曰：“唯然，贤晡利多离俗断俗，舍诸俗事。”

于是，晡利多居士遍游行彷徉，往诣佛所，共相问讯，当在佛前，拄杖而立。世尊告曰：“居士，有座，欲坐便坐。”

晡利多居士白曰：“瞿昙，此事不然，此事不可。所以者何？我离俗断俗，舍诸俗事，而沙门瞿昙唤我为居士耶？”

世尊答曰：“汝有相标帜如居士，是故我唤汝：‘居士，有座，欲坐便坐。'”

世尊如是复至再三告曰：“居士，有座，欲坐便坐。”

晡利多居士亦至再三白曰：“瞿昙，此事不然，此事不可。我离俗断俗，舍诸俗事，而沙门瞿昙唤我为居士耶？”

世尊答曰：“汝有相标帜如居士，是故我唤汝：‘居士，有坐，欲坐便坐。'”

世尊问曰：“汝云何离俗断俗，舍诸俗事耶？”

晡利多居士答曰：“瞿昙，我家一切所有财物尽持施儿，我无为无求游，唯往取食，存命而已，如是我离俗断俗，舍诸俗事。”

世尊告曰：“居士，圣法、律中不如是断绝俗事。居士，圣法、律中有八支断俗事也。”

于是，晡利多居士舍杖却盖，及脱俗屣，叉手向佛，白曰：“瞿昙，圣法、律中云何八支断俗事耶？”

世尊答曰：“居士，多闻圣弟子依离杀、断杀，依离不与取、断不与取，依离邪淫、断邪淫，依离妄言、断妄言，依无贪著、断贪著，依无害恚、断害恚，依无憎嫉恼、断憎嫉恼，依无增上慢、断增上慢。

“居士，多闻圣弟子云何依离杀、断杀耶？多闻圣弟子作是思惟：‘杀者必受恶报，现世及后世。若我杀者，便当自害，亦诬谤他。天及诸智梵行者道说我戒，诸方悉当闻我恶名。身坏命终，必至恶处，生地狱中。如是杀者受此恶报，现世及后世，我今宁可依离杀、断杀耶？'便依离杀、断杀，如是多闻圣弟子依离杀、断杀也。

“居士，多闻圣弟子云何依离不与取、断不与取耶？多闻圣弟子作是思惟：‘不与取者必受恶报，现世及后世。若我不与取者，便当自害，亦诬谤他。天及诸智梵行者道说我戒，诸方悉当闻我恶名。身坏命终，必至恶处，生地狱中。如是不与取者受此恶报，现世及后世，我今宁可依离不与取、断不与取耶？'便依离不与取、断不与取，如是多闻圣弟子依离不与取、断不与取也。

“居士，多闻圣弟子云何依离邪淫、断邪淫耶？多闻圣弟子作是思惟：‘邪淫者必受恶报，现世及后世。若我邪淫者，便当自害，亦诬谤他。天及诸智梵行者道说我戒，诸方悉当闻我恶名。身坏命终，必至恶处，生地狱中。如是邪淫者受此恶报，现世及后世，我今宁可依离邪淫、断邪淫耶？'便依离邪淫、断邪淫，如是多闻圣弟子依离邪淫、断邪淫也。

“居士，多闻圣弟子云何依离妄言、断妄言耶？多闻圣弟子作是思惟：‘妄言者必受恶报，现世及后世。若我妄言者，便当自害，亦诬谤他。天及诸智梵行者道说我戒，诸方悉当闻我恶名。身坏命终，必至恶处，生地狱中。如是妄言者受此恶报，现世及后世，我今宁可依离妄言、断妄言耶？'便依离妄言、断妄言，如是多闻圣弟子依离妄言、断妄言也。

“居士，多闻圣弟子云何依无贪著、断贪著耶？多闻圣弟子作是思惟：‘贪著者必受恶报，现世及后世。若我贪著者，便当自害，亦诬谤他。天及诸智梵行者道说我戒，诸方悉当闻我恶名。身坏命终，必至恶处，生地狱中。如是贪著者受此恶报，现世及后世，我今宁可依无贪著、断贪著耶？'便依无贪著、断贪著，如是多闻圣弟子依无贪著、断贪著也。

“居士，多闻圣弟子云何依无害恚、断害恚耶？多闻圣弟子作是思惟：‘害恚者必受恶报，现世及后世。若我害恚者，便当自害，亦诬谤他。天及诸智梵行者道说我戒，诸方悉当闻我恶名。身坏命终，必至恶处，生地狱中。如是害恚者受此恶报，现世及后世，我今宁可依无害恚、断害恚耶？'便依何无害恚、断害恚，如是多闻圣弟子依无害恚、断害恚也。

“居士，多闻圣弟子云何依无憎嫉恼、断憎嫉恼耶？多闻圣弟子作是思惟：‘憎嫉恼者必受恶报，现世及后世。若我憎嫉恼者，便当自害，亦诬谤他。天及诸智梵行者道说我戒，诸方悉当闻我恶名。身坏命终，必至恶处，生地狱中。如是憎嫉恼者受此恶报，现世及后世，我今宁可依无憎嫉恼、断憎嫉恼耶？'便依无憎嫉恼、断憎嫉恼，如是多闻圣弟子依无憎嫉恼、断憎嫉恼也。

“居士，多闻圣弟子云何依无增上慢、断增上慢耶？多闻圣弟子作是思惟：‘增上慢者必受恶报，现世及后世。若我增上慢者，便当自害，亦诬谤他。天及诸智梵行者道说我戒，诸方悉闻我恶名。身坏命终，必至恶处，生地狱中。如是增上慢者受此恶报，现世及后世，我今宁可依无增上慢、断增上慢耶？'便依无增上慢、断增上慢，如是多闻圣弟子依无增上慢、断增上慢也。是谓圣法、律中有八支断绝俗事。”

居士问曰：“瞿昙，圣法、律中但是断俗事？复更有耶？”

世尊答曰：“圣法、律中不但有是断绝俗事，更有八支断绝俗事得作证也。”

晡利多居士闻已，便脱白巾，叉手向佛，白曰：“瞿昙，圣法、律中云何更有八支断绝俗事得作证耶？”

世尊答曰：“居士，犹如有狗，饥饿羸乏，至屠牛处，彼屠牛师、屠牛弟子净摘除肉，掷骨与狗。狗得骨已，处处咬啮，破唇缺齿，或伤咽喉，然狗不得以此除饥。居士，多闻圣弟子亦复作是思惟：‘欲如骨锁，世尊说欲如骨锁，乐少苦多，多有灾患，当远离之。若有此舍离欲、离恶不善之法，谓此一切世间饮食永尽无余，当修习彼。'居士，犹去村不远，有小肉脔，堕在露地，或乌或鸱，持彼肉去，余乌鸱鸟竞而逐之。于居士意云何？若此乌鸱不速舍此小肉脔者，致余乌鸱竞而逐耶？”

居士答曰：“唯然，瞿昙。”

“于居士意云何？若此乌鸱能速舍此小肉脔者，余乌鸱鸟当复竞逐耶？”

居士答曰：“不也，瞿昙。”

“居士，多闻圣弟手亦复作是思惟：‘欲如肉脔，世尊说欲如肉脔，乐少苦多，多有灾患，当远离之。若有此舍离欲、离恶不善之法，谓此一切世间饮食永尽无余，当修习彼。'居士，犹如有人，手把火炬，向风而行，于居士意云何？若使此人不速舍者，必烧其手、余肢体耶？”

居士答曰：“唯然，瞿昙。”

“于居士意云何？若使此人速舍炬者，当烧其手、余肢体耶？”

居士答曰：“不也，瞿昙。”

“居士，多闻圣弟子亦复作是思惟：‘欲如火炬，世尊说欲如火炬，乐少苦多，多有灾患，当远离之。若有此舍离欲、离恶不善之法，谓此一切世间饮食永尽无余，当修习彼。'居士，犹去村不远，有大火坑，满其中火，而无烟焰。若有人来，不愚不痴，亦不颠倒，自住本心，自由自在，用乐不用苦，甚憎恶苦，用活不用死，甚憎恶死。于居士意云何？此人宁当入火坑耶？”

居士答曰：“不也，瞿昙。所以者何？彼见火坑，便作是思惟：‘若堕火坑，必死无疑；设不死者，定受极苦。'彼见火坑，便思远离，愿求舍离。”

“居士，多闻圣弟子亦复作是思惟：‘欲如火坑，世尊说欲如火坑，乐少苦多，多有灾患，当远离之。若有此舍离欲、离恶不善之法，谓此一切世间饮食永尽无余，当修习彼。'居士，犹去村不远，有大毒蛇，至恶苦毒，黑色可畏。若有人来，不愚不痴，亦不颠倒，自住本心，自由自在，用乐不用苦，甚憎恶苦，用活不用死，甚憎恶死。于居士意云何？此人宁当以手授与及余肢体，作如是说：‘蜇我！蜇我！'耶？”

居士答曰：“不也，瞿昙。所以者何？彼见毒蛇，便作是思惟：‘若我以手及余肢体使蛇蜇者，必死无疑；设不死者，定受极苦。'彼见毒蛇，便思远离，愿求舍离。”

“居士，多闻圣弟子亦复作是思惟：‘欲如毒蛇，世尊说欲如毒蛇，乐少苦多，多有灾患，当远离之。若有此舍离欲、离恶不善之法，谓此一切世间饮食永尽无余，当修习彼。'居士，犹如有人，梦得具足五欲自娱，彼若寤已，都不见一。居士，多闻圣弟子亦复作是思惟：‘欲如梦也，世尊说欲如梦也，乐少苦多，多有灾患，当远离之。若有此舍离欲、离恶不善之法，谓此一切世间饮食永尽无余，当修习彼。'

“居士，犹如有人假借乐具，或宫殿楼阁，或园观浴池，或象马车乘，或缯绵被，或指环、臂钏，或香璎珞颈钳，或金宝华鬘，或名衣上服，多人见已，而共叹曰：‘如是为善！如是为快！若有财物，应作如是极自娱乐。'其物主者，随所欲夺，或教人夺，即便自夺，或教人夺，多人见已，而共说曰：‘彼假借者，实为欺诳，非是假借。所以者何？其物主者，随所欲夺，或教人夺，即便自夺，或教人夺。'居士，多闻圣弟子亦复作是思惟：‘欲如假借，世尊说欲如假借，乐少苦多，多有灾患，当远离之。若有此舍离欲、离恶不善之法，谓此一切世间饮食永尽无余，当修习彼。'

“居士，犹去村不远，有大果树，此树常多有好美果。若有人来，饥饿羸乏，欲得食果。彼作是念：‘此树常多有好美果，我饥羸乏，欲得食果，然此树下无自落果可得饱食及持归去。我能缘树，我今宁可上此树耶？'念已便上。复有一人来，饥饿羸乏，欲得食果，持极利斧，彼作是念：‘此树常多有好美果，然此树下无自落果可得饱食及持归去。我不能缘树，我今宁可斫倒此树耶？'即便斫倒。于居土意云何？若树上人不速来下者，树倒地时，必折其臂、余肢体耶？”

居上答曰：“唯然，瞿昙。”

“于居士意云何？若树上人速来下者，树倒地时，宁折其臂、余肢体耶？”

居士答曰：“不也，瞿昙。”

“居士，多闻圣弟子亦复作是思惟：‘欲如树果，世尊说欲如树果，乐少苦多，多有灾患，当远离之。若有此舍离欲、离恶不善之法，谓此一切世间饮食永尽无余，当修习彼。'是谓圣法、律中更有此八支断绝俗事而得作证。

“居士，彼有觉、有观息，内静、一心，无觉、无观，定生喜、乐，得第二禅成就游。彼已离喜欲，舍无求游，正念正智而身觉乐，谓圣所说、圣所舍、念、乐住、空，得第三禅成就游。彼乐灭、苦灭，喜、忧本已灭，不苦不乐、舍、念、清净，得第四禅成就游。彼已如是定心清净，无秽无烦，柔软善住，得不动心，修学漏尽智通作证。彼知此苦如真，知此苦集、知此苦灭、知此苦灭道如真；知此漏如真，知此漏集、知此漏灭、知此漏灭道如真。彼如是知、如是见，欲漏心解脱，有漏、无明漏心解脱；解脱已，便知解脱：生已尽，梵行已立，所作已办，不更受有，知如真。”

说此法时，晡利多居士远尘离垢，诸法法眼生。于是，晡利多居士见法得法，觉白净法，断疑度惑，更无余尊，不复由他，无有犹豫，已住果证，于世尊法得无所畏，稽首佛足，白曰：“世尊，我今自归于佛、法及比丘众，惟愿世尊受我为优婆塞！从今日始，终身自归，乃至命尽。

“世尊，我本著白净衣，白巾裹头，拄杖执盖，及著俗屣，从园至园，从观至观，从林至林，遍游行彷徉，若见诸沙门、梵志者，便作是语：‘诸贤，我离俗、断俗、舍诸俗事。'彼诸沙门、梵志濡软柔和，语我言：‘唯然！贤晡利多离俗、断俗，舍诸俗事。'世尊，我于尔时，彼实无智安著智处，实无智祠，又无智食，实无智，奉事如智慧人。世尊，我从今日，诸比丘众及世尊弟子，此实有智，安著智慧处，实有智祠，又有智食，实有智，奉事智慧人也。

“世尊，我今再自归佛、法及比丘众，惟愿世尊受我为优婆塞！从今日始，终身自归，乃至命尽。世尊，我本所信敬重外道沙门、梵志者，从今日断。世尊，我今三自归佛、法及比丘众，惟愿世尊受我为优婆塞！从今日始，终身自归，乃至命尽。”

佛说如是，晡利多居士及诸比丘闻佛所说，欢喜奉行。

--------------

** 第56卷 晡利多品.罗摩经第三

我闻如是：一时，佛游舍卫国，在于东园鹿子母堂。

尔时，世尊则于晡时从宴坐起，堂上来下，告尊者阿难：“我今共汝至阿夷罗婆提河浴。”

尊者阿难白曰：“唯然。”

尊者阿难执持户钥，遍诣诸屋而彷徉，见诸比丘，便作是说：“诸贤，可共诣梵志罗摩家。”诸比丘闻已，便共往诣梵志罗摩家。世尊将尊者阿难往至阿夷罗婆提河，脱衣岸上，便入水浴。浴已还出，拭体著衣。

尔时，尊者阿难立世尊后，执扇扇佛。于是，尊者阿难叉手向佛，白曰：“世尊，梵志罗摩家极好整顿，甚可爱乐。惟愿世尊以慈悯故，往至梵志罗摩家！”世尊为尊者阿难默然而受，于是世尊将尊者阿难往至梵志罗摩家。

尔时，梵志罗摩家，众多比丘集坐说法，佛住门外，待诸比丘说法讫竟。众多比丘寻说法讫，默然而住，世尊知已，謦欬敲门，诸比丘闻，即往开门。世尊便入梵志罗摩家，于比丘众前敷座而坐，问曰：“诸比丘向说何等？以何事故集坐在此？”

时，诸比丘答曰：“世尊，向者说法，以此法事集坐在此。”

世尊叹曰：“善哉！善哉！比丘集坐当行二事，一曰、说法，二曰、默然。所以者何？我亦为汝说法。谛听！谛听！善思念之。”

时，诸比丘白曰：“唯然，当受教听。”

佛言：“有二种求，一曰、圣求，二曰、非圣求。

“云何非圣求？有一实病法、求病法，实老法、死法、愁忧戚法，实秽污法、求秽污法。云何实病法、求病法？云何病法耶？儿子、兄弟是病法也。象马、牛羊、奴婢、钱财、珍宝、米谷是病害法。众生于中触染贪著，骄傲受入，不见灾患，不见出要，而取用之。云何老法、死法、愁忧戚法、秽污法耶？儿子、兄弟是秽污法。象马、牛羊、奴婢、钱财、珍宝、米谷是秽污害法。众生于中染触贪著，骄傲受入，不见灾患，不见出要，而取用之。彼人欲求无病无上安隐涅槃，得无病无上安隐涅槃者，终无是处；求无老、无死、无愁忧戚、无秽污无上安隐涅槃，得无老、无死、无愁忧戚、无秽污无上安隐涅槃者，终无是处，是谓非圣求。

“云何圣求耶？有一作是念：‘我自实病法，无辜求病法。我自实老法、死法、愁忧戚法、秽污法，无辜求秽污法。我今宁可求无病无上安隐涅槃，求无老、无死、无愁忧戚、无秽污法无上安隐涅槃。'彼人便求无病无上安隐涅槃，得无病无上安隐涅槃者，必有是处；求无老、无死、无愁忧戚、无秽污无上安隐涅槃，得无老、无死、无愁忧戚、无秽污无上安隐涅槃者，必有是处。

“我本未觉无上正尽觉时，亦如是念：‘我自实病法，无辜求病法。我自实老法、死法、愁忧戚法、秽污法、无辜求秽污法。我今宁可求无病无上安隐涅槃，求无老、无死、无愁忧戚、无秽污无上安隐涅槃耶？'我时年少童子，清净青发，盛年年二十九，尔时极多乐戏，庄饰游行。我于尔时，父母啼哭，诸亲不乐。我剃除须发，著袈裟衣，至信、舍家、无家、学道，护身命清净，护口、意命清净。我成就此戒身已，欲求无病无上安隐涅槃，无老、无死、无愁忧戚、无秽污无上安隐涅槃故，更往阿罗罗伽罗摩所，问曰：‘阿罗罗，我欲于汝法行梵行，为可尔不？'阿罗罗答我曰：‘贤者，我无不可，汝欲行便行。'我复问曰：‘阿罗罗，云何汝此法自知、自觉、自作证耶？'阿罗罗答我曰：‘贤者，我度一切识处，得无所有处成就游，是故我法自知、自觉、自作证。'

“我复作是念：‘不但阿罗罗独有此信，我亦有此信；不但阿罗罗独有此精进，我亦有此精进；不但阿罗罗独有此慧，我亦有此慧。'阿罗罗于此法自知、自觉、自作证，我欲证此法故，便独住远离、空安静处，心无放逸，修行精勤。我独住远离、空安静处，心无放逸，修行精勤已，不久得证彼法。证彼法已，复往诣阿罗罗伽罗摩所，问曰：‘阿罗罗，此法自知、自觉、自作证，谓度一切无量识处，得无所有处成就游耶？'阿罗罗伽罗摩答我曰：‘贤者，我是法自知、自觉、自作证，谓度无量识处，得无所有处成就游。'阿罗罗伽罗摩复语我曰：‘贤者，是为如我此法作证，汝亦然；如汝此法作证，我亦然。贤者，汝来共领此众。'是为阿罗罗伽罗摩师处，我与同等，最上恭敬、最上供养、最上欢喜。

“我复作是念：‘此法不趣智，不趣觉，不趣涅槃，我今宁可舍此法，更求无病无上安隐涅槃，求无老、无死、无愁忧戚、无秽污无上安隐涅槃。'我即舍此法，便求无病无上安隐涅槃，求无老、无死、无愁忧戚、无秽污无上安隐涅槃已，往诣郁陀罗罗摩子所，问曰：‘郁陀罗，我欲于汝法中学，为可尔不？'郁陀罗罗摩子答我曰：‘贤者，我无不可，汝欲学便学。'我复问曰：‘郁陀罗，汝父罗摩自知、自觉、自作证何等法耶？'郁陀罗罗摩子答我曰：‘贤者，度一切无所有处，得非有想非无想处成就游。贤者，我父罗摩自知、自觉、自作证，谓此法也。'

“我复作是念：‘不但罗摩独有此信，我亦有此信；不但罗摩独有此精进，我亦有此精进；不但罗摩独有此慧，我亦有此慧。罗摩自知、自觉、自作证此法，我何故不得自知、自觉、自作证此法耶？'我欲证此法故，便独往远离、空安静处，心无放逸，修行精勤。我独住远离、空安静处，心无放逸，修行精勤已，不久得证彼法。证彼法已，复往郁陀罗罗摩子所，问曰：‘郁陀罗，汝父罗摩，是法自知、自觉、自作证，谓度一切无所有处，得非有想非无想处成就游耶？'郁陀罗罗摩子答我曰：‘贤者，我父罗摩，是法自知、自觉、自作证，谓度一切无所有处，得非有想非无想处成就游。'郁陀罗复语我曰：‘如我父罗摩此法作证，汝亦然；如汝此法作证，我父亦然。贤者，汝来共领此众。'郁陀罗罗摩子同师处，我亦如师，最上恭敬、最上供养、最上欢喜。

“我复作是念：‘此法不趣智，不趣觉，不趣涅槃，我今宁可舍此法，更求无病无上安隐涅槃，求无老、无死、无愁忧戚、无秽污无上安隐涅槃。'我即舍此法，便求无病无上安隐涅槃，求无老、无死、无愁忧戚、无秽污无上安隐涅槃已，往象顶山南，郁鞞罗梵志村，名曰斯那，于彼中地至可爱乐，山林郁茂，尼连禅河清流盈岸。我见彼已，便作是念：‘此地至可爱乐，山林郁茂，尼连禅河清流盈岸。若族姓子欲有学者，可于中学，我亦当学，我今宁可于此中学。'即便持草往诣觉树，到已布下敷尼师檀，结跏趺坐，要不解坐，至得漏尽。我便不解坐，至得漏尽。我求无病无上安隐涅槃，便得无病无上安隐涅槃；求无老、无死、无愁忧戚、无秽污无上安隐涅槃，便得无老、无死、无愁忧戚、无秽污无上安隐涅槃。生知生见，定道品法，生已尽，梵行已立，所作已办，不更受有，知如真。

“我初觉无上正尽觉已，便作是念：‘我当为谁先说法耶？'我复作是念：‘我今宁可为阿罗罗伽摩先说法耶？'尔时有天，住虚空中，而语我曰：‘大仙人，当知阿罗罗伽摩彼命终来至今七日。'我亦自知阿罗罗伽摩其命终来得今七日。我复作是念：‘阿罗罗伽摩，彼人长衰不闻此法；若闻此者，速知法次法。'

“我初觉无上正尽觉已，作如是念：‘我当为谁先说法耶？'我复作是念：‘我今宁可为郁陀罗罗摩子先说法耶？'天复住空，而语我曰：‘大仙人，当知郁陀罗罗摩子命终已来二七日也。'我亦自知郁陀罗罗摩子命终已来二七日也。我复作是念：‘郁陀罗罗摩子，彼人长衰不闻此法；若闻法者，速知法次法。'

“我初觉无上正尽觉已，作如是念：‘我当为谁先说法耶？'我复作是念：‘昔五比丘为我执劳，多所饶益。我苦行时，彼五比丘承事于我，我今宁可为五比丘先说法耶？'我复作是念：‘昔五比丘今在何处？'我以清净天眼出过于人，见五比丘在波罗柰仙人住处鹿野园中。我随住觉树下，摄衣持钵，往波罗柰加尸都邑。尔时，异学优陀遥见我来，而语我曰：‘贤者瞿昙，诸根清净，形色极妙，面光照耀。贤者瞿昙，师为是谁？从谁学道？为信谁法？'我于尔时即为优陀说偈答曰：

<div class="poem">

‘我最上最胜，不著一切法，\\
诸爱尽解脱，自觉谁称师？\\
无等无有胜，自觉无上觉，\\
如来天人师，普知成就力。'

</div>

“优陀问我曰：‘贤者瞿昙，自称胜耶？'我复以偈而答彼曰：

<div class="poem">

‘胜者如是有，谓得诸漏尽，\\
我害诸恶法，优陀故我胜。'

</div>

“优陀复问我曰：‘贤者瞿昙，欲至何处？'我时以偈而答彼曰：

<div class="poem">

‘我至波罗柰，系妙甘露鼓，\\
转无上法轮，世所未曾转。'

</div>

“优陀语我曰：‘贤者瞿昙，或可有是。'如是语已，即彼邪道经便还去。我自往至仙人住处鹿野园中。时，五比丘遥见我来，各相约敕而立制曰：‘诸贤，当知此沙门瞿昙来，多欲多求，食妙饮食，好粳粮饭，及麦酥蜜，麻油涂体，今复来至。汝等但坐，慎莫起迎，亦莫作礼，预留一座，莫请令坐，到已语曰：“卿，欲坐者，自随所欲。”'我时往至五比丘所，时，五比丘于我不堪极妙威德，即从座起，有持衣钵者，有敷床者，有取水者，欲洗足者。我作是念：‘此愚痴人！何无牢固，自立制度还违本要？'我知彼已，坐五比丘所敷之座。

“时，五比丘呼我姓字，及卿于我，我语彼曰：‘五比丘，我如来、无所著、正尽觉，汝等莫称我本姓字，亦莫卿我。所以者何？我求无病无上安隐涅槃，得无病无上安隐涅槃；我求无老、无死、无愁忧戚、无秽污无上安隐涅槃，得无老、无死、无愁忧戚、无秽污无上安隐涅槃。生知生见，定道品法，生已尽，梵行已立，所作已办，不更受有，知如真。'彼语我曰：‘卿瞿昙，本如是行，如是道迹，如是苦行，尚不能得人上法差降圣知圣见，况复今日多欲多求，食妙饮食，好梗粮饭，及麦酥蜜，麻油涂体耶？'我复语曰：‘五比丘，汝等本时见我如是诸根清净，光明照耀耶？'时，五比丘复答我曰：‘本不见卿诸根清净，光明照耀。卿瞿昙，今诸根清净，形色极妙，面光照耀。'

“我于尔时即告彼曰：‘五比丘，当知有二边行，诸为道者所不当学：一曰、著欲乐下贱业凡人所行；二曰、自烦自苦，非贤圣法，无义相应。五比丘，舍此二边，有取中道，成明成智，成就于定，而得自在，趣智趣觉，趣于涅槃，谓八正道，正见乃至正定，是谓为八。'意欲随顺教五比丘，教化二人，三人乞食，三人持食来，足六人食。教化三人，二人乞食，二人持食来，足六人食。我如是教，如是化彼，求无病无上安隐涅槃，得无病无上安隐涅槃；求无老、无死、无愁忧戚、无秽污无上安隐涅槃，得无老、无死、无愁忧戚、无秽污无上安隐涅槃。生知生见，定道品法，生已尽、梵行已立，所作已办，不更受有，知如真。

“于是，世尊复告彼曰：‘五比丘，有五欲功德可爱、可乐、可意所念，善欲相应。云何为五？眼知色，耳知声，鼻知香，舌知味，身知触。五比丘，愚痴凡夫而不多闻，不见善友，不知圣法，不御圣法。彼触染贪著，骄傲受入，不见灾患，不见出要，而取用之。当知彼随弊魔，自作弊魔，堕弊魔手，为魔网缠，魔网所缠，不脱魔缠。五比丘，犹如野鹿，为网所缠，当知彼随猎师，自作猎师，堕猎师手，为猎师网缠，猎师来已，不能得脱。如是，五比丘，愚痴凡夫而不多闻，不见善友，不知圣法，不御圣法。彼于此五欲功德触染贪著，骄傲受入，不见灾患，不见出要，而取用之。当知彼随弊魔，自作弊魔，堕弊魔手，为魔网缠，魔网所缠，不脱魔缠。

“‘五比丘，多闻圣弟子见善知识，而知圣法，又御圣法。彼于此五欲功德，不触、不染、不贪、不著，亦不骄傲、不受入，见灾患，见出要，而取用之。当知彼不随弊魔，不自作魔，不堕魔手，不为魔网所缠，不为魔网所缠，便解脱魔缠。五比丘，犹如野鹿得脱于缠，当知彼不随猎师，不自在猎师，不堕猎师手，不为猎师网所缠，猎师来已，则能得脱。如是，五比丘，多闻圣弟子见善知识而知圣法，又御圣法，彼于此五欲功德，不触、不染、不贪、不著，亦不见骄傲、不受入，见灾患，见出要，而取用之。当知彼不随弊魔，不自作魔，不堕魔手，不为魔网所缠，不为魔网所缠，便解脱魔缠。

“‘五比丘，若时如来出兴于世，无所著、等正觉、明行成为、善逝、世间解、无上士、道法御、天人师，号佛、众佑，彼断乃至五盖、心秽、慧羸，离欲、离恶不善之法至得第四禅成就游。彼如是定心清净，无秽无烦，柔软善住，得不动心，修学漏尽智通作证。彼知此苦如真，知此苦集、知此苦灭、知此苦灭道如真；知此漏如真，知此漏集、知此漏灭、知此漏灭道如真。彼如是知、如是见，欲漏心解脱，有漏、无明漏心解脱；解脱已，便知解脱：生已尽，梵行已立，所作已办，不更受有，知如真。彼于尔时自在行、自在住、自在坐、自在卧。所以者何？彼自见无量恶不善法尽，是故彼自在行、自在住、自在坐、自在卧。

“‘五比丘，犹如无事无人民处，彼有野鹿，自在行、自在往、自在坐、自在卧。所以者何？彼野鹿不在猎师境界，是故自在行、自在住、自在坐、自在卧。如是，五比丘，比丘漏尽得无漏，心解脱、慧解脱，自知、自觉、自作证成就游：生已尽，梵行已立，所作已办，不更受有，知如真。彼于尔时自在行、自在住、自在坐、自在卧。所以者何？彼自见无量恶不善法尽，是故彼自在行、自在住、自在坐、白在卧。五比丘，是说无余解脱，是说无病无上安隐涅槃，是说无老、无死、无愁忧戚、无秽污无上安隐涅槃。'”

佛说如是，尊者阿难及诸比丘闻佛所说，欢喜奉行。

--------------

** 第56卷 晡利多品.五下分结经第四

我闻如是：一时，佛游舍卫国，在胜林给孤独园。

尔时，世尊告诸比丘：“我曾说五下分结，汝等受持耶？”诸比丘默然不答。

世尊复再三告诸比丘：“我曾说五下分结，汝等受持耶？”诸比丘亦再三默然不答。

尔时，尊者鬘童子在彼众中。于是，尊者鬘童子即从座起，偏袒著衣，叉手向佛。白曰：“世尊曾说五下分结，我受持之。”

世尊问曰：“鬘童子，我曾说五下分结，汝受持耶？”

尊者鬘童子答曰：“世尊曾说欲初下分结，是我受持，恚、身见、戒取、疑，世尊说第五下分结，是我受持。”

世尊诃曰：“鬘童子，汝云何受持我说五下分结？鬘童子，汝从何口受持我说五下分结耶？鬘童子，非为众多异学来，以婴孩童子责数喻诘责汝耶？鬘童子，婴孩幼小，柔软仰眠，意无欲想，况复欲心缠住耶？然彼性使故，说欲使。鬘童子，婴孩幼小，柔软仰眠，无众生想，况复恚心缠住耶？然彼性使故，说恚使。鬘童子，婴孩幼小，柔软仰眠，无自身想，况复身见心缠住耶？然彼性使故，说身见使。鬘童子，婴孩幼小，柔软仰眠，无有戒想，况复戒取必缠往耶？然彼性使故，说戒取使。鬘童子，婴孩幼小，柔软仰眠，无有法想，况复疑心缠往耶？然彼性使故，说疑使。鬘童子，非为众多异学来，以此婴孩童子责数喻诘责汝耶？”于是，尊者鬘童子为世尊面诃责已，内怀忧戚，低头默然，失辩无言，如有所伺。

彼时，世尊面前诃责鬘童子已，默然而住。尔时，尊者阿难立世尊后，执扇扇佛。于是，尊者阿难叉手向佛，白曰：“世尊，今正是时。善逝，今正是时。若世尊为诸比丘说五下分结者，诸比丘从世尊闻已，善受善持。”

世尊告曰：“阿难，谛听！善思念之。”

尊者阿难白曰：“唯然，当受教听。”

佛言：“阿难，或有一为欲所缠，欲心生已，不知舍如真；彼不知舍如真已，欲转炽盛，不可制除，是下分结。阿难，或有一为恚所缠，恚心生已，不知舍如真；彼不知舍如真已，恚转炽盛，不可制除，是下分结。阿难，或有一为身见所缠，身见心生已，不知舍如真；彼不知舍如真已，身见转盛，不可制除，是下分结。阿难，或有一为戒取所缠，戒取心生已，不知舍如真；彼不知舍如真已，戒取转盛，不可制除，是下分结。阿难，或有一为疑所缠，疑心生已，不知舍如真；彼不知舍如真已，疑转炽盛，不可制除，是下分结。

“阿难，若依道、依迹、断五下分结；彼不依此道、不依此迹，断五下分结者，终无是处。阿难，犹如有人欲得求实，为求实故，持斧入林。彼人见树成就根、茎、枝、叶及实，彼人不截根、茎，得实归者，终无是处。如是，阿难，若依道、依迹，断五下分结；不依此道、不依此迹，断五下分结者，终无是处。阿难，若依道、依迹，断五下分结；彼依此道、依此迹，断五下分结者，必有是处。阿难，犹如有人欲得求实，为求实故，持斧入林。彼人见树成就根、茎、枝、叶及实，彼人截根、茎，得实归者，必有是处。如是，阿难，若依道、依迹，断五下分结；依此道、依此迹，断五下分结者，必有是处。

“阿难，依何道、依何迹，断五下分结？阿难，或有一不为欲所缠，若生欲缠，即知舍如真；彼知舍如真已，彼欲缠便灭。阿难，或有一不为恚所缠，若生恚缠，即知舍如真；彼知舍如真已，彼恚缠便灭。阿难，或有一不为身见所缠，若生身见缠，即知舍如真；彼知舍如真已，彼身见缠便灭。阿难，或有一不为戒取所缠，若生戒取缠，即知舍如真；彼知舍如真已，彼戒取便灭。阿难，或有一不为疑所缠，若生疑缠，即知舍如真；彼知舍如真已，彼疑缠便灭。阿难，依此道、依此迹，断五下分结。

“阿难，犹恒伽河，其水溢岸。若有人来彼岸，有事欲得度河，彼作是念：‘此恒伽河，其水溢岸。我于彼岸有事欲度，身无有力令我安隐浮至彼岸。'阿难，当知彼人无力。如是，阿难，若有人觉、灭、涅槃，其心不向而不清净，不住解脱，阿难，当知此人如彼羸人无有力也。阿难，犹恒伽河，其水溢岸。若有人来彼岸，有事欲得度河，彼作是念：‘此恒伽河，其水溢岸。我于彼岸有事欲度，身今有力令我安隐浮至彼岸。'阿难，当知彼人有力。如是，阿难，若有人觉、灭、涅槃，心向清净而住解脱，阿难，当知此人如彼有力人。

“阿难，犹如山水，甚深极广，长流驶疾，多有所漂，其中无船，亦无桥梁。或有人来彼岸，有事则便求度，彼求度时而作是念：‘今此山水甚深极广，长流驶疾，多有所漂，其中无船，亦无桥梁而可度者。我于彼岸有事欲度，当以何方便令我安隐至彼岸耶？'复作是念：‘我今宁可于此岸边收聚草木，缚作椑筏，乘之而度。'彼便岸边收聚草木，缚作椑筏，乘之而度，安隐至彼。如是，阿难，若有比丘攀缘厌离，依于厌离，住于厌离，止息身恶故，心入离、定故，离欲、离恶不善之法，有觉、有观，离生喜、乐，得初禅成就游。彼依此处，观觉兴衰；彼依此处，观觉兴衰已，住彼必得漏尽。设住彼不得漏尽者，必当升进得止息处。

“云何升进得止息处？彼觉、观已息，内静、一心，无觉、无观，定生喜、乐，得第二禅成就游。彼依此处，观觉兴衰；彼依此处，观觉兴衰已，住彼必得漏尽。设住彼不得漏尽者，必当升进得止息处。云何升进得止息处？彼离于喜欲，舍无求游，正念正智而身觉乐，谓圣所说、圣所舍、念、乐住、空，得第三禅成就游。彼依此处，观觉兴衰；彼依此处，观觉兴衰已，住彼必得漏尽。设住彼不得漏尽者，必当升进得止息处。

“云何升进得止息处？彼乐灭、苦灭、喜、忧本已灭，不苦不乐、舍、念、清净，得第四禅成就游。彼依此处，观觉兴衰；彼依此处，观觉兴衰已，住彼必得漏尽。设住彼不得漏尽者，必当升进得止息处。

“云何升进得止息处？彼度一切色想，灭有碍想，不念若干想，无量空，是无量空处成就游；彼依此处，观觉兴衰。彼依此处，观觉兴衰已，住彼必得漏尽。设住彼不得漏尽者，必当升进得止息处。

“云何升进得止息处？彼度一切无量空处，无量识，是无量识处成就游。彼依此处，观觉兴衰；彼依此处，观觉兴衰已，住彼必得漏尽。设住彼不得漏尽者，必当升进得止息处。

“云何升进得止息处？彼度一切无量识处，无所有，无所有处成就游。彼若有所觉，或乐或苦，或不苦不乐。彼观此觉无常，观兴衰、观无欲、观灭、观断、观舍；彼如是观此觉无常，观兴衰、观无欲、观灭、观断、观舍已，便不受此世；不受此世已，便不恐怖；因不恐怖，便般涅槃：生已尽，梵行已立，所作已办，不更受有，知如真。

“犹去村不远，有大芭蕉，若人持斧破芭蕉树，破作片，破为十分，或作百分。破为十分，或作百分已，便擗叶叶，不见彼节，况复实耶？阿难，如是比丘若有所觉，或乐或苦，或不苦不乐。彼观此觉无常，观兴衰、观无欲、观灭、观断、观舍；彼如是观此觉无常，观兴衰、观无欲、观灭、观断、观舍已，便不受此世；不受此世已，便不恐怖；因不恐怖已，便般涅槃：生已尽、梵行已立，所作已办，不更受有，知如真。”

于是，尊者阿难叉手向佛，白曰：“世尊，甚奇！甚特！世尊为诸比丘依依立依，说舍离漏，说过度漏，然诸比丘不速得无上，谓毕究竟尽。”

世尊告曰：“如是，阿难。如是，阿难。甚奇！甚特！我为诸比丘依依立依，说舍离漏，说过度漏，然诸比丘不速得无上，谓毕究竟尽。所以者何？人有胜如故，修道便有精粗。修道有精粗故，人便有胜如。阿难，是故我说人有胜如。”

佛说如是，尊者阿难及诸比丘闻佛所说，欢喜奉行。

--------------

** 第56卷 晡利多品.心秽经第五

我闻如是：一时，佛游舍卫国，在胜林给孤独园。

尔时，世尊告诸比丘：“若比丘、比丘尼不拔心中五秽，不解心中五缚者，是为比丘、比丘尼说必退法。

“云何不拔心中五秽？或有一疑世尊，犹豫、不开意、不解意、意不静。若有一疑世尊，犹豫、不开意、不解意、意不静者，是谓不拔第一心秽，谓于世尊也。如是法、戒、教，若有诸梵行，世尊所称誉，彼便责数、轻易、触娆、侵害，不开意、不解意、意不静，是谓第五不拔心中秽，谓于梵行也。

“云何不解心中五缚？或有一身不离染、不离欲、不离爱、不离渴。若有身不离染、不离欲、不离爱、不离渴者，彼心不趣向，不静、不住、不解，自方便断宴坐。若有此心不趣向，不静、不住、不解，自方便断宴坐者，是谓第一不解心缚，谓身也。

“复次，于欲不离染、不离欲、不离爱、不离渴。若有于欲不离染、不离欲、不离爱、不离渴者，彼心不趣向，不静、不住、不解，自方便断宴坐。若有此心不趣向，不静、不住、不解，自方便断宴坐者，是谓第二不解心缚，谓欲也。

“复次，有一所说圣义相应，柔软无疑盖，谓说戒、说定、说慧、说解脱、说解脱知见、说损、说不聚会、说少欲、说知足、说断、说无欲、说灭、说宴坐、说缘起。如是比丘，沙门所说者，彼心不趣向，不静、不住、不解，自方便断宴坐。若有此心不趣向，不静、不住、不解，自方便断宴坐者，是谓第三不解心缚，谓说也。

“复次，数道俗共会，掉乱、骄傲、不学问。若有数道俗共会，掉乱、骄傲、不学问者，彼心不趣向，不静、不住、不解，自方便断宴坐。若此心不趣向，不静、不住、不解，自方便断宴坐者，是谓第四不解心缚，谓聚会也。

“复次，少有所得故，于其中间住，不复求升进。若有少所得故，于其中间住，不复求升进者，彼心不趣向，不静、不住、不解，自方便断宴坐。若此心不趣向，不静、不住、不解，自方便断宴坐者，是谓第五不解心缚，谓升进也。

“若有比丘、比丘尼不拔此心中五秽，及不解此心中五缚者，是谓比丘、比丘尼必退法也。若有比丘、比丘尼善拔心中五秽，善解心中五缚者，是谓比丘、比丘尼清净法。

“云何善拔心中五秽？或有一不疑世尊，不犹豫、开意、意解、意静。若有不疑世尊，不犹豫、开意、意解、意静者，是谓第一善拔心中秽，谓于世尊也。如是法、戒、教，若有梵行，世尊所称誉，彼不责数、不轻易、不触娆、不侵害，开意、意解、意静，是谓第五善拔心中秽，谓于梵行也。

“云何解心中五缚？或有一身离染、离欲、离爱、离渴。若有身离染、离欲、离爱、离渴者，彼心趣向，静、住、解，自方便断宴坐。若有此心趣向，静、住、解，自方便断宴坐者，是谓第一解心中缚，谓身也。

“复次，于欲离染、离欲、离爱、离渴。若有于欲离染、离欲、离爱、离渴者，彼心趣向，静、住、解，自方便断宴坐。若有此心趣向，静、住、解，自方便断宴坐者，是谓第二解心中缚，谓欲也。

“复次，有一所说，圣义相应，柔软无疑盖，谓说戒、说定、说慧、说解脱、说解脱知见、说损、说不聚会、说少欲、说知足、说断、说无欲、说灭、说宴坐、说缘起，如是比丘，沙门所说者，彼心趣向，静、住、解，自方便断宴坐。若有此心趣向，静、住、解，自方便断宴坐者，是谓第三解心中缚，谓说也。

“复次，不数道俗共会，不掉乱、不骄傲学问。若有不数道俗共会，不掉乱、不骄傲学问者，彼心趣向，静、住、解，自方便断宴坐。若有此必趣向，静、往、解，自方便断宴坐者，是谓第四解心中缚，谓不聚会也。

“复次，少有所得故，于其中间不住，复求升进。若有少所得故，于其中间不住，复求升进者，彼心趣向，静、住、解，自方便断宴坐。若此心趣向，静、住、解，自方便断宴坐者，是谓第五解心中缚，谓升进也。

“若有比丘、比丘尼善拔此心中五秽，及善解此心中五缚者，是谓比丘、比丘尼清净法。彼住此十支已，复修习五法。云何为五？修欲定心成就断如意足，依离、依无欲、依灭、依舍，趣向非品。修精进定、心定、思惟定成就断如意足，依离、依无欲、依灭、依舍，趣向非品，堪任第五。

“彼成就此堪任等十五法，成就自受者，必知必见，必正尽觉，至甘露门，近住涅槃，我说无不至涅槃。犹如鸡生十卵，或十二，随时覆盖，随时温暖，随时看视。鸡设有放逸者，彼中或鸡子以[唯/乃]以足，啄破其卵，自安隐出者，彼为第一。如是比丘成就此堪任等十五法自受者，必知必见，必正尽觉，必至甘露门，近住涅槃，我说无不得涅槃。”

佛说如是，彼诸比丘闻佛所说，欢喜奉行。

--------------

** 第57卷 晡利多品.箭毛经上第六

我闻如是：一时，佛游王舍城，在竹林伽兰哆园，与大比丘众俱，千二百五十人而受夏坐。

尔时，世尊过夜平旦，著衣持钵，入王舍城而行乞食。行乞食已，收举衣钵，澡洗手足，以尼师檀著于肩上，往至孔雀林异学园中。

尔时，孔雀林异学园中有一异学，名曰箭毛，名德宗主，众人所师，有大名誉，众所敬重，领大徒众，五百异学之所尊也。彼在大众喧闹娆乱，放高大音声，说种种畜生之论，谓论王、论贼、论斗、论食、论衣服、论妇人、论童女、论淫女、论世间、论空野、论海中、论国人民。彼共集坐论如是比畜生之论。异学箭毛遥见佛来，敕己众曰：“汝等默然住，彼沙门瞿昙来，彼众默然，常乐默然，称说默然，彼若见此众默然者，或来相见。”异学箭毛令众默然已，自默然住。

世尊往诣异学箭毛所，异学箭毛即从座起，偏袒著衣，叉手向佛，白曰：“善来！沙门瞿昙，沙门瞿昙久不来此，愿坐此座。”世尊便坐异学箭毛所敷之座。异学箭毛则与世尊共相问讯，却坐一面。

世尊问曰：“优陀夷，向论何等？以何事故共集坐此？”

异学箭毛答曰：“瞿昙，且置此论，此论非妙。沙门瞿昙欲闻此论，后闻不难。”

世尊如是再三问曰：“优陀夷，向论何等？以何事故共集坐此？”

异学箭毛亦再三答曰：“瞿昙，且置此论，此论非妙。沙门瞿昙欲闻此论，后闻不难。沙门瞿昙若至再三，其欲闻者，今当说之。瞿昙，我等与拘萨罗国众多梵志，悉共集坐拘萨罗学堂，说如是论：鸯伽摩竭陀国人有大善利，鸯伽摩竭陀国人得大善利，如此大福田众在王舍城共受夏坐，谓不兰迦葉。所以者何？瞿昙，不兰迦葉名德宗主，众人所师，有大名誉，众所敬重，领大徒众，五百异学之所尊也，于此王舍城共受夏坐。如是摩息迦利瞿舍利子、裟若鞞罗迟子、尼揵亲子、波复迦旃、阿夷哆鸡舍剑婆利。

“瞿昙，阿夷哆鸡舍剑婆利名德宗主，众人所师，有大名誉，众所敬重，领大徒众，五百异学之所尊也，于此王舍城共受夏坐。向者亦论沙门瞿昙，此沙门瞿昙名德宗主，众人所师，有大名誉，众所敬重，领大比丘众，千二百五十人之所尊也，亦在此王舍城共受夏坐。

“瞿昙，我等复作是念：‘今此诸尊沙门、梵志，谁为弟子所恭敬、尊重、供养、奉事耶？非为弟子法骂所骂，亦无弟子难师，此一向不可、不相应，不等说已，便舍而去？'瞿昙，我等复作是念：‘此不兰迦葉不为弟子所恭敬，尊重、供养、奉事，为弟子法骂所骂，众多弟子难师，此不可，此不相应，此不等说已，便舍而去。'瞿昙，昔时不兰迦葉数在弟子众举手大唤：‘汝等可住，无有人来问汝等事，人问我事，汝等不能断此事，我能断此事。'而弟子于其中间更论余事，不待师说事讫。瞿昙，我等复作是念：‘如是此不兰迦葉不为弟子所恭敬、尊重、供养、奉事，为弟子法骂所骂，众多弟子难师，此不可，此不相应，此不等说已，便舍而去。'

“如是摩息加利瞿舍利子、娑若鞞罗迟子、尼揵亲子、彼复迦旃、阿夷哆鸡舍剑婆利。瞿昙，我等作如是念：‘此阿夷哆鸡舍剑婆利不为弟子所恭敬、尊重、供养、奉事，为弟子法骂所骂，众多弟子难师，此不可，此不相应，此不等说已，便舍而去。'瞿昙，昔时阿夷哆鸡舍剑婆利数在弟子众举手大唤：‘汝等可住，无有人来问汝等事，人问我事，汝等不能断此事，我能断此事。'而弟子于其中间更论余事，不待师说事讫。瞿昙，我等复作是念：‘如是此阿夷哆鸡舍剑婆利不为弟子所恭敬、尊重、供养、奉事，为弟子法骂所骂，众多弟子难师，此不可，此不相应，此不等说已，便舍而去。'

“瞿昙，我等复作是念：‘此沙门瞿昙为弟子所恭敬、尊重、供养、奉事，不为弟子法骂所骂，亦无弟子难师，此不可，此不相应，此不等说已，便舍而去。'瞿昙，昔时沙门瞿昙数在大众，无量百千众围绕说法，于其中有一人鼾眠作声，又有一人语彼人曰：‘莫鼾眠作声！汝不欲闻世尊说微妙法，如甘露耶？'彼人即便默然无声。瞿昙，我等复作是念：‘如是此沙门瞿昙为弟子所恭敬、尊重、供养、奉事，不为弟子法骂所骂，亦无弟子难师，此不可，此不相应，此不等说已，便舍而去。'”

世尊闻已，问异学箭毛曰：“优陀夷，汝见我有几法，令诸弟子恭敬、尊重、供养、奉事我，常随不离耶？”

异学箭毛答曰：“瞿昙，我见瞿昙有五法，令诸弟子恭敬、尊重、供养、奉事，常随不离。云何为五？沙门瞿昙粗衣知足，称说粗衣知足。若沙门瞿昙粗衣知足，称说粗衣知足者，是谓我见沙门瞿昙有第一法，令诸弟子恭敬、尊重、供养、奉事，常随不离。复次，沙门瞿昙粗食知足，称说粗食知足。若沙门瞿昙粗食知足，称说粗食知足者，是谓我见沙门瞿昙有第二法，令诸弟子恭敬、尊重、供养、奉事，常随不离。复次，沙门瞿昙少食，称说少食。若沙门瞿昙少食，称说少食者，是谓我见沙门瞿昙有第三法，令诸弟子恭敬、尊重、供养、奉事，常随不离。复次，沙门瞿昙粗住止床座知足，称说粗住止床座知足。若沙门瞿昙粗住止床座知足，称说粗住止床座知足者，是谓我见沙门瞿昙有第四法，令诸弟子恭敬、尊重、供养、奉事、常随不离。复次，沙门瞿昙宴坐、称说宴坐。若沙门瞿昙宴坐，称说宴坐者，是谓我见沙门瞿昙有第五法，令诸弟子恭敬、尊重、供养、奉事，常随不离。是谓我见沙门瞿昙有五法，令诸弟子恭敬、尊重、供养、奉事、常随不离。”

世尊告曰：“优陀夷，我不以此五法，令诸弟子恭敬、尊重、供养、奉事我，常随不离。优陀夷，我所持衣，随圣力割截，染污恶色，如是圣衣染污恶色。优陀夷，或我弟子谓尽形寿衣所弃舍粪扫之衣，亦作是说：‘我世尊粗衣知足，称说粗衣知足。'优陀夷，若我弟子因粗衣知足故，称说我者，彼因此处故，不恭敬、尊重、供养、奉事我，亦不相随。

“复次，优陀夷，我食粳粮成熟，无䵃[kuàng]无量杂味。优陀夷，或我弟子尽其形寿而行乞食所弃舍食，亦作是说：‘我世尊粗食知足，称说粗食知足。'优陀夷，若我弟子因粗食知足故，称说我者，彼因此处故，不恭敬、尊重、供养、奉事我，亦不相随。

“复次，优陀夷，我食如一鞞罗食，或如半鞞罗。优陀夷，或我弟子食如一拘拖，或如半拘拖，亦作是说：‘我世尊少食，称说少食。'优陀夷，若我弟子因少食故，称说我者，彼因此处故，不恭敬、尊重、供养、奉事我，亦不相随。

“复次，优陀夷，我或住高楼，或住棚阁。优陀夷，或我弟子彼过九月、十月，一夜于覆处宿，亦作是说：‘我世尊粗住止床座知足，称说粗住止床座知足。'优陀夷，若我弟子因粗住止床座知足故，称说我者，彼因此处故，不恭敬、尊重、供养、奉事我，亦不相随。

“复次，优陀夷，我常作闹比丘、比丘尼、优婆塞、优婆夷，或我弟子过半月一入众，为法清净故，亦作是说：‘我世尊宴坐，称说宴坐。'优陀夷，若我弟子因宴坐故，称说我者，彼因此处故，不恭敬、尊重、供养、奉事我，亦不相随。优陀夷，我无此五法，令诸弟子恭敬、尊重、供养、奉事我，常随不离。

“优陀夷，我更有五法，令诸弟子恭敬、尊重、供养、奉事我，常随不离。云何为五？优陀夷，我有弟子，谓无上戒称说我：‘世尊行戒大戒，如所说所作亦然，如所作所说亦然。'优陀夷，若我弟子因无上戒称说我者，彼因此处，恭敬、尊重、供养、奉事我，常随不离。

“复次，优陀夷，我有弟子，谓无上智慧称说我：‘世尊行智慧，极大智慧，若有谈论来相对者，必能伏之，谓于正法、律不可说，于自所说不可得说。'优陀夷，若我弟子因无上智慧故，称说我者，彼因此处，恭敬、尊重、供养、奉事我，常随不离。

“复次，优陀夷，我有弟子，谓无上知见称说我：‘世尊遍知非不知，遍见非不见，彼为弟子说法，有因非无因，有缘非无缘，可答非不可答，有离非无离。'优陀夷，若我弟子因无上知见故，称说我者，彼因此处，恭敬、尊重、供养、奉事我，常随不离。

“复次，优陀夷，我有弟子，谓厌爱箭而来问我：‘苦是苦，集是集，灭是灭，道是道？'我即答彼：‘苦是苦，集是集，灭是灭，道是道。'优陀夷，若我弟子而来问我，我答可意令欢喜者，彼因此处，恭敬、尊重、供养、奉事我，常随不离。

“复次，优陀夷，我为弟子或说宿命智通作证明达，或说漏尽智通作证明达。优陀夷，若我弟子于此正法、律中得受得度，得至彼岸，无疑无惑，于善法中无有犹豫者，彼因此处，恭敬、尊重、供养、奉事我，常随不离。优陀夷，是谓我更有五法，令诸弟子恭敬、尊重、供养、奉事我，常随不离。”

于是，异学箭毛即从座起，偏袒著衣，叉手向佛，白曰：“瞿昙，甚奇！甚特！善说妙事，润泽我体，犹如甘露。瞿昙，犹如大雨，此地高下，普得润泽。如是沙门瞿昙为我等善说妙事，润泽我体，犹如甘露。世尊，我已解。善逝，我已知。世尊，我今自归于佛、法及比丘众，惟愿世尊受我为优婆塞！从今日始，终身自归，乃至命尽。”

佛说如是，异学箭毛闻佛所说，欢喜奉行。

--------------

** 第57卷 晡利多品.箭毛经下第七

我闻如是：一时，佛游王舍城，在竹林迦兰哆园。

尔时，世尊过夜平旦，著衣持钵，入王舍城而行乞食。行乞食已，收举衣钵，澡洗手足，以尼师檀著于肩上，往至孔雀林异学园中。

尔时，孔雀林异学园中有一异学，名曰箭毛，名德宗主，众人所师，有大名誉，众所敬重，领大徒众，五百异学之所尊也。彼在大众喧闹娆乱，放高大音声，说种种畜生之论，谓论王、论贼、论斗、论食、论衣服、论妇人、论童女、论淫女、论世间、论空野、论海中、论国人民。彼共集坐说如是比畜生之论。异学箭毛遥见佛来，敕已众曰：“汝等默然住，彼沙门瞿昙来，彼众默然，当乐默然，称说默然，彼若见此众默然者，或来相见。”异学箭毛命众默然已，自默然住。

世尊往诣异学箭毛所，异学箭毛即从座起，偏袒著衣，叉手向佛，白曰：“善来！沙门瞿昙，沙门瞿昙久不来此，愿坐此座。”世尊便坐异学箭毛所敷之座。异学箭毛便与世尊共相问讯，却坐一面。

世尊问曰：“优陀夷，向论何等？以何事故共集坐此？”

异学箭毛答曰：“瞿昙，且置此论，此论非妙。沙门瞿昙欲闻此论，后闻不难。”

世尊如是再三问曰：“优陀夷，向论何等？以何事故共集坐此？”

异学箭毛亦再三答曰：“瞿昙，且置此论，此论非妙。沙门瞿昙欲闻此论，后闻不难。沙门瞿昙若至再三，其欲闻者，今当说之。瞿昙，我有策虑，有思惟，住策虑地，住思惟地，有智慧，有辩才。自说实有萨云然，一切知，一切见，无余知，无余见。我往问事，然彼不知。瞿昙，我作是念：‘此是何等耶？'”

世尊问曰：“优陀夷，汝有策虑，有思惟，有策虑地，住思惟地，有智慧，有辩才。谁说实有萨云然，一切知，一切见，无余知，无余见，汝往问事，而彼不知耶？”

异学箭毛答曰：“瞿昙，谓不兰迦葉是。所以者何？瞿昙，不兰迦葉自说实有萨云然，一切知，一切见，无余知，无余见也。我有策虑，有思惟，住策虑地，住思惟地，有智慧，有辩才。我往问事，然彼不知。瞿昙，是故我作是念：‘此是何等耶？'如是摩息迦利瞿舍利子、娑若鞞罗迟子、尼揵亲子、波复迦旃、阿夷哆鸡舍剑婆利。瞿昙，阿夷哆鸡舍剑婆利自说实有萨云然，一切知，一切见，无余知，无余见也。我有策虑，有思惟，住策虑地，住思惟地，有智慧，有辩才。我往问事，然彼不知。瞿昙，是故我作是念：‘此是何等耶？'瞿昙，我复作是念：‘若我当往诣沙门瞿昙所，问过去事者，沙门瞿昙必能答我过去事也。我当往诣沙门瞿昙所，问未来事者，沙门瞿昙必能答我未来事也。复次，若我随所问沙门瞿昙事者，沙门瞿昙必亦答我随所问事。'”

世尊告曰：“优陀夷，止！止！汝长夜异见、异忍、异乐、异欲、异意故，不得尽知我所说义。优陀夷，我有弟子有因有缘，忆无量过去本昔所生，谓一生、二生、百生、千生，成劫、败劫、无量成败劫。众生名某，我会生彼，如是姓、如是字、如是生、如是饮食、如是受苦乐、如是长寿、如是久住、如是寿讫。此死生彼，彼死生此，我生在此，如是姓、如是字、如是生、如是饮食、如是受苦乐、如是长寿、如是久住、如是寿讫。彼来问我过去事，我答彼过去事；我亦往问彼过去事，彼亦答我过去事；我随所问彼事，彼亦答我随所问事。复次，优陀夷，我有弟子，谓清净天眼出过于人，见此众生死时生时、好色恶色、妙与不妙，往来善处及不善处，随此众生之所作业，见其如真。若此众生成就身恶行，成就口、意恶行，诬谤圣人，邪见，成就邪见业；彼因缘此，身坏命终，必至恶处，生地狱中。若此众生成就身妙行，成就口、意妙行，不诬谤圣人，正见，成就正见业；彼因缘此，身坏命终，必升善处，得生天中。彼来问我未来事，我答彼未来事；我亦往问彼未来事，彼亦答我未来事；我随所问彼事，彼亦答我随所问事。”

异学箭毛白曰：“瞿昙，若如是者，我转不知，我转不见，转痴堕痴，谓沙门瞿昙如是说：‘优陀夷，止！止！汝长夜异见、异忍、异乐、异欲、异意故，不得尽知我所说义。优陀夷，我有弟子有因有缘，忆无量过去本昔所生，谓一生、二生、百生、千生，成劫、败劫、无量成败劫。众生名某，我曾生彼，如是姓、如是字、如是生、如是饮食、如是受苦乐、如是长寿、如是久住、如是寿讫。此死生彼，彼死生此，我生在此，如是姓、如是字、如是生、如是饮食、如是受苦乐、如是长寿、如是久往、如是寿讫。彼来问我过去事，我答彼过去事；我亦往问彼过去事，彼亦答我过去事；我随所问彼事，彼亦答我随所问事。复次，优陀夷，我有弟子，谓清净天眼出过于人，见此众生死时生时、好色恶色、妙与不妙，往来善处及不善处，随此众生之所作业，见其如真。若此众生成就身恶行，成就口、意恶行，诬谤圣人，邪见，成就邪见业；彼因缘此，身坏命终，必至恶处，生地狱中。苦此众生成就身妙行，成就口、意妙行，不诬谤圣人，正见，成就正见业；彼因缘此，身坏命终，必升善处，得生天中。彼来问我未来事，我答彼未来事；我亦往问彼未来事，彼亦答我未来事；我随所问彼事，彼亦答我随所问事。'

“瞿昙，我于此生作本所作，得本所得，尚不能忆，况复能忆有因有缘，无量本昔所生事耶？瞿昙，我尚不能见飘风鬼，况复清净天眼出过于人，见此众生死时生时、善色恶色、妙与不妙，趣至善处及不善处，随此众生之所作业，见其如真耶？瞿昙，我作是念：‘若沙门瞿昙问我从师学法者，倘能答彼，令可意也。'”

世尊问曰：“优陀夷，汝从师学其法云何？”

异学箭毛答曰：“瞿昙，彼说过于色，彼色最胜，彼色最上。”

世尊问曰：“优陀夷，何等色耶？”

异学箭毛答曰：“瞿昙，若色更无有色最上、最妙，为最胜也，彼色最胜，彼色最上。”

世尊告曰：“优陀夷，犹如有人作如是说：‘若此国中有女最妙，我欲得彼。'彼若有人如是问者：‘君知国中有女最妙，如是姓、如是名、如是生耶？为长短粗细？为白、黑？为不白不黑？为刹利女？为梵志、居士、工师女？为东方、南方、西方、北方耶？'彼人答曰：‘我不知也。'复问彼人：‘君不知、不见国中有女最妙，如是姓、如是名、如是生，长短粗细、白、黑、不白不黑，刹利女，梵志、居士、工师女，东方、南方、西方、北方者，而作是说：我欲得彼女耶？'如是，优陀夷，汝作是说：‘彼说色过于色，彼色最胜，彼色最上。'问汝彼色，然不知也。”

异学箭毛白曰：“瞿昙，犹如紫磨，极妙金精，金师善磨，莹治令净，藉以白练，安著日中，其色极妙，光明照耀。如是，瞿昙，我说彼色过于色，彼色最胜，彼色最上。”

世尊告曰：“优陀夷，我今问汝，随所解答。优陀夷，于意云何？谓紫磨金精，藉以白练，安著日中，其色极妙，光明照耀，及萤火虫在夜暗中光明照耀，于中光明，何者最上、为最胜耶？”

异学箭毛答曰：“瞿昙，萤火光明于紫磨金精光明，最上、为最胜也。”

世尊问曰：“优陀夷，于意云何？谓萤火虫在夜暗中光明照耀，及燃油灯在夜暗中光明照耀，于中光明，何者最上、为最胜耶？”

异学箭毛答曰：“瞿昙，燃灯光明于萤火虫光明，最上、为最胜也。”

世尊问曰：“优陀夷，于意云何？谓燃油灯在夜暗中光明照耀，及燃大木积火在夜暗中光明照耀，于中光明，何者最上、为最胜耶？”

异学箭毛答曰：“瞿昙，燃大木积火之光明于燃油灯光明，最上、为最胜也。”

世尊问曰：“优陀夷，于意云何？谓燃大木积火，在夜暗中光明照耀，及太白星平旦无曀光明照耀，于中光明，何者最上、为最胜耶？”

异学箭毛答曰：“瞿昙，太白星光于燃大木积火光，最上、为最胜也。”

世尊问曰：“优陀夷，于意云何？谓太白星平旦无曀光明照耀，及月殿光夜半无曀光明照耀，于中光明，何者最上、为最胜耶？”

异学箭毛答曰：“瞿昙，月殿光明于太白星光，最上、为最胜也。”

世尊问曰：“优陀夷，于意云何？谓月殿光夜半无曀光明照耀，及日殿光秋时向中，天净无曀光明照耀，于中光明，何者最上、为最胜耶？”

异学箭毛答曰：“瞿昙，日殿光明于月殿光，最上、为最胜也。”

世尊告曰：“优陀夷，多有诸天，今此日月虽有大如意足，有大威德，有大福佑，有大威神，然其光明故不及诸天光明也。我昔曾与诸天共集，共彼论事，我之所说，可彼天意，我不作是说：‘彼色过于色，彼色最胜，彼色最上。'优陀夷，而汝于萤火虫光色最弊最丑，说彼色过于色，彼色最胜，彼色最上，问已不知。”

异学箭毛白曰：“世尊，悔过此说！善逝，悔过此说！”

世尊问曰：“优陀夷，汝何意如是说：‘世尊，悔过此说！善逝，悔过此说！'耶？”

异学箭毛答曰：“瞿昙，我作是说：‘彼色过于色，彼色最胜，彼色最上。'沙门瞿昙今善检我，善教善诃，令我虚妄无所有也。瞿昙，是故我如是说：‘世尊，悔过此说！善逝，悔过此说！'”

异学箭毛语曰：“瞿昙，后世一向乐，有一道迹一向作世证。”

世尊问曰：“优陀夷，云何后世一向乐？云何有一道迹一向作世证耶？”

异学箭毛答曰：“瞿昙，或有一离杀断杀、不与取、邪淫、妄言乃至离邪见得正见，瞿昙，是谓后世一向乐，是谓有一道迹一向作世证。”

世尊告曰：“优陀夷，我今问汝，随所解答。优陀夷，于意云何？若有一离杀断杀，彼为一向乐、为杂苦耶？”

异学箭毛答曰：“瞿昙，是杂苦也。”

“若有一离不与取、邪淫、妄言乃至离邪见得正见，彼为一向乐、为杂苦耶？”

异学箭毛答曰：“瞿昙，是杂苦也。”

世尊问曰：“优陀夷，非为如是杂苦乐道迹作世证耶？”

异学箭毛答曰：“瞿昙，如是杂苦乐道迹作世证也。”

异学箭毛白曰：“世尊，悔过此说！善逝，悔过此说！”

世尊问曰：“优陀夷，汝何意故作如是说：‘世尊，悔过此说！善逝，悔过此说！'耶？”

异学箭毛答曰：“瞿昙，我向者说后世一向乐，有一道迹一向作世证。沙门瞿昙今善检我，善教善诃，令我虚妄无所有也。瞿昙，是故我如是说：‘世尊，悔过此说！善逝，悔过此说！'”

世尊告曰：“优陀夷，世有一向乐，有一道迹一向作世证也。”

异学箭毛问曰：“瞿昙，云何世一向乐？云何一道迹一向作世证耶？”

世尊答曰：“优陀夷，若时如来出世，无所著、等正觉、明行成为、善逝、世间解、无上士、道法御、天人师，号佛、众佑，彼断乃至五盖，心秽、慧羸，离欲、离恶不善之法，有觉、有观，离生喜、乐，得初禅成就游，不共彼天戒等、心等、见等也。彼觉、观已息，内静、一心，无觉、无观，定生喜、乐，得第二禅成就游，不共彼天戒等、心等、见等也。彼离于喜欲，舍无求游，正念正智而身觉乐，谓圣所说、圣所舍、念、乐住、空，得第三禅成就游，不共彼天戒等、心等、见等也。优陀夷，是谓世一向乐。”

异学箭毛问曰：“瞿昙，世中一向乐，唯极是耶？”

世尊答曰：“世中一向乐，不但极是也。优陀夷，更有一道迹一向作世证。”

异学箭毛问曰：“瞿昙，云何更有一道迹一向作世证耶？”

世尊答曰：“优陀夷，比丘离欲、离恶不善之法，有觉、有观，离生喜、乐，得初禅成就游，得共彼天戒等、心等、见等也。彼觉、观已息，内静、一心，无觉、无观，定生喜、乐，得第二禅成就游，得共彼天戒等、心等、见等也。彼离于喜欲，舍无求游，正念正智而身觉乐，谓圣所说、圣所舍、念、乐、乐住、空，得第三禅成就游，得共彼天戒等、心等、见等也。优陀夷，是谓一道迹一向作世证。”

异学箭毛问曰：“瞿昙，沙门瞿昙弟子为此世一向乐故，一道迹一向作世证故，从沙门瞿昙学梵行耶？”

世尊答曰：“优陀夷，我弟子不为世一向乐故，亦不为一道迹一向作世证故，从我学梵行也。优陀夷，更有最上、最妙、最胜，为作证故，我弟子从我学梵行也。”

于是，彼大众放高大音声：“彼是最上、最妙、最胜，为作证故，沙门瞿昙弟子从沙门瞿昙学梵行也。”

于是，异学箭毛敕己众，令默然已，白曰：“瞿昙，云何最上、最妙、最胜，为作证故，沙门瞿昙弟子从沙门瞿昙学梵行耶？”

世尊答曰：“优陀夷，比丘者乐灭、苦灭，喜、忧本已灭，不苦不乐、舍、念、清净，得第四禅成就游。优陀夷，是谓最上、最妙、最胜，为作证故，我弟子从我学梵行也。”

于是，异学箭毛即从座起，欲稽首佛足。于是，异学箭毛诸弟子异学梵行者白异学箭毛曰：“尊今应作师时，欲为沙门瞿昙作弟子耶？尊不应作师时，为沙门瞿昙作弟子也。”是为异学箭毛诸弟子学梵行者，为异学箭毛而作障碍，谓从世尊学梵行也。

佛说如是，异学箭毛闻佛所说，欢喜奉行。

--------------

** 第57卷 晡利多品.鞞摩那修经第八

我闻如是：一时，佛游舍卫国，在胜林给孤独园。

尔时，异学鞞摩那修中后彷佯，往诣佛所，相问讯已，问曰：“瞿昙，最色最色，瞿昙，最色。”

世尊问曰：“迦旃，何等色耶？”

异学鞞摩那修答曰：“瞿昙，若色更无有色最上、最妙、最胜，瞿昙，彼色最胜，彼色最上。”

世尊告曰：“迦旃，犹如有人作如是说：‘若此国中有女最妙，我欲得彼。'彼若有人如是问者：‘君知国中有女最妙，如是姓、如是名、如是生耶？为长短粗细？为白、黑？为不白不黑？为刹利女？为梵志、居士、工师女？为东方、南方、西方、北方耶？'彼人答曰：‘我不知也。'复问彼人：‘君不知、不见国中有女最妙，如是姓、如是名、如是生，长短粗细，白、黑、不白不黑，刹利女，梵志、居士、工师女，东方、南方、西方、北方者，而作是说：我欲得彼女耶？'如是，迦旃，汝作是说：‘彼妙色最妙色，彼色最胜，彼色最上。'问汝彼色，然不知也。”

异学鞞摩那修白曰：“瞿昙，犹如紫磨，极妙金精，金师善磨，莹治令净，藉以白练，安著日中，其色极妙，光明照耀。如是，瞿昙，我说彼妙色最妙色，彼色最胜，彼色最上。”

世尊告曰：“迦旃，我今问汝，随所解答。迦旃，于意云何？谓紫磨金精，藉以白练，安著日中，其色极妙，光明照耀，及萤火虫在夜暗中光明照耀，于中光明，何者最上、为最胜耶？”

异学鞞摩那修答曰：“瞿昙，萤火光明于紫磨金精光明，最上、为最胜也。”

世尊问曰：“迦旃，于意云何？谓萤火虫在夜暗中光明照耀，及燃油灯在夜暗中光明照耀，于中光明，何者最上、为最胜耶？”

异学鞞摩那修答曰：“瞿昙，燃灯光明于萤火虫光明，最上、为最胜也。”

世尊问曰：“迦旃，于意云何？谓燃油灯在夜暗中光明照耀，及燃大木积火在夜暗中光明照耀，于中光明，何者最上、为最胜耶？”

异学鞞摩那修答曰：“瞿昙，燃大木积火之光明于燃油灯光明，最上、为最胜也。”

世尊问曰：“迦旃，于意云何？谓燃大木积火在夜暗中光明照耀，及太白星平旦无曀光明照耀，于中光明，何者最上、为最胜耶？”

异学鞞摩那修答曰：“瞿昙，太白星光于燃大木积火光，最上、为最胜也。”

世尊问曰：“迦旃，于意云何？谓太白星平旦无曀光明照耀，及月殿光夜半无曀光明照耀，于中光明，何者最上、为最胜耶？”

异学鞞摩那修答曰：“瞿昙，月殿光明于太白星光，最上、为最胜也。”

世尊间曰：“迦旃，于意云何？谓月殿光夜半无曀光明照耀，及日殿光秋时向中，天净无曀光明照耀，于中光明，何者最上、为最胜耶？

异学鞞摩那修答曰：“瞿昙，日殿光明于月殿光，最上、为最胜也。”

世尊告曰：“迦旃，多有诸天，今此日月虽有大如意足，有大威德，有大福佑，有大威神，然其光明故不及诸天光明也。我昔会与诸天共集，共彼论事，我之所说，可彼天意，然我不作是说：‘彼妙色最妙色，彼色最胜，彼色最上。'迦旃，而汝于萤火虫光色最弊最丑，说彼妙色最妙色，彼色最胜，彼色最上，问已不知。”于是，异学鞞摩那修为世尊面诃责已，内怀忧戚，低头默然，失辩无言，如有所伺。

于是，世尊面诃责已，复令欢悦，告曰：“迦旃，有五欲功德，可喜、意、念爱欲相应乐：眼知色，耳知声，鼻知香，舌知味，身知触。迦旃，色或有爱者，或不爱者。若有一人，彼于此色可意、称意、乐意、足意、满愿意，彼于余色虽最上、最胜，而不欲、不思、不愿、不求，彼于此色最胜、最上。迦旃，如是声、香、味、触。迦旃，触或有爱者，或不爱者。若有一人，彼于此触可意、称意、乐意、足意、满愿意，彼于余触虽最上、最胜，而不欲、不思、不愿、不求，彼于此触最胜、最上。”

于是，异学鞞摩那修叉手向佛，白曰：“瞿昙，甚奇！甚特！沙门瞿昙为我无量方便说欲乐、欲乐第一。瞿昙，犹如因草火燃木火，因木火燃草火。如是沙门瞿昙为我无量方便说欲乐、欲乐第一。”

世尊告曰：“止！止！迦旃，汝长夜异见、异忍、异乐、异欲、异意故，不得尽知我所说义。迦旃，谓我弟子初夜后夜常不眠卧，正定正意，修习道品，生已尽，梵行已立，所作已办，不更受有，知如真，彼尽知我所说。”

于是，异学鞞摩那修向佛瞋恚，生憎嫉、不可，欲诬谤世尊，欲堕世尊。如是诬谤世尊，如是堕世尊，语曰：“瞿昙，有沙门、梵志，不知世前际，不知世后际，不知无穷生死，而记说得究竟智，生已尽，梵行已立，所作已办，不更受有，知如真。瞿昙，我如是念：‘云何此沙门、梵志，不知世前际，亦不知世后际，不知无穷生死，而记说得究竟智，生已尽，梵行已立，所作已办，不更受有，知如真'耶？”

于是，世尊便作是念：“此异学鞞摩那修向我瞋恚，生憎嫉、不可，欲诬谤我，欲堕于我。如是诬谤我，如是堕我，而语我曰：‘瞿昙，有一沙门梵志，不知世前际，不知世后际，不知无穷生死，而记说得究竟智，生已尽，梵行已立，所作已办，不更受有，知如真。瞿昙，我作是念：“云何此沙门、梵志，不知世前际，不知世后际，不知无穷生死，而记说得究竟智，生已尽，梵行已立，所作已办，不更受有，知如真”耶？'”

世尊知已，告曰：“迦旃，若有沙门、梵志，不知世前际，不知世后际，不知无穷生死，而记说得究竟智，生已尽，梵行已立，所作已办，不更受有，知如真者，彼应如是说：‘置世前际，置世后际。'迦旃，我如是说：‘置世前际，置世后际。'设不忆一生，我弟子比丘来，不谀谄、无欺诳、质直，我教化之。若随我教化，如是行者，必得知正法。迦旃，犹如婴孩童子，少年柔软，仰向卧，父母缚彼手足；彼于后转大，诸根成就，父母解彼手足，彼唯忆解缚时，不忆缚时也。如是，迦旃，我如是说：‘置世前际，置世后际。'设令不忆一生，我弟子比丘来，不谀谄、不欺诳、质直，我教化之。若随我教化，如是行者，必得知正法。

“迦旃，譬若因油因炷而燃灯也，无人益油，亦不易炷者，前油已尽，后不更益，无所受已，自速灭也。如是，迦旃，我如是说：‘置世前际，置世后际。'或令不忆一生，我弟子比丘来，不谀谄、不斯诳、质直，我教化之。若随我教化，如是行者，必得知正法。迦旃，犹如十木聚，二十、三十、四十、五十、六十木聚，以火烧之，炯然俱炽，遂见火焰，后无有人更益草、木、糠、粪扫者，前薪已尽，后不更益，无所受已，自速灭也，如是，迦旃，我如是说：‘置世前际，置世后际。'设令不忆一生，我弟子比丘来，不谀谄、不欺诳、质直，我教化之。若随我教化，如是行者，必得知正法。”

说此法时，异学鞞摩那修远尘离垢，诸法法眼生。于是，异学鞞摩那修见法得法，觉白净法，更无余尊，不复由他，断疑度惑，无有犹豫，已住果证，于世尊法得无所畏，稽首佛足，白曰：“世尊，愿得从佛出家学道，受具足，得比丘，行梵行。”

世尊告曰：“善哉！比丘行梵行也。”

异学从佛得出家学道，即受具足，得比丘，行梵行。尊者鞞摩那修出家学道，受具足已，知法见法，乃至得阿罗诃。

佛说如是，尊者鞞摩那修及诸比丘闻佛所说，欢喜奉行。

--------------

** 第58卷 晡利多品.法乐比丘尼经第九

我闻如是：一时，佛游舍卫国，在胜林给孤独园。

尔时，毘舍佉优婆夷往诣法乐比丘尼所，稽首礼足，却坐一面，白法乐比丘尼曰：“贤圣，欲有所问，听我问耶？”

法乐比丘尼答曰：“毘舍佉，欲问便问，我闻已当思。”

毘舍佉优婆夷便问曰：“贤圣，自身，说自身，云何为自身耶？”

法乐比丘尼答曰：“世尊说五盛阴，自身色盛阴，觉、想、行、识盛阴，是谓世尊说五盛阴。”

毘舍佉优婆夷闻已，叹曰：“善哉！善哉！贤圣。”毘舍佉优婆夷叹已，欢喜奉行。

复问曰：“贤圣，云何为自身见耶？”

法乐比丘尼答曰：“不多闻愚痴凡夫不见善知识，不知圣法，不御圣法。彼见色是神，见神有色，见神中有色，见色中有神也。见觉、想、行、识是神，见神有识，见神中有识，见识中有神也，是谓自身见也。”

毘舍佉优婆夷闻已，叹曰：“善哉！善哉！贤圣。”毘舍佉优婆夷叹已，欢喜奉行。

复问曰：“贤圣，云何无身见耶？”

法乐比丘尼答曰：“多闻圣弟子见善知识，知圣法，善御圣法。彼不见色是神，不见神有色，不见神中有色，不见色中有神也。不见觉、想、行、识是神，不见神有识，不见神中有识，不见识中有神也，是谓无身见也。”

毘舍佉优婆夷闻已，叹曰：“善哉！善哉！贤圣。”毘舍佉优婆夷叹已，欢喜奉行。

复问曰：“贤圣，云何灭自身耶？”

法乐比丘尼答曰：“色盛阴断无余，舍、吐、尽、不染、灭、息、没也。觉、想、行、识盛阴断无余，舍、吐、尽、不染、灭、息、没也，是谓自身灭。”

毘舍佉优婆夷闻已，叹曰：“善哉！善哉！贤圣。”毘舍佉优婆夷叹已，欢喜奉行。

复问曰：“贤圣，阴说阴盛，阴说盛阴；阴即是盛阴，盛阴即是阴耶？为阴异、盛阴异耶？”

法乐比丘尼答曰：“或阴即是盛阴，或阴非盛阴。云何阴即是盛阴？若色有漏有受，觉、想、行、识有漏有受，是谓阴即是盛阴。云何阴非盛阴？色无漏无受，觉、想、行、识无漏无受，是谓阴非盛阴。”

毘舍佉优婆夷闻已，叹曰：“善哉！善哉！贤圣。”毘舍佉优婆夷叹已，欢喜奉行。

复问曰：“贤圣，云何八支圣道耶？”

法乐比丘尼答曰：“八支圣道者，正见乃至正定，是谓为八，是谓八支圣道。”

毘舍佉优婆夷闻已，叹曰：“善哉！善哉！贤圣。”毘舍佉优婆夷叹已，欢喜奉行。

复问曰：“贤圣，八支圣道有为耶？”

法乐比丘尼答曰：“如是八支圣道有为也。”、

毘舍佉优婆夷闻已，叹曰：“善哉！善哉！贤圣。”毘舍佉优婆夷叹已，欢喜奉行。

复问曰：“贤圣，有几聚耶？”

法乐比丘尼答曰：“有三聚，戒聚、定聚、慧聚。”

毘舍佉优婆夷闻已，叹曰：“善哉！善哉！贤圣。”毘舍佉优婆夷叹已，欢喜奉行。

复问曰：“贤圣，八支圣道摄三聚，为三聚摄八支圣道耶？”

法乐比丘尼答曰：“非八支圣道摄三聚，三聚摄八支圣道。正语、正业、正命，此三道支圣戒聚所摄；正念、正定，此二道支圣定聚所摄；正见、正志、正方便，此三道支圣慧聚所摄。是谓非八支圣道摄三聚，三聚摄八支圣道。”

毘舍佉优婆夷闻已，叹曰：“善哉！善哉！贤圣。”毘舍佉优婆夷叹已，欢喜奉行。

复问曰：“贤圣，灭有对耶？”

法乐比丘尼答曰：“灭无对也。”

毘舍佉优婆夷闻已，叹曰：“善哉！善哉！贤圣。”毘舍佉优婆夷叹已，欢喜奉行。

复问曰：“贤圣，初禅有几支耶？”

法乐比丘尼答曰：“初禅有五支，觉、观、喜、乐、一心，是谓初禅有五支。”

毘舍佉优婆夷闻已，叹曰：“善哉！善哉！贤圣。”毘舍佉优婆夷叹已，欢喜奉行。

复问曰：“贤圣，云何断？云何定相？云何定力？云何定功？云何修定耶？”

法乐比丘尼答曰：“若善心得一者，是谓定也。四念处，是谓定相也。四正断，是谓定力也。四如意足，是谓定功也。若习此诸善法，数数专修精勤者，是谓修定也。”

毘舍佉优婆夷闻已，叹曰：“善哉！善哉！贤圣。”毘舍佉优婆夷叹已，歡喜奉行！

复问曰：“贤圣，有几法生身死已，身弃冢间，如木无情？”

法乐比丘尼答曰：“有三法生身死已，身弃冢间，如木无情。云何为三？一者、寿，二者、暖，三者、识。是谓三法生身死已，身弃冢间，如木无情。”

毘舍佉优婆夷闻已，叹曰：“善哉！善哉！贤圣。”毘舍佉优婆夷叹已，欢喜奉行。

复问曰：“贤圣，若死及入灭尽定者，有何差别？”

法乐比丘尼答曰：“死者寿命灭讫，温暖已去，诸根败坏。比丘入灭尽定者寿不灭讫，暖亦不去，诸根不败坏。若死及入灭尽定者，是谓差别。”

毘舍佉优婆夷闻已，叹曰：“善哉！善哉！贤圣。”毘舍佉优婆夷叹已，欢喜奉行。

复问曰：“贤圣，若入灭尽定及入无想定者，有何差别？”

法乐比丘尼答曰：“比丘入灭尽定者，想及知灭；入无想定者，想、知不灭。若入灭尽定及入无想定者，是谓差别。”

毘舍佉优婆夷闻已，叹曰：“善哉！善哉！贤圣。”毘舍佉优婆夷叹已，欢喜奉行。

复问曰：“贤圣，若从灭尽定起及从无想定起者，有何差别？”

法乐比丘尼答曰：“比丘从灭尽定起时，不作是念：‘我从灭尽定起。'比丘从无想定起时，作如是念：‘我为有想？我为无想？'若从灭尽定起及从无想定起者，是谓差别。”

毘舍佉优婆夷闻已，叹曰：“善哉！善哉！贤圣。”毘舍佉优婆夷叹已，欢喜奉行。

复问曰：“贤圣，比丘入灭尽定时，作如是念：‘我入灭尽定耶？'”

法乐比丘尼答曰：“比丘入灭尽定时，不作是念：‘我入灭尽定。'然本如是修习心，以是故如是趣向。”

毘舍佉优婆夷闻已，叹曰：“善哉！善哉！贤圣。”毘舍佉优婆夷叹已，欢喜奉行。

复问曰：“贤圣，比丘从灭尽定起，作如是念：‘我从灭尽定起耶？'”

法乐比丘尼答曰：“比丘从灭尽定起时，不作是念：‘我从灭尽定起。'然因此身及六处缘命根，是故从定起。”

毘舍佉优婆夷闻已，叹曰：“善哉！善哉！贤圣。”毘舍佉优婆夷叹已，欢喜奉行。

复问曰：“贤圣，比丘从灭尽定起已，心何所乐、何所趣、何所顺耶？”

法乐比丘尼答曰：“比丘从灭尽定起已，心乐离、趣离、顺离。”

毘舍佉优婆夷闻已，叹曰：“善哉！善哉！贤圣。”毘舍佉优婆夷叹已，欢喜奉行。

复问曰：“贤圣，有几觉耶？”

法乐比丘尼答曰：“有三觉，乐觉、苦觉、不苦不乐觉。此何缘有耶？缘更乐有。”

毘舍佉优婆夷闻已，叹曰：“善哉！善哉！贤圣。”毘舍佉优婆夷叹已，欢喜奉行。

复问曰：“贤圣，云何乐觉，云何苦觉，云何不苦不乐觉耶？”

法乐比丘尼答曰：“若乐更乐所触生，身心乐善觉，是觉谓乐觉也。若苦更乐所触生，身心苦不善觉，是觉谓苦觉也。若不苦不乐更乐所触生，身心不苦不乐，非善非不善觉，是觉谓不苦不乐觉。”

毘舍佉优婆夷闻已，叹曰：“善哉！善哉！贤圣。”毘舍佉优婆夷叹已，欢喜奉行。

复问曰：“贤圣，乐觉者，云何乐，云何苦，云何无常，云何灾患，云何使耶？苦觉者，云何乐，云何苦，云何无常，云何灾患，云何使耶？不苦不乐觉者，云何乐，云何苦，云何无常，云何灾患，云何使耶？”

法乐比丘尼答曰：“乐觉者，生乐住乐，变易苦，无常者即是灾患，欲使也。苦觉者，生苦住苦，变易乐，无常者即是灾患，恚使也。不苦不乐觉者，不知苦、不知乐，无常者即是变易，无明使也。”

毘舍佉优婆夷闻已，叹曰：“善哉！善哉！贤圣。”毘舍佉优婆夷叹已，欢喜奉行。

复问曰：“贤圣，一切乐觉欲使耶？一切苦觉恚使耶？一切不苦不乐觉无明使耶？”

法乐比丘尼答曰：“非一切乐觉欲使也，非一切苦觉恚使也，非一切不苦不乐觉无明使也。云何乐觉非欲使耶？若比丘离欲、离恶不善之法，有觉、有观，离生喜、乐，得初禅成就游，是谓乐觉非欲使也。所以者何？此断欲故。云何苦觉非恚使耶？若求上解脱乐，求愿悒悒生忧苦，是谓苦觉非恚使也。所以者何？此断恚故。云何不苦不乐觉非无明使耶？乐灭、苦灭，喜、忧本已灭，不苦不乐、舍、念、清净，得第四禅成就游，是谓不苦不乐觉非无明使也。所以者何？此断无明故。”

毘舍佉优婆夷闻已，叹曰：“善哉！善哉！贤圣。”毘舍佉优婆夷叹已，欢喜奉行。

复问曰：“贤圣，乐觉者有何对耶？”

法乐比丘尼答曰：“乐觉者以苦觉为对。”

毘舍佉优婆夷闻已，叹曰：“善哉！善哉！贤圣。”毘舍佉优婆夷叹已，欢喜奉行。

复问曰：“贤圣，苦觉者有何对耶？”

法乐比丘尼答曰：“苦觉者以乐觉为对。”

毘舍佉优婆夷闻已，叹曰：“善哉！善哉！贤圣。”毘舍佉优婆夷叹已，欢喜奉行。

复问曰：“贤圣，乐觉苦觉者有何对耶？”

法乐比丘尼答曰：“乐觉苦觉者以不苦不乐为对。”

毘舍佉优婆夷闻已，叹曰：“善哉！善哉！贤圣。”毘舍佉优婆夷叹已，欢喜奉行。

复问曰：“贤圣，不苦不乐觉者有何对耶？”

法乐比丘尼答曰：“不苦不乐觉者以无明为对。”

毘舍佉优婆夷闻已，叹曰：“善哉！善哉！贤圣。”毘舍佉优婆夷叹已，欢喜奉行。

复问曰：“贤圣，无明者有何对耶？”

法乐比丘尼答曰：“无明者以明为对。”

毘舍佉优婆夷闻已，叹曰：“善哉！善哉！贤圣。”毘舍佉优婆夷叹已，欢喜奉行。

复问曰：“贤圣，明者有何对耶？”

法乐比丘尼答曰：“明者以涅槃为对。”

毘舍佉优婆夷闻已，叹曰：“善哉！善哉！贤圣。”毘舍佉优婆夷叹已，欢喜奉行。

复问曰：“圣贤，涅槃者有何对耶？”

法乐比丘尼告曰：“君欲问无穷事，然君问事不能得穷我边也。涅槃者，无对也。涅槃者，以无羂、过羂，羂灭讫，以此义故，从世尊行梵行。”

于是，毘舍佉优婆夷闻法乐比丘尼所说，善受善持，善诵习已，即从座起，稽首礼法乐比丘尼足，绕三匝而去。

于是，法乐比丘尼见毘舍佉优婆夷去后不久，往诣佛所，稽首佛足，却坐一面，与毘舍佉优婆夷所共论者，尽向佛说，叉手向佛，白曰：“世尊，我如是说、如是答，非为诬谤世尊耶？说真实、说如法、说法次法耶？于如法中，非有相违、有诤、有咎耶？”

世尊答曰：“比丘尼，汝如是说、如是答，不诬谤我。汝说真实，说如法、说法次法，于如法中而不相违，无诤咎也。比丘尼，若毘舍佉优婆夷以此句、以此文来问我者，我为毘舍佉优婆夷亦以此义、以此句、以此文而答彼也。比丘尼，此义如汝所说，汝当如是持。所以者何？此说即是义故。”

佛说如是，法乐比丘尼及诸比丘闻佛所说，欢喜奉行。

--------------

** 第58卷 晡利多品.大拘絺罗经第十

我闻如是：一时，佛游王舍城，在竹林迦兰哆园。

尔时，尊者舍梨子则于晡时从宴坐起，往诣尊者大拘絺罗所，共相问讯，却坐一面。

尊者舍梨子语曰：“贤者拘絺罗，欲有所问，听我问耶？”

尊者大拘絺罗白曰：“尊者舍梨子，欲问便问，我闻已当思。”

尊者舍梨子问曰：“贤者拘絺罗，不善者说不善，不善根者说不善根。何者不善？何者不善根耶？”

尊者大拘絺罗答曰：“身恶行，口、意恶行，是不善也。贪、恚、痴，是不善根也。是谓不善，是谓不善根。”

尊者舍梨子闻已，叹曰：“善哉！善哉！贤者拘絺罗。”尊者舍梨子叹已，欢喜奉行。

复问曰：“贤者拘絺罗，善者说善，善根者说善根。何者为善？何者善根耶？”

尊者大拘絺罗答曰：“身妙行，口、意妙行，是善也。不贪、不恚、不痴，是善根也。是谓为善，是谓善根。”

尊者舍梨子闻已，叹曰：“善哉！善哉！贤者拘絺罗。”尊者舍梨子叹已，欢喜奉行。

复问曰：“贤者拘絺罗，智慧者说智慧，何者智慧？”

尊者大拘絺罗答曰：“知如是故说智慧，知何等耶？知此苦如真，知此苦集、知此苦灭、知此苦灭道如真，知如是故说智慧。”

尊者舍梨子闻已，叹曰：“善哉！善哉！贤者拘絺罗。”尊者舍梨子叹已，欢喜奉行。

复问曰：“贤者拘絺罗，识者说识。何者识耶？”

尊者大拘絺罗答曰：“识识是故说识。识何等耶？识色，识声、香、味、触、法，识识是故说识。”

尊者舍梨子闻已，叹曰：“善哉！善哉！贤者拘絺罗。”尊者舍梨子叹已，欢喜奉行。

复问曰：“贤者拘絺罗，智慧及识，此二法为合为别，此二法可得别施设耶？”

尊者大拘絺罗答曰：“此二法合不别，此二法不可别施设。所以者何？智慧所知，即是识所识，是故此二法合不别，此二法不可别施设。”

尊者舍梨子闻已，叹曰：“善哉！善哉！贤者拘絺罗。”尊者舍梨子叹已，欢喜奉行。

复问曰：“贤者拘絺罗，知者汝以何等知？”

尊者大拘絺罗答曰：“知者我以智慧知。”

尊者舍梨子闻已，叹曰：“善哉！善哉！贤者拘絺罗。”尊者舍梨子叹已，欢喜奉行。

复问曰：“贤者拘絺罗，智慧有何义？有何胜？有何功德？”

尊者大拘絺罗答曰：“智慧者有厌义、无欲义、见如真义。”

尊者舍梨子闻已，叹曰：“善哉！善哉！贤者拘絺罗。”尊者舍梨子叹已，欢喜奉行。

复问曰：“贤者拘絺罗，云何正见？”

尊者大拘絺罗答曰：“知苦如真，知习、灭、道如真者，是谓正见。”

尊者舍梨子闻已，叹曰：“善哉！善哉！贤者拘絺罗。”尊者舍梨子叹已，欢喜奉行。

复问曰：“贤者拘絺罗，几因几缘生正见耶？”

尊者大拘絺罗答曰：“二因二缘而生正见。云何为二？一者、从他闻，三者、内自思惟。是谓二因二缘而生正见。”

尊者舍梨子闻已，叹曰：“善哉！善哉！贤者拘絺罗。”尊者舍梨子叹已，欢喜奉行。

复问曰：“贤者拘絺罗，有几支摄正见，得心解脱果、慧解脱果，得心解脱功德、慧解脱功德耶？”

尊者大拘絺罗答曰：“有五支摄正见，得心解脱果、慧解脱果，得心解脱功德、慧解脱功德。云何为五？一者、真谛所摄，二者、戒所摄，三者、博闻所摄，四者、止所摄，五者、观所摄。是谓有五支摄正见，得心解脱果、慧解脱果，得心解脱功德、慧解脱功德。”

尊者舍梨子闻已，叹曰：“善哉！善哉！贤者拘絺罗。”尊者舍梨子叹已，欢喜奉行。

复问曰：“贤者拘絺罗，云何生当来有？”

尊者大拘絺罗答曰：“愚痴凡夫无知、不多闻，无明所覆，爱结所系，不见善知识，不知圣法，不御圣法，是谓生当来有。”

尊者舍梨子闻已，叹曰：“善哉！善哉！贤者拘絺罗。”尊者舍梨子叹已，欢喜奉行。

复问曰：“贤者拘絺罗，云何不生当来有？”

尊者大拘絺罗答曰：“若无明已尽，明已生者，必尽苦也，是谓不生于当来有。”

尊者舍梨子闻已，叹曰：“善哉！善哉！贤者拘絺罗。”尊者舍梨子叹已，欢喜奉行。

复问曰：“贤者拘絺罗，有几觉耶？”

尊者大拘絺罗答曰：“有三觉，乐觉、苦觉、不苦不乐觉。此缘何有耶？缘更乐有。”

尊者舍梨子闻已，叹曰：“善哉！善哉！贤者拘絺罗。”尊者舍梨子叹已，欢喜奉行。

复问曰：“贤者拘絺罗，觉、想、思，此三法为合为别？此三法可别施设耶？”

尊者大拘絺罗答曰：“觉、想、思，此三法合不别，此三法不可别施设。所以者何？觉所觉者，即是想所想、思所思，是故此三法合不别，此三法不可别施设。”

尊者舍梨子闻已，叹曰：“善哉！善哉！贤者拘絺罗。”尊者舍梨子叹已，欢喜奉行。

复问曰：“贤者拘絺罗，灭者有何对？”

尊者大拘絺罗答曰：“灭者无有对。”

尊者舍梨子闻已，叹曰：“善哉！善哉！贤者拘絺罗。”尊者舍梨子叹已，欢喜奉行。

复问曰：“贤者拘絺罗，有五根异行、异境界，各各受自境界。眼根，耳、鼻、舌、身根，此五根异行、异境界，各各受自境界，谁为彼尽受境界？谁为彼依耶？”

尊者大拘絺罗答曰：“五根异行、异境界，各各自受境界。眼根，耳、鼻、舌、身根，五根异行、异境界，各各受自境界，意为彼尽受境界，意为彼依。”

尊者舍梨子闻已，叹曰：“善哉！善哉！贤者拘絺罗。”尊者舍梨子叹已，欢喜奉行。

复问曰：“贤者拘絺罗，意者依何住耶？”

尊者大拘絺罗答曰：“意者依寿，依寿住。”

尊者舍梨子闻已，叹曰：“善哉！善哉！贤者拘絺罗。”尊者舍梨子叹已，欢喜奉行。

复问曰：“贤者拘絺罗，寿者依何住耶？”

尊者大拘絺罗答曰：“寿者依暖，依暖住。”

尊者舍梨子闻已，叹曰：“善哉！善哉！贤者拘絺罗。”尊者舍梨子叹已，欢喜奉行。

复问曰：“贤者拘絺罗，寿及暖，此二法为合为别？此二法可得别施设耶？”

尊者大拘絺罗答曰：“寿及暖，此二法合不别，此二法不可别施设。所以者何？因寿故有暖，因暖故有寿。若无寿者则无暖，无暖者则无寿。犹如因油因炷，故得燃灯，彼中因焰故有光，因光故有焰。若无焰者则无光，无光者则无焰。如是因寿故有暖，因暖故有寿。若无寿者则无暖，无暖者则无寿。是故此二法合不别，此二法不可别施设。”

尊者舍梨子闻已，叹曰：“善哉！善哉！贤者拘絺罗。”尊者舍梨子叹已，欢喜奉行。

复问曰：“贤者拘絺罗，有几法生身死已，身弃冢间，如木无情？”

尊者大拘絺罗答曰：“有三法生身死已，身弃冢间，如木无情。云何为三？一者、寿，二者、暖，三者、识。此三法生身死已，身弃冢间，如木无情。”

尊者舍梨子闻已，叹曰：“善哉！善哉！贤者拘絺罗。”尊者舍梨子叹已，欢喜奉行。

复问曰：“贤者拘絺罗，若死及入灭尽定者，有何差别？”

尊者大拘絺罗答曰：“死者寿命灭讫，温暖已去，诸根败坏。比丘入灭尽定者，寿不灭讫，暖亦不去，诸根不败坏。死及入灭尽定者，是谓差别。”

尊者舍梨子闻已，叹曰：“善哉！善哉！贤者拘絺罗。”尊者舍梨子叹已，欢喜奉行。

复问曰：“贤者拘絺罗，若入灭尽定及入无想定者，有何差别？”

尊者大拘絺罗答曰：“比丘入灭尽定者，想及知灭；比丘入无想定者，想、知不灭。若入灭尽定及入无想定者，是谓差别。”

尊者舍梨子闻已，叹曰：“善哉！善哉！贤者拘絺罗。”尊者舍梨子叹已，欢喜奉行。

复问曰：“贤者拘絺罗，若从灭尽定起及从无想定起者，有何差别？”

尊者大拘絺罗答曰：“比丘从灭尽定起时，不如是念：‘我从灭尽定起。'比丘从无想定起时，作如是念：‘我为有想？我为无想？'从灭尽定起及从无想定起者，是谓差别。”

尊者舍梨子闻已，叹曰：“善哉！善哉！贤者拘絺罗。”尊者舍梨子叹已，欢喜奉行。

复问曰：“贤者拘絺罗，比丘入灭尽定时先灭何法？为身行？为口、意行耶？”

尊者大拘絺罗答曰：“比丘入灭尽定时，先灭身行，次灭口行，后灭意行。”

尊者舍梨子聞已，叹曰：“善哉！善哉！贤者拘絺罗。”尊者舍梨子叹已，欢喜奉行。

复问曰：“贤者拘絺罗，比丘从灭尽定起时，先生何法？为身行，口、意行耶？”

尊者大拘絺罗答曰：“比丘从灭尽定起时，先生意行，次生口行，后生身行。”

尊者舍梨子闻已，叹曰：“善哉！善哉！贤者拘絺罗。”尊者舍梨子叹已，欢喜奉行。

复问曰：“贤者拘絺罗，比丘从灭尽定起时触几触？”

尊者大拘絺罗答曰：“比丘从灭尽定起时触三触。云何为三？一者、不移动触，二者、无所有触，三者、无相触。比丘从灭尽定起时触此三触。”

尊者舍梨子闻已，叹曰：“善哉！善哉！贤者拘絺罗。”尊者舍梨子叹已，欢喜奉行。

复问曰：“贤者拘絺罗，空、无愿、无相，此三法异义、异文耶？为一义、异文耶？”

尊者大拘絺罗答曰：“空、无愿、无相，此三法异义、异文。”

尊者舍梨子闻已，叹曰：“善哉！善哉！贤者拘絺罗。”尊者舍梨子叹已，欢喜奉行。

复问曰：“贤者拘絺罗，有几因几缘生不移动定耶？”

尊者大拘絺罗答曰：“有四因四缘生不移动定。云何为四？若比丘离欲、离恶不善之法至得第四禅成就游，是谓四因四缘生不移动定。”

尊者舍梨子闻已，叹曰：“善哉！善哉！贤者拘絺罗。”尊者舍梨子叹已，欢喜奉行。

复问曰：“贤者拘絺罗，有几因几缘生无所有定耶？”

尊者大拘絺罗答曰：“有三因三缘生无所有定。云何为三？若比丘度一切色想至得无所有处成就游，是谓有三因三缘生无所有定。”

尊者舍梨子闻已，叹曰：“善哉！善哉！贤者拘絺罗。”尊者舍梨子叹已，欢喜奉行。

复问曰：“贤者拘絺罗，有几因几缘生无想定？”

尊者大拘絺罗答曰：“有二因二缘生无想定。云何为二？一者、不念一切想，二者、念无想界。是谓二因二缘生无想定。”

尊者舍梨子闻已，叹曰：“善哉！善哉！贤者拘絺罗。”尊者舍梨子叹已，欢喜奉行。复问曰：“贤者拘絺罗，有几因几缘住无想定耶？”

尊者大拘絺罗答曰：“有二因二缘住无想定。云何为二？一者、不念一切想，二者、念无想界。是谓二因二缘住无想定。”

尊者舍梨子闻已，叹曰：“善哉！善哉！贤者拘絺罗。”尊者舍梨子叹已，欢喜奉行。

复问曰：“贤者拘絺罗，有几因几缘从无想定起？”

尊者大拘絺罗答曰：“有三因三缘从无想定起。云何为三？一者、念一切想，二者、不念无想界，三者、因此身因六处缘命根。是谓三因三缘，从无想定起。”

如是，彼二尊更相称叹善哉善哉，更互所说，欢喜奉行，从座起去。

晡利多品第十七竟。

--------------

