* 第三章


01 尔时世尊于清晨著衣持钵往□舍离乞食。行乞归来后，饭食已毕，彼告尊者阿难说：「阿难，携取坐具，我将去洽巴拉神舍休息。」「是，世尊。」尊者阿难回答说，即携坐具随从佛后。

02 于是薄伽梵走向洽巴拉神舍，坐于敷座上。尊者阿难亦就坐其侧。坐已，薄伽梵告尊者阿难说：「阿难，□舍离是一可喜悦之处。而乌但那神舍、乔达摩卡神舍、七□果神舍、多子神舍、沙然达达神舍、洽巴拉神舍等亦是可喜乐的。

03 「阿难，若有人修持、留住、扩展四神足的极顶，既精于此，可用之如车乘，以此为基础，若欲，彼可住寿一劫，或其劫之某部份。而佛陀曾充份修持，扩展此四神足(其详见上)，彼若有意，可住寿一劫或其劫之某部份。」

04 尊者阿难对佛陀所给与之明显提示未能了解，他未曾恳请世尊说：「世尊，请住寿一劫，慈尊为众生之利益与快乐，及慈愍此世界，为人天之利益，快乐与幸福，请寿一劫！」因其心为魔所蒙蔽。

05 如是再三，薄伽梵告尊者阿难说(其详见上)。但尊者阿难数次均为魔所蒙蔽。

06 于是薄伽梵告尊者阿难说：「去，阿难，可宜知时。」「是，世尊。」尊者阿难回答说。即从座起，向佛作礼，右□而去，坐于一附近树下。

07 尔时恶魔于尊者阿难去后不久，即来至佛所，立于其侧，白佛言：「世尊，薄伽梵现在应入涅槃。慈尊，现在正是如来入涅槃之时，请速入涅槃，甚至根据前薄伽梵所说：『恶魔，若我之比丘、比丘尼、优婆塞优婆夷，尚未成为正闻、聪慧、善摄、多闻、熟记圣典、精娴教义、奉持戒律；既精于法，乃能教导、宣演、建立、开启、详释、明辨，能以正法扫荡，降伏异论，及广宣妙法－－之弟子时，我将不入涅槃。』

08 世尊，现在诸比丘、比丘尼、优婆塞、优婆夷皆已成为正闻、聪慧、善摄……(其详见上)之弟子。世尊，薄伽梵现在应入涅槃。慈尊，现在正是如来入涅槃之时，请速入涅槃！甚至依照薄伽梵所说：『恶魔，若我之清净教不成功、兴盛、广布、普遍及遍传于人间时，我将不入涅槃。』世尊，现在你之清净教已成功、兴盛、广布、普遍、及遍传于人间。世尊，薄伽梵现在应入涅槃。慈尊，现在正是如来入涅槃之时，请速入涅槃！」

09 他既作此语，薄伽梵告恶魔说：「恶魔，你且自喜。佛之圆寂已近。此后三月如来即将入涅槃。」

10 尔时薄伽梵于洽巴拉神舍谨然住念舍寿。佛既舍寿，有大地震，殊可惊怖及天雷响震。佛见此事已，既说偈曰：生命之源无量或微小。牟尼今舍其寿数。以内心静乐，打破其如甲胄之生命之源。

11 尔时尊者阿难自念：「此诚奇妙不可思议。此大地震殊可惊怖及天雷响震，此地震出现之远近因缘究何所在？」

12 于是尊者阿难走向佛前向佛作礼，就座其侧以后，白佛言：「世尊，此诚奇妙不可思议，此大地震殊可惊怖及天雷响震。世尊，此地震出现之远近因缘究何所在？」

13 「阿难，大地震之出现有八种因缘，何者为八？阿难，此大地止于水上，水止于风，风止于空。阿难，有时空中起大风，起大风则水动，水动则地动。此为大地震出现之第一因缘。

14 「复次，阿难，有时具大智慧力之沙门或婆罗门作摄心想；或有大威神之神祗－－当彼等观水想多，观地想少，地即大震动。此为大地震出现之第二因缘。

15 「复次，阿难，当菩萨谨然住念离兜率天而入于母胎时，地即大震动。此为大地震出现之第三因缘。

16 「复次，阿难，当菩萨谨然住念出母胎时，地即大震动，此为大地震出现之第四因缘。

17 「复次，阿难，当如来证无上正等觉时，地即大震动。此为大地震出现之第五因缘。

18 「复次，阿难，当如来转无上*轮时，地即大震动。此即大地震出现之第六因缘。

19 「复次，阿难，当如来谨然住念舍寿时，地即大震动。此为大地震出现之第七因缘。

20 「复次，阿难，当如来于无余涅槃界证取涅槃时，地即大震动。此为大地震出现之第八因缘。阿难，此为大地震出现之八种因缘。」

21 「阿难，有八种众。何者为八？即：刹帝利众、婆罗门众、居士众、沙门众、四天王众、忉利天众、魔众及梵天众。

22 「阿难，我忆念往昔曾参加一约数百人之刹帝利众。于我未就座、或言说、或交谈以前，我使我自己与其颜色相同、与其声音相同，以法要示教利喜之。当我宣说时，彼等不识我，自问说：『宣说者为谁？是神是人？』以法要示教利喜之后，我即隐身不见。彼等亦不知我何时隐去，自问说：『隐去者为谁？是神是人？』

23 「阿难，我忆念往昔曾参加一约数百人之婆罗门众、居士众、沙门众、四天王众、忉利天众、魔众及梵天众。于我未就座、或言说、或交谈以前，我使我自己与其颜色相同，与其声音相同，以法要示教利喜之。当我宣说时，彼等不识我，自问说：『宣说者为谁？是神是人？』以法要示教利喜之后，我即隐身不见。彼等亦不知我何时隐去，自问说：『隐去者为谁？是神是人？』阿难，此为八种众。」

24 「阿难，有八胜处。何者为八？

25 「阿难，若人有主观色想视外间有限或苦或乐之诸相，既专精于此，遂有『我知我见』之念。此为第一胜处。

26 「若人以主观色想视外间无穷或苦或乐之诸相，既专精于此，遂有『我知我见』之念。此为第二胜处。

27 「若人无主观色想视外间有限或苦或乐之诸相，既专精于此，遂有『我知我见』之念。此为第三胜处。

28 「若人以无主观色想视外间无穷或苦或乐之诸相，既专精于此，遂有『我知我见』之念。此为第四胜处。

29 「若人以无主观色想视外间诸相是青色、青相、青映影。正如乌马花是青色、青相、青映影。又如波罗奈所产细布，表裹精致是青色、青相、青映影。若如此以无主观色想视外间诸相是青色、青相、青映影，既专精于此，遂有『我知我见』之念。此为第五胜处。

30 「若人以无主观色想视外间诸相是黄色、黄相、黄映影。正如堪尼卡罗花是黄色、黄相、黄映影。又如波罗奈所产细布，表裹精致是黄色、黄相、黄映影，既专精于此，遂有『我知我见』之念。此为第六胜处。

31 「若人以无主观色想视外间诸相是红色、红相、红映影。正如班都几瓦卡是红色、红相、红映影，又如波罗奈所产细布，表裹精致是红色、红相、红映影，既专精于此，遂有『我知我见』之念。此为第七胜处。

32 「若人以无主观色想视外间诸相是白色、白相、白映影。正如俄沙底星是白色、白相、白映影。又如波罗奈所产细布，表裹精致是白色、白相、白映影。若人如此以无主观色想视外间诸相是白色、白相、白映影，既专精于此，遂有『我知我见』之念。此为第八胜处。阿难，此为八胜处。」

33 「阿难，此为八解脱。何者为八？「以相见相，是第一解脱。「不觉其自相见外间诸相，是第二解脱。「存心于善，是第三解脱。「超出诸色想，断除诸愤怒想，不思念诸相，自念：是『空无边』而入于空无边处定，是第四解脱。「超出空无边处，自念：是『识无边处』而入于识无边处定，是第五解脱。「超出识无边处，自念：是『无所有』而入于无所有处定，是第六解脱。「超出无所有处，自念：是『非想非非想』而入于非想非非想处定，是第七解脱。　「超出一切『非想非非想处』而入于灭想定，是第八解脱。阿难，此为八解脱。

34 「阿难，往昔我于尼连禅河岸边，牧羊人菩提树下初成正觉时，彼时恶魔来至我所，立于我侧向我说：『世尊，薄伽梵现在应入涅槃。慈尊，现在正是如来入涅槃之时，请速入涅槃。』

35 「阿难，彼作是语已，我告恶魔说：『恶魔，若我之比丘、比丘尼、优婆塞、优婆夷尚未成为正闻、聪慧、善摄、多闻、熟记圣典、精娴教义、奉持戒律；既精于法乃能教导、宣演、建立、开启、详释、明辨；能以正法扫荡、降伏异论及广宣妙法之弟子时，我将不入涅槃。「『恶魔，若我之清净戒不成功、兴盛、广布、普遍及遍传于人间时，我将不入涅槃。』

3637 「阿难，我今于洽巴拉神舍，该恶魔复来我所，立于我侧向我说：『世尊，薄伽梵现在应入涅槃。慈尊，现在正是如来入涅槃之时，请速入涅槃！世尊，即使依照前薄伽梵所说：(其详见上)』「阿难，他既作此语，我告恶魔说：『恶魔，你应欢喜！佛陀不久即将圆寂。此后三月，如来即将入涅槃。』「阿难，如来今日于洽巴拉神舍谨然住念舍寿。」

38 彼说是语时，尊者阿难白佛言：「世尊，请住寿一劫，慈尊为众生之利益与快乐，及慈愍此世界，为人天之利益、快乐与幸福，请住寿一劫！」「阿难，止止，莫恳请如来。现今劝请如来，已非其时。」

39 如是第二第三(阿难如是恳请，佛陀如是回答)。「阿难，你对佛陀之智慧是否有信仰？」「是，世尊。」「阿难，你为何烦扰如来至于第三次？」

40 「世尊，我亲从佛闻及亲从佛受：『若有人修持、留住、扩展及抵达四神足的极顶，既精于此，可用之如车乘。以此为基础，若欲，彼可住寿一劫或劫之剩余部份；而佛陀曾充份修持、扩展及抵达此四神足………(其详见上)他若有意，可住寿一劫或其劫之某部份。』「阿难，你是否有信仰？」「是，世尊。」「阿难，此是你之错误及罪过。前如来给与你之明显提示，你都未能了解，未曾恳请如来说：『世尊，请住寿一劫，慈尊为众生之利益与快乐，及慈愍此世界，为人天之利益，快乐与幸福，请住寿一劫。』阿难，你若如是垦请如来，至于第二次，他或不俯允，但第三次他或将纳受。因此，阿难，此是你之错误及罪过！」

41 「阿难，往昔我住王舍城灵鹫山峰时亦曾向你说：『阿难，王舍城与灵鹫山峰是甚可喜乐之处。阿难，若有人修持、留住、扩展及抵达四神足的极顶，既精于此，可用之如车乘。以此为基础，若欲，彼可住寿一劫或其劫之剩余部份；而佛陀曾充份修持、扩展及抵达此四神足……(其详见上)，他若有意，可住寿一劫或其劫之剩余部份。』而你，阿难，如来给与你之明显提示，你都未能了解，未曾恳请如来说：『世尊，请住寿一劫，慈尊为众生之利益与快乐，及慈愍此世界，为人天之利益、快乐与幸福，请住寿一劫！』阿难，你若如是恳请如来至于第二次，他或不俯允，但第三次他或将纳受。因此，阿难，此是你之错误及罪过！」

42 「阿难，往昔我住王舍城榕树园，住王舍城贼峰，住王舍城韦跋罗坡之沙打畔尼洞，住王舍城伊思□里坡之黑岩，住王舍城沙巴桑底卡山□斯塔园，住王舍城塔坡达园，住王舍城竹园喂松鼠处，住王舍城耆婆之□果，住王舍城马打苦其之鹿林。

43 「阿难，在上列各处，我也曾向你说：『阿难，王舍城等等(其详见上)是甚可喜乐之处。』

44 「『阿难，若有人修持、留住、扩展及抵达四神足的极顶，既精于此，可用之如车乘。经此为基础，若欲，彼可住寿一劫或其劫之剩余部份；而佛陀曾充份修持、扩展及抵达此四神足(其详见上)，他若有意，可住寿一劫或其劫之剩余部份。』而你，阿难，如来给与你之明显提示，你都未能了解，未曾恳请如来说：『世尊，请住寿一劫，慈尊为众生之利益与快乐，及慈愍此世界，为人天之利益、快乐与幸福，请住寿一劫！』阿难，你若如是恳请如来至于第二次，他或不俯允，但第三次他或将纳受。因此，阿难，此是你之错误及罪过！」

45 「阿难，往昔我住□舍离之乌但拉神舍时，亦曾向你说『阿难，□舍离与乌但拉是甚可喜乐之处。若有人修持、留住、扩展及抵达四神足的极顶，既精于此，可用之如车乘，以此为基础，若欲，彼可住寿一劫或其劫之剩余部份；而佛陀曾充份修持、留住及扩展此四神足……(其详见上)，他若有意，可住寿一劫或其劫之剩余部份。』而你，阿难，如来给与你之明显提示，你都未能了解，未曾恳请如来说：『世尊，请住寿一劫，慈尊为众生之利益与快乐，及慈愍此世界，为人天之利益、快乐与幸福，请住寿一劫！』阿难，你若如是恳请如来至于第二次，他或不俯允，但第三次他或将纳受。因此，阿难，此是你之错误及罪过！」

46 「阿难，往昔我住□舍离之乔达摩卡神舍，住□舍利之七□果神舍，住□舍离之多子塔神舍，住□舍离之沙然达达神舍时，亦曾向你说：『阿难，□舍离各地是甚可喜乐之处……。」(其祥见上)

47 「阿难，现今在洽巴拉神舍，我也曾向你说：『阿难，□舍离是甚为幽静，乌但拉神舍，乔达摩卡神舍，七□果神舍，多子塔神舍，沙然达达神舍等是甚可喜乐之处。若有人修持、留住、扩展及抵达四神足的极顶，既精于此，可用之如车乘，以此为基础，若欲，彼可住寿一或其劫之剩余部份；而佛陀曾充份修持、留住及扩展此四神足。他若有意，可住寿一劫或其劫之剩余部份。』而你，阿难，如来给与你之明显提示，你都未能了解，未曾恳请如来说：『世尊，请住寿一劫，慈尊为众生之利益与快乐，及慈愍此世界，为人天之利益、快乐与幸福，请住寿一劫！』阿难，你若如是恳请如来至于第二次，他或不俯允，但第三次他或将纳受。因此，阿难，此是你之错误及罪过！」

48 「阿难，是否往昔我曾告诉你说：万物实性如此，其与我们最亲近者将要与我们分别隔离？当一物既生而成形，既具分离必然性，不要其解离，此何可能，且必无此理。阿难，如来已舍弃寿命。且他一言既出：『佛陀之圆寂甚近，此后三月如来即将入涅槃。』如来为生存而食言，应无是处！」「来，阿难，我等去大林的重阁讲堂。」「是，世尊。」尊者阿难回答说。

49 尔时佛陀与尊者阿难走向大林的重阁讲堂。到已，佛告尊者阿难说：「阿难。你往告住在□舍离附近的诸比丘尽集讲堂。」「是，世尊。」尊者阿难回答说。他即往告住在□舍离附近的诸比丘尽会讲堂。回来时他向佛作礼，退立一面说：「世尊，比丘僧众已齐集讲堂，唯圣知时。」

50 于是薄伽梵从座起，走向讲堂，就座已，告诸比丘说：「因此，诸比丘，我所知及为汝等所宣说之法，当善学、善修、善思、善布，因而梵教可以长远住世。此是为众生之利益与快乐，及慈愍此世界，为人天之利益、快乐与幸福。诸比丘，云何为我所知及为汝等所宣说之法，当善学、善修、善思、善布，因而梵教可以长远住世。此是为众生之利益与快乐，及慈愍此世界，为人天之利益、快乐与幸福？盖即：四念处四正勤四神足五根五力七菩提分八圣道诸比丘，此是我所知及为汝等所宣说之法，当善学、善修、善思、善布，因而梵教可以长远住世。此是为众生之利益与快乐，及慈愍此世界，为人天之利益、快乐与幸福。」

51 尔时薄伽梵告诸比丘说：「诸因缘合和法皆归老朽，当精勤取证！如来的圆寂甚近，此后三月，如来即将入涅槃。」薄伽梵说此后，复以偈曰：我之生命已成熟，我之寿命将尽。我将离尔等而去，独依靠我自己。诸比丘当精勤、持净及善思维，应有坚定决心及自观心。谁能勤恳住于法与戒，则超度生命之海，而证得苦尽。
