* 第五章


01 尔时薄伽梵告尊者阿难说：「来，阿难，我等去醯连尼耶瓦提河之彼岸，拘尸那罗的乌帕瓦塔那，马拉之娑罗树林。」「是，世尊。」尊者阿难回答说。于是佛与大比丘僧众向醯连尼耶瓦提河之彼岸，拘尸那罗的乌帕瓦塔那，马拉之娑罗树林进行。到已，语尊者阿难说：「阿难，请为我敷设床具于娑罗双树间，其头北向，我倦甚，欲偃卧。」「是，世尊。」尊者阿难回答说，即于娑罗树间敷陈床具，其头北向。时世尊心境安稳，偃卧右侧，将其双足叠并，作狮子睡。

02 尔时娑罗双树忽于非时鲜花开发，缤纷散落在如来身上以供养如来。天上的曼陀罗华亦从天下降，缤纷散落在如来身上以供养如来。天上的旃陀罗香屑亦从天下降缤纷散落在如来身上以供养如来。天上的音乐亦从天演奏以供养如来。天上的歌唱亦从天发出以供养如来。

03 于是世尊告尊者阿难说：「阿难，娑罗双树忽于非时鲜花开发，缤纷散落在如来身上以供养如来。天上的曼陀罗华亦从天下降缤纷散落在如来身上以供养如来。天上的旃陀罗香屑亦从天下降缤纷散落在如来身上以供养如来。天上的音乐亦从天演奏以供养如来。天上的歌唱亦从天发出以供养如来。「阿难，并非如此是对如来有适宜的恭敬供养。若比丘、比丘尼、优婆塞、优婆夷继续担负大小责任，持身端正，依止戒律－－如是，其人是对如来有适宜的恭敬供养和最有价值的敬礼。是以阿难，汝应继续负担大小责任，持身端正，依止戒律。阿难，应如此教化。」

04 尔时尊者乌帕宛那立于佛前以扇扇佛。世尊对他不悦并告之曰：「汝退出，比丘，不用立在我面前。」尊者阿难自念：「此尊者乌帕宛那亲身奉侍如来已为时很久。现在于临终之际，世尊对之不悦并告之曰：『汝退出，比丘，不用立在我面前。』究竟是何因缘，世尊对他不悦而发出此语？」

05 尔时尊者阿难白佛言：「世尊，此尊者鸟帕宛那亲身奉侍如来为时已久。现在于临终之际对他不悦并向他说：『汝退出，比丘，不用立在我面前。』究竟是何因缘，世尊对他不悦而发出此语？」「阿难，十方世界无数天神云集来瞻仰如来。环□拘尸那罗的乌帕瓦塔那，马拉之娑罗双树林十二由旬的附近，无一容发尖之缝隙没有被具大威神的天神所占据。阿难，此诸天神埋怨说：『我等自远道来瞻视如来，正等正觉阿罗汉如来之出世是甚为希有。在今晚更末如来将取涅槃，而这位有名的比丘立于其前遮蔽之，我等不得于临终之际瞻仰如来！』阿难，诸天神如此埋怨说。」

06 「但世尊认彼等为何等样的天神？」「阿难，在天上的神祗还有尘世意念，彼等或披发而哭，或挺臂而哭，或自投地宛转而哭，当一念及：『薄伽梵取涅槃何如是其迅速，慈尊取涅槃何如是其迅速！世界之光熄灭何如是其迅速！』「阿难，在地上的神祗还有尘世意念，彼等或披发而哭，或挺臂而哭，或自投地宛转而哭，当一念及：『薄伽梵取涅槃何如是其迅速，慈尊取涅槃何如是其迅速！世界之光熄灭何如是其迅速！』「但诸离欲的神祗泰然自摄忍受之，并忆念及：『缘会诸法实是无常，若不如此，实不可能。』

07 「世尊，往昔诸比丘于各地坐夏后皆来觐见如来。我等接待诸长老，使晤见及侍候如来。但于如来去世后，我等不能接待诸长老使晤见及侍候如来。」

08 「阿难，有四处，具信仰之族姓王子应朝礼致敬，何者为四？「(1)阿难，信仰者于一处能说：『此是如来降生处』，则为应朝礼及致敬之处。」「(2)阿难，信仰者于一处能说：『此是如来证无上正等正觉处』，则为应朝礼及致敬之处。」「(3)阿难，信仰者于一处能说：『此是如来转*轮处』，则为应朝礼及致敬之处。」「(4)阿难，信仰者于一处能说：『此是如来入无余涅槃界处』，则为应朝礼及致敬之处。」「阿难，此为四处，具信仰之族姓子应朝礼致敬。阿难，信仰者－－比丘、比丘尼、优婆塞、优婆夷等将赴上列各处并说：『此是如来降生处』、或『此是如来证无上正等觉处』、或『此是如来转*轮处』、或『此是如来入无余涅槃界处』。「阿难，当彼等朝礼诸圣地，其有信心而死去时，彼等于身坏命终将上生快乐的天界。」

09 「世尊，我们对于妇女将何以自处？」「阿难，不要看她们。」「若见了她们，我们将何以自处？」「阿难，不要交谈。」「世尊，若她们向我们攀谈又将如何？」「阿难，当自警惕！」

10 「世尊，我们对于如来的遗体将如何处理？」「阿难，你们向如来的遗体致敬不必顾虑，我请求你们当自勉、当专重于自善、当自精勤不懈及注法于自善。在刹帝利、婆罗门、居士中有智者，他们对如来有坚固信仰；他们将对如来的遗体致敬。」

11 「世尊，对于如来的遗体当如何处理？」「阿难，如人处理转轮圣王的遗体，对如来的遗体亦应如此。」「世尊，如何处理转轮圣王的遗体？」「他们以新布包裹转轮圣王的遗体，继以亲净棉，再以新细布，如是一层布、一层棉，至各有五百层为止。然后将其安放在有油之金(1)棺内，复以另一金棺盖之，用诸种香□作火葬场以焚烧转轮圣王的遗体；于十字街头为之建塔。此为人们处理转轮圣王的遗体之法。「阿难，人们如此处理转轮圣王的遗体，对如来的遗体亦应如此；也应在十字街头为如来建塔。若有人对之奉献花香、图绘或礼拜，其人将获永久福利及快乐。」^2□1巴利文AYASAYA原意为「铁」，或「铜」，佛音谓此地应作「金」。

12 「阿难，有四种人应值得为之造塔，何者为四？「(1)正等正觉如来应值得造塔。(2)辟支佛应值得造塔。(3)如来的声闻弟子应值得造塔。(4)转轮圣王应值得造塔。「阿难，云何正等正觉如来应值得造塔？若人念及：『此为正等正觉如来的塔』之时，那将使很多人内心平静及愉快。他们既得内心平静快慰，于身坏命终之后能转生快乐的天界。阿难，此为正等正觉如来应值得造塔的理由。「阿难，云何辟支佛应值得造塔？若人念及：『此为辟支佛的塔』之时，那将使很多人内心平静及愉快。他们既得内心平静快慰，于身坏命终之后能转生快乐的天界。阿难，此为辟支佛应值得造塔的理由。「阿难，云何如来之声闻弟子应值得造塔？若人念及：『此为如来声闻弟子的塔』之时，那将使很多的人内心平静及愉快。他们既得内心平静快慰，于身坏命终之后能转生快乐的天界。阿难，此为如来的声闻弟子应值得造塔的理由。「阿难，云何转轮圣王应值得造塔？若人念及：『此为公平正值转轮王的塔』之时，那将使很多人内心平静及愉快。他们既得内心平静快慰，于身坏命终之后能转生快乐的天界。阿难，此为转轮圣王应值得造塔的理由。「阿难，此为四种人应值得为之造塔。」

13 尔时尊者阿难走入精舍，立于门楣，哭泣自念：『现在我还是一个声闻，未获道果，而慈愍的导师即将入涅槃！」尔时薄伽梵告诸比丘说：「诸比丘，阿难在Α魾？」「世尊，尊者阿难走入精舍，立于门楣，哭泣自念：『现在我还是一个声闻，未获道果，而慈愍的导师即将入涅槃！』于是薄伽梵语某一比丘说：「比丘，你称我名告阿难说：『阿难师兄，导师唤你。』」「是，世尊。」该比丘回答说，遂走向尊者阿难所在处。到已，他告尊者阿难说：「阿难师兄，导师唤你。」「是，师弟。」尊者阿难回答说，遂走向佛陀所在处。到已，向佛作礼，退坐一面。

14 当尊者阿难就座后，薄伽梵向他说：「止止，阿难，不要自苦，也不要哭！是否我于往昔曾告诉你万物实性如此，其与我们最亲近者将要与我们分别隔离？当一物既生而成形，即具分离的必然性，不要其解离，此何可能？且必无此理。阿难，很久以来，以你的慈而善的爱行、爱语、爱念亲近于我，永不更变及莫可计算，甚堪嘉奖。阿难，当自精勤，不久你也将获得漏竟。」

15 尔时薄伽梵告诸比丘说：「诸比丘，于过去世正等正觉阿罗汉诸佛有忠诚的侍者为诸如来服务，正如阿难之对于我。而未来世若有人作正等正觉阿罗汉诸佛，亦有忠诚的侍者为诸如来服务，也正如阿难之对于我。「诸比丘，阿难为一智者，他知何时为比丘、比丘尼、优婆塞、优婆夷、国王、大臣、外道及其信徒等去觐见如来是最为适宜。

16 「诸比丘，阿难有四种希有特质。何者为四？」诸比丘，若有(1)比丘众往访阿难，谒见后他们充满欣悦，彼遂向之开示法要。他们对其所说充满欣喜；当阿难默然不语，则诸比丘殊觉不安。「诸比丘，若有(2)比丘尼、(3)优婆塞、(4)优婆夷往访阿难，谒见后他们充满欣悦，彼遂向之开示法要。他们对其所说也充满欣喜；当阿难默然不语，则诸比丘尼等殊觉不安。「诸比丘，转轮圣王有四种希有特质。何者为四？「诸比丘，若(1)刹帝利、(2)婆罗门、(3)居士、(4)沙门等众往谒转轮圣王，觐见后他们充满欣悦，彼遂向之开示法要。他们对其所说充满欣喜；当转轮圣王默然不语，则他们殊觉不安。「诸比丘，正如此，阿难有此四种希有特质。若比丘、比丘尼、优婆塞、优婆夷众往访阿难，谒见后他们充满欣悦，彼遂向之开示法要。他们对其所说充满欣喜；当阿难默然不语，则彼等殊觉不安。「诸比丘，此为阿难的四种希有特质。」

17 当其作如是语已，尊者阿难白佛言：「世尊，请不要在此鄙陋小城，荒毁之地，证取涅槃。因为更有大城如：瞻波、王舍、舍卫、萨克陀、柯善必、波罗奈等，请薄伽梵于其中之一证取涅槃，彼处多诸富有的刹帝利、婆罗门、长者居士－－信佛弟子。他们对如来的遗体将致敬仰。」

18 「止止，阿难，不应作如是语：此是一鄙陋小城，荒毁之地。阿难，往昔有一王名大善见。他是一正直之人，以正直御世，拥有七宝，征服全球，为四天下之主，并为人民保护者。此大善见王之首都名拘舍婆提，即在此拘尸那罗城。其城东西长十二由旬，南北宽七由旬。「阿难，此拘舍婆提首都甚为广阔繁荣，人民汇集，充满各种食品，正如诸天之首都阿拉卡曼达，广阔繁荣，民众及诸天神荟集，各种食品充满。阿难，拘舍婆提首都亦复如是。「阿难，此拘舍婆提首都日夜发出十种声音，如：象声、马声、车声、鼓声、手鼓声、琵琶声、歌声、钵铙钵声、锣声及「吃、喝、嬉笑声」。

19 「阿难，你去拘尸那罗通知该地的马拉说：『瓦舍塔们，今晚更末如来将取涅槃，你们请自便，不要后来自责说：『如来在我们的乡村圆寂，而我们失去最后觐见的机会。』「是，世尊，」尊者阿难回答说。他遂著衣持钵，有另一比丘作伴，走向拘尸那罗。

20 尔时拘尸那罗的马拉正集于会厅商议公事。尊者阿难走向该会厅。到已，他告诉马拉说：『瓦舍塔们，今晚更末如来将取涅槃。你们请自便！不要后来自责说：『如来在我们的乡村圆寂，而我们失去最后觐见的机会。』

21 闻尊者阿难如是语已，马拉们与其少年、少女及妻子皆悲哀惨凄，中心忧伤，当一念及：「薄伽梵取涅槃何如是其迅速！慈尊取涅槃何如是其迅速！世界之光熄灭何如是其迅速！」他们或披头散发而哭，或伸臂而哭，或自投地宛转而哭。尔时马拉们与其少年、少女及妻子皆悲哀惨凄，中心忧伤走向乌帕瓦塔那、马拉的娑罗树林尊者阿难的所在处。

22 尔时尊者阿难如是思维：「若我许拘尸那罗的马拉们一一向佛作礼，恐全部礼佛未毕即将天明。今且令彼等分队站立，每家为一队向世尊引见说：『世尊，今有某某马拉与其妻子，侍从，亲友等顶礼佛足。』」尊者阿难遂将拘尸那罗的马拉们每家组成一队向薄伽梵敬礼说：「世尊，今有某某马拉与其妻子侍从亲友等顶礼佛足。」采用如此方法，尊者阿难于一更时分已令拘尸那罗的全部马拉进前礼佛。

23 尔时有一游行者苏跋陀抵达拘尸那罗。彼听说：「今晚三更时分沙门乔达摩将入无余涅槃。」于是游行者苏跋陀如是思维：「我曾从诸长老、师父与弟子游行者处闻来：『正等正觉阿罗汉如来之出世是甚为希罕。』但在今夜三更时分沙门乔达摩即将入涅槃。今我心有疑。然我对沙门乔达摩有信心；我想他能揭示真理，用释我之疑惑。」

24 于是游行者苏跋陀走向乌帕瓦塔那．马拉的娑罗树林，尊者阿难的所在处。到已，他向尊者阿难说：「尊者阿难，我曾从诸耆宿长老、师父与弟子游行者处闻来：『正等正觉阿罗汉如来之出世是甚为希罕。』但在今夜三更时分沙门乔达摩即将入涅槃。今我心有疑。然我对乔达摩有信心；我想他能揭示真理，用释我之疑惑。尊者阿难，或者我也被许可去见沙门乔达摩？」「止止，朋友苏跋陀，请不用劳扰如来，他很倦乏。」第二第三次游行者苏跋陀向尊者阿难说：(其详见上)

25 当薄伽梵听到尊者阿难与游行者苏跋陀的谈话，彼告尊者阿难说：「止止，阿难，不用阻拦苏跋陀，且听他瞻仰如来。随彼所问，是因求知而问，非为劳扰；而随我所答，彼将迅速了解。」于是尊者阿难向游行者苏跋陀说：「请进，朋友苏跋陀，如来已给了许可。」

26 游行者苏跋陀遂走向佛前致敬，与之互相问讯后，即就座其侧，白佛言：「乔达摩，彼诸宗教领袖，门徒之首领，教派之创建者，远近知名，群众钦仰其为贤者如：(一)富兰迦叶，(二)末伽梨□舍梨，(三)阿浮多，翅舍钦婆罗，(四)波浮迦旃延，(五)萨若□耶梨弗，(六)尼犍子等，依照其自称，是否他们已彻底了解诸法？或有了解，或有不了解者？」「止止，苏跋陀，且放下：『依照其自称，是否他们已彻底了解诸法？或有了解，或有不了解者』，我将向你说法，且专心谛听！」「是，世尊」，游行者苏跋陀回答说。

27 于是薄伽梵说：「苏跋陀，若于任何法中无八圣道者，则无第一、第二、第三及第四沙门果。若于任何法戒中有八圣道者，则有第一、第二、第三及第四沙门果。今我法戒中有八圣道，苏跋陀，亦有第一、第二、第三及第四沙门果。外道诸师之法皆空幻，无沙门果，苏跋陀，若比丘能行正道，则世间不会缺少阿罗汉。『苏跋陀，我年二十九，出家求善道。自出离已来，已逾五一年。道法广阔界，常游巡仰企；于其领域外，实无沙门果。不但无第一沙门果，且无第二、第三及第四沙门果。外道诸师之法皆空幻、无沙门果。苏跋陀，若比丘能行正道，则世间不会缺少阿罗汉。」

28 当其如是语已，游行者苏跋陀白佛言：「世尊，你之法语优妙绝伦，正如倾者扶之，晦者显之，迷途者示以正道，住黑暗者示以明灯，因而有眼者能视外物。薄伽梵以众多譬喻为我开示真理亦复如是。因此，世尊，我皈依佛法僧，甚愿能许我在佛前出家及受具足戒。」

29 「苏跋陀，若人先为外道门徒，欲来此法戒中出家或受具足戒，他应有四月试习；四月期满，诸比丘喜悦听其出家或受具足戒。但我宣布此事是因人而异。」「世尊，若人先为外道门徒欲来此戒法中出家或受具足戒，此人应试习四月；四月期满，诸比丘喜悦，听其出家，或受具足戒。现我愿试习四月，四月之后，诸比丘喜悦听我出家或受具足戒。」尔时薄伽梵告尊者阿难说：「阿难，听许苏跋陀出家。」「是，世尊，」尊者阿难回答说。

30 尔时游行者苏跋陀向尊者阿难说：「阿难，你亲从导师沾润而为此僧团之弟子，你获大饶益，你得大福利。」是时游行者苏跋陀于薄伽梵之僧团出家并受具足戒，尊者苏跋陀于受具足戒之后即坚定精勤，离群独居。不久即证得最高梵行境界。为此之故，族姓子舍弃各种家庭利益与舒适而出家。诚然，于现世以自力证取最高目标。他自知生死已断，梵行已立，所作已作，今生后不再有来生。尊者苏跋陀成了阿罗汉之一，他为薄伽梵所化的最后弟子。


