* 尘封的足迹-<feff>-我的禅修经历（十一）

过了一段时间，妻子也来到了禅修中心，我便领她到中心里到处走走，在禅堂通往宿舍的路上，妻子指着路边的树说：你看，长了这么多波罗蜜果。我抬眼望去才发现，原来从禅堂到宿舍路边的大树居然是波罗蜜树，树干和树根上挂着许多波罗蜜果，以前就听说过波罗蜜果是长在树干上的，但从来没见过，一直都很好奇，没想到这次居然亲眼见到了。而这些大树离路不过一两米远，每天在这条路上来来回回多少次，一个多月了我居然都没有注意到它们。看来这次真正做到了守护根门，完全投入到了观察身心中，我为自己这段时间的精进感到非常的喜悦。\\

file:./imgs/11-0.png

很快一个月便过去了，我和妻子一同回到了家中，并整理了一个小房间作为禅堂，经过了这近两个月的密集禅修，禅修已经成了习惯，每天都会安排4个小时以上的固定禅修时间。传说禅修的人越修越冷漠、离群、厌世，但我发现禅修后反而更加开朗乐观了，过去生活所带来的茫然和束缚感已经一扫而空。一直和我朝夕相处的妻子最为了解，她时常开玩笑说：你不是我老公，我不知道你把我老公绑架到哪里去了，但我希望你把他撕票。

为了确定是否证的道果智，我开始查阅缅甸、泰国、斯里兰卡等国内外尊者的开示书籍，依照尊者们的描述，我仍然觉得上次体验到寂灭的那次，无论其前后还是过程本身，都很符合书中所描述的观智过程。

file:./imgs/11-1.png

但毕竟文字对这些现象描述的精确性是有限的，内心仍然感到有些没把握，更主要的是，虽然这些体验很特殊，超乎想象，并确实给我带来了持久的平静和喜乐，但我并没有发现在获得这些体验的瞬间，会像经典中所描述的那样，认知到“凡所有集法都是灭法”，也没有底气说出“我已见法、已知法，对法已无疑，已得无畏”，而这些在经典中好像是一个证果者的标配。更没有像有些禅师说的，知道有哪些烦恼被灭了，并能确定自己不再堕入恶道。

回想这一年来的禅修经历，反而是那两次看到“听识”和“意识”的体验对我来说收获最大，但在论书及开示书中却没有找到类似的记载。古往今来，人们认为涅槃的首要条件就是没有名色，而我在那一刻却是明显有现象的，这显然不符合人们对涅槃的描述。那段时间，对确定是否证果的思考常常让我感到困惑。

几个月后，恰宓长老要到南昌举办禅修营，这是个寻求答案的好机会，于是我再次报名参加了禅修营，可惜的是，因为某些原因，此次长老不能讲法，所以禅修营里并没有安排长老的工作，大多数时间长老都不在寺院，要找到长老小参相当困难。

file:./imgs/11-2.png

连续几天我都守在长老的房间附近经行，并多次请求翻译能否帮我向长老约个时间，但是因为长老在寺院的时间实在太少，为了节约时间，翻译让我把要报告给长老的事情提前告诉她，她找时间向长老转达后再通知我。于是我只好长话短说，将经历过的类似书中所描述的体验告诉了她，只想让长老验证这些体验是不是涅槃。

几天后，终于在长老又要出门时找到了机会，长老听了翻译转达的话后，又询问了我几个细节问题，然后让翻译告诉我：“你所看到的现象都是正确的，继续用功，你会看到更好的”。这就是答案吗？我不甘心，再三询问时，长老便闭上了眼睛，不再回答我的任何问题了，翻译告诉我说：长老已经知道你的情况了，不再回答你的问题一定有他的用意的，你不需要再问了，安心禅修去吧。

file:./imgs/11-3.gif

走出了长老的房间，我心里的一块大石头终于落地了，虽然没有得到答案，但是我认为，在禅修方面，恰宓长老已经是目前世界上最权威之一，如果连恰宓长老都不给我答案，便再也没有人能给我答案了。断绝了寻找答案的念头，反而让我放下了一个沉重的负担，内心轻松多了。（未完待续。。。）

