* 尘封的足迹---我的禅修经历（十二）

禅修营结束后，我和妻子开始了另外半个中国的旅行，之后回到江西老家陪伴父母，因为父母对禅修不理解，怕打坐会引起他们误会，所以我白天一直都只在卧室经行，偶尔他们看到，也只是像边走边思考问题，晚上夜深人静的时候才打坐。

家里有几个不满十岁的小孩，放学后和假期，多数时间都在家中戏耍，时常在我经行的时候跑进卧室，拉扯着、围着我追逐打闹。客厅电视的声音也很大，特别是看过几眼的电视，听到声音后就会自动脑补画面，父母有时也会喊我去聊天或帮忙做一些杂活，定力经常被中断，于是我不得不提起更强的精进，不断地对治这些干扰，并尽量让自己能快速地在禅修和生活之间切换。

file:./imgs/12-0.png

在老家的几个月，每天超过10个小时的经行，定力得到了极大的提升，喜乐常常充盈全身，犹如之前在缅甸的那段时间的状态。即便其间有事处理，之后回到房间也只需走两三步就能恢复，而小孩们的追闹拉扯已经丝毫不影响定力。经过了一整天的经行，夜深人静时的打坐，则更加的平静，之前在禅修营出现的下坠的现象也时常出现，经历了几次之后我发现，这应该就是因为内心过于平静，而观察的精进力不够所引起的一种定境。以前偶尔才有的其它特殊体验，如今也成为了常态，书中所描述的许多观智，在这种状态下，不断地被更深层地、清晰地、频繁地体证。

file:./imgs/12-1.png

过完年后回到云南，我发现定力和精进力已经非常平衡了，无论何时，当我决意禅修，便不见有任何事务能影响我，即便妻子在我边上看电影，我也仍然不会被电影的内容所干扰，并且随时都可以在生活和禅修之间瞬间切换，丝毫没有障碍。禅修几乎已经成了我的全部工作，每天早上从醒来便开始观察，除了买菜、煮饭、用餐、午休等必要的时间外，大多数的时间都在禅修。

file:./imgs/12-2.jpeg

2018年夏天，我再次报名参加了因德嘉长老在江西耕香寺举办的禅修营，距离上次禅修营已经一年多了，为了确定这一年来有没有修错，在开营的前一天，我便提前向长老报告了我的近况，希望得到长老的指导，以便能在此次禅修营中修正。长老告诉我说，他将会在这期禅修营中仔细审察我的禅法的正确性，因为之前两次看到两个对象的体验对我的改变相当大，又一直没搞清楚是什么现象，所以也将这个告诉了长老，但是可能因为用语言很难表达清楚，又是通过翻译，长老似乎并不能理解我所说的现象，经过了长时间的解释，最终仍然无法确定是什么体验，只好作罢。

禅修营开始后，我仍然继续如之前般地禅修，每次小参时，长老都告诉我，你的禅法已经完全正确、你的禅法已经没有任何错误、你的禅法已经不会再有任何问题了，等等诸如此话，我对禅修的信心也越来越强了，而禅修状态也的确令人满意，当时正值盛夏，气温超过40度，打坐时汗如雨下，但是内心却仍然不受干扰，静静地观察着身心所生起的一切现象。

file:./imgs/12-3.gif

有一天打坐时，当我紧密地观察着炎热的天气下，身体不断生起的各种感受以及内心的反应时，身心现象经过清晰又短暂的一个加速后，又一次戛然而止，我看到极其清净的状态下，面前有一团类似浓雾的现象，“这是什么？”念头紧接着生起，“一团苦”，内心如此说到。

瞬间，这团苦连同身心内外所有的苦受都如同潮水般迅速退去，身心没有一处不是清凉、纯净的。那一刻，感觉到所有的苦都完全脱落、消失了。很快，我的身体再次如以前般的沸腾，所有细胞都开始震动，眼泪不由自主地流了出来，但并非是因为痛苦，而是充满着极其喜悦的眼泪。

“一团苦”，太震撼了，身心就只是这一团苦，人们常说三界如火宅，而如今却发现，原来这个身心就是火宅，就是苦本身，这样一团苦的身心，生在哪都是一样的苦，这一刻，我不想再以任何形式的生命在任何地方出生，对身心的执着似乎完全消失，就像一堆粪便，放到哪都是臭的，因为它本身就是臭的。\\

当这样思维后，我突然想起了泰国某位尊者所说，看到身是苦就是三果，看到心是苦就是四果，而如今我同时看到身心都是苦，而且对任何一界的生存都没有了意愿，难道是证悟了阿罗汉了吗？回想起这两年多体验过的各种各样的观智，我开始有点飘飘然了，想着自己即使没有证得四果，至少也是三果了，今生的禅修任务终于完成了。（未完待续。。。）

