* 尘封的足迹---我的禅修经历（十三）

我向长老报告了这次的体验，并询问他那苦完全消失的瞬间应该是涅槃了吧。长老并没有正面回答，而是给了我一个关于证悟涅槃时的比喻，并描述了在证得涅槃后应该会有的果定状态，但在这里我就不写出来了，以免有禅修者会因错误的理解而走偏。\\
file:./imgs/13-0.jpeg

当长老详细地告知我这些内容后，我发现，这些好像在我过去的禅修中便已经体验过了，而这次的则更像泰国尊者所说的状态，特别是每当回想起那“一团苦”的体验时，仍然极其喜悦到难以抑制的流泪，我想，这不正是有位泰国尊者所说的阿罗汉的眼泪吗？之后的几天里，身心依然持续着极致的清净和喜乐，自认为已经完成禅修工作的我，开始沉浸在对佛法理论的各种思维中。

禅修营结束后我回到家，为了确定自己是否真的没有烦恼了，我刻意地不再禅修，虽然如此，身心也仍然一直感觉充满喜乐，但是并没有维持多久，几天后，随着这种喜乐逐渐变淡，生活中各种状况所引发的贪欲、排斥、紧张、担忧、厌烦等情绪开始滋生并且越来越明显。做了一个星期的“阿罗汉”梦的我猛然醒来，原来我又陷入了特殊体验的坑里了。

file:./imgs/13-1.png

我开始评估自己，根据长老所说，我的禅修方法并没有错，而且也经历了这么多和书中描述相符的观智，如今内心虽然还会有一些贪瞋的情绪生起，但和以前相比已经减轻了不少，按照理论，三果之后才会没有这些情绪，我想如今也许是二果了吧。

但是生活中时常因不如意而引起的不适情绪，总是像隐藏在肉中的细刺，说不定什么时候出来戳一下，而且若不控制，发现同样会演变成大烦恼，这让我非常的不满意，我禅修的初衷本就是为了去除它们，如今它们虽然已经被削弱，但我仍然觉得没有达到目标，特别是最近这么好的状态，我想，离彻底去除它们应该不远了。

就像一个即将到达终点的赛跑者，我决定开始最后的冲刺，想着也许用不了几天，最多几个月，我就能完全灭除这一切令人不快的情绪了。

file:./imgs/13-2.jpeg

之后的日子中，我几乎全天都在家里禅修，过去所培育的定力再加上日日夜夜持续不断的观察，各种超越世间的喜乐和观智体验开始层出不穷，所观察到的现象也越来越深入和清晰，禅修似乎已经进展到极致，经常在名色生灭的尽头体验到寂灭、寂静、空白、中断、永恒、无时等各种类似人们所描述的涅槃，类似禅师们所说的四禅八定的定境也时常发生。在整体禅修过程中，常常都住于犹如已经没有任何烦恼的解脱状态中，若不是因为还是在家人，我有时候甚至怀疑是不是已经是阿罗汉了。

但是，当我放下禅修，直面烦恼的时候，我发现内心仍然隐藏着令人不快的情绪，随时都可能因为各种原因而生起，但是因为每天的状态实在太好了，这些烦恼显现出来的时候相当微弱，让我总是觉得也许下一坐，也许明天，我就能完全清除它们，这一修就是大半年，就像追逐着一个永远只差一点点的猎物，我开始有些急躁了，于是不断督促自己用功，一刻也不放松。

一年后，由于过度的努力再加上突然受到了生活上一些事情的刺激，情绪波动极大，两天两夜都没有睡觉，很快便因为免疫力低下而得了带状疱疹，并迅速长满了半个腰，之后因为没有得到有效的治疗，几乎是挨到疱疹自行痊愈，并留下了几个月的后遗症，体内神经日日夜夜都在撕裂般的抽疼，皮肤奇痒无比，连衣服都穿不了。

file:./imgs/13-3.gif

在此期间我发现，无论当时有多痛多痒，只要坐下来禅修，所有的身苦便会完全消失，就如无病一般。但是禅修并不能代替睡眠，晚上睡觉的时候，失去了定力的保护，睡不了几分钟，就会被神经疼和皮肤的奇痒给折磨醒。

长久的病痛，身心已非常疲惫，晚上坐不了几分钟便会睡着，一睡着便又疼醒，几乎无法安稳地睡上完整的一小时，每天如此反复，令我烦躁不安。网上说这种后遗症有可能会持续很多年甚至一生，想到这里，内心更是充满了痛苦和绝望。

在这几个月中，所有的烦恼暴露无遗，而这几年禅修的成效也同样明显，根据这段时间的表现，我发现自己竟然能被外界的事情刺激到这种程度，说明我的烦恼并没有真正减少，而是被平时的定力所带来的喜乐所掩盖，烦恼减弱的原因也应该是被定力所压制，所以一旦失控，便打回原形。强烈的病痛下，一进入禅修状态就完全没有痛苦，这也正是说明了这一切也许都是因为定力很强的原因，而并不是真正从根本上去除了烦恼。（未完待续。。。）
