* 尘封的足迹---我的禅修经历（十四）

庆幸的是，三个月后，身体逐渐恢复，因为儿子开始在老家读小学了，我也回到了老家陪读，妻子则趁此机会去缅甸修习慈心禅。在老家每天除了接送小孩，晚上辅导一下他的功课外，几乎没有别的事情，所以再次开始了每天十多个小时的经行。\\
file:./imgs/14-0.jpeg

儿子放寒假后我回到了云南，经过了两三个月的长时间经行，定力又再进一步的提升，同时也有了更多更深的体验。但因为这些年来，这些体验已经经历了太多，并没有发现给我带来了本质上的改变，因此，我对这些已经无动于衷了，一心就只安住于观察。

没过多久，我发现，过去我能一直让自己努力观察的动力是因为听禅师们说，观察当下身心所发生的现象时，会看清身心现象无常、苦、不断坏灭的本质，看清后就会了知无我，并会对其厌离，由厌离而舍，当舍成熟，则会体证到身心现象的止息，也就是涅槃。当证得涅槃时，烦恼就会被灭除一部份，如此往复几次后，最终将会完全灭除烦恼。

file:./imgs/14-1.jpeg

所以这些年来，我一直坚持如实观察当下的身心现象，也只努力做这一件事，而在这种努力下，也确实如禅师们所说的那样，经历了层层的观智，最终抵达了身心现象的止息。而且自从禅修以来，身心也确实有了很大的改变，如果不是因为还在家生活，会经常遇到一些不如意的人或事的话，我也许真的会感觉已经解脱了。但是，虽然我已经经历了许多次完整的观智过程，生活中的各种不如意仍然时常让我明白，我并没有什么烦恼被真正根除。

我对灭除烦恼的期望仍然很强，但对观智过程已经不感兴趣了，同时对如实观察当下的这个行为也逐渐感觉是个负担，就像一个迟迟拿到不工资的工人，对手头上的工作失去了动力。

file:./imgs/14-2.jpeg

但这世上所有已知的方法也早就考量过了，除了如实观察的这一个方法外，我也找不到其它更好的办法来了解身心的真相，对于经典也是似懂非懂，更别说用经典上的教导来实修了，所以每天只好继续强迫着自己观察，常常因为这不得不观察而感觉烦躁。

直到有一天打坐时，我想，如果不观察，难道我就不知道当下正在发生什么了吗？难道就会成为一个毫无知觉的木头吗？答案非常明显，谁也不会因为不观察身心就变成木头，于是在那时我彻底放弃了所有主动的、被动的观察以及一切有行为的意志，只任由身心现象自生自灭，本来烦躁的我一下子就平静了下来，身心现象反而比以往更加清晰，而我已经不再参与其中，心稳定地住于离所有现象的状态。\\
file:./imgs/14-3.gif

一个从未有过也从未看过的了知生起：身心现象发生时，其本身就有知，根本无需画蛇添足地去观察，此知即是现象本身的功能，而所谓的观察，无非是在其后生起的另外一个现象。

我想起几年前初学禅修时偶然看到涟漪时的感悟，那时我只是留意那一小片水面上生起了什么，依照那种感觉，我不再主动观察身心，而是只注意身心这个范围里生起了哪些知。如今的定力已经与那时完全不同，当我再次运用这种方法时，身心现象本身所生起的各种知变的及时、完整、清晰，而我自己也如释重负般的轻松。

正如工人和老板，之前我不断观察身心现象，就像工人不断地做着工作，疲惫不堪却拿着微薄的工资，如今，我发现了知是身心现象自生的功能，我便不需要再做这些工作了，而只需要留意身心生起了什么知，这就像老板，只需要收购这些工人的劳动成果，这样不仅轻松，而且获利极大。

当这样熟练后，我开始运用以前在缅甸禅修时的灵感，以观察到生命最后一个现象的方式，尽量严密、不漏失地留意身心最近生起的任何知，就像一个勤快的老板，不放过收购任何一个工人所制造的产品。

当这样禅修后，我的心远离一切欲、一切有为、一切贪忧，住于无欲、无为、无畏、稳定、不动、正知。我想，这应该才是正确的道路。（未完待续。。。）
