* 尘封的足迹-我的禅修经历（二）

禅修营开始后，每天几乎都在昏沉、散乱、烦躁、腿疼以及各种妄想中度过，能真正专注于观察的时间非常少，即便有那么强的意愿来禅修，遇到这些烦恼，心里仍然一边怀疑禅修的有效性，一边打着退堂鼓，不断地想要回到外面的世界中去，每天计算着禅修营还有几天结束，烦燥的心就如同一条被刚捞上岸的鱼，不停地挣扎想要回到水中。

还好每天有长老的开示和小参时的鼓励，勉强能支撑着，如此过去了五六天，有一次打坐时，我仍然像往常一样在昏沉中醒来，然后在妄想和疼痛中来回观察，不知何时开始，妄想慢慢减少了，疼痛也不如开始那么难受，随着心越来越清明，内心对疼痛的观察也越来越清楚，此时发现，疼痛开始变成一团团热量来回游走，之后经过一系列的变化后，那令人难以忍受的疼痛，居然远离而变成了一片如同雨点打到水面上的水泡，又像是沸腾的水在不断冒泡般展示在我面前，此起彼伏，而明亮的心正在一旁看着它们，那个情景极为清澈、壮观，就像是处在一个清净无染的空间，比眼睛看到还清晰，完全不再有疼痛的苦受，身心反而变的极为轻安和宁静，如此观察了一会，我开始激动了，这景象也随之消失了。太神奇了，兴奋的我下坐后，就赶紧跑去找禅师报告这个体验，我想，如此特别的体验，说不定再观察一会儿就能看到涅槃了，想来一定会得到禅师的肯定和赞扬。\\

file:./imgs/2-0.png

出乎意料的是，禅师在听了我的汇报后，却非常严肃地告诉我，对看到的这些现象要标记看到、看到，不要去思维它。听完禅师的教导后，我心情很低落，感觉我花了这么久的时间才看到如此神奇的现象，在禅师眼里却什么也不是，我甚至还有点认为，禅师也许就没有体验过这么神奇的状态，所以听不懂我在说什么，否则怎么会一点都不惊讶呢。

之后的几天，我开始有意地寻找这些特别的体验，幻想着通过这样的体验最后能抵达传说中的涅槃，但直到禅修营结束也没有什么进展。

回家不久便是过年，长大后的年，过的总是充满烦恼，我感觉这个世间大多数人的生活都不是我想要的，生命也绝不应该像多数人那样，赚钱花钱娱乐等死，我决定在这有限的生命里，一定要找到人生真正的意义。元宵节过后，我戒了酒，因为我想时刻保持清醒的大脑，来寻找生命的真相。\\

file:./imgs/2-1.png

2个月后，我报名参加了缅甸的德加尼亚禅师在宝峰寺主办的十天禅修营，但是他们虽然同为缅甸的佛教，禅法却不相同，各方面考虑后，我便继续沿用马哈希禅法。

经历了上次的禅修营后，对禅修营的生活有点适应了，但仍然每天期待着结营，受之前特殊体验的影响，我开始不断强迫自己努力，打坐时便紧盯着腹部，经行时便紧盯着脚，期待能从中再次看到一些特殊的现象，有时候一走就两三个小时，每天都非常的疲倦，等禅修营结束后，发现虽然获得了些和书上描述似是而非的观智，但却没有什么能像上次那样留下深刻的印象。

file:./imgs/2-2.png

回家后我开始反思，第一，几年前我对禅修一点概念都没有，反而随便一坐就获得了好的体验，那时正是因为我单纯地只是想知道腹部在起伏的过程中会发生什么，上次禅修营也是一样，那也只是单纯地想知道痛到底是什么，而这次禅修营，我却是在寻找特殊的现象，这完全偏离了看清身心现象本质的初心；第二，虽然打坐和经行很用功，但是其他时间并没有做到随时保持观察，也就无法培养出深厚的定力。6月下旬缅甸的因德嘉长老要到宝峰寺举办禅修营，教导的也是马哈希禅法，于是我早早就报了名，并认真阅读了马哈希尊者及恰宓长老开示书中的关于禅修方法的部分，准备重新开始。（未完待续......）
