* 尘封的足迹-<feff>-我的禅修经历（七）

到禅修营后，我便去找了长老，因为这些天对书中的道果智的查阅发现，下坠的那次体验最接近，而且书上也没有找到类似我那次观察声音的描述，时间有限，我便只详细地报告了下坠那次的体验，并询问长老这是不是证果。\\

长老仔细听完后告诉我：你这些描述和经论是有交集的，但是不是道果智只有你自己知道。我再三询问后，长老说：你去用功吧，如果已经证得了道果智，果智则会经常出现，到时候你再来告诉我。然而，十天的禅修营结束后，我并没有体验到与之前相同的现象，不过虽然当时武汉的温度高达40度，但整个禅修营中，身心依然是非常轻安喜乐。

回家之后，这种喜乐也仍然持续着，感觉烦恼好像已经远离了，从来没有过的轻松和平静，直到半个月后的一天晚上，当时正和一位朋友聊着禅修的事，突然，内心毫无征兆的一阵空虚，所有的喜乐在那一瞬间完全消失，心如死灰，对一切都失去了动力，感觉除了证得道果获得解脱外，其它事都不重要了。

file:./imgs/7-0.png

就像一个学生突然想起他的功课还没完成一般，从第二天开始，我便放弃了所有的工作，深居简出，天没亮就起床看书，特别是《清净道论》《阿毗达摩论》几十遍地反复研究，还从各种渠道找来国内外的尊者写的禅修书籍，每一本都认真看完，并在网上把两种译本的《巴利经藏》对照着看了一遍，期间看累了就打坐经行，之后又继续看书，直至午夜，即便是有事外出，也一定会带上书本，哪怕是有几分钟的空闲时间，我都不想浪费。

这样努力了两三个月后，我对解脱的欲望越来越强了，虽然我已经完全放弃了工作，只和妻子过着简单的生活，但仍然感觉时间不够，在家的生活环境已经无法满足我对禅修的追求了，于是我决定去缅甸莫比的恰宓森林禅修中心密集禅修。我想，如果之前没有证得道果，那这次一定要证得，就算之前已经证得了，但如今自己却不能确定，所以这次一定要证得更高的道果，这样至少应该能确定是否已经是初果了。

为了保证此次密集禅修的效果，我做了充分的准备，在临去缅甸前一个月，放下了所有其它的书籍，只专注于几本马哈希尊者和恰宓尊者开示的禅修方法，将其方法的重点内容反复推敲并在家实践，之后又再次阅读，如此不断反复，直到完全掌握。

file:./imgs/7-1.jpeg

在反复的实践中我发现，也许是因为太想要结果，所以非常容易陷入掉举中而无法自拔，恰好德加尼亚禅师教导的一些作意非常适合放松，于是我总结出自己容易出现问题的地方，并将对治的方法写在其中一本书的背后，订了两个月的机票并办好禅修签证后，再次提醒自己，此次去缅甸虽然是为了道果智，但所要做的就只有如实观察身心，而不能执取体验，然后完全放空自己，放下了一切世俗，放下了所有过去所学的理论和所获得的认知，只带着这一本书和德师的一本小册子，于2016年11月，坐上了去往缅甸的飞机。

从出了家门的那一刻开始，我便将自己置身于禅修的状态，那是我第一次出国，但我并没有感觉到激动，除了从仰光机场去往禅修中心的出租车上，用手机拍了几张路边的景色外，大多数时间我都让自己保持着对当下身心现象的观察。\\
file:./imgs/7-2.png

按照缅甸禅修中心的善戒尊者提供的地点，很快便到了中心并办好手续，简单地记下了尊者告知的宿舍、禅堂、食堂的地点以及早中餐的时间后，便开始进入了完全的禅修状态中，甚至都没有心思去看一眼中心的环境。

11月的缅甸早上气温才10多度，下午却是30多度，温差极大，上午我能平静地观察身心，但到了下午就开始烦躁不安，充满了掉举，在无法忍受时，就用德师教导的一些作意来对治，让自己从早上醒来到晚上睡着，都尽量处在观察身心现象的状态中。（未完待续。。。）

file:./imgs/7-3.gif
