* 尘封的足迹---我的禅修经历（九）

为了不被特殊现象所干扰，我仍然尽量保持不去分析思考，而只是不断地观察并加以适当标记，直到第三天早上，一切仍然如此，此时，再也无法说服自己保持观察了，能持续这么久我想一定是证得道果了，开始兴奋了起来，早餐后，我将这些告诉了禅师，并问禅师这应该是证的道果了吧。\\

禅师听完之后告诉我这不是道果，然而我并不相信，我当时很肯定禅师一定是没有经历过这样特殊的体验，心想，这连续几天几夜都不会退失的状态，除了经历了道果外，还会有什么东西有这么强的力量呢？于是再次向禅师解释，禅师看我如此坚持后，很严厉地再次否定了我，并在我还要继续解释的时候，将我赶了出来。

file:./imgs/9-0.png

曾经我一直认为特殊的体验只会短暂地出现在禅修中，不会像这样持续几天几夜的，但面对禅师如此坚决的态度，我的信心有点动摇了，来到中心的书架上，我找到了《清净道论》，仔细地阅读了上面关于道非道智见清净的描述，开始相信禅师说的是真的了。

在经历了这起起落落，连这么努力得来的极致体验都不是道果，那一瞬间，我对禅修几乎绝望了，虽然身心清澈的感觉依然还在，但我却对这感觉产生了厌恶，认为是它们害我沉沦于此，这些天来，从接近死亡般的痛苦到极度的快乐，再从希望跌落到绝望，感觉已经没有什么动力能支撑我继续禅修下去了，完全失去了方向。

file:./imgs/9-1.png
在惯性的作用下，每天仍然像个陀螺般不停地打坐经行，但很快我便发现，我已经不适合再禅修了，因为我所观察到的一切都在消失，当我经行时，观察脚步，脚却消失了，感觉下半身完全是空的，若不低头看看，甚至都察觉不到自己有脚。打坐时，观察坐姿，整个身体便消失了，观察腹部，腹部也消失了，所有要观察的身心现象，看到的都只有消失。

这种消失并不是说看不到它们，而是当内心看到时，它们便瞬间消失了，就像看着泼到沙漠上的水，当下瞬间消失，内心开始莫名的恐惧，不敢再观察了，害怕稍专注一点就连生命都完全消失了。

不再对当下身心现象观察后，内心开始涌现出大量的思维，特别是过去这些天所体验到的现象，很契合北传佛教中的一些理论，这让我陷入了庞大的生命和世间理论的逻辑思维中，这些思维很快便让我感到非常的累，于是只好强迫自己继续观察，如此不断疲惫地挣扎于观察和思维之间，渐渐形成了更为沉重的负担，压的我透不过气，但又无法摆脱。

file:./imgs/9-2.png

一专注观察便只见无处立足的、令人可怕的消失，一停下来便淹没于无穷无尽的、令人窒息的思维中，最后，对这两者的厌恶都到达了顶点，在我的心中开始生起了一个强烈的念头：我要离开禅修中心，去哪都行，我要离开。然而在异国他乡，唯一想到的地方只有回家。

这个念头越来越强大，最后完全占据了我的内心，我试着修慈心禅，很快便进入了完全的空无，长久地住于没有意识的状态，但当从这样的状态中出来后，离开的念头便又像洪水般汹涌而至，无论如何观察和标记，所有的念头都带着强烈想要离开的欲望，再也控制不住了，我决定离开。

file:./imgs/9-3.png

来到小参室，向禅师说明了情况后，禅师告诉我说：禅修需要趁热打铁，但如果你执意离开的话，那就先回家休息一下吧。在得到禅师的允许后，我走出了小参室，就在跨出房门的那一刻，犹如炎夏时一桶清水从头浇下，又像是突然卸下了千斤重担，所有的痛苦和挣扎在那一瞬间烟消云散，放弃了禅修，心情变的无比的轻松自在，那些让人窒息的庞大的理论思维也不再生起了，身心宛如新生一般的干净。

我联系了妻子，让她帮我订了后天的机票，第二天一早收拾好了行李，和同修打了招呼后，我觉得已经没有什么事情可做了，也许以后再也不会回来了，于是准备好好地享受一下这最后一天的禅修时光。

我来到禅堂，开始毫无负担地轻松打坐，清澈的感觉依然还在，观察哪里，哪里也依然瞬间消失，但经过了这段时间的大喜大悲、希望绝望，我已经什么都不在意了，消失就随它们消失吧，即便是生命消失了我也不在意了。

很快，身体的感觉在观察中完全消失了，只有意识，当观察这意识，意识也同样消失了，一切就只剩下腹部时有时无的起伏，当我观察这起伏，起伏的现象和观察它的欲也在成双成对地不断消失，此时我发现，当有欲生，起伏的现象便生起一点，然后陆续消失，重新有欲生时，现象又生起一点，然后又陆续消失，这欲是导致现象生起之因，是作为者，是沉重的负担，劳累却白忙活，毫无价值，正如即将枯灭的油灯，用手挑一下灯芯便亮一下，接着又逐渐灭去，欲就像那挑灯芯的行为；正如用漏网捞水，水便从漏网上流走了，欲就像那捞水的行为；正如立不起的猪大肠，手一放便倒，欲就像那立起猪肠之行为。这样见到后，一丁点的欲都不想再生起了。“就任由它们消失吧”，就在内心决意的那一瞬间，欲和起伏现象犹如两只相续掉进陷阱的兔子，消失在了深邃的寂灭中，再也没有现象生起......。

file:./imgs/9-4.gif

不久之后，念头生起，我忆起刚刚那两个现象的相续消失以及后面没有任何现象的寂灭后，又再次沉入寂灭中，不知何时，我从平静中恢复，然后继续经行，再次打坐时，这个相继消失的现象又短暂地再次出现了几次，但我并没有在意，一直都处在平静中。

第二天早餐后，我行走在禅修中心的树林中，想拍几张照片留做纪念，身心依然平静而又安乐，就连蚊子咬我，内心也完全没有任何波动，随手也给它拍了一张。中午，和禅师以及中心的住持告别后，走出了禅修中心，回头看去，在这只住了半个多月，却犹如过了好几年，曾经被我视为牢笼般的禅修中心，如今看来却像天堂般的静谧，我满意地离开了。（未完待续。。。）

