* 尘封的足迹-<feff>-我的禅修经历（十）

回国后，身心仍然一直持续着之前的平静和安乐，我开始总结这次禅修的收获，并参阅马哈希尊者及其它禅师们所描述的十六观智，发现这次所经历的体验竟和书中所提到的各种观智进程几乎完全相同，特别是最后几天的体验和书中最后的一些观智极其吻合，我有点觉得最后那天的体验应该就是书中所描述的涅槃。\\
file:./imgs/10-0.png

但是几天后，无意中对妻子发了一下火，虽然只是短暂的一瞬，但把沉浸在喜乐中的我给震醒了：无论之前获得了体验多么殊胜，身心多么的平静，但我的贪瞋痴还是一个也没少，这和我的初心相违，我禅修的目的不就是为了灭除烦恼吗？若没有达到目的，即便是涅槃那又如何呢？更何况虽然体验和书上描述相似，仍不免有误，有这样的疑惑，可见我自己仍然无法绝对性地确定是否证得道果，我的目标还没有完成。

回国不到一个星期便呆不住了，因为之前买了两个月的往返机票，距离那张返程机票还有一个多月，我决定再次去缅甸禅修，于是去领事馆办了签证，订了一个星期后的机票，再次坐上了去往缅甸的飞机。

file:./imgs/10-1.png

有了之前的经历，这次禅修不会像上次那样痛苦了，反而感觉有些太轻安，为了不陷入放逸，我不断督促自己提高精进，想起焦谛卡禅师说过，他希望在临死时，最后的一念是正念，这给了我灵感，既然我现在身心如此轻安，我何不将精进提高到极限呢？若能将每一个当下都作为生命最后一瞬间来观察，那应该便是最极限的精进了。

于是我作意：如果生命就此结束，我希望能观察到生命的最后一个现象，生命是脆弱的，随时都可能结束，谁也无法预知，任何一个现象都有可能是生命的最后，所以若要保证不错过生命的最后一个现象，我只能把每一个现象都当成生命中最后的一个现象来观察。即便生命还在延续，总有一天也会结束，若我现在训练好了，无论生命何时走到尽头，我都能以完全了知之心结束最后的生命了。

file:./imgs/10-2.png

这样作意后，我便常常以这样的方式来严密观察，争取对每一个现象都不放过，有时候会因为失念而忘失了观察，也会很快便会发现，并警醒自己：若前面生命就此结束了，我便是以无知的心死亡了。在这样不断的训练之下，观察变的越来越紧密，也越来越熟练。

持续几天后，失察的次数也越来越少，即便是早课，也仍然如此观察，有一次，在早课诵戒时，不断交替观察着所听到的其它人念诵声和自己念诵的行为，突然间一切静止，包括时间，我好像完全从世间抽离，所有现象都变成了背景，突出的只有纯净、独立、静止的知，一会儿后恢复了正常。

file:./imgs/10-3.gif

有一天打坐时，我仍然以这种紧密的方式观察着身心现象，发现念头的变化速度极快，完全跟不上，总是错过。进一步发现，过去以为已经看到最当下的现象了，实际上仍然是属于过去的，原来还有许多念头是更当下发生的，于是我放弃了所有其它的观察，全力紧密地观察念头的变化，但仍然无法跟上，此时发现，观察是个障碍，是多余的，这个观察心总是间隔着念头，因为有这个的存在，所以无法跟上念头的速度。

于是我放弃了观察，就只是紧随念头，当没有这多余的观察行为的干扰，就只有念头生起时自动的知了。这样的状态下，每个瞬间生灭的念头开始完整地了知，它们已经不再是变化的，而是一个个单独生起消失的意识，意识生灭的速度开始越来越快，像冲刺一般，瞬间到达了极限，突然戛然而止。如同火箭加速突然冲出了地球的引力，在那瞬间，我感受到了彻底的自由，就像半年前在国内的那次禅修营中所体验到的一样，我再次看到了两个对象。

“我呢？”一个念头同时生起，而答案却非常明显，只有那两个对象，没有“我”。如同上次一般，瞬间过后，一切又如电影倒放般倒退并恢复了正常，我思维了片刻：的确，所谓的“我”，当下不过就只是这两对象而已，半年前我看到了“听识”的由两现象生成，如今我看到的是“意识”也是由两现象生成。再次看清了“我”的本质，身心也再次有种彻底的轻松感。（未完待续。。。）
