* 尘封的足迹-<feff>-我的禅修经历（十六）

思维了5天后，我再次开始禅修，此时的定力及内心的清净度似乎已经翻了一倍，对身心现象的了知也更为清晰。我发现，原来无数个识被当下的思所取，集合成一个概念或内容，就比如人们将小时候所有的识，在当下思维成“那是小时候的我”，将昨天所有的识，在当下思维成“那是昨天的我”，将正在发生的见闻觉知的识，思维成“这是现在的我”，这便是“识的集合”。

file:./imgs/16-0.jpeg

而这些思维都是因为不知道什么是识；不知道识是由因缘条件所生；不知道识生起之前不曾存在，生起后便消失，消失后便不复存在；不知道识因生起的因缘条件的性质不同而有苦乐的特性；不知道识的危险性、不确定性、前导性、无法掌控性；不知道如何离识；不知道识如何不再生，而把这些识以无明之思，集合成各种概念和内容，并将之视为我、我的。

就像把电影屏幕上所发出的无数个不断生灭的各种颜色光点，以及音响里发出的每次震动，以思维集合成某某故事，并认为是我在看在听。把7D电影的所有感官的触识，以思维集合成身临其境的感觉，并认为是我在体验。试想，若有一种电影不仅能提供看、听、闻、尝、触，还能直触意识的话，谁还能区分出这是电影还是现实呢？而无论是眼耳鼻舌身识还是意识，这一切所反应的概念内容仍然是由无数个生已即灭的识集合而成，世间的一切概念都是如此产生。

当对所有的识及识的各种特性如实了知后，我进一步发现，凡所有的思取都是发生在现象生起后的，思取的概念内容看起来像正在发生，实际上都是忆念过去已经发生的、消失了的识，并集合成概念，概念本身并没有宣称那是我、我的，是其后的无明思，把概念视为我、我的，再其后的思又忆念前思的集合并取为我、我的，认为这前思集是我、是我的思、我在思、我所思，如此不断增长和延续。\\
file:./imgs/16-1.jpeg

而事实上，凡所有的集合现象都是已经灭去的现象，或者说，凡所有集法都是已灭法。是因为忆念，而有看似现象的再现和恒常，但因为过去我对这一切的无知，而颠倒地认为，先有能取之心，后有被取的现象生起，先有能观察之心，后有被观察的现象生起，所以才有了以主动或被动地观察身心现象的方式来了解身心，以这种错误的方式便无法真正完全了知到身心真相。

当知道现象是因缘和合而生起的，其本身就有识的属性，此识便也同样是缘生的了，如此了知后，识生起时便不会认为识是我、我拥有识、识在我中，我在识中等错误的邪见，也不会认为会有一识能识知另一识，而只会就现象本身的识了知现象本身。

file:./imgs/16-2.jpeg

也就是，就身本身观身，就心本身观心。而不是另起一观察心来观察前心，当后心生起时，前心便已经消失了，又如何能真正观察到呢？也许正是因为这样，所以之前在缅甸，当我观察到极致时，看到的都只是现象的消失，就像是只能看到现象离去的背影，而无法正知现象本身，我想，这种就现象自身了知现象也许就是正知吧。

于是，当定力弱时，我便以粗现象的识了知粗现象本身，比如走时，便正知走，当定力强时，我便以细现象的识了知细现象本身，比如听识刚生时，其时就有正知。

当对所正知的现象有思有想时，我便了知，这是对已经消失了的现象的忆念，于正知而起的忆念就不会认为这是我、我的、我所的，也就不会有对忆念内容的贪和瞋，这种忆念我觉得应该就是正念。

file:./imgs/16-3.gif

如此，我常常住于正知、正念、真实、无痴、不颠倒、无贪瞋烦恼的清净中，我想这可能才是世尊所说的离欲、离不善法的正定。（未完待续。。。）
