* 尘封的足迹-<feff>-我的禅修经历（八）

禅修中心是建在森林中的，经常有蛇从路上爬过，特别在禅堂大门和厕所之间，有一片一尺高的杂草，每次上厕所时都要从草丛上跨过，虽然那里并没有见过蛇，但每次经过那片杂草都会担忧和紧张，于是更加提高警惕地观察内心。

有一次，我清晰地看到了脑海中出现的是一条蛇扑来咬我的景象，恐惧同时生起，接着，景象消失，恐惧也随之消失了。内心瞬间变的轻松，紧张感也完全消失而显的更加的平静。原来是因为有这样的想，而有这样的恐惧，没有这样的想，便没有这样的恐惧。明白了以后，对蛇的害怕从那刻开始就淡化了，有几次经行时，蛇从我面前爬过，我也只是平静地看着它。

file:./imgs/8-0.png

马哈希禅法很重视吃饭时的观察，所以吃饭时，我也着重严密地观察想吃、想夹菜、想伸手、伸手...想张嘴、张嘴、想咬、想吞等等，很快便发现，吃一口饭原来需要这么多密密麻麻的动机和行为，而食物进嘴后，触及舌尖的乐味却只有一瞬间便消失了，特别在吞咽后，观察到食物从喉咙到胃的感觉，更是毫无乐味，肚子的饥饿就像生病，充满了苦受，吃饭就如吃药，当饥饿感消失后，我一口都不想再吃了。当对食物没有了兴趣之后，为了定力不中断，我连下午的糖水也不再去食堂喝了。

小参的时候经常会听别人说他们禅修时有多么的快乐，而我却觉得自己越禅修就越痛苦，感觉所有的一切就像牢笼般困住了我，充满了苦，越来越想要挣脱这一切，甚至连禅修也不想要。有时候会想，自己为什么放着家里的好日子不过，却来这里折磨自己，世上有那么多人都不禅修，还不是过的好好的。但这些情绪也只能被不断地观察和标记“情绪”“痛苦”等，心想再难也得撑过这两个月。

随着所观察到的现象越来越深入和清晰，心情也越来越烦躁，大约到了第8天，我便已经受不了了，对观察到的现象甚至包括禅修这项工作的本身，都感到难以忍受，感觉再禅修下去就要死了，情绪几乎接近崩溃，根本无法安住于禅修，经行的时候想打坐，打坐的时候想经行，像个热锅上的蚂蚁，狂躁不安。下午经行的时候，看着动机和脚步的移动不断地重复，就像看着一台不断来回往返的机器，毫无乐趣可言，枯燥、厌烦、压抑，无处释放，于是我决定回宿舍冲个冷水澡平静一下。

file:./imgs/8-1.png

洗完澡后，身心得到了放松，我便直接在床上盘腿坐了下来，轻松地观察着腹部，也不去强求看清楚什么，就只是轻轻地把注意力安放在上面，很快身心便开始轻安，慢慢地平静，直到似乎安止到完全没有了意识......

不知过了多久，突然，一个短促的空白如同闪电般划过，身心瞬间清净到了极点，并很快沸腾了起来，此时身体好像完全溶解，如同无数个不断高频震动的粒子组合而成，毛细血管的微弱跳动也变的极其清晰。我一时不知发生了什么，观察了一段时间后仍然持续在这种状态中，以至于无法观察到任何其它的现象。

file:./imgs/8-2.png

于是我睁开了眼睛，想要经行，就在我下地的那一刻，我感觉体重似乎减轻了至少一半，走路轻飘飘的，难以适应。身体的溶解感虽然没有了，但却觉得全身通透，没有一处不是轻安的。当我走出宿舍时，外面的景色明显比以前清澈了不少，像是进入了水晶般干净的世界中，极为的舒适，一切声音也变的清脆悦耳，因为对特殊体验的警觉，我仍然不断地观察并标记这些现象，而克制自己不去思维它们。

这样的状态一直持续到了晚上，我发现根本没有困意，平时都是9点左右一上床便睡着了，而如今在床上已经躺到半夜，也仍然如刚睡醒一般精神饱满，只好继续不断观察身体和床的触感以及腹部的起伏等现象，慢慢地进入到似乎身体已经睡去而精神仍然清醒的状态，一切显的非常寂静，感官也变的非常敏锐，以至于偶尔听到的声音都如打雷般的响。（未完待续。。。）

file:./imgs/8-3.gif
