#+OPTIONS: toc:2 ^:nil
* 首次葛印卡四念住禅修心得 (1)    [2012-09-15]-<feff>-[2016-03-14]
  :PROPERTIES:
  :CUSTOM_ID: 首次葛印卡四念住禅修心得-1
  :CLASS: entry-title
  :END:

今年去了七天的四念住禅修，一次把前三次十日课程的疑问全都补足了，可谓是收获满满！

在此简要的记录一下在法的道路上拾得的小小心得：

** 亲见无常
    :PROPERTIES:
    :CUSTOM_ID: 亲见无常
    :END:
最近一次参加葛印卡老师的四念住禅修时，不断的扫描身体，由上到下，由下到上，但这次己经不再有全身消融的感受了，只觉得各种感受很快生起，又很快灭去，像泡泡一样。

这些泡泡生灭的速度越来越快，最後这样的感受竟然连了起来，如电、如泡、如聚沫，让身体好像一团被烧著的火球一样，不断的受无常的逼▫迫，好苦好苦...

想著以前如果遇到幻觉，睁开眼幻觉就会不见了，於是睁眼。

喔不！睁眼和闭眼的感觉都一样耶？无常像火一样，继续燃烧、燃烧！

问了助理老师，老师竟然说，「很好很好，保持平等心，继续保持觉知无常。」不解。

接下来，那苦实在变本加厉了起来...实在太苦了！连呼吸都像火烧一样鞭打著我的全身，简直无処可躲。然而别人看到的我并没有什么变化。只有我的感受变化了。

有点害怕，便不再观生灭，只观呼吸。很快的，泡泡、电火、燃烧都不见了，我的呼吸又带给了我平静和快乐。

再问助理老师，老师说：「要小心，你是不是对呼吸的感受产生贪爱了？」我说「是。」老师：「记住保持平等心。修行唯一的衡量标准就只是『觉知』和『平等心』。」

直到看到葛印卡的老师，乌巴庆老师的禅修方法介绍，方才觉得「知我者老师也」！老师讲的就是我遇到的。幸好我的修行是走著前人走过的道路啊！

#+begin_quote
  ...当一个人培养出来的涅盘元素，冲击自身内在的杂念和毒素时，会产生某些剧变，必须要能忍受。这剧变会增强身内原子幅射、摩擦、振动等的灵敏度。
#+end_quote

[[http://static.rhinoera.com/wp-content/uploads/2012/09/1393917][Jack
Kornfield]]在这里提到：

#+begin_quote
  ...这强度增长得非常之多，以致於人会感觉到，好像他的身体就像电和苦团。

  -<feff>-
  [[http://static.rhinoera.com/wp-content/uploads/2012/09/1393917][《当代南传佛教大师》]]，Jack Kornfield，P. 379，「乌巴庆」章。
#+end_quote

无常是这麽的可怕、无情！怪不得我们平常光是想到「无常」就摇头，而沉迷在声色犬马之中，让无明麻痹我们的神经。然而这就是世间的真▫相，我们想逃到哪里去呢？唯有修行四念住才能到达我们真正的避风港啊！

** 对消融的执取
    :PROPERTIES:
    :CUSTOM_ID: 对消融的执取
    :END:
「消融」这种重要的里程碑也会成为修行上的障碍。

我曾经在第三次十日禅修时经验到全身消融。那真是很震撼的经验！全身都像是透明一样，然而心中却没有一丝一毫的激动，非常的平静，只是去觉知透明如水晶的全身。那觉知可以微细到，从心中的一点扩散到每一个细胞，像水滴一样的毫不费力地渗透全身。

然而四念住开示时，在入出息念章的最后，葛印卡老师提到，觉知全身的感受止息后，会有「全身消融」的感受。然而我在那次全身消融的经验，就再也没有经验过了。虽然葛印卡老师说明：「不要执着在这种微细振动的感受上。全身消融之后，粗重的感觉会再度出现，要保持平等心，只是觉知。粗重的感受和微细的感受一样，都只是感受，没有差别。」

但是如果每次入出息都会全身消融，而我没有经验到的话，是不是我修错方向了呢？

于是我去找助理老师小参。老师说：「不要去强求全身的消融。让它自然的发生。」

我问：「老师，消融只会发生一次吗？」

老师说：「不会，当你的心完全的平等时，全身自然会消融，但是你不要去贪爱这种感受，让它自然的发生吧。」

老师突然脸色一变，严厉的说：「现在你对『消融』产生了很大的贪爱和执着。不要再讨论它了，等到你的心平静下来再说！继续觉知感受吧！」

我发现，我的心跳的确加快了很多，我心中非常渴求再次经验到全身消融的感受。

啊！这就是贪爱，这就是执取啊！

** 亲见心
    :PROPERTIES:
    :CUSTOM_ID: 亲见心
    :END:
有天晚上，扫描全身的感受的速度自行加快了，本来只是一呼一吸间扫描一遍，慢慢变成二遍、三遍...最後越来越快，快到整个连了起来。睁大眼睛继续觉知，这感受并没有不见，可见这是如实知，不是幻觉，於是闭眼继续观察。

连起来的东西带给我的感受是一个圆圆的，像池塘一样的东西。而我就好像池里的鱼，如果我的心念动起来，池子里的水就会开口，漏出来，洒到我的身体各処，产生种种可辨识的粗重感受－诸如腿痛、背痛、眼睛痛、头痛等。

这些痛起初都源自於一点点小小的感受，如果我的心念持续在池子中不随著感受跑走，那麽那些小小的感受就会像泡沫一样，生起一下就灭去了；然而，如果我的心念跟著感受跑了，那麽池子就会开始一滴、两滴、三滴...的开始漏水，小小的感受就会受到滋润，开始累积、变大，最後长成一条很痛很痛的筋，痛死我也。

很妙的是，如果我只是观察那条大大的痛觉，而不起讨厌的念头，我的心念就会回到中心，痛死人的筋开始缩小，心中那个漏水的开囗也会开始变小，最後变成两滴、一滴...然後关起来；同时那个痛死人的感受也完全不见了。

#+begin_quote
  ...在无常知觉持续时，行者会瞭解，专注和正念的力量，而除去身体内能量流动的障碍。这种专注会变得更快、更清楚，当身体清楚感觉到能量流动，所有知觉的无常（苦和无我）感更明显时，行者的注意力会移到中心（心）。

  -<feff>-[[http://static.rhinoera.com/wp-content/uploads/2012/09/1393917][《当代南传佛教大师》]]，Jack
  Kornfield，P. 399，「乌巴庆」章。
#+end_quote

姑且就把这个觉知当做是觉知「心」了吧！

** 亲见五盖－贪、嗔
    :PROPERTIES:
    :CUSTOM_ID: 亲见五盖贪嗔
    :END:
能见着心之后，五盖也就很清楚了。虽然经上写的十六种心还没能一个一个遍历，但是五盖是随时都现前的，不想见都不行啊！既然都见着了，就照着经上写的观察看看吧！

心有贪、嗔等五盖时，心中那平静的水池会漏水，漏得大了，身上的感受就会长大，变成一大团难以忍受的东西。例如坐禅时，大家的腿都会痛，可是如果能保持觉知、彻知无常的话，那个痛不会长大，顶多就是像个小泡泡一样，刺你一下又不见了，再刺你一下又不见了，始终像泡泡一样；最后泡泡也不见了，只剩遍布全身的、很微细的波动。

见着心之后，就可以找到五盖漏出去的地方了。

一开始观察时，那漏的地方实在太多，很难分辨清楚。记得第二次十日禅修时，还数了数，身上有漏的地方一共有30处左右，主要都在关节等地方。

然而对五盖来说，要找到哪个盖往哪里漏，却是异常的简单。因为五盖可以一个一个关起来，关了哪个，就找哪里止漏，那就是盖在心上的位置。难的是你怎么知道现在是在观察哪个盖的现象。

嗔盖最容易观，因为腿痛非常明显，讨厌腿痛的心念，那就是嗔。所以腿痛消失了，表示嗔盖灭去了，这时候去找哪个地方止漏了，那就是嗔盖在心上的位置。

目前就我的观察，嗔盖是在心的下半部左边五分之二的地方。

贪盖却是挺细微的，因为有时候你会不知道自己有没有在贪爱某个境界，还以为自己很超然呢！几经观察后，我发现，贪盖出现时会有好像多重心跳一样的感觉，还以为自己心悸呢！其实是从心里漏出去的波动产生的振动，你的觉知力变强了，可以感觉到了，和心脏的跳动感有时候会重合在一起。

而贪盖止息的时候，那股像心跳一样的振动也会停止，有些法友在禅修的时候会发现，心中不再执着什么事情的时候会感觉好像心脏被撞了一下，像心悸的感觉；我个人认为很有可能是因为贪盖暂时止息的关系。不是很好受，但是这是好现象喔！因为无常撞到了你的心。

贪盖止息的时候，我特意去找心上哪里止漏了，发现似乎是在心的下半部左边数来五分之一的地方。

\\

* 首次葛印卡四念住禅修心得 (2)    [2012-09-15]-<feff>-[2014-12-02]
  :PROPERTIES:
  :CUSTOM_ID: 首次葛印卡四念住禅修心得-2
  :CLASS: entry-title
  :END:

** 亲见五盖
    :PROPERTIES:
    :CUSTOM_ID: 亲见五盖
    :END:
睡眠是我第一次接触内观就面临的大敌。

还记得第一次内观时是夏天，禅堂非常热，不停流汗，流着汗很累，眼睛也会渐渐觉得沉重，最后就歪着头睡着了。

晚上开示时更是睡得厉害，中文开示的配音员声音虽然不像葛印卡老师那样低沉，但也是很稳重的类型，没听两句就睡着了，直到开示结束，大家齐声说「Saddu,
Saddu（太好了，太好了）」时才会醒来。

第二次、第三次十日禅修睡着的时间越来越少。如果真的是因为身体太累的话，早上我就会先睡到六点，避免睡眠时间太少，下午昏沉无力。但是还是没什么用，要睡时挡也挡不住。

第二次禅修时，我询问助理老师，他说：「你观察到昏沉了，很好。观察到就表示有一天你能够克服它。瑜珈行者修行时甚至是不睡觉的喔～～」让我暂时振奋了精神。

但这次四念住禅修前，我的生活非常不正常，几乎已经是熬夜晚睡，隔天又早起的生活了。想当然尔，身体一定是累坏了。因此修入出息念的前三天，我只要呼吸到全身的感受都变微细了，就会睡着。

助理老师针对我随时都会睡着这件事也给了一些指示，包括早上晚点起来，吃完饭小睡一下，早晚喝加盐柠檬水净化身心等。

第四天开始，传授内观后（注意力从觉知呼吸转为觉知全身感受），我觉得我准备好了，决定和睡眠对抗到底。

照着大念住经指示的顺序，我觉知呼吸，觉知长呼吸、觉知短呼吸、觉知鼻下唇上三角区域的感受...

觉知全身有感受，觉知全身的感受变得微细...

然后从头顶开始，一部份一部份扫描全身的感受...

最后一呼一吸间从上扫描到下，再从下扫描到上。

全身都变得很平静...很安详...只有微细的感受...

既不觉得迷恋，也不排斥...

快来了，昏沉就是在这种时候随时会出现的。

我提高警觉。

然而，不知不觉的，我的头部在中心点小小的抖了一下...

只抖这么一小下，就睡去了！

醒来时可能已经过了五分钟了吧，感觉没有很久。但是觉得很讨厌这样无力的自己。

然而，立刻想起葛印卡老师的开示：

#+begin_quote
  知道自己失败了，也没关系，不要产生厌恶的感受，继续保持觉知、保持平等心。
#+end_quote

好吧。把睡着当做没事一样，不需要责备自己，只是更加精进。

不知道经过几次的睡着后，继续保持平等心。终于有一次，我开始清醒的看到我是如何入睡的。

首先是先感受到平静的心，像水池一样无波的心。

然后突然间，心的下半部，最中间的地方漏了一滴水滴，往上掉到了头顶，眼睛跟着抖了一下。

漏到第二、三滴的时候，眼睛和头的中心点跟着振动了两下，这个振动一下就把我的意识卷进去，瞬间就睡着了。

根本来不及反应啊！

** 醒见昏沉
    :PROPERTIES:
    :CUSTOM_ID: 醒见昏沉
    :END:
再经过不知几次的战斗，睡了又醒，醒了又睡，我终于看到了那一下振动之后，我是如何睡着的。

先说明一下，注意力就像是电影的画面。

大家都知道电影是怎么动的吧？其实就是每秒给你看24格的画面闪过，你的心里就自动会把这些画面连起来，电影就栩栩如生的活了起来，动了起来。

当你一心一意专注于感受的时候，五盖是动不了你的。因为你那24格的「画面」全部都牢牢定在身体的感受上面。

昏沉非常厉害的地方是，它会复制你的「画面」。例如你的24格都是感受，它就复制一份，插到你的注意力里的一格。

那一格非常非常像，几乎是完全一样。你是在注意感受，它就给你感受。你是在注意心，它就给你心的样子。要非常小心才能分辨，那只是心里漏出来的振动造作出来的。

如果你的注意力被那一格牵动了，昏沉就会给你第二格。也是很像，但是和实际上的感受一定不一样。是造作出来的，假的！

如果第二格也带得走你，接下来就没有什么能停止昏沉了，你就会开始进入昏沉造出来的梦中，甚至你还能「以为」你在觉知感受、觉知呼吸，但一切都已经与实相背道而驰了。

然后就是各种想、受、行的生起，你的眼睛在梦中看见了东西，遇见了人，听到了声音、讲起了话...产生了各种感受，在你的梦中栩栩如生的演起电影来。因为正念已经不见了，所以只好等到电影演完。这一演可能就是五分钟、十分钟...有时搞不好到下坐了才醒来。

再经过不知道几次的昏沉攻击后，我决定在入梦的时候和昏沉对抗。

这一次我告诉自己，进入梦中后要再回到身上的感受，要睁开眼确认自己在禅堂里。

没想到这正是恶梦的开始。

觉知呼吸，觉知感受，觉知心...

一格假的「画面」冒了出来。挡不住，第二格又来，卷进去了。

...过了不知多少画面...

「快醒来！觉知呼吸！觉知感受！」

我成功的在梦中醒来了！赶快睁开眼睛。很好！我还在禅堂，还在禅坐。

再来吧！

又一格假的「画面」出来，我半睁着眼睛想要确认哪个画面是梦，然而，昏沉精明得可怕，第二格「画面」给我的就是我睁眼看到的，禅堂里的画面！

接下来，昏沉模拟着我的呼吸、我的感受、我看到的禅堂地板、白色的盖脚巾。我的24格「画面」里面，很快就有一半12格是模拟出来的。

就这样，我半睡半醒的和昏沉拉锯着。

渐渐的，我的眼睛闭了起来。然而我不知道，因为昏沉用模拟出来的禅堂和感受占据了我所有的「画面」。

接着画面越变越快，终于换成了梦境。我的心里又演起了电影。我又当起了导演。

「不行！醒来！」

我奋力睁开眼睛，24格模拟的「画面」终于有个5格是实际的禅堂。

真实的「画面」...7格...10格...20格...

「太好了，安心了。」

一放松，昏沉又趁势而起，

模拟的「画面」...3格、5格，成长到10格、20格，占据了我的注意力。

我整个心里好像在做着像电影「Inception」一样的梦。

到底哪个是梦？哪个是真的？

** 陷阱
    :PROPERTIES:
    :CUSTOM_ID: 陷阱
    :END:
我不断的和昏沉拉锯，数了数，我至少赢了有十六、七次的战役，真可谓是惊心动魂。因为每次醒来，都不知道这是梦？还是现实？是还在梦里？还是在梦里醒来？

幸好，助理老师在这时进度检查了。

助理老师：「坐的情况如何啊？」

我说：「老师，我和昏沉战斗了十几次，我赢了，但是现在我都不知道是在做梦还是在现实了。」

老师笑着说：「其实你只是自己在跟自己作战而已。如果你在梦中，你怎么会呼吸，怎么会坐在这里跟我讲话呢？」

我说：「老师，我梦中也能呼吸，也能感受呢！我都分不清楚我现在是不是在做梦了，我很害怕，怎么办？」

老师脸色一变，摇摇头说：「你不要掉进自己的陷阱里去了。这就是疑法、这就是掉举！知道吗！要注意。五盖随时都会出现，要回到觉知呼吸、觉知感受，知道吗？」

我问：「老师！我现在理智上不害怕了，可是我现在身体还会抖，好像身体很害怕的样子，我要专门观察身体上害怕的振动感受吗？」

老师说：「不用，你先专注呼吸，注意鼻子下方的感受就好。」

还好有老师的指导，我很快就恢复了平静。

然后我藉着这次机会，抓紧观察感受平静来下和心里止漏的地方，直接找到了疑和掉举在心的位置。

原来我们平常觉得做工作没把握的时候，那种惴惴不安、害怕、身体发抖的感觉，也是从心里漏出来的啊！

疑是在心的下半部的最右边。由左开始数五分之五的地方。

掉举在疑的旁边。是在心下半部的由左开始数五分之四的地方。

\\

* 首次葛印卡四念住禅修心得 (3)    [2012-09-15]-<feff>-[2014-12-02]
  :PROPERTIES:
  :CUSTOM_ID: 首次葛印卡四念住禅修心得-3
  :CLASS: entry-title
  :END:

** 聚集和止息
    :PROPERTIES:
    :CUSTOM_ID: 聚集和止息
    :END:
总结我所观察到的五盖特性，都是在心中某个位置开始产生「漏」，然后这些「水滴」被吸到身体上的各个部位，聚集之后产生各种感受。若能保持平等心，只是觉知和观察心和五盖，那么这些「漏」的开口就会慢慢的变小，感受也会渐渐的变弱，直到最后「漏」像水龙头关起来一样时，感受也会跟着完全的消失。

很巧的是，五盖都是在心的下半部，分别占据由左到右的五个位置，顺序是「贪、嗔、昏沉／睡眠、掉举／后悔、疑」。

其实除了五盖会在心中产生「漏」之外，我在有「我」或是「我慢」这种感觉的时候，也在心中感觉到有地方会「漏」。但是和五盖不同的是，五盖几乎都在心的下半部开始产生「漏」，「我」和「我慢」则是心的上半部会产生「漏」，但由于经上没有明确提到「我慢」，所以我就不管心的上半部了。至于有明确的提到「五盖」们，我很有实验精神的去一个一个观察它们，并且去确定它们在心中生起和灭去的位置。「我慢」也许要到下一个阶段才会去观它吧！那就不是这次修行要做的事了。

** 疑的止息
    :PROPERTIES:
    :CUSTOM_ID: 疑的止息
    :END:
我很好奇的是，如果「疑惑」只是心中的一种化学反应产生的感受，那么，没有这种「疑惑感」时的思考，岂不是就是「不再疑惑的思考」了吗？换言之，就是「解答」？！

于是针对我与昏沉的战争，我对我最害怕的那件事提出了疑问：

「人生只是一场梦吗？」

仔细观察现在的心。没有疑。没有掉举。没有昏沉，也没有贪、嗔。

五盖现在没有生起。

很好。那就回答我吧！

果然，我完全没有疑惑的得到了清楚的答▫案。写成文字大概是这样：

#+begin_quote
  「没错。人生就是一场梦。你的人生就是一场每秒24格的电影。你要做哪种版本的梦，就看你在随机插入的画面里选了哪一格，每个选择都会长成一齣每秒24格的电影。

  就像你在和昏沉战斗的时候一样。

  选择是无穷无尽的。你的人生也无穷无尽。

  你的每个选择最后都会造成一个完整的人生。无休无止。

  你的每个选择最后都也都会回到你身上。

  这就是轮回。」
#+end_quote

我最害怕的事也成为了解答。

我看到了人生的真▫相。一点也不真实的人生。

因为我的人生几乎就是被心里的「漏」模拟出来的「电影格子」带着走的。它一点也不真实。

就算我吃到超好吃的美味，看到超美丽的景色、碰到超舒服的东西、听到美丽的音乐...这一切都是模拟出来的。都是假的！

我的人生就是一场真实的「Matrix」！

你说我能够不害怕吗！

不，我不用害怕。

如果我只是看到了真▫相而发现无法逃脱，那么我就仍然疑惑，也许从此我就会发疯了吧？

但是现在我的心一片平静，没有任何疑惑，所以我得到了回答。

#+begin_quote
  「解脱这逃不出的轮回是可能的。

  就是时时刻刻觉知、保持清醒。

  就像你与昏沉的战争那样。在每一秒里，一格一格的争取回觉知真▫相的能力。

  直到再也不让昏沉生起任何『画面』。」
#+end_quote

觉知真▫相？什么才是真▫相？到底觉知什么呢？

#+begin_quote
  「精勤、觉知。时时彻知『无常』。

  Atapi Sampajanno Satima。」
#+end_quote

这就是整个四念住开示中，葛印卡不断提醒我们最重要的事实，也是和十日禅修唯一不同的一点。

要「时时刻刻彻知无常」。

「没有疑惑的思考」下，得到的回答都非常清楚、直接，用简单的文字就可以表达。简单到无法挑剔，而且都是与切身经验相关、不含糊的回答。

我必须为我的人生负责。如果我作了坏事，最后这些坏事会直接储存在我的生命里，造成新的轮回，我完全无法逃脱。

因此在这样的认知下，我是无法容忍自己再去做任何坏事的。

有了这样的认知，持守五戒就是很自然的选择了。因为这是轮回这场博奕赛局下最佳的选择，能够保护自己不再受到自己的伤害。

持续的修行也无法停止了，因为唯有持续的修行才能停止造出新的轮回，新的轮回只是不断的苦再生起。唯有修行戒、定、慧才让现有的轮回停止、息灭，不再创造新的轮回。

死亡时的状态我也明白了，我不再害怕死亡。它就是进入一片黑暗的海洋。

再生就是从那黑暗的海洋里再喷出一个新的生命。

** 有分心－目标对准死亡的心
    :PROPERTIES:
    :CUSTOM_ID: 有分心目标对准死亡的心
    :END:
这其实不是这次禅修的收获，只是确认一下上次禅修时看到的东西。不过，结论先说，这不是什么好东西。

禅修时会看到很多异象，大部份睁开眼睛就不见了，那都是幻象，没什么好执取的。例如我就看过自己全身放光啦，看到什么如来佛来跟我讲话啦，什么壮丽的宇宙在我心里绽放啦...等等，实在比电影还精彩，不过那都没什么好玩的，因为它们和电影一样，一谢幕就没了力量，只是浪费时间跟自己玩儿罢了。

唐望说得好：「你要在心里看这些幻像，不如去看场电影就好了。」

助理老师对幻像的处置很简单：「你管它是什么东西干嘛？一睁眼它们都不见啦，那都是幻觉。」

这个有分心也是这样。

虽然葛印卡老师教导我们要保持平等心，不要去玩弄感受，但是我本人实在是个好奇宝宝。有一次我发现我的呼吸越来越微弱，心里也越来越平静，那心里一点点的波动也能很清楚的觉知，并且可以控制心念不外漏，就像把水龙头关掉一样，让波动一点一滴的消失...最后心里就像一面平静的水池一样。

为了确认这个状态不是幻觉，我特地睁眼来看一下它会不会消失不见，发现居然不会，可见得这不是幻觉（因为这可能是观察到了心），于是就这样继续观了下去。

然而，我发现那平静的水池中间有一小粒黑色的点，是我完全没办法觉知的地方。要知道心里觉知出来的平静水面其实是非常非常微细的振动、波动，是这些小小的波动连续起来所构成的，怎么会有地方是连波动都没有的？好奇之下，就去观察它。

这一观，就发现它变大了一些。

这也太好玩儿了！于是我把葛印卡老师的觉知、平等心什么的抛到脑后了，专心来看这个小黑点儿。

哇～～这个小黑点居然扩大到和我身体一样大了。好黑啊，什么觉知都找不到，到底要观什么啊？

心念一横，想着，既然它会扩大，那就让它扩大吧，反正那么多人一起禅修，出事了也有人照应。

这么一观察下去，哇哈，那黑点瞬间变成了黑洞，转眼扩散到无边无际，超越了我的身体，超越了禅堂、超越了地球，变成了一片无止尽的黑暗。同时，我觉知我的身体并不是挺直的，反而是渐渐弯了下去，头顶整个碰到了地面，呼吸也完全消失了，好像没有了呼吸一样...

「啊哈！这不是闹着玩的，怎么好像死了一样。不然我来大口呼吸看看还是不是活着。」

心念一起的时候，从头顶涌现了各种的知觉出来，好像喷泉一样，迅速地把黑暗都赶走了，知觉像泉水一样，笼罩了我的全身。

我又回来了，赶快挺起身来。

晚上去问助理老师，我说：「老师，我刚刚好像死掉了。」然后描述我遇到的状况。老师笑眯眯的说：「你碰到有分心了。如果你一直看下去，真的会死掉喔～」让我吓了一跳。

「继续保持觉知呼吸，觉知感受，扫描全身。」老师指示。

回家后，查了查各种书籍、资料，也上网问了问，据说有分心的目标是正对着死亡的。不过还是不太了解什么叫「有分心」。因为理论上来说，受的止息、触的止息、贪爱的止息应该就会导向涅盘啊？所以一切的灭尽...不就是黑漆漆一片吗？

于是这次禅修时，我那好奇心又来了。

觉知感受，扫描身体，了知无常，保持平等心...

觉知心...觉知心中的各种执着...执着消失了，觉知各种波动渐渐变小...

水龙头关掉了...滴答、滴答、滴...停了...心中一片澄静，像一片水池。

我吐气，找到那个小黑点。它出来了。

我刻意减弱呼吸，呼吸越来越微弱，黑点越来越大，笼罩了我的身体。

身体渐渐向前弯...呼吸渐渐微细...呼吸不见了，头快要碰到地面了...黑洞越来越大...

最后头碰到了地面。

瞬间黑洞无限延伸，我的知觉居然...消失了！

\\
* 首次葛印卡四念住禅修心得 (4)    [2012-09-15]-<feff>-[2015-06-19]
  :PROPERTIES:
  :CUSTOM_ID: 首次葛印卡四念住禅修心得-4
  :CLASS: entry-title
  :END:

** 黑漆桶
    :PROPERTIES:
    :CUSTOM_ID: 黑漆桶
    :END:
「搞啥啊，黑漆漆...理论上这好像是五蕴的灭尽，但这绝对不是修行的最高目标－涅盘吧？」

小参时问了助理老师，老师说：「不要再看了喔，你再看下去，连老师都救不了你。回▫归到觉知呼吸，觉知感受，知道吗？」

我的好奇心满足了。那个黑洞就是有分，目标就是死亡。

有些人会以为这就是五蕴的灭尽了，这就是最高的目标，这就是灭尽定了！但其实它不是。它只是修行路上的一条叉路，不要分心了。

在此引述一句豆瓣上的朋友的话：

#+begin_quote
  ...世界上假的东西、错的道路数不胜数，纠结在这种东西里人很难进步。人要开拓正确的道路难免会误入歧途，但并不是说你要看尽歧途才能走入正途。看尽歧途不仅浪费时间，而且最终也无法使你走上正途。

  -<feff>- 豆友 笑紅尘
#+end_quote

修行不是要修到直接死掉喔！有分心看过就算了，人死亡的时候也就是那个样子。我们修行的目标是要直达那超越身心的境界－涅盘才对。

乌巴庆老师提醒我们，若是真正经验涅盘者，会有以下的特性：

#+begin_quote
  ...只要有初觉悟经验的行者，都可以完全经验法的成果。所有的圣弟子都有这内在涅盘的宁静。他们可以随心所欲地享受这宁静之乐。他们进入所谓正果的祥和状态，这是关于出世间意识的涅盘宁静，在此，没有任何感觉会因感官中心而引起。此时，*身体姿态变直*，这状态是完美的生理和心理宁静，涅盘的祥和是最高的悦乐。...
#+end_quote

不离四念住，直直的往前走，我们就能够走出身心这个大迷宫。

** 错误的精进
    :PROPERTIES:
    :CUSTOM_ID: 错误的精进
    :END:
晚上听到葛印卡老师的开示说「要精勤、觉知、时时彻知无常」，再加上我不想再被昏沉控制，被模拟的感受带走，见不着无常，于是我好像屁股被针刺一样地，在半夜也不想睡着，持续地觉知呼吸、觉知感受。

我的精进太猛烈了，因为我太害怕昏沉，而不自觉的产生了掉举，导致到了12点多了，我还睡不着，而且呼吸越来越粗重。

我乾脆起来禅坐，并且告诉我自己「我不要再被『假的』迷惑了！我只要真的！我只要彻见无常！」

然后又对自己发誓：「今天晚上不完全彻知无常我就不停止禅坐！难道你还要再被昏沉再控制个一千年吗？花个一个晚上打败昏沉，赚到一千年，实在太值得了，不是吗？！」还特意双盘了起来，完全不怕脚会痛死。

但是那掉举太猛烈了，很快，不到二十分钟我的脚就痛到不行，身体不断因为害怕而抖动。

还好我意识到这不是正确的精进。正确的精进是精进的观察，保持觉知和平等心，不是「我要什么」这样的欲望，也不是因为害怕而反应。

又是一个被五盖欺负的夜晚。

没什么，观察到被打败了就算了，明天继续！

我安心的睡了个好觉。

** 自动化生活内观禅修
    :PROPERTIES:
    :CUSTOM_ID: 自动化生活内观禅修
    :END:
这次禅修，我得到了非常大的利益。

- 其一，我观察到了心的面貌(?有待进一步确认，不过很实用)。
- 其二，我知道了五盖的生起，及五盖的灭去，以及如何观察它们。
- 其三，我得到了能够在生活中自动修行的方式。

自动化的修行就是经中的那句话：

#+begin_quote
  「精勤、觉知、时时彻知无常。」
#+end_quote

目前我只能在没有外务的清闲时刻和早晚一小时的禅修时持续观察。然而最终的目标是，每分每秒都不间断的目击无常，让身体、感受、心自动地持续修行。

乌巴庆老师告诉我们，在家居士应如何觉知无常：

#+begin_quote
  ...毗婆舍那的最初目标是启发自身内的「活化无常」（注∶乌巴庆有时用「活化无常」activate
  impermanence，这似乎是指可以完全经验到真正无常，即身心连续体很快融化，像「掉落在湖面的雨水」，在那时，心灵产生净化力，他称之为「涅盘元素」），或感受内在自我的无常，最终达到内、外宁静和平衡的状态，个人全神贯注于身内无常时，即可达成此一目标。

  ...当一个人能感觉到无常，经验到无常，完全感受到无常，他可随意脱离外在的观念世界。无常对在家居士而言，是生活的宝石，他将加以珍惜，为自己创造宁静和平衡能源的贮藏所。它冲击人身心疾病的根源，并逐渐拔除这种身心疾病的根源。

  ...在佛陀时代，修习毗婆舍那的在家居士人数很多。无常并非保留给出家修行的人。在家生活虽然有使人不安的缺点，但好老师或引导人员可以协助学生在很短时间内活化无常。

  ...一旦认知无常，唯一要做的事就是试着保持它。

  ...只要有精进的时机，行者必须坚持它，以得到所有物质和精神现象快速改变本质的知见。假如到达这知见，就没有问题，因为那时他应可以毫不费力的，几乎是自动地经验无常了。在这种情形，无常成为他的基础，一旦家居生活的需要结束，他即可回到那里。

  ...然而，对于尚未具足正观，可以看清物质和精神现象快速改变本质的人而言，可能有些困难。这对他就像是身心内外活动与无常的拉锯战。

  ...对这种人而言，聪明的方式是依循一句箴言∶「工作时工作，玩乐时尽情玩乐。」不需随时启动无常。将练习分订于白天或晚上固定时间，应已足够。

  ...在这练习时间，应试着将心──注意力保持于身内，警觉于无常上，无常警觉应时时存在，这样继续地不使有任何绝对有害进步的散漫或令人分心的思想插入。

  ...如果不能如此的话，应回▫归到出入息法，因为专注是启动「活化无常」之钥。

  ...记住，为获致好的专注，必须有完美的道德，因为好的专注筑基于道德之上。而且，要正念于无常，专注必须扎实，假如专注十分好，无常警觉也会变得很好。除了培养对禅修对象的专注外，没有培养无常的特殊技巧。

  ...这意谓着，为了感觉身体上面或内部的无常，而将专注转回到身体感觉上，首先应在人可以很容易全神贯注的部位上，这也意指可随处改变专注的部位，从头变到脚，从脚变到头，有时也细察内在。必须很清楚瞭解，不要将注意力指向身体解剖上，而是指向直接经验物质的形成（极微）的感觉和它们持续改变的本质。
#+end_quote

修行就是成为一个完整的人，这没有捷径，就是从戒、定、慧开始，一步一步在四念住这条道路上修行，达到最终的目标。

\\

* 第三次葛印卡内观十日禅修心得 (1)    [2011-01-01]-<feff>-[2014-12-02]
  :PROPERTIES:
  :CUSTOM_ID: 第三次葛印卡内观十日禅修心得-1
  :CLASS: entry-title
  :END:

参加了第三次的内观课程，前二次一直执着于种种幻想与幻象。直到第三次参加后，才决定抛下所有成见，专心修习内观。之前也有自费学习灵气等其它的灵修课程，但发现它们与内观是完全冲突的，因此第三次参加前已停止所有其它灵修课程的修习。

内观是以身体的感受入手，直接体验到身体的苦、苦集、苦灭、以及苦灭的方法。除此之外，我们在课程中体验到的种种光明、黑暗、全身透明、放光，或身体变大变小、以及闭眼出现的、睁眼出现的各种天人、魔王...等等，都跟其它的想法、感受并无不同，皆以平等心看待即可。说实话，通常当睁眼一阵子后，这些有的没的也就消失了。它们和下雨的雨滴一样，因为云层厚了就下雨，转瞬就落下、变化，不断生灭（无常），没有永久可承载的实体（无我）。执着于转瞬消失的各种体验、境界，只是导致苦的不断生起（苦集）。我们能做的，就像葛印卡老师的开示一样，静静的观察它们的生起，消失，它就不再生起（苦灭）。会生起这些诸种体验，都是心的造作而已（此生故彼生），只要观察、观察、再观察而不起习性反应，它们就没有产生的动力了（此灭故彼灭）。

痛也是一样的。当心发现是因为执着（贪爱舒服的感受、讨厌不舒服的感受）、没有可持续承受的实体（非我）后，痛会像渐渐关掉的水龙头一样，从整条腿缩到半条腿、从半条腿缩到一条筋...范围越来越小、越来越没力、最后缩到一点，然后或者0.5秒生起一次、然后延长到1秒生起一次、10秒生起一次，最后停了，不再产生。心变清净了，对我不再执着、因此痛不再生起。

因此，灵气等New
age的灵修方式，如果它们能让心专注、时时刻刻亲自见到无常、我想是没有问题的。可惜亲自去这些灵修课程的体验后，只有不断的观想光明、能量、增长幻相、增加「我」的功力、「我的」身体，就算短时间可以觉得很开心，过了一段时间后，苦仍然存在，没有解决。我们的一生有多长，可以将这些灵修课程一个个修个遍？因此，目前除了内观之外，其它的灵修方式多只能隔靴搔▫痒。虽然内观没像时下的课程那么炫，但一旦亲身体验了苦、苦集、苦灭后，我相信哪种方式是最适合的就不言自明了。

\\

* 第三次葛印卡内观十日禅修心得 (2)    [2012-04-05]-<feff>-[2016-03-14]
  :PROPERTIES:
  :CUSTOM_ID: 第三次葛印卡内观十日禅修心得-2
  :CLASS: entry-title
  :END:

实际上，此次禅修出现了一个我无法了解的超验现象，老师的回答并没有让我满意，于是我求教于原始佛教论坛上的法友。

（[[http://blog.rhinoera.com/wp-content/uploads/2012/04/modules.php?name=Forums&file=viewtopic&t=2376&postdays=0&postorder=asc&start=0][原贴连结于此]]）

顶礼各位大德，

小弟在佛法的修行上，最近遇到了一个难以解答的问题，也就是十二缘起的实修体验。

#+begin_quote
  苦集：...受缘爱，爱缘取，取缘有...

  苦灭：...取灭则爱灭，爱灭则受灭，受灭则触灭...
#+end_quote

小弟近日于台中内观中心进行十日禅修时，心中不断思惟“取灭则爱灭，爱灭则受灭，受灭则触灭”，并不断扫描身上生起及灭去的种种感受。初期非常惊讶的发现，原来各种受觉如果没有“执取”，痛觉是可以不感到痛的，例如久处盘坐姿势时，脚上的痛、麻、痒、酸等，只要心中没有执取，这些受觉在每一秒都会变化，它不会变成“好痛...好酸...”的感受，只是一种好像与心中无关的感受。

经由这种有“超然感”（平等心？）的练习后，小弟了解这就是“苦”的来源，也就是执取造成苦的聚集。

然后小弟再思惟，既然苦是如此产生的，如果不再执取的话，会发生什么事呢？

小弟继续不带执取的观察各种感受，发现各种感受不仅不断变化，而且强度渐渐减小、减小...。神奇的是，各种感受就像是水龙头渐渐关掉时一样，最后只剩三滴、二滴、一滴感受，直到“关掉了”。此时心里居然”暂时”不再有感受！

小弟再思惟，“爱灭则受灭”就是这样吗？那再下去会是什么样呢？诡异的情况发生了，小弟发现心中有一个黑点出现，能够形容它的只能用“黑洞”来形容，因为它里面什么都没有，连想感受都没得感受。小弟心里想“这就是所谓的‘灭'吗？”

虽然如此，小弟发现自己还有呼吸，我的生命仍然依赖着呼吸继续着。小弟再思惟：“如果完全不依赖任何东西，会是什么样呢？”，此时这个黑点扩大了，它盖住了我的身体。

小弟再思惟：“如果连呼吸也不依赖呢？”吓人的是，这个黑洞又再扩大了，超过了我的身体。

“管它的，大不了就一死吧！就算真的要死，旁边也有老师和同修帮忙啊...”意识再深入那个黑洞，身体是不是还能活着也不管了...

在一秒内，黑洞放大到无边无际，我的身体也感受不到了，只觉得好像有超越了一切的什么东西在那里，有一股像水流一样的东西从我的头上不断流出...

“妈呀！这样流下去会不会真的死掉？不然我呼吸一下好了，看是不是还活着。”

当我再呼吸的时候，一切都回复正常了，但是我的头完全向前90度顶在地上。赶紧再挺回身子回到觉知呼吸、觉知全身从头开始。对我而言，发生的时间似乎只有一秒钟而已。

事后我非常疑惑，难道“苦灭”是要修到连生命都“灭去”吗（死掉）？但是先贤们体验到“苦的止息”后，还是活着啊？！那我是修到了什么东西去了？

经过请教指导老师后，老师说这是被“有分心”抓走了，回到身体继续从头到尾扫描，觉知感受就好了。这是虽然定力很深但是觉知力不够的关系。

经过这样的体验，我了解到这是“定”超过了觉知，只有定是无助于解脱的，需要定慧并行。但是小弟很想知道我到底体验到了什么。因此在此请教各位大德：

1. 请问这是什么样的定境呢？
2. 那个黑洞又是什么呢？
3. 从头上流出来的又是什么呢？
4. 呼吸也要“止息”才是正确的修行吗？
5. 体验苦灭的时候，因为“爱灭则受灭”，所以连感受到没有了，那要缘什么来修行呢？小弟发现，没有受的情况下还能思考，那如何依思考修行呢？
6. 这种体验要如何才能帮助我达到解脱呢？我的体验是正确的吗？如果不是，如何才是正确的体验“苦的灭尽”呢？

小弟深信法是可以亲见，现下就可以体验到，就像小弟所体验到的十二缘起是在每一分每一秒就亲见一样，不是等到死后或是下一生才能见到。就像佛使比丘所说：“...缘起如闪电般生灭，制造出心中的苦，而且就出现在我们的日常生活中。”我相信　贵论坛的大德也能够亲身体验这一真▫相，因此特来此论坛请教已经亲身体验缘起的大德、善知识，以解小弟心中之疑惑。

*答覆：*

#+begin_quote
  *希拉*：

  你在修法的过程中，那个奇怪的经验是审视全身的感受无常而发生，依缘起法的观念，缘“A”则生“B”，B会发生是因为A所造成；如果你一直将重点放在“审视全身的感受无常”(A），照理说，那个奇怪的经验(B)就会持续存在。但问题你的注意力被B抓▫住就丧失了A，那B也就跟着消失了。

  *metta*：

  关于黑洞的问题，我没有经验，但是听说过。因为正在翻译Sujiva禅师的书，书中讲到在证果的时候用了一个词black-out，还有很多情况会出现这种black-out，有的人会误以为证果了。
  在和张贵人师兄讨论这个词如何翻译的时候，他提到这种black-out就是像黑洞一样，很黑。是定力很深的时候出现的情况。他提到似乎禅宗有用“黑漆漆”来形容。

  *法友来函回覆*：

  你提出的问题：“难道“苦灭”是要修到连生命都“灭去”吗（死掉）？”可参考《杂阿含》568经、《相应部》41.
  6经。
#+end_quote

*再问：*

我不想管其它人怎么想的。请告诉我，既然受灭，身体还有任何感受可以“体验”吗？

*答覆：*

#+begin_quote
  *希拉*：

  佛陀体证缘起法之后，他从来没有说过，他就因此不再有任何感受了。解脱圣者们从此”只是不再执取这些感受为我”罢了。

  经文有些实证的内容，超越一般人的生活经验。如果真的对这些问题难以理解也觉得困惑，不妨暂时先放下，总是有别的佛法内容可以先学的。
#+end_quote

*再问：*

感谢希拉大德您的回覆！

佛陀说的，因为我不能理解所以才来讨论区讨论，如果懂了又复何言？

只是就小弟渺小的修行经验，认为佛陀说的，是可以“直接体验，当下可以获得成果，让大家一起来看，向内观照，智者亲自体证。”而且他的言语是“简单而且定义清楚，每个人都可以练习，不会有任何疑惑”。佛陀也告诉我们，“不要因为以下的情况而接受任何道理：...只因为你相信传统或前人...”

如果您也同意，那我们继续聊下去，毕竟这是讨论区不是见面聊天，我们不用急着回答，或是说服我及看这个帖子的任何人。

佛陀说的我们没有机会去亲证了，我也没办法去戳一下佛陀看他会不会有感受。因此佛陀有没有感受...这只是猜测，没有意义。我能做的，只是依照经文，找出清楚的定义，让我的修行能够依理而行，实际亲证。

因为佛陀告诉我们，这条这样走那样走就能到某处，而我们一直听到别人说“走那条路不是那么容易就能走到”“一般人不是那么容易理解”“超越一般人的生活经验”，反正我有眼有手有脚，走看看不就知道了吗？

根据各位大德的答覆，我实在修行不出来什么“初禅”“二禅”，更别说什么“五自在”了，但是我修行得出来什么是“受灭”，只不过它只发生在我闭眼独自盘坐，无人干扰的地方，我的身体还在，只有感受不见了，我也不知道它去了哪里；我一睁眼，一切受又都再回来，让我觉得很无助，修行是一场幻觉迷惑自己吗？

回到主题，受灭到底是什么体验，是还有受吗？还是有一半受（身受心不受什么的）？既然“此无故彼无”，六入处都灭了，为什么还有身受心不受这种奇怪的道理？

*答覆：*

#+begin_quote
  *希拉*：

  只有证悟缘起法的时候，才会知道什么是“受灭”，普通人不可能会知道“受灭”。普通人觉得没有感受的时候，只是心灵陷入无明的影响，他失去正念观照，他自己不知道罢了。

  我自己用学理去推，我自己解读所谓的“受灭”也并不是真的指感受消失而是无明灭-<feff>->无明受灭。就是说，解脱者对于感受的认知不再受到无明的影响而失真，他清清楚楚认知、观照“感受”的真▫相，就像“第一义空经”所说：“身生时，无有来处；灭时，无有去处，如是，身不实而生，生已尽灭，有业报而无作者。”(眼、耳、鼻、舌、身、意六入处皆如是说)。

  建议可以多看一些南传内观行者的修行体验谈论一类的书，如马哈希的内观禅修法：\\
  毕竟，假如你、我都做不到的事，光二人在那里空谈、空论也不是办法。\\
  本论坛有位”道”法友写的“如何完成正定“与“四念处之身念处修行”都可以尝试修行看看。

  *Dogbert*：

  参考杂阿含经（475），重点整理如下。

  受：三受，乐受、苦受、不苦不乐受。\\
  受集：触集是受集。\\
  受灭：触灭是受灭。\\
  受集道迹：于受爱乐、赞叹、染着、坚住。\\
  受灭道迹：于受不爱乐、(不)赞叹、(不)染着、(不)坚住。\\
  受味：受因缘生乐喜。\\
  受患：受无常变易法。\\
  受离：于受断欲贪、越欲贪。

  看完应该就知道受灭是要断除什么，也不会再去管受灭后身心有没有感受，因为重点不在有没有”感受”，而是有没有”三受”。

  注：一般人说的感受是指觉知外在事物，这跟佛法中的受是不太一样的。若是把两者划上等号，那受一灭，不就等于死人了？
#+end_quote

\\

* 第四次葛印卡内观十日禅修心得（1）    [2013-02-07]-<feff>-[2014-12-01]
  :PROPERTIES:
  :CUSTOM_ID: 第四次葛印卡内观十日禅修心得1
  :CLASS: entry-title
  :END:

「在不平常的领域中做平常的事情」这句话总结了我第四次参加内观十日禅的经验。

每次禅修都会发生很多无法解释的事情，通常要花掉好几个月的时间去找书、去追究，不断的写、写、写，实验、对照、归纳、总结，才会知道当时发生了什么。

重点是，知道发生了什么，才能重现。

在哪里重现？在日常的禅修中重现。

重现的好处是什么？是让正法渗透到我的日常生活中，让我能时时刻刻不离正法，这才是最重要的。

一切境界都会消失，都是会变的，不能持续的。惟有解脱、断轮回才是要紧事。

我一直觉得「正法」是公开的，请你来看的，所以不应该有什么秘密。因此，我认为，我所经历的各种情况，都是可以公开的，别人也会走到的，世尊有说过的。如此公开的东西写成文字，不应该有问题。

那么各种境界也可以写出来吗？

我写了很多，但是到这次禅修完才发现，除了世尊说过的，代表「里程碑」的境界外，还真的没什么可写的...写了，也是白写。

举个例子，我在禅修时看到了佛陀，听见了佛陀的声音。

先说声音，那个声音的共呜非常多层次，感觉是全身都在共呜，一个音节就能让你遍体愉悦，更何况是讲一个句子。（我实在还不会用名词来写作啊，只好用形容语和动词，工科思维真要命）

我看到的佛陀，也不是一般看到人的样子，而是一格一格的，不连续的画面组合而成。

为什么呢？

因为我们平常的视觉都是所谓「相续」的幻觉构建而成的，破坏了「相续」就没有动作了，都是一格一格的。

我看到的佛陀也不是「立体」的，居然是「平面」的，而且非常非常大，有我一个人的十几倍大！

不过，我看到佛陀的时候，也不知道我自己是多大，所以只能就相对来形容，我和佛陀比起来就像一只小猫一样小。

为什么看到的是「平面」的？我想到可能的解释是，因为我看过「三体」描述的「四维空间」，把佛陀解读成高维空间的人现身在三维了，所以我用三维的视角看，当然会是平面的。

而且妙的是，我看着佛陀一转身，就像看着一张纸转成侧面一样，变成一条线，消失在空气中，看不到了。

这分明是高维空间在三维的呈现。

很明显的，是我的「想」蕴根据「三体」这本小说的描述，在解读我的经验。

这些体验，这些境界是什么呢？全都是「意」根经验到的东西（专有名词，称为「法」），经由「想」蕴解读出来的结果。

在经历的当时，我是很清楚明白的，知道自己坐在禅堂中，知道自己在呼吸，知道自己在扫描全身的感受，却又同时在解读意根发生的经验。

是的，我分心在做这些事。

当下看到、听到时真的是很震撼的，虽然明知道把这些讲给老师听，老师只会说「不要卷进去看，回到呼吸，回到感受」，但还是忍不住拨出20％的注意力一直看。

但是这些声音画面真的没什么好说，因为都是解读后的东西而已。真正在那时经历到的东西，只能说是「法」触到了「意」根，就这样而已，没别的。只要那20%的注意力回到感受上，就没什么可看的了。

那为什么会从意根生出这些美妙的声音和画面呢？因为我「想」看了，有欲望，无明缘行、识、名色、六入...最后就有了「色」给我的眼识看。

眼缘色尘生内结，耳...乃至意缘法尘生内结，于是各种境界生起，唉唉。

讲完收工，真没意思。

禅坐有非常多的境界可以玩，不只是有形状的境界（例如看到佛陀和他的弟子们），还有很多没有形状的境界，简直不知道从何描述起。

然而这些全都可以归结成「意」与「法」接触产生的结果。

为什么会这么平淡，平淡到没什么好说呢？

因为除了听到声音、看到画面之外，我体验到了一个完全毁灭我的三观的事情，震掉了我对各种境界的依恋。

--> [[http://blog.rhinoera.com/635/][续集请点此]]

\\

* 第四次葛印卡内观十日禅修心得（2）    [2013-04-02]-<feff>-[2014-12-18]
  :PROPERTIES:
  :CUSTOM_ID: 第四次葛印卡内观十日禅修心得2
  :CLASS: entry-title
  :END:

写东西是为了解决迷惑的。

我相信有些朋友看了小弟[[http://blog.rhinoera.com/447/][之前的心得]]是有疑惑的。怎么内观会看到佛陀呢？这不是鼓励幻觉吗？

这些幻觉其实小弟已经解决了，不过要从其它的经验说明才能让看倌们了解，在此继续记录下去。希望有缘看到的朋友都能疑惑冰消。

上次写到小弟看到了佛陀，很大很大的二次元佛陀。那只是插曲。现在来讲主题。

** 身体的感受和你想的不一样
    :PROPERTIES:
    :CUSTOM_ID: 身体的感受和你想的不一样
    :END:
葛印卡内观的方法主要是由上而下，扫描身体的每一寸感觉。首先是皮肤的感觉，慢慢的禅修者会将感觉延伸到皮下，最后穿透身体。

当扫描的感觉穿透身体时，禅修者会感觉到身体像是一块透明的水晶，所有的感觉上痛、硬、粗、重等的阻碍都会在一次次的扫描下瓦解；最后，身体的每一部份都会像是融解了一样，整个身体像是一团透明的水，一旦禅修者作意观察，观察点就像是水波一样，立刻由身体中央的一点散播到全身，无处不遍。

这是一个惊人的事实：你对身体的感受并不是你久远以来熟悉的那样。

什么是感受呢？

其实我们对身体的各个部份都有一种形状的概念，神经传达的脉冲由身体的各个部份回传讯息，然后由我们的脑部区分、组合成形状。

你摸着你的手，感到一种柔▫滑的触感。然而，这只是一阵阵的神经脉冲。这些脉冲，并不必然永远会解读成一样的讯息。有可能不同的讯息传回来，例如你摸▫到了一个小伤口，而脑部却将它判读为和其它部位一样的柔▫滑，因此你不经意的忽略了它。

这反映了一件事，那就是：你对触感的感受，其实是脑部组合出来的。

因此，脑部可以任意的组合讯息，造出形状和感受。

换句话说，你对身体的认知不必然要有形状和感受！

内观的修习的精妙之处在于，它让你完全的了解：感受和身体是两件事。

当你不断的扫描身体，日夜不断，具足坚定的勇气后，身体会像拨云见日一样，将它的实相揭露给你看。

我在扫描身体时就发现了这样的怪事。

** 身体的形状
    :PROPERTIES:
    :CUSTOM_ID: 身体的形状
    :END:
当我由上而下，由下而上的扫描身体时，我发现，身体的形状开始消失，很多地方虽然仍然能够扫描到，但是无法对映回身体的位置。

为了避免幻觉，我睁开了眼睛，继续的扫描，发现对身体的形状感仍然在消失中。

很快的，身体的形状感不断缩小、缩小，最后成了一个三角椎体。

当我仔细的分辨时，我发现，并不是我的身体变成了三角椎体，而是我所有的感受都被压缩在这个三角椎体中了。

例如，我扫描我的手，扫描出的感受会出现在三角椎体的中心往前一点点的地方，像气泡一样，「波波波」的冒出来。

葛印卡老师的教导说明：「当禅修者能够扫描穿透身体时，要更细致不断的扫描，直到身体一点点粗重的感受都融解为微细的感受。」

因此，我不断的扫描我的身体，直到我发现我感觉中的那个三角椎体完全没有了任何粗重的感受。

粗重的感受就好像大的气泡，细微的感受就好像小的气泡，在我那三角椎体中不断的冒出来，然后消失。

我继续扫描、扫描...

最后，一点点微弱的气泡都再也冒不出来。

身体的感受就像是一团平静的湖水一样，清澈、透明。只要一动念觉知，念头就像水波一样，一下子就遍扫了全身。

我的身体像水晶一样的透明。

所有对身体的感受都是不断在变化的。

「无常，无常！」

这种无常的变化以感受的方式呈现在身体上，每秒钟都被我们的心诠释着。

因此，这个透明如水晶一样的感受，一样也是无常的。

果不其然，这透明的水晶开始由中央冒出了气泡，接着，气泡四散而出，心来不及辨识它们，感受就充满了身体。于是，厚、重、粗、麻的各种感受又遍布了全身。

葛印卡老师彷佛预知了我的感受，再一次提醒着：

#+begin_quote
  「粗重的感受和细微的感受都是一样的，都具有无常的特性。当你经验了可以遍扫全身的细微感受后，会再次经验到粗重的感受。」

  「不要把这个现象当作是退步，反而要知道这是进步。这是因为，更深层的不净烦恼进一步的浮上表面来了。要不断的用功。」

  「在内观的路上，惟一衡量的标准只有觉知和平等心。不要觉得今天我有粗重的感受就是退步，今天我有微细的感受就是进步了，这样你只是在玩弄感受的游戏！」
#+end_quote

踏着导师走过的路，我一步步的了解内观的奇妙。

那水晶般透明的感受开始出现。过了一阵了又没了。过了一阵了又出现，然后消失。

好像猫捉老鼠一样，永无止尽。

烦恼不尽，现象就不尽。

小参时，我问老师：

#+begin_quote
  老师！请问要经过几次这样的透明感觉，烦恼才能够完全灭除呢？

  老师：...（笑了一下，假装沉思着）

  老师：...好吧，无数次。

  我：（倒...）...老师你开玩笑吧？！...

  老师：不要去期待要经历几次。你只要去努力，也许有一天，你就会发现，再也没有烦恼需要去除了。
#+end_quote

接下来，我经验了好几次全身透明的感受，几乎是只要我全心投入，透明的感受就会出现，不费吹灰之力。以前可是要花上好几天的功夫才能出现一次呢！

这个经验让我清楚的了解到，身体是身体，感受是感受。我睁开眼看到的这个身体，和我感觉到的身体不必然有关连。

我不再认为我就是我的身体。

有了这个认知后，接下来的经验更玄了。

** 玩弄脉轮
    :PROPERTIES:
    :CUSTOM_ID: 玩弄脉轮
    :END:
我有一个坏习惯没改，不小心带到了内观禅修中，就是玩弄身体的脉轮。

当我发现，身体中的感受好像气泡一样时，便好奇了起来。

这些气泡从哪里冒出来，会冒到哪里去呢？

我开始客观的研究起「感受」的气泡。

很快的，我发现，心轮（在身体正中，与心脏平行的位置）有大范围的气泡冒出来。于是我不扫描全身了，开始专心观察心轮上的感受。

在内观时的注意力有个特点，因为心比较清净的关系，你观察哪里，那里的反应就会变小、减弱、然后消失。

观察心轮时也是一样，那些感受的气泡会变少，然后变成一条细线一样，最后减弱成涓滴细流，然后消失。

如果你的平等心很强的时候，观察现象是很容易消失的。但是我的好奇心太强了，失去了平等心，所以我观察的现象消失不了，它只会变成一条细线，或是一点点断断续续的气泡，就是不会完全消失。

这很恼人的，于是我采取了积极的手段。（当然，这时已经失去了平等心。）

我发现，只要采取类似瑜珈士的姿势，缩腹，提肛，然后屏住呼吸，那心轮上的气泡就会完全消失。

但是这个姿势有个副作用，就是我的腰会开始往前弯（因为提肛缩腹的关系），一直往下弯，直到头顶碰地，整个人变成拱型。

于是我努力地缩腹、提肛、屏住呼吸，然后头不自觉的不断往下弯...心轮的气泡一步一步的减少...

直到我头碰地的那一刻，「碰！」的一下，我的心轮完全没有了感受的气泡！

太好了！我满足地把身体挺了回来。

不过怪的是，心轮下面的太阳轮，好像接棒了一样，开始冒出大量的感受气泡。

这怎么行？于是我又以同样的方式再「息灭」感受的气泡。

耶？太阳轮没气泡了，又换脐轮？！

再一次...咦？脐轮完，换海底轮？！

好吧，再拼一次...

海底轮的气泡冒完，换顶轮了？！

我就这样搞了三天的时间。此时，下四轮已经不再有气泡冒出来了，我也累到快没有呼吸了（因为强▫迫屏住呼吸的关系）。

晚上，因为累了不再玩脉轮，回到以扫描身体的方法继续用功。

突然间，我好像又被佛陀「拎」了出去，意识里感觉到那身形超级庞大的佛陀和他的弟子们。

他的弟子们顶着庞大的身体，脸上挂着大大的笑容，似乎都觉得很好笑的看着我。

#+begin_quote
  「...息灭所有感受...」
#+end_quote

那庞大的二次元佛陀半闭着眼的看着我说。

啊，这个我会，这三天我就是在息灭我的感受「气泡」呢。于是我盘腿坐好，觉知感受的气泡，准备用同样的技俩-<feff>-提肛、缩腹、头顶地-<feff>-来息灭气泡们。

佛陀用着超有磁性的低音说着我不懂的语言，整个天地都因为那股低音在微微的振动着。

我的意识解读成这句话：

#+begin_quote
  「...入灭尽定...」
#+end_quote

当我头往下垂，开始弯腰的时候，佛陀突然睁开眼了。

他对着我说：「我的弟子，不是用这种愚笨的方法入灭尽定的。」

我红了脸，发现全部的弟子们都在偷笑着。我的意识甚至可以辨识出有笑声传来。

佛陀继续告诫我：「我所有弟子都是正坐着入灭尽定的。」然后示意我从头来。

我不好意思的把头拉回来，挺好身子，然后从头到脚扫描身体，直到对身体的形状感缩小成一个三角椎，就像之前做过的一样。

然而，也许是太急着想表现了吧？！三角椎中不断有感受的气泡冒出来，不再像之前一样，一下就可以变得透明。

「这要花一些时间。要继续努力用功。」二次元佛陀回到半闭着眼的状态，示意我照着这个方法继续努力。然后起身，慢慢走远，最后用二次元的方式消失在空中。

我的意识又回复了平静。

小参时，老师问我：「你怎么常常弯腰呢？是在做什么吗？」

我照实以答，当然，意识飞去见到佛陀的那一段没有讲（因为那是幻觉好吗？！）。

老师说：「我知道你想做一些实验，玩过了就算了，接下来不要再这样做了，知道吗！」

我赶紧点头。

真是神奇，这三天老师其实一直有看到我弯腰顶地，小参时却完全没过问我弯腰的事情，直到我意识中被佛陀「拎」去训诫的事件发生后，才告诫我不要再玩了...难道...幻觉非幻...？

\\
* 第四次葛印卡内观十日禅修心得（3）    [2013-04-04]-<feff>-[2014-12-23]
  :PROPERTIES:
  :CUSTOM_ID: 第四次葛印卡内观十日禅修心得3
  :CLASS: entry-title
  :END:

有了[[http://blog.rhinoera.com/635/][感受和身体分开的经验]]后，我的认知系统已经大大的改变。

接下来，扫描身体的时候，身体的形状已经不再固定是三角椎状了。

有时候是一团圆型，有时候是一颗小丸子，有时候只有身体的皮肤外缘，有时候则像树枝，只有身体的神经系统有形状。

我完全明白，这诸种形状，全都是心的造作而已。

真正有意义的只有一件事：*无常*。

一切感受、一切形状，全都是无常的反映。

一切都是心在造作，全都是无法控制的，只会带来气恼，无奈...

这就是苦。

不断变迁的造作，只会给心带来各种逼▫迫，逼▫迫感带来了痛苦。

我只能不断的扫描全身，让全身的感受消融，减轻那逼▫迫感带来的痛苦。

接着而来的经验就更让人摸不着头绪了。

** 感受的消失
    :PROPERTIES:
    :CUSTOM_ID: 感受的消失
    :END:
在我扫描全身时，无论形状为何，本来扫描到最后都会全身透明的，像一盆水一样。

但是在继续扫描的过程中，我发现，那盆水居然在...慢慢的蒸发中？！

那蒸发的感觉，和扫描到全身透明的过程并不一样。

扫描到全身透明的过程，全身会由粗重的感受，转变成一阵一阵像火烧一样的感受，接着变成一段一段的跳动，然后跳动会越来越小，长度越来越短，最后平息，只剩下顺畅的微细感受。

如果要用四大来对映，就像是地->火->风->水这样的顺序。

然而，当全身只剩水大的感受时，这个水居然也开始褪去！

我开始认真的观察这些水大是往哪里褪去的，才发现，这些褪去的水大，和之前观察到的感受气泡有一样的特性。

之前观察到的感受气泡是由脉轮冒出来，消失于脉轮，有一个集中点；褪去的水大，却是往身体各处消失。它们同时消失在太多点了，以至于无法分辨出是在哪一个点消失的。

我再仔细的分辨它们的出现和消失。这次，我分段来观察，先观察身体中央。

** 原始讯息
    :PROPERTIES:
    :CUSTOM_ID: 原始讯息
    :END:
当我仔细分辨后，才发现，我观察到的「消失」现象，并不是真的消失，而是一种「趋势」。原来这些水大并不是真的「消失」！

它们只是「产生」的速度变慢了，以致于我感觉到它们「消失中」；其实，之前观察到的感受气泡也是同样的，只是我现在才分辨出来。

至于它们消失到哪里去了？其实并没有消失，只是被脑部拿去（也可说是「心」），组成了我们对身体的连续认知和感受。我们以为这些认知和感受是连续的，其实不是，它们的原始讯息是一段一段组合而成的。

原始讯息 -> 组合 -> 产生感受（受）

而我现在观察到了「原始讯息」。因为原始讯息是一段一段的，所以才觉得它们像「气泡」一样。

当原始讯息大量产生时，观察者就会感觉好像瀑布、河流一样；然而，当原始讯息慢下来时，观察者就会开始感觉到气泡感，甚至再慢一点，就会像一条细线一样；最后，变成一滴一滴的水滴，然后停止。

眼尖的看倌在这里会开始挑毛病了：原始讯息怎么可能慢下来？！

没错，我也认为原始讯息是不可能「变慢」的。

话说，最新的物理学证明了，整个宇宙没有所谓的「绝对速度」，只有「相对速度」。微观世界也是一样的，因此禅修时也不例外。禅修者的心是非常活跃的，而且不是乱跳，是不断的加速着跃入被观察的对象。

照这样来说，惟一有可能解释这个现象的，就是禅修者观察的速度*跟上了*原始讯息的速度，才会发现对象「变慢」了。

那么，当观察者的速度*超过了*原始讯息的速度时，会发生什么事呢？

观察者会见到所有原始讯息开始往后退！

以观察者为中心，所有的讯息都好像在远离他一样。

在禅修者主观的经验来说，禅修者会经历他不曾见过的奇怪现象。首先他会看到原本他认为是连续的现象，现在变得一闪一闪的，现象一生起就灭去，好像在闪烁一样。

接下来他会看到，任何他观察的现象都在「灭去」。

这就是「生灭随观智」到「坏随观智」的过程。

这样就简单了，消失点是找不到的，但是找得到产生点。只要能够加快观察者的速度（加强「正念」），产生点的相对速度就会减慢，当原始讯息由瀑流变成一条细线时，就可以循线往回找到产生点了。

** 寻找六入处
    :PROPERTIES:
    :CUSTOM_ID: 寻找六入处
    :END:
那么，身体中央的讯息产生点在哪里呢？

经由详细的观察，我发现，身体左右有两条细线，产生点分别在：

1. 脐轮左右
2. 手掌心
3. 脚掌心

这两条线贯穿了整个身体的触觉。

当我正念观察原始讯息，直到它变成水滴，最后停下来时，触觉也「停了」。

什么叫「停了」？

就是虽然皮肤有接触，但是心中没有任何「振动」。

那接触只停留在「表面」，没有任何感受的气泡延伸到身体内部。（振动就是气泡）

发现触觉的产生点后，其它五种感官也可以找得到了。

1. 眼 -> 左右眉间各一点
2. 耳 -> 左右太阳穴附近各一点
3. 鼻 -> 前额上方一点
4. 舌 -> 喉头上方一点
5. 身 -> 左右两条，由脐轮旁一点延伸到手和脚
6. 意 -> 头顶上一点，风池穴附近两点，往下连到会▫阴穴一点

（有趣的是鼻子，如果注意力非常强时（正念具足？），它会连到意识的那一条，把整个身体都连在一起，不费吹灰之力就可以观察整个身体。也许这就是安般念的原理吧？）

遍满全身的水大就是这么样由六种感官的产生点上「消失」的。

正确来说，是「身」产生的水大感觉就是这么慢慢变少，然后停止的。

分别观察的实验完了，继续回到禅修上。

** 观察缘起
    :PROPERTIES:
    :CUSTOM_ID: 观察缘起
    :END:
咦？

没有东西可以观察了。

因为刚才在实验时，六种感官都不再产生振动了。连一滴水滴般的振动都没有。

所有输入讯息都停留在与六根接触的表面，进不来。换句话说，我没有任何感受。

这...是不错啦，好平静呢。不过接下来要干什么，没事做呢！怎么办呢？

只好放一些讯息进来，观察讯息的产生了。

先由触觉开始。

皮肤接触到空气、衣服，通过四肢的两条线振动了起来，在线上产生了无数的小气泡。

Wait！那些气泡连进了心轮！

心轮转了起来！

太阳轮、脐轮也跟着转起来了！

这些脉轮一动起来，我的各种感受也都出现了！

天啊！一切都连起来了。

原来脉轮的动力就是由六种感官所输入的。

我想起了十二缘起的其中三支：

#+begin_example
  六入 -> 触 -> 受
#+end_example

喔！原来那些像水滴、像气泡、像细线般、像河流瀑布的原始讯息，就是「触」！

不断有触由六入处输入心轮，因此我才产生了感「受」。

心轮流向了太阳轮、脐轮、海底轮，对映到由感受衍生了「爱」、「取」、「有」，接下来就一发不可收拾了。

#+begin_example
  受 -> 爱 -> 取 -> 有 -> 生、老病死
  纯大苦聚集
#+end_example

整个身体在「生」之后，全部都是无法再回头的大苦聚。

这就是缘起，活生生的缘起！

什么是缘灭？就是观察原始讯息，以平等心作意，直到原始讯息停止！

** 息火
    :PROPERTIES:
    :CUSTOM_ID: 息火
    :END:
当你观察到事物发生的源头时，它表现得一点也不像事物产生的结果。

举个例子来说，有一壶水在瓦斯炉上烧，烧滚着、沸腾着。

一个小孩眼看着水要烧干了，回头找要怎么让水不再沸腾。

他伸手碰了一下水，发现水太烫了，不可能这样让水止沸。

他首先找到了炉上的火，发现火是由炉控制的。

接着，他发现炉上有开关，控制瓦斯管线送瓦斯进来。

当然他可以继续去找瓦斯管线是从哪里输进来的，不过这样下去他最后就会找上当地的天然气公司了。要真等到天然气公司来，他家早就烧个精光了。

于是这个小孩关了开关，火停止，水也不再沸腾。

当我们最大的苦果－身体燃烧时，我们最常做的事就是在另一种感官来麻痹痛苦。例如，身体痒的时候，我们就去抓它，让痛的感觉盖过痒的感觉。

当我们感到孤独的时候，我们就去找人陪。

当我们生活不如意的时候，我们就去喝酒，和朋友诉苦。

这些作法都只是暂时的让我们忽视痛苦的根源，就像把手放到滚烫的水里一样，并不能真正的止息痛苦。

佛陀发现了真正痛苦的根源－无明，也发现了痛苦在我们身上的起点，但是那起点怎么看也都不像痛苦－就是你身上最开始的感受。

一点点细小的感受累积在一起，就变成一条感受；一条条线状的感受累积在一起，就变成块状的感受。

最后整片整片的感受包住了你的整个身体，让你不由自主的生气、快乐，不再是自己的主人。

虽然佛陀发现了痛苦的根源、以及在我们身上的起点，但是这样还不足以止息痛苦，难道我们要去找到一个产生「无明」的地方和无明大吵大闹吗？

不需要的，佛陀还发现了止息痛苦的开关，就在你的身上－那就是「爱」。

#+begin_example
  身体（「生」）就像沸水，
  痛苦（「有」）就像火，
  痛苦的根源（「无明」）就像天然气总公司，
#+end_example

只看到十二缘起的头和尾是无法止息痛苦的，就像前面提的小孩去找天然气总公司是关不了火的一样。

只要在我们自己的身上用功，就可以关掉火，就如同小孩关掉自家瓦斯一样。

#+begin_example
  痛苦在我们身上的起点「受」就像瓦斯，
  痛苦的止息「爱」就像瓦斯炉上的开关。
#+end_example

怎么止息痛苦？并不像一些「伪」禅宗的人讲的，什么都不用做，痛苦就止息了；甚至是「你就是佛」，烦恼也是佛，佛性本具，不用动作...没有的事！

各位，要达到苦的止息，重点不是烦恼的「样子」或烦恼的「本源」，那就像是看到沸水然后去找天然气公司一样，解决不了问题。

重点是要停止「渴爱」！手段是「觉知」和「平等心」！那就是你关掉开关的那只手！

关掉「渴爱」，瓦斯就不再供给，火就不再燃烧，水也不再沸腾。

这就是十二缘起从中间任何一支断开，十二支就一起止息的原理。

** 息诸渴爱
    :PROPERTIES:
    :CUSTOM_ID: 息诸渴爱
    :END:
「渴爱」抓不到，摸不着，怎么关掉？

可以的，只要看到你的「受」越来越微细，越来越少，有这样的「趋势」，就可以知道「渴爱」在止息了。

具体的修法，传统的说法就是修习三十七道品。

在葛印卡老师教导的内观禅修中，是「觉知」和「平等心」。我相信，这两者只是为了让初学者不要执着于各种境界上而特别提出的，实际修法仍然是遵循三十七道品。

（补充说明：内观的修法其实是完全遵照包含三十七道品的「大念住经」，四念住课程就是将十日课程的内容完全以大念住经的脉络讲解的，而四念住课程完全等价于十日课程）

当我一次一次地观察感受变得微细、变成涓滴细流，最后停止时，痛苦也暂时的止息了。

那是什么感觉呢？

心里没有任何感受。

举例来说，风吹到我的脸上，我觉知身上的触觉，但是我体内没有任何感受的气泡，没有任何振动。所有的触觉都停在「表面」。

另一个例子，当我走在经行小道上，有一只蜜蜂飞来，试图停在我的手上。

我吓到了，以为它要叮我，于是挥手赶走它。

当我吓到的那一瞬间，我的太阳轮产生了一股振动，滚滚的冒着感受的气泡，延着身体里的细线传到手上，在手上组成了一整片的麻痹感。

我清楚了知，这就是苦受的生起。

然后，麻痹感减退，由太阳轮产生的振动越来越少，最后止息。

手上的麻痹感由一整片慢慢褪去，接着变成一条线，最后变成几滴水滴，然后曳然而止。

这就是苦的止息。

禅修倒数第二天的下午，葛印卡老师开示（原话有点记不清了，以下是摘要）：

「当我们的行蕴减弱，识蕴变强时，苦就不再生起。禅修者可以试着检验，例如碰触皮肤时，感受是否只在皮肤表面生起。」

我修过三次十日课程，也听过这一句话三次。然而，直到此次，我才知道葛印卡老师在讲什么。（之前听到这句话的时候，只觉得「啊～～再一天就结束了，好棒啊！」根本听不进老师的话。）

老师讲的都是真实可以体验到的，不止是老师本身已经体验过，也是佛陀和他的弟子们都体验过的。包括全身变成透明的、感受像水一样从中央散开、以及感受只在表面生起，全都是你亲自可以体验到的境界，而且最重要的是－它*不是幻觉*构成的。

「...法是亲自来看的，可以体验的...」

我站着在心中默念着这句话，感谢佛陀及他的弟子们，成功的将法传到了现在这个时代。

** 想受灭
    :PROPERTIES:
    :CUSTOM_ID: 想受灭
    :END:
最后一个晚上，我回到了禅房，却不想睡。

既然不想睡，那就来禅坐好了。

在微弱的夜光下，我观察感受，由粗重的，变成微细的...

由微细的，变成一条一条线...

由一条一条线，变成一滴一滴...

由一滴一滴，直到所有感受停止。

整个六入处也开始停止。

由六根接触六尘的接触点，本来有一条细细的感受线连到体内的气泡产生点。例如眼睛就是通过眼球到眉头上方；意根就是透过后脑勺连到头顶上。

现在连那条线也变成一滴一滴...最后停了。

真好玩，我的身体好像机器一样，关机了。

那种感觉就好像...身体死掉了。

真的。就是身体和我分开了，然后它死掉了。

就在这时，我发现一件事。

身体的感受没了，却还有一个观察者可以观察自己？

那...谁是观察者？

我仔细检查，原来意根还有最后的一条线没断。

现在观察它，它好像被抓到了一样，立刻在后脑勺现形，变成一条细线...然后变成一滴滴水滴。

非常非常微弱的意念在活动。

回头来看，从粗重的感觉，到火烧身的感觉，变成跳动的感觉，再到遍满全身的微细感觉，最后到六感停止的感觉，一切都是无常，仍然还是心的造作啊！（有没有像孙悟空再怎么跳都跳不出如来佛手掌心的感觉？）

心的最后一丝造作，就是「想」。

继续观察它。

当意念的最后一滴水滴停止时，我也停止了观察。

造作者停止了造作。观察者停止了观察。

整个身心过程只是一连串因果的连续体。没有什么是可以被称做是「我」的东西存在。

找不到呀...找不到。

空空如也。身与心、山河大地。

\\
* 第四次葛印卡内观十日禅修心得（4）    [2013-04-06]-<feff>-[2016-03-14]
  :PROPERTIES:
  :CUSTOM_ID: 第四次葛印卡内观十日禅修心得4
  :CLASS: entry-title
  :END:

此贴是专题「[[http://blog.rhinoera.com/series/4th-goenka-ten-day-retreat-review/][第四次葛印卡内观十日禅修心得]]」的第4
节（共4 节）

\\
这[[http://blog.rhinoera.com/645/][空空如也]]的境界，虽然平静，但似乎有一个问题在。

那就是，当你滑进去后，会*失去意识*。

这可不是很好呢...所谓的内观就是要清清楚楚，明明白白，怎么会让意识就这样不小心溜掉了呢？

好吧。那我就先出去，再回来。

于是后脑勺的意根开始转动...接着海底轮，脐轮、太阳轮、心轮。回到了平常的状态。

接着，我发现了一件事不太一样，那就是－*顶轮*的转动。

如果顶轮不转动的话，心轮以下各轮的转动都会被意根解读，好像罩上了一层纱一样。

这...很难解释，也很难检查。

这样好了，以有明确定义的四种禅定境界来检查好了。

- 实验组：入初禅到四禅，*不*转动顶轮。
- 对照组：入初禅到四禅，转动顶轮。

** 初禅
    :PROPERTIES:
    :CUSTOM_ID: 初禅
    :END:
回想一下，初禅是什么呢？喔对，是「有寻有伺，有喜有乐，离生喜乐」，同时要检查是否已离五盖。

在内观的修行方法里，由头到脚扫描就是寻，持续将注意力压在身体上（或深入身体里）就是伺。

喜是全身像海浪一样跳跃的振动，乐则是一瞬间遍扫全身的微细振动，一境性是全身最后像片湖水一样的毫无振动的平静。

以上四者加上一境性，就是五禅支，整理如下：

- 寻－上下扫描身体
- 伺－注意力压在身体上
- 喜－跳动、踊跃的振动
- 乐－微细振动
- 一境性－平静无波，持续不断的注意力

好，确认五禅支，注意力很稳定的扫描着身体，并且钉在身体的表层，「有寻有伺」。

检查五盖，目前都没有生起。

哇，全身粗重的感受开始软化，融解。只剩下跳动，跳动...

跳动很快变成了摩擦，让所有的感受变成像火烧一样。

很快的，注意力又穿过了骨头。原来...骨头也有感受！全身都在燃烧着！

同时，检查顶轮，嗯，没有在转。那，现在...转起顶轮。

哇！没有骨头，没有神经系统，没有火烧感，只有各处冒出来的感受，像气泡一样，啵啵啵的四散全身。

概念！概念！像火烧一样的感受是被「诠释」后的概念！没有顶轮介入时才会有的感受！

顶轮转动的时候，概念就被「驱散」了！

据说，正念现前的时候，禅修者的注意力会去除概念法的干扰，直接接触对象。

之前我看到佛陀、佛弟子之类的，也是同样的，都是因为看到的是*「诠释」后的「概念」*。其实只是「法」触到「意根」罢了，如同「色」触到「眼根」一样，没什么特别的。

一切境界都有两种看法，一种是由顶轮去看（正念），一种是由后脑勺的意根诠释后的看（概念法）。

我瞬间失去了对各种境界和神迹的迷恋。

所以说...顶轮是所谓「正念」的关键啰？嗯嗯，这是个好发现。怪不得每次禅修前头顶都有一股像虫爬，像电流的感觉，原来是顶轮开始作用了。

** 二禅
    :PROPERTIES:
    :CUSTOM_ID: 二禅
    :END:
接着，继续扫描身体。

全身都变透明了，像一团水一样。

不用花什么功夫就能觉知全身，感觉不像扫描，而是每秒钟都被动的接收着感受。

像一团水一样的概念，应该是顶轮没有转动才形成的。

Yes！转动顶轮，全身像水的概念就消失了。转而只感觉到全身各处的气泡，只是气泡变得比较小一点。

** 三禅
    :PROPERTIES:
    :CUSTOM_ID: 三禅
    :END:
全身就像是是电流流过一样，剩下非常微细的振动，感觉就像全身只剩下神经系统一样，不断的脉冲着。

没错，这也是顶轮没转动时的意像，是概念。

转动顶轮，神经系统的概念又消失了，遍布全身的气泡剩下了一条线。

** 四禅
    :PROPERTIES:
    :CUSTOM_ID: 四禅
    :END:
没有概念，没有意像了。

就只是振动，振动...更小的振动、更弱的振动...停了。

顺便停下顶轮。

有一个概念由意根冒出来了。

是...光？！

非常强烈的光，从眼角射▫出来。

那些振动就好像一层布一样，好像盖住灯泡的布。

现在振动越来越弱、越来越小，就像布越来越薄一样，灯泡就越来越亮。

我想起一句话：

#+begin_quote
  心者，是极光净者，却为客随烦恼所杂染

  －－《增支部》第一集第六《弹指品》
#+end_quote

当然，这也是顶轮未转动时才会看到的，不管多亮都一样。

转动顶轮，光就消失了，只看到五根附近的入处在转动，最后停下来。

有了这样的了知，我瞬间失去了对「光」的迷恋。

为什么说五根呢？因为顶轮带动着后脑勺的意根在转动着，没有停。

** 五蕴
    :PROPERTIES:
    :CUSTOM_ID: 五蕴
    :END:
原来，我的整个身体就像一部精密的机器一样。依照正确的操作手册操作它，它就非常听话，一个口令一个动作。

太好了！

还有什么未解决的疑惑吗？

还有的，就是前面提到的，想和受都停止时，我的意识也会停止的问题。

对对，那就来实验一下，把还在运转的想和受给关了。

问题是，想和受是在哪里呢？

色很容易，整个身体只要有四大特征的就是色。

受呢？

如果感受的气泡没有流到心轮的话，我也不会有感受，只会有「触」在五根的表面。所以「受」应该就是心轮的转动。

接下来，心轮的转动往下驱动了太阳轮的转动。嗯嗯...不知道这是不是「想」。

不过可以确定的是，如果有习性反应出现时，第一个转的是再下面的「脐轮」。习性反应就是「行」，如果是的话，那脐轮就是「行」。

那...太阳轮就是「想」啰？

好，来实验一下。

五入处的气泡细线越来越细，接下来变成水滴状。最后停了下来。

停下来时，心轮的转动先停了。

接下来，太阳轮停了。

最后，脐轮停了。

顶轮仍然在转动，表示我目前接收到的讯息不是经过诠释的「概念法」。

当我一动念，起习性反应时，脐轮转了起来，然后太阳轮转，接下来心轮转，然后延伸出一条条细线到六入处上。苦就是这样增生的。

好，那么全部停止时，就是「行蕴」停止了。

当行蕴停止，「识蕴」继续转动，就是十二缘起断裂的时候。苦就是这样息灭的。

所有的「触」都留在六入处的表面。

因为心轮不转，所以没有感「受」。

太阳轮也没转，没有「想」。
file:./img/clipart_chakra_yoga.jpg

** 四无色定
    :PROPERTIES:
    :CUSTOM_ID: 四无色定
    :END:
如果这个时候让顶轮停止转动，会怎么样呢？

当顶轮停止，也就意谓着讯息开始被意根「诠释」，会出现各种意象和概念。

准备好了吗？

停止顶轮转动。

喔...天啊！整个能被感知的范围好像缩小到一点一样。

我的整个世界好像成为了一个「奇点」，只有数学上才存在的，纯粹的一点。

赶快转动顶轮，看一下各个脉轮现在是什么情况。

嗯...有很细微的线流转在脐轮和太阳轮间（行蕴－想蕴）。但是心轮没有转动，也没有细线流到六入处。

再转动大一点，然后停止顶轮呢？

哇...整个可感知的范围有了这里和那里的分别，不再是「奇点」了。不过，「这里」什么都没有，「那里」也什么都没有。仍然挤在一起，很小很小，不过不再是「奇点」。可以说是没有「空间」。

再动大一点呢？

喔！时间的概念出现了，不过「我」可以感知到所有时间。同时在「这里」，也在「那里」，其间没有任何延迟。

再大一些？！

空间扩张了！我可以感知到「这里」，但是「那里」是需要时间的，整个空间扩张到无边无际！

禅修完后我查了书，发现四无色定最像我感知到的东西：

- 空无边处－无边无际的「空间」
- 识无边处－无止无尽的「时间」
- 无所有处－有「这里」和「那里」的概念，但是没有任何其它概念
- 非想非非想处－只有数学上成立的概念「奇点」

我必须说，这些境界非常令人「着迷」。因为它会让你感觉好像脱离了世界一样。

确切的说，是你没有任何身体上的感觉，却可以体验到这些境界，就好像「离开」了身体一样。

是的，那就和「出体」一模一样。「出体」是很容易让人迷失的。

这些境界也是一样，让人迷失，因为它们实在是...

太美了。

你有想过你可以「同时」在两个以上的地方吗？识无边处可以让你立刻体验到。

想了解「奇点」是什么概念吗？非想非非想处就是了。

尤其是两者之间的交界处，你能想像所有「距离」的概念瞬间缩短，最后变成一个小点的感觉吗？那就好像...好像电影演的，穿过宇宙的隧道一样。

要知道，我是读理工科的，理工人最醉心的不是秋天的落叶，不是恋人的眼神，而是纯粹抽象的「概念」之美。例如数学的工整，代数的抽象，甚至是程式的抽象架构，建筑物的骨架等。

整个四无色处都是纯粹的「概念」。没有任何具体的形状，一切都是完全的抽象着。

太美了。

我相信有些古代的大德来到了这个境界，就不再前进了，甚至错把「无所有处」当成「空」，「非想非非想处」当成「无差别」。不能怪大德们，因为它们真的有这样的性质。

有没有什么事物能够让各位想像一下四无色处是什么样子呢？

我找了半天，还真的被我找到了！

那就是：黑洞。

我从来没想过黑洞和无色▫界有什么关系。

但是据最新的科学研究表示：我们所在的这个宇宙运转的中心点，很可能就是一个非常非常大的黑洞。

这黑洞简直太巨大了，而且它有着一条圆柱的形状，也许这就是佛陀说的「须弥山」吧。

那为什么我们看不到它呢？

因为接近黑洞前，所有的物质（四大）都被激发了，只能看得到很亮的光。然后黑洞的上下两端会喷出一条很亮的线，这个东西...怎么看都很亮，无法想像它里面是没有任何光的。

因为任何物质都会消失在黑洞里，所以黑洞里面的样子，只能用物理学、数学去推测。

很巧的，这个推论实在太像我禅修时经历的四无色定了，推荐各位可以去看看。

视频：Travel inside a black
hole（墙*内网友可以[[http://static.rhinoera.com/wp-content/uploads/2013/04/xjQ7cMWI43M][在土豆网观看]]）

然而，四无色处并不是最终的目标，只是接近终点而已。

终点只有一个，就是涅盘。

但是涅盘只是目标，没办法「停」在涅盘里。它就像北极星，只是指示我们北方在哪里，但是无法「停」在北方。

最接近的一个定就是「想受灭定」。

** 「想受灭定」和「无想定」
    :PROPERTIES:
    :CUSTOM_ID: 想受灭定和无想定
    :END:
于是我跳出四无色定，观察所有脉轮都停了下来，只剩下顶轮，好像一轮月光一样，孤独地照着整个身体。

再作意观察，直到顶轮停下。

喔不，意识消失了，真的好像死亡一样，全身渐渐被无止尽的黑暗吞噬。

整个人好像楇木死灰一样，无知无觉，进去后不知何时能出来，这个定...好奇怪...

我无法认同这就是「想受灭定」！

因为这个问题没厘清，禅修后也没机会问老师，因此困扰了我很久。

我找了很多「想受灭定」的资料，才发现，原来有一个和「想受灭定」非常像的定，就是「无想定」。

这个定是不了解佛教禅定的外道，强制将所有心识、感受制住不起的一种定。

入了定之后无知无觉，外界也无法动摇，最后会落在四禅天，经过500大劫后因为心念一动，再落入轮回，甚至打到畜生道重新练起。

所以说，各位，上一篇你所看到的「什么都没有了，空空如也」的这个结论，是「*无想定*」，并不是真正的「想受灭定」。它也许有助于体验「无我」，但是不是佛教最终的目标，因为*失去意识*了。

我在想，这个最接近涅盘的定会取名为「想受灭定」，最大的原因就是顶轮没有停止，也就是「识蕴」没有停止，停止的只有代表「受」的心轮，代表「想」的太阳轮，代表「行」的脐轮。

后期有些论师开始把「灭尽定」和「想受灭定」混用，就很容易把「无想定」偷混进来。

因为就以上的经验来看，识蕴没有灭，并没有什么都「灭尽」。强要「灭尽」一切，停止代表「识蕴」的顶轮的话，最后就会变成「无想定」了。

这是很严重的差别。我不得不怀疑这是有意为之的，目的是要让人无法搞懂原本定义和操作都很明确的教法。

这边看倌又有一个问题了：「但是识蕴一定不灭才能入「想受灭定」吗？世尊自己不是也说过，没有『长存不灭』的识蕴？」

这边有一个概念要注意，那就是代表「识蕴」的顶轮是*可以不转*的。它转的时候才有「识蕴」，代表这个「识蕴」是缘生的，*并非长存不灭*。

所以说，入「想受灭定」是有意为之的，*有意的*让识蕴继续运转，并不代表识蕴本身是长存不灭。问题解决。

** 想受灭定
    :PROPERTIES:
    :CUSTOM_ID: 想受灭定
    :END:
有一些古大德挑明了讲：「[[http://blog.rhinoera.com/631/][无心犹隔一重关]]」，我相信，这一关就是如何从「无想定」跳到「想受灭定」。

根据以上实验得出的结论，「想受灭定」很简单，就是让五蕴只留下识蕴运转。

葛印卡老师最后一天的开示说明：

#+begin_quote
  随着表面实相的分解消融，我们建渐体验到身心结构的究竟实相，也就是每一刹那都在生起灭去的振动，除此别无它物。到了这个阶段就不再起分别心，因此也不会有偏好或成见，没有习性反应（*行蕴*）。

  内观修行方法逐渐减弱受制约的想蕴，因此也减弱了习性反应，达到*受、想不起*的阶段，也就是涅盘的的体验。
#+end_quote

禅修者从头到尾没有停止「识蕴」，而是让「识蕴」不受到「行蕴」的干扰，不起「受」「想」，这样会发生什么事呢？

「识」强而「行」弱，有没有让你想到什么？

#+begin_example
  无明 -> 行 -> 识 -> 名色…
#+end_example

这就是[[http://blog.rhinoera.com/173/][十二缘起中的「行缘识」这二支的断裂（另篇专述）]]！

只有识蕴运转，没有想受行的干扰，就产生了智慧。

就像把灯泡外的黑罩子拿掉，整个房间就被照亮了一样。

我们的心本来就是[[http://blog.rhinoera.com/693/][非常光亮、有力的]]，只是从来都被五盖罩住，被行蕴干扰着，发挥不出它原本的功用。

「想受灭定」让我们能完整体会心原本的样子。

** 生活中修行
    :PROPERTIES:
    :CUSTOM_ID: 生活中修行
    :END:
禅修完了，生活还要继续。

怎么继续呢？

持续觉知身、受、心、法，不让行蕴再运转。这就是最理想的生活方式。

当然，有时候我们会被五蕴所迷，又再增生痛苦。

没关系，早晚留一个小时，修习禅定，让痛苦有中断的时候。

中断一二秒，就会变成二三秒；二三秒就会变成三四秒...慢慢的，你的苦就会像潮水一样，[[http://blog.rhinoera.com/656/%e7%ac%ac%e5%9b%9b%e6%ac%a1%e8%91%9b%e5%8d%b0%e5%8d%a1%e5%86%85%e8%a7%82%e5%8d%81%e6%97%a5%e7%a6%85%e4%bf%ae%e5%bf%83%e5%be%97%ef%bc%884%ef%bc%89/blog.rhinoera.com/205/][一层一层的消退]]。

持续体会各种苦的灭，直到它们完全不再生起，为人间及天上，增长最大的利益吧！

** 参考资料
    :PROPERTIES:
    :CUSTOM_ID: 参考资料
    :END:
各个脉轮在内观中的用途可以参考：

[[http://blog.rhinoera.com/424/][赞念长老的内观开示－五蕴在十二缘起中生起的过程\\
]][[http://blog.rhinoera.com/81/][[转载] 内观禅修与身体七个脉轮的关系]]

无想定：

[[http://blog.rhinoera.com/631/][与白云师兄说无心犹隔一重关]]\\
[[http://static.rhinoera.com/wp-content/uploads/2013/04/03.htm][略談滅盡定]]

灭尽定次第：

[[http://wiki.rhinoera.com/%E5%9B%9B%E7%A6%85%E5%85%AB%E5%AE%9A%E4%B8%8E%E7%81%AD%E5%B0%BD%E5%AE%9A][四禅八定与灭尽定／广超法师]]

\\

