* 中译序

<embed src=./mp3/1-0.mp3 width='530px' height='80px'/>

记得有一次，看到有位斯里兰卡的森林僧在信中写道：“每个修行人都应该读阿姜查的《平静的林湖》一百遍！”

当时有些纳闷，那些僧人到底在原始森林中做些什么呢？说是修行，那修些什么呢？为什么一定要在危机四伏、野兽毒蛇出没、疟疾肆虐的稠密热带雨林里修行，而不在生活稳定的寺院里修行？这实在是我们这些过现代生活的人所难以想象的。

近年来，随着翻译成英文的泰国佛教著作逐渐普及，森林僧的各种资料也被越来越多地翻译出来，以便让人了解他们的生活与修行。这当中最受欢迎的，大概是阿姜查的著作。

阿姜查是对西方佛教界最有影响力的禅修老师之一，开示风格幽默直接，用的都是浅白的言语，没有深涩的佛学专有名词，而内容全部都是佛法的核心，没有半句废话。他的开示令人每次阅读都有新的受用，这应该是他那么受欢迎的原因吧！

既然开示都已那么有摄受力，阿姜查个人的修行生活事迹应该更加精彩吧！可惜他的个人传记却一直未翻译出来。二〇〇八年初，永觉比丘（Cagino
Bikkhu）从巴蓬寺带回至今还未正式出版的《阿姜查传》英文节译本，要我将它翻译成中文，与读者分享。

我的中英文底子皆不好，平时没有写文章的习惯，对于泰国佛教文化又不熟悉，自知是无法胜任这项工作的。可是受到师父的鼓励，最终还是接下这项任务。这是本书能够呈现在中文读者面前的因缘。

翻译过程中，我不断写信询问各种问题，承蒙师父细心解答，并且在翻译结束后，还与泰文原著对照校正。此外，杨常康居士也协助厘清书中巴利语名词及一些难解的概念，在此一并致谢！

最后 还要感激一直在背后默默护持本书翻译出版的刘杨叇居士以及协助发行流通的
W.A.V.E 中心。限于个人水平，书中内容如有失误，概由中译者负责。

--------------

*编者注：*

此书中称呼简介

1、“隆波”为巴利文音译，意为“师父”。

2、阿姜查，“阿姜”为音译，也写作“阿迦”，为泰国对上座比丘的尊称，“查”属于个人名字。后面所提到的阿姜也都为尊称，而不是指某个派系等。

3、美琪为音译，指泰国受沙弥十戒的女众，剃发后一般住在寺院，但还不属于正式的沙弥尼，身份介于出家和在家之间，因为泰国现在没有女众出家戒法的传承。

4、昭坤（Chao Kun）为泰国僧伽系统里的头衔，由僧王赐封。

5、乌汶，泰国城市名，可翻译为“莲花”，为阿姜查尊者出生地，后来并在此建立寺院。

6、“莲花中的珍宝”也可翻译为“乌汶的珍宝”。

另，文中“编者注”，为“溯源”编辑小组所加。

